### ISSUE TITLE
Slow downs in Horizon Zero Dawn on 6800M (PRIME)

### ISSUE THREAD

**Issue by FireBurn** [HansKristian-Work/vkd3d-proton#1003]
I'm not 100% sure when this broke, I'm running 

kernel 5.17-rc4
mesa 22.1.0-devel
wine-staging 7.2
vkd3d-proton latest git

On steam I tried running Proton 7.2-GE-test3, Proton 6.21-GE-2 with the same results

It does work successfully with Proton 6.3-8, and renders at full speed in the Benchmark

When it isn't working, I get the main menu but the water is rendering lower than 1fps, navigating the menus is very difficult and near impossible to change any graphics settings

Detroit Become Human renders fine

**Comment by FireBurn** [comment]
So I think something might have changed in the VKD3D_FILTER_DEVICE_NAME code, if I use VKD3D_VULKAN_DEVICE=0 along with DRI_PRIME=1 it works fine but using VKD3D_FILTER_DEVICE_NAME="NAVY_FLOUNDER" seems to have stopped working

**Comment by FireBurn** [comment]
Devices:
========
GPU0:
        apiVersion         = 4206796 (1.3.204)
        driverVersion      = 92274787 (0x5800063)
        vendorID           = 0x1002
        deviceID           = 0x1638
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = AMD RADV RENOIR
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 22.1.0-devel (git-100c80392a)
        conformanceVersion = 1.2.7.1
        deviceUUID         = 00000000-0800-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
        apiVersion         = 4206796 (1.3.204)
        driverVersion      = 92274787 (0x5800063)
        vendorID           = 0x1002
        deviceID           = 0x73df
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = AMD RADV NAVY_FLOUNDER
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 22.1.0-devel (git-100c80392a)
        conformanceVersion = 1.3.0.0
        deviceUUID         = 00000000-0300-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000

**Comment by doitsujin** [comment]
The `VKD3D_FILTER_DEVICE_NAME` code hasn't changed since it was introduced over a year ago.

**Comment by FireBurn** [comment]
Could something perhaps have changed in the vulkan-loader?

It seems strange I need to set VKD3D_VULKAN_DEVICE=0 in order to select GPU1 and setting VKD3D_FILTER_DEVICE_NAME="NAVY_FLOUNDER" is picking RENOIR

**Comment by FireBurn** [comment]
I'm wondering if I'm hitting https://github.com/KhronosGroup/Vulkan-Loader/commit/356945ba6607b238929ed80e2181dadd123079c8

**Comment by FireBurn** [comment]
Switching form vulkan-loader 1.3.204 t0 1.3.206 sorted things
