### ISSUE TITLE
3DMark Demo: Time Spy Invalid semantic 'SV_VertexID'

### ISSUE THREAD

**Issue by ernstp** [HansKristian-Work/vkd3d-proton#1004]
Hi, when running the 3DMark Demo and trying to start the Time Spy DX12 benchmark I get the following error:

D3DCompile2() fullscreen_rectangle failed: no filename:3:9: E5013: Invalid semantic 'SV_VertexID'. (HRESULT: -2147467259)

To just get 3DMark Demo to start I have to set the commands to "%command% --use-gl=osmesa" and then always select "force 64bit" when launching. The OSmesa thing is only for the UI AFAICT. The "Fire Strike" DX11 benchmark runs well.

GPU: Radeon 6800 XT
Mesa driver: 22.0.0~rc2+git2202102200.b8dc56f5f81

I have tested both with Proton 7.0-1 so that would be 33f17cc7 and Proton Experimental.

**Comment by Oschowa** [comment]
> D3DCompile2() fullscreen_rectangle failed: no filename:3:9: E5013: Invalid semantic 'SV_VertexID'. (HRESULT: -2147467259)

That's a d3dcompiler issue and unrelated to vkd3d-proton. Maybe `winetricks d3dcompiler_47` on the prefix gets you further.

**Comment by ernstp** [comment]
You were correct!
