### ISSUE TITLE
Issues with DLSS + The Ascent

### ISSUE THREAD

**Issue by eaglemmoomin** [HansKristian-Work/vkd3d-proton#1009]
Not sure if this is an issue with VKD3D-Proton, with the game itself or the NVidia driver. The DLSS options in the game are greyed out and the game has been installed from Steam. Ray Tracing appears to be working well. Checking the game installation I can see the nvngx_dlss.dll is present in the folder ../steamapps/common/The Ascent/Engine/Plugins/Runtime/Nvidia/DLSS/Binaries/ThirdParty/Win64

I know the EGS version of the game had a bug with DLSS not being an option. On Steam however I'm led to believe it works. Machine is running a 3080. I've tried with Proton Experimental, Proton 7.01 and the most recent Proton-GE (7.2) to see if the behaviour was different on any of them.

![Screenshot from 2022-02-24 22-23-05](https://user-images.githubusercontent.com/26004829/155618503-42dfe0fb-12d0-43bf-afdb-6cc105095dd3.png)

**Comment by doitsujin** [comment]
Are you using the required environment variables to make DLSS work (`PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0`)?

**Comment by eaglemmoomin** [comment]
Yep did set both of them. Not in that order. Didn't think that mattered.

**Comment by doitsujin** [comment]
order doesn't matter and i'm not sure if the nvapi one actually implies the other, but yeah, it *should* work; if it doesn't it's most likely not a vkd3d thing.

**Comment by eaglemmoomin** [comment]
Yeah I figured as much given the other two games I checked seemed to be fine.

**Comment by aufkrawall** [comment]
I don't know if Proton does this automatically, but when running CyberPunk in Wine with native system libs only, I need to  either copy `_nvngx.dll` and `nvngx.dll` into the game's bin directory to make DLSS work (system32 prefix folder doesn't do the trick). Or I need to point to them via `LD_PRELOAD=path/to/_nvngx.dll:path/to/nvngx.dll`.

**Comment by eaglemmoomin** [comment]
> I don't know if Proton does this automatically, but when running CyberPunk in Wine with native system libs only, I need to either copy `_nvngx.dll` and `nvngx.dll` into the game's bin directory to make DLSS work (system32 prefix folder doesn't do the trick). Or I need to point to them via `LD_PRELOAD=path/to/_nvngx.dll:path/to/nvngx.dll`.

No Proton 'should' normally sort that out in my experience. Cyberpunks DLSS options are all present and accounted for. As are the other DLSS titles I've tested with. I think this is more likely a bug with The Ascent. I know the GamePass version of the game had issues with DLSS also.

**Comment by Vash63** [comment]
I can't duplicate this with the latest Proton Experimental (didn't try older version). DLSS works fine for me on Nvidia 515 with `PROTON_ENABLE_NVAPI_1 %command%` as my launch options.

**Comment by eaglemmoomin** [comment]
Can confirm using lastest 7.05 stable and copying the Cyberpunk NVAPI dll into the DLSS  plug in folder structure on disk. Then cycling between DX11 and DX12 enables DLSS and let's the game use it.
