### ISSUE TITLE
Myst Crashes with either the dxr or dxr11 flags enabled.

### ISSUE THREAD

**Issue by ILOVEPIE** [HansKristian-Work/vkd3d-proton#1018]
The engine pops up a window with the error:
```
Error: RayTracingDevice->CreateStateObject(&Desc, IID_PPV_ARGS(Result.GetInitReference())) failed 
 at I:/Workspace/Engine/Source/Runtime/D3D12RHI/Private/D3D12RayTracing.cpp:383 
 with error E_FAIL
```
in proton experimental and 7.0, the unofficial GE fork of proton actually experiences a null dereference error instead.

**Comment by doitsujin** [comment]
Is this Unreal Engine 4 or something? DXR is known not to work with that at the moment.

**Comment by ILOVEPIE** [comment]
I believe it is, but the crash occurs even with raytracing disabled.

**Comment by Blisto91** [comment]
@ILOVEPIE Friendly ping pong. Do you still have this issue today with never vkd3d-proton versions?

**Comment by ILOVEPIE** [comment]
I'll get back to you on that, have to reinstall it.

**Comment by ILOVEPIE** [comment]
@Blisto91 this is still crashing as far as I can tell.

**Comment by ILOVEPIE** [comment]
But it gives a different error message now.

**Comment by Blisto91** [comment]
@ILOVEPIE Can you verify that this works now? I just tested with Proton Experimental bleeding edge without issue

**Comment by ILOVEPIE** [comment]
@Blisto91 I'll check after I get back from work.

**Comment by ILOVEPIE** [comment]
It seems to work now, but I can't tell if the ray tracing is actually working or not.

**Comment by Blisto91** [comment]
Comparing fps is usually a good indicator

**Comment by ILOVEPIE** [comment]
> Comparing fps is usually a good indicator 

The GPU does show 99% utilization, so I assume it is.
