### ISSUE TITLE
Elden Ring: Black screen with game cursor only

### ISSUE THREAD

**Issue by SSimco** [HansKristian-Work/vkd3d-proton#1025]
I've been trying to run Elden Ring with a nvidia geforce gtx 950m and I got it to launch without crashing by setting the environment variable `VKD3D_FEATURE_LEVEL=12_0`, but I only get a black screen with cursor and I can hear the main menu music.
I had the same problem on windows 10 where I was getting a white screen and then it would crash but I was able to play using this [https://github.com/tuffee88/d3d12ProxyEdrDx11_0](https://github.com/tuffee88/d3d12ProxyEdrDx11_0).
Is there anything I could do to make it work?
I'm using the Flatpak version of Steam with bleeding edge proton experimental.
[steam-1245620.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8193691/steam-1245620.log)

**Comment by doitsujin** [comment]
Not seeing any errors that would point to an obvious issue, but in general, if the game doesn't support your hardware on Windows even with that kind of workaround, it's **very** unlikely to work any better on vkd3d-proton.

**Comment by SSimco** [comment]
The game works on Windows with the proxy library

**Comment by Blisto91** [comment]
Sounds like the same issue some people with some [nvidia 700 series have in other dx12 games](https://github.com/HansKristian-Work/vkd3d-proton/issues/989) on linux.
Have been reported for some nvidia GPU's in AOE IV and AOE II DE and other dx 12 games.

**Comment by doitsujin** [comment]
> The game works on Windows with the proxy library

Sorry, I misread (adding a comma here or there would help with that), but again, I don't really see anything wrong and the game works fine on other hardware that actually meets the minimum requirements, so :shrug:

**Comment by SneakyLittleman** [comment]
Same problem as original poster (Nvidia 860m - latest drivers 510 / kernel 5.17 / ubuntu 22 / latest mesa / vulkan / proton-bleeding-edge) - no logos and no main screen but the game loads fine to a black screen with background music.
Game performs decently on Windows 11 on this hardware & with the dx11 hack.
I've checked all required VK extensions listed on the VKD3D-Proton main page with vulkaninfo | grep XXX and my card has ALL extensions listed as supported.
FYI, Death stranding produces the same result, more or less: main menu screen (maybe?) with just the game cursor & grey background.
Cheers.
