### ISSUE TITLE
Elden Ring crashes on launch (vkd3d_allocate_device_memory: Memory allocation failed)

### ISSUE THREAD

**Issue by controlman** [HansKristian-Work/vkd3d-proton#1037]
Elden Ring crashes on launch. i noticed the following from the log file:
`013c:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.`
`013c:warn:vkd3d_allocate_device_memory: Memory allocation failed, but it is not possible to fallback to system memory here. Deferring allocation.`
which might be what causes the page fault later in the log file
[steam-1245620.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8227800/steam-1245620.log)

OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.10.0-11-amd64 
CPU: Intel i7-3770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 770 4GB
GPU Driver Version: 460.91.03
Memory: 1763MiB / 15968MiB 
Wine version: 7.0
DXVK: 1.10

I should have enough video and system memory so what's causing this?

**Comment by doitsujin** [comment]
There's nothing we can really do if the Vulkan driver fails to allocate memory.

Also note that
a) the game requests Feature Level 12_0, while Kepler only supports 11_0
b) we can no longer support Kepler GPUs since Nvidia dropped driver support

**Comment by controlman** [comment]
> Also note that a) the game requests Feature Level 12_0, while Kepler only supports 11_0 b) we can no longer support Kepler GPUs since Nvidia dropped driver support

just because ((((they)))) stopped supporting perfectly capable hardware doesn't mean that you should act like (((((them))))). you are german ffs, act like it.

**Comment by K0bin** [comment]
I seriously hope you didn't mean what those parentheses often mean online...

**Comment by HansKristian-Work** [comment]
Pretty obvious what's going on here, and no, this is not how you open an issue on Github.
