### ISSUE TITLE
Can't even open up the file

### ISSUE THREAD

**Issue by LordMala** [HansKristian-Work/vkd3d-proton#1042]
I can't even open up this file "vkd3d-proton-2.6.tar.zst" so therefor I have no way of installing it.

**Comment by nanokatze** [comment]
install gentoo

**Comment by LordMala** [comment]
> install gentoo

That's for Linux, I'm using Windows 10. Any way on putting this into a zip file instead?

**Comment by Joshua-Ashton** [comment]
`Right Click + Compression -> Add to Zip File` will add the .tar.zst to a zip.

Joking aside, you can use 7Zip ZST on Windows to extract it.

**Comment by LordMala** [comment]
> `Right Click + Compression -> Add to Zip File` will add the .tar.zst to a zip.
> 
> Joking aside, you can use 7Zip ZST on Windows to extract it.

I tried using 7Zip and it doesn't work.

**Comment by LordMala** [comment]
> [vkd3d-proton-2.6.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8289481/vkd3d-proton-2.6.zip) here

Thank you so much! Now I can use it!

**Comment by doitsujin** [comment]
Also please note that we don't support Windows, all you're going to get is poor performance and/or instability.

**Comment by LordMala** [comment]
Oh, I had no idea, thanks for letting me know. I got directed here through the Elden Ring Reddit.

**Comment by K0bin** [comment]
@LordMala https://github.com/soupstream/EldenRingStutterFix is probably the better Elden Ring fix for Windows users. It replicates the optimization VKD3D-Proton has for Elden Ring on regular D3D12.
