### ISSUE TITLE
Still can't open up the file

### ISSUE THREAD

**Issue by LordMala** [HansKristian-Work/vkd3d-proton#1043]
Yes I know that this was closed but I tried using 7Zip, Winzip and many others and I still cannot extract the file. It says that it isn't a valid archive, or something like that.

**Comment by SolitudeSF** [comment]
try harder

**Comment by LordMala** [comment]
Ok, how the hell do I open this thing? What do you all use to open this file?

**Comment by LordMala** [comment]
Close this one out, somebody else was able to help me open up the file.
