### ISSUE TITLE
[Regression] Cyberpunk 2077 - Black Flickering with Proton 7

### ISSUE THREAD

**Issue by richardtatum** [HansKristian-Work/vkd3d-proton#1045]
Machine:
Ryzen 5 3700X
Radeon 6800XT
Mesa 21.3.7-2

Using Proton 7.0-1 (or any of the GE variants) I am able to consistently reproduce a black flickering that happens mostly when indoors, and mostly when hovering over interactable objects, in Cyberpunk 2077. 

The flickering is most certainly from within the game, as it shows on recordings and streams, and you can just about make out the work being rendered back in as the black disappears, although the whole thing does only take a split second.

Things I tried to rectify the issue:
- Mangohud On/Off
- VKBasalt On/Off
- VSYNC On/Off
- Fullscreen/Borderless Window
- Mesa-git (22)
- Different GPU (5700XT)

If I switch to Proton 6.3-8 (or any of its GE variants) the issue goes away.

I have attached a save file from within one of the new Patch 1.5 apartments. If you load the file, and walk to the bar on the right to hover over one of the interactable drinks you should be able to consistently reproduce the issue.

If I can provide anything else please let me know.

[cp2077_black_flickering.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8309863/cp2077_black_flickering.zip)

**Comment by HansKristian-Work** [comment]
We suspect this is likely caused by Proton 7.0 changes w.r.t. syscall stack, and not really a vkd3d-proton regression. Things to try would be:

- Use the same vkd3d-proton on Proton 6.3 and Proton 7.0.
- Try latest bleeding edge which has some fixes.
- Try PROTON_LOG=1 and look for "overflow"

**Comment by richardtatum** [comment]
Thanks for your reply. I haven't had much time to do extra experimentation but I will attempt to use the bleeding edge proton this evening and see if that fixes the issue.

In the mean time, I was able to quickly start up the game and replicate the issue with the proton log variable set. Please see attached.

Note I closed the game almost immediately after it happened. I also don't see any 'overflow' references.

[steam-1091500.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8322600/steam-1091500.log)

**Comment by HansKristian-Work** [comment]
I cannot reproduce any obvious flicker. Do you have a screenshot of the exact objects that are supposed to flicker?

**Comment by HansKristian-Work** [comment]
Tried some more with variants of:
- Proton 6.3, 7.0, experimental (and their included vkd3d-proton build)
- Mesa 21.3.7 and git

and I cannot see any significant difference or any indication there is a bug.

**Comment by HansKristian-Work** [comment]
Seeing some differences on experimental + latest vkd3d-proton though, hm.

**Comment by richardtatum** [comment]
> Do you have a screenshot of the exact objects that are supposed to flicker?
Its not objects, but the entire scene. I will see if I can get a recording to help clarify.

**Comment by richardtatum** [comment]
So I just went back to Cyberpunk to try and take a video and saw that the Patch 1.52 has just released. Within the notes was the following line:

> Fixed an issue where the loot UI could flicker and change before picking up the item.

Whether this is directly related or not I am not sure, but I can no longer replicate the issue that was previously very easy to replicate from the save file.

I do some further testing this evening to confirm that I no longer see the flickering issue and if so I will close this ticket.

Thanks for all of your help so far.
