### ISSUE TITLE
How to be sure if FSR is enable?

### ISSUE THREAD

**Issue by ghost** [HansKristian-Work/vkd3d-proton#1046]
Hi there,

I'm trying to use AMD FidelityFX Super Resolution (FSR) on Monster Hunter Rise (Proton, VKD3D) and I do not know if FSR is working or not since many people claim that we should guess if FSR is working checking ingame 'weird' available resolution displayed, such as 2954x1662, 2293x960, 1720x720 or something like that, but my issue is that game already display these kind of resolution, even before set any parameters.

So, my question is simple: how can I be sure that FSR is enable correctly? There is a log file that I can check?

Thanks in advance.

**Comment by doitsujin** [comment]
FSR in this case is a game feature, not something that vkd3d-proton interacts with in any way. It should just work if you enable it in-game.

**Comment by Oschowa** [comment]
Monster Hunter Rise doesn't support FSR natively. But either way this has nothing to do with vkd3d-proton and official proton builds don't support the FSR hack. For support with this you should ask the providers of the 3rd party proton builds that have it patched in, like glorious eggroll for proton-ge. On AMD you can also use [gamescope](https://github.com/Plagman/gamescope) for FSR scaling in every game.
