### ISSUE TITLE
Death Stranding shadows flickering

### ISSUE THREAD

**Issue by Hadrianneue** [HansKristian-Work/vkd3d-proton#1061]
Ever since vkd3d 2.4 shadows flicker (also on newer versions), works fine on vkd3d 2.3.1, its very noticeable in open worlds areas where hills cast shadows.

using lutris-GE-Proton7-7-x86_64 with VKD3D_FEATURE_LEVEL 12

logs with trace.
[vkd3d_2.3.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/8405159/vkd3d_2.3.tar.gz)
[vkd3d_2.4.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/8405160/vkd3d_2.4.tar.gz)

```
CoreCtrl v1.2.3

==== Software ====
Kernel version: 5.15.28
Mesa version: 21.3.7

==== Radeon R7 360 [GPU 0] ====
BIOS version: 113-TOBAGO_PROL_D5_
Device: Tobago PRO
Device ID: 665F
Device model: Radeon R7 360
Device model ID: 7360
Driver: amdgpu
Memory: 2048 MB
OpenGL version (compat): 4.6
OpenGL version (core): 4.6
PCI Slot: 0000:01:00.0
Revision: 81
Vendor: Advanced Micro Devices, Inc.
Vendor ID: 1002
Vendor model ID: 1682
Vulkan API version: 1.2.195

==== Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz [CPU 0] ====
Architecture: x86_64
Bogomips: 6587.31
Bugs: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
Byte order: Little Endian
CPU Family: 6
Cores: 4
Execution units: 8
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
L1 cache (data): 128 KiB (4 instances)
L1 cache (instructions): 128 KiB (4 instances)
L2 cache: 1 MiB (4 instances)
L3 cache: 8192 KB
Microcode version: 0x21
Model: 58
Model Name: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
Operation modes: 32-bit, 64-bit
Stepping: 9
Vendor ID: GenuineIntel
```

**Comment by Oschowa** [comment]
It's a long standing driver bug specific to GCN2 AMD GPUs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5147
It works fine on other hardware.

**Comment by Hadrianneue** [comment]
> It's a long standing driver bug specific to GCN2 AMD GPUs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5147

yeah it looks pretty much buried at this point

> You can try RADV_DEBUG=nohiz as a workaround.

well that works, thanks. i also get the performance improvements ever since 2.3.1 which is nice.

**Comment by Blisto91** [comment]
@Hadrianneue Hi there. Even if this is a driver issue i just wanted to check if it is still present?

**Comment by Hadrianneue** [comment]
> @Hadrianneue Hi there. Even if this is a driver issue i just wanted to check if it is still present?

i don't have the gcn2 GPU anymore... issue still open on mesa repo, so its likely still present.

**Comment by Hadrianneue** [comment]
> It's a long standing driver bug specific to GCN2 AMD GPUs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5147 It works fine on other hardware. You can try RADV_DEBUG=nohiz as a workaround.

also should've closed with this back then... doing it now.

**Comment by Blisto91** [comment]
Thanks for the reply anyway 👍
