### ISSUE TITLE
DIRT 5 on GTX960m REQUIRED FIX

### ISSUE THREAD

**Issue by milo-it** [HansKristian-Work/vkd3d-proton#1064]
Hello, is there a way of playing DIRT 5 on non-dx12 gpu (i've a gtx960m)

without any fix, my game crashes without starting
with Elden ring fix (https://github.com/tuffee88/d3d12ProxyEdrDx11_0), i can get past intro video, then crashes with error:
s_cpuReadbackBuffers[readbackBufferIndex][qID]->Map(0, &range, (void**)&pMappedMem)' failed with 'HR = 0x887a0005, Reason = Istanza del dispositivo GPU sospesa. Utilizzare GetDeviceRemovedReason per determinare l'azione appropriata.

BTW, i've no clue in using vkd3d-proton.. if you can share also some guide to try this out
thanks for support
Milo

**Comment by Blisto91** [comment]
([Transfered from dxvk](https://github.com/doitsujin/dxvk/issues/2583))

**Comment by Blisto91** [comment]
@milo-it Just to make sure. Are you using Linux?

**Comment by milo-it** [comment]
nope.. i'm on Win

**Comment by Blisto91** [comment]
Oh. Then i'm not sure vkd3d-proton will be able to help you (the main focus is linux). You are probably better to wait for an answer on the pr tool you linked above where i see you've made a issue.

**Comment by Venemo** [comment]
VKD3D-Proton is a compatibility layer that translates games from D3D12 to Vulkan. However, VKD3D-Proton does not aim to "emulate" features that are missing from your hardware. If a game needs D3D12 hardware capabilities and your hardware is missing some features from that, then the game won't work on that hardware and this project won't help with that.

**Comment by HansKristian-Work** [comment]
Closed due to inactivity on issue and unsupported use case.
