### ISSUE TITLE
AC Valhalla black quadtratic render artefacts

### ISSUE THREAD

**Issue by SicLuceatLux** [HansKristian-Work/vkd3d-proton#1086]
AC Valhalla 
produces black artifacts at geometry boarders

![image](https://user-images.githubusercontent.com/43041463/165139410-c9f18b0b-3e69-4048-a2a7-46961a362f8c.png)

comparable to those https://github.com/HansKristian-Work/vkd3d-proton/issues/409#issuecomment-817101682
wasn't able to catch them as good as those.

vkd3d log to the above screenshot sceen
[vkd3d.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8556656/vkd3d.zip)

mesa latest git of today d217fb9b0a7d0d3ad5ab4950c65b6633bf20e91c
[glxinfo-short.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8556703/glxinfo-short.zip)

[vulkaninfo.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8556704/vulkaninfo.zip)

the effect gets worse with after screwing around with the resolution scaling this "scanline bushes" are also an issue

![Screenshot from 2022-04-25 19-30-19](https://user-images.githubusercontent.com/43041463/165142323-72d0b043-b8a1-49df-a9c4-f87b3a16ee15.png)
(near the stones. Way more visible when walking because the quadratic shape stays as an artifact in the scene)

**Comment by Oschowa** [comment]
Try with Mesa 22.0

**Comment by SicLuceatLux** [comment]
So downgrade?

**Comment by Oschowa** [comment]
yes

**Comment by SicLuceatLux** [comment]
> yes

ok need to go will check it out later - thx !

**Comment by Oschowa** [comment]
this might also fix it https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/16148

**Comment by SicLuceatLux** [comment]
Thx for the hint. indeed Mesa 22.0 was a good start for bisecting it works till

https://gitlab.freedesktop.org/mesa/mesa/-/commit/15640e58d96c5db0cd78769a06b6b204dcd60799

**Comment by Oschowa** [comment]
Try the MR above, it will probably fix it.

**Comment by SicLuceatLux** [comment]
The MR fixed it - thx for the help!
