### ISSUE TITLE
Ray tracing corruption on some surfaces in The Ascent

### ISSUE THREAD

**Issue by Vash63** [HansKristian-Work/vkd3d-proton#1115]
Running The Ascent with `PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr %command%` allows RT to work but has corrupted reflections in some scenes. I have confirmed this occurs with or without DLSS enabled and they are not present in Windows in the same area. The game crashes at launch with dxr11 enabled. Tested on both Proton Experimental and with latest master d3d12.dll placed next to `TheAscent-Win64-Shipping.exe` with Nvidia 515.48.07 on an RTX 2080.

The issue appears as large sawtooth artifacts on specific surfaces and pan strangely with the camera in motion making it very difficult to miss. It is not present in all locations in the game or on all surfaces.

![20220604130751_1](https://user-images.githubusercontent.com/3086017/171996495-6a18e7d3-ebd0-4999-bf5a-6abbbb92f648.jpg)
![20220604123729_1](https://user-images.githubusercontent.com/3086017/171996508-9fe8a34c-af0b-47a0-a0d9-3a3cd9930aa3.jpg)

Windows for comparison (see surface directly under character's feet)
![979690_screenshots_20220604124550_1](https://user-images.githubusercontent.com/3086017/171996578-a8d25f5b-f5a9-468c-8efa-1af344044037.jpg)

**Comment by Vash63** [comment]
[AppData.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8839913/AppData.zip)

Not sure if saves are portable but if so this should load you into this area.

**Comment by adamnv** [comment]
I've seen this on raytraced reflections under VKD3D on a number of UE4 titles - this is a nice clear example though.

**Comment by adamnv** [comment]
> a number of UE4 titles

**Comment by Blisto91** [comment]
Spoken with the original reporter on Discord but they have limited time.
But I've verified on a Nvidia RTX 4080 and a AMD RX 6800 that this issue is fixed since commit https://github.com/HansKristian-Work/vkd3d-proton/commit/d0580cb6e3c63424e92c4f787c8d1d00b953826b
