### ISSUE TITLE
link error when building on windows with cygwin64

### ISSUE THREAD

**Issue by KOTOKORURU** [HansKristian-Work/vkd3d-proton#1186]
FAILED: libs/d3d12/d3d12.dll
"x86_64-w64-mingw32-g++"  -o libs/d3d12/d3d12.dll libs/d3d12/d3d12.dll.p/main.c.obj ../libs/d3d12/d3d12.def "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "..\libs\d3d12\d3d12.def" "-Wl,--start-group" "-Wl,--out-implib=libs\d3d12\d3d12.dll.a" "-Wl,--file-alignment=4096" "-static" "-static-libgcc" "-static-libstdc++" "libs\vkd3d\libvkd3d-proton.a" "libs\vkd3d
-common\libvkd3d_common.a" "libs\vkd3d-shader\libvkd3d-shader.a" "subprojects\dxil-spirv\libdxil-spirv.a" "-pthread" "-ldxgi" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: libs\vkd3d\libvkd3d-proton.a(libvkd3d-proton.a.p/device.c.obj): error opening thin archive member: No such file or directory
collect2: error: ld returned 1 exit status
[78/79] Linking target libs/vkd3d-utils/libvkd3d-proton-utils-3.dll
FAILED: libs/vkd3d-utils/libvkd3d-proton-utils-3.dll
"x86_64-w64-mingw32-g++"  -o libs/vkd3d-utils/libvkd3d-proton-utils-3.dll libs/vkd3d-utils/libvkd3d-proton-utils-3.dll.p/vkd3d_utils_main.c.obj ../libs/vkd3d-utils/vkd3d-proton-utils.def "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "..\libs\vkd3d-utils\vkd3d-proton-utils.def" "-Wl,--start-group" "-Wl,--out-implib=libs\vkd3d-utils\libvkd3d-proton-utils.dll.
a" "-Wl,--file-alignment=4096" "-static" "-static-libgcc" "-static-libstdc++" "libs\vkd3d\libvkd3d-proton.a" "libs\vkd3d-common\libvkd3d_common.a" "libs\vkd3d-shader\libvkd3d-shader.a" "subprojects\dxil-spirv\libdxil-spirv.a" "-pthread" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--en
d-group"
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: libs\vkd3d\libvkd3d-proton.a(libvkd3d-proton.a.p/vkd3d_main.c.obj): error opening thin archive member: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

i' not sure if i still missing something nessary.
thanks

**Comment by KOTOKORURU** [comment]
build libs/d3d12/d3d12.dll: cpp_LINKER libs/d3d12/d3d12.dll.p/main.c.obj ../libs/d3d12/d3d12.def | C$:/vkd3d-proton/libs/d3d12/d3d12.def libs/vkd3d-common/libvkd3d_common.a libs/vkd3d-shader/libvkd3d-shader.a libs/vkd3d/libvkd3d-proton.a subprojects/dxil-spirv/libdxil-spirv.a
 LINK_ARGS = "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "..\libs\d3d12\d3d12.def" "-Wl,--start-group" "-Wl,--out-implib=libs\d3d12\d3d12.dll.a" "-Wl,--file-alignment=4096" "-static" "-static-libgcc" "-static-libstdc++" **"\libs\vkd3d\libvkd3d-proton.a" ".\libs\vkd3d-common\libvkd3d_common.a" "libs\vkd3d-shader\libvkd3d-shader.a" "subprojects\dxil-spirv\libdxil-spirv.a"** "-pthread" "-ldxgi" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"


seems the cygwin64 console couldn't recognize the '\', replace it with "/" in build.ninja can fix this problem.

**Comment by HansKristian-Work** [comment]
Cygwin is not supported.
