### ISSUE TITLE
Gears 5 Black Screen when launched with latest VKD3D from git

### ISSUE THREAD

**Issue by kodatarule** [HansKristian-Work/vkd3d-proton#1187]
As the title explains it, Gears 5 seems to be having some very weird hitches/stutters/freezes even after a while.
Initially I thought it could be my GPU VRAM being consumed so I tried lowering the settings to no avail, further to that I kept monitoring the VRAM usage and it never fills the 8GB VRAM maximum it hits even on ultra settings is like 7,8gb and then drops back to 7,6GB so it frees memory on the fly.
When you start playing(the campaign) - for a level it's great, then when the next cinematic occurs(it also frees up VRAM to something like 6.8GB) the game goes into 1fps mode - fixing it is by going into options changing from ultra to high and then back to ultra and vice versa. It seems to be triggered whenever a new cinematic plays(level loads).
Not too sure how this can be debugged.

EDIT: Just for information of the specs + distro and DE
Arch Linux / KDE Plasma
CPU: Ryzen 7 5800X3D
GPU: RTX 3070 8GB
RAM: 4x8GB DDR4 3000mhz

EDIT:
Just to add a screenshot of what exactly happens and how the entire system starts freezing(another workaround to this after a while is to go back to main menu and then get back to playing the game.
It seems more like a bug with VKD3D than a VRAM or something else going on, as it's visible that it never exceeds the limit or tasks the system heavily, it just degrades after a while.
![Screenshot_20220802_053431](https://user-images.githubusercontent.com/65848953/182279508-e3ab66d8-1584-4f68-98ef-10850da06c44.png)

**Comment by doitsujin** [comment]
Note that on Nvidia, it's impossible to oversubscribe VRAM, so even if the game uses more than 8GB you'll never see it in the HUD since we'll explicitly fall back to system memory allocation.

With D3D12 games we have no real control over VRAM usage, so if 8GB isn't sufficient to run this game with highest texture quality then I'd suggest lowering texture quality.

**Comment by kodatarule** [comment]
Will try, but even on medium settings this was occurred(and not just the texture settings set to medium)

**Comment by kodatarule** [comment]
Reinstalled game, cleared the shader cache, left textures to high and everything else ultra, tested a bit more. No issues what so ever. Might've been corrupt install as it was happening on every setting. I'll go ahead and close this issue. In case someone else experience it they can easily reopen.

**Comment by kodatarule** [comment]
I am reopening as this seems to be some very weird glitch happening after a while of playing on every setting, could it be an nvidia related bug?(something like the halo infinite screen freeze/hang)

**Comment by HansKristian-Work** [comment]
Should be fixed now.
