### ISSUE TITLE
Ghosts 'n Goblins Resurrection (1375400) fails to launch in dx12 mode

### ISSUE THREAD

**Issue by alasky17** [HansKristian-Work/vkd3d-proton#1188]
experimental-bleeding-edge-7.0-21341-20220801-pf97544-w48159a-d8db2eb-vd00d03
Tested with the Steam Deck and on an AMD desktop

Ghosts 'n Goblins Resurrection is crashing on launch with the default dx12 mode.  It works when you change the confirmation settings to prefer dx11 mode (steamapps/common/Makaimura_GG_RE/config.ini and change TargetPlatform=DirectX12 to TargetPlatform=DirectX11).  Attaching log of the crash on the deck.
[ghosts-n-goblins-crash-dx12.log.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/9235885/ghosts-n-goblins-crash-dx12.log.zip)

**Comment by HansKristian-Work** [comment]
Reproduced.
