### ISSUE TITLE
New versions of Reshade are broken for DirectX 12 games. 

### ISSUE THREAD

**Issue by canceralp** [HansKristian-Work/vkd3d-proton#1195]
This is not VKD3D's problem but I have already asked this in Reshade forums and channels (and many Linux forums). So, I'm trying my chances asking here as well. 

The problem: 
Reshade versions up to 4.9.1 works perfectly with DirectX 12 games. But newer 5.x.x versions don't work. Reshade.log file says it has successfully connected to the game's exe but there is no overlay in the game. 

I have tried this with: 
- Guardians of the Galaxy
- Cyberpunk 2077 
- AC: Valhalla
- Shadow of the Tomb Raider 
None worked.

I have tried to install Reshade with 3 different ways:
- with the classical way of downloading and clicking the exe. 
- through Kevinlekiller's reshade-steam-proton script 
- by manually creating dll files as it is explained here
[https://forum.endeavouros.com/t/foss-screen-space-ray-tracing-with-any-game-and-gpu/6252](https://forum.endeavouros.com/t/foss-screen-space-ray-tracing-with-any-game-and-gpu/6252) 

None works.

**Comment by Blisto91** [comment]
@canceralp Hi there. Is this still the case today with up to date vkd3d-proton and reshade? 🙂

**Comment by Blisto91** [comment]
@canceralp Friendly ping

**Comment by canceralp** [comment]
> @canceralp Friendly ping

No, this is not the case anymore. Crosire, the developer who has created Reshade, has fixed the problem. Reshade works on any DirectX 12 games I have tried with VKD3D layer.
