### ISSUE TITLE
Pixel shader input layout mismatch

### ISSUE THREAD

**Issue by sherief** [HansKristian-Work/vkd3d-proton#1204]
I'm doing bring-up of a proprietary engine on Steam Deck using compatibility layer Proton 7.0-4 and OS version 3.3.1, Build 20220817.1, and the simple PSO for Dear imgui is suffering from a layout mismatch corrupting the UI rendering. Here's the HLSL versions:

Vertex shader:
```float4x4 ProjectionMatrix : register(b0);
struct PSInput { float2 TexCoord : TEXCOORD; float4 Color : COLOR; };
PSInput main(float2 Position : POSITION, float2 TexCoord : TEXCOORD, float4 Color : COLOR, out float4 OutPosition : SV_POSITION)
{
    OutPosition = mul(ProjectionMatrix, float4(Position, 0, 1));
    PSInput Result;
    Result.TexCoord = TexCoord;
    Result.Color = Color;
    return Result;
}
```

And pixel shader:

```struct PSInput { float2 TexCoord : TEXCOORD; float4 Color : COLOR; };
SamplerState TextureSampler : register(s0);
Texture2D Texture : register(t0);
float4 main(PSInput Input, float4 ScreenSpace : SV_POSITION) : SV_TARGET
{
    float4 SampledColor = Texture.Sample(TextureSampler, Input.TexCoord).aaaa;
    return (Texture.Sample(TextureSampler, Input.TexCoord) * Input.Color);
}
```

The first line in main() is vestigial, and always gets optimized out on Windows. The shaders are compiled using the legacy compiler via D3DCompile() and profiles vs_5_0 / ps_5_0

Looking at GLSL versions in a Renderdoc capture, the vertex shader declares its outputs as such:
```layout(location = 1) out vec2 o1;
layout(location = 2) out vec4 o2;
```

While the pixel shader declares its inputs as 
```layout(location = 0) in vec2 v0;
layout(location = 1) in vec4 v1;
```

So vertex shader's o1 (tex coord) ends up going to the pixel shader's v1 (color), causing incorrect texcoords to be used for sampling the imgui texture and corrupted UI rendering.

The full shaders are attached as HLSL, SPIR-V, and GLSL; with the latter two obtained from a Renderdoc capture running remotely on the Steam Deck.

[ps-glsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455077/ps-glsl.txt)
[ps-hlsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455080/ps-hlsl.txt)
[ps-spirv.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455081/ps-spirv.txt)
[vs-glsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455082/vs-glsl.txt)
[vs-hlsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455083/vs-hlsl.txt)
[vs-spirv.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455084/vs-spirv.txt)

**Comment by sherief** [comment]
GitHub's UI implementation is wonderful, and I hope it actually works this time to attach the files.

[ps-glsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455090/ps-glsl.txt)
[ps-hlsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455091/ps-hlsl.txt)
[ps-spirv.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455093/ps-spirv.txt)
[vs-glsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455094/vs-glsl.txt)
[vs-hlsl.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455095/vs-hlsl.txt)
[vs-spirv.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9455096/vs-spirv.txt)

**Comment by K0bin** [comment]
Do you compile those shaders at runtime or do you ship the precomputed DXBC?

If you compile them at runtime, do you ship your own D3DCompiler DLL?

**Comment by sherief** [comment]
I compile them at runtime and rely on the Wine implementation.

**Comment by sherief** [comment]
BTW, it's on my near-term roadmap to convert it to ship ax DXBC - if it makes things easier for you we could wait till I submit that change then see if it fixes things. What do you think?

**Comment by K0bin** [comment]
I compiled your HLSL shaders with both Microsofts HLSL compiler and the Wine one,

Microsoft:
```
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// SV_POSITION              0   xyzw        2      POS   float   xyzw
```

Wine:
```
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyzw        2     NONE   float   xyzw
```

So this seems to be an issue with the Wine HLSL compiler rather than vkd3d-proton which only compiles from DXBC (or DXIL) to SPIR-V. To make things extra confusing, Wine's HLSL compiler is part of the original upstream vkd3d project.

**Comment by sherief** [comment]
Compiling on Windows using D3DCompile() then shipping that bytecode to Proton worked. Interesting bug..

**Comment by HansKristian-Work** [comment]
Yes, this is a HLSL compiler bug. Generally, mixing and matching output structs and out variables tends to cause confusion.
