### ISSUE TITLE
Elden Ring Flickering issue

### ISSUE THREAD

**Issue by bibitocarlos** [HansKristian-Work/vkd3d-proton#1206]
Description

When i launch Elden Ring from Steam, it flickers everytime . It was working perfectly with my older config -AMD 2400G) On mesa and Mesa-git, on radv, amdvlk. AMD-PRO crash the game at launch
Screenshots/video files

https://youtu.be/Zl_QFX5Iy1k
Log files (for system lockups / game freezes / crashes)

Steps to reproduce
Play Elden ring on 6600XT

System information

OS: (Archlinux)
GPU: (`0e:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1)
Kernel version: ( 5.19.3-zen1-1-zen)
Mesa version: (OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.0-devel and OpenGL 22.2)AND MESA-GIT
Desktop environment: (KDE_DESKTOP, X11 and Wayland)
Xserver version: .Org X Server 1.21.1.4 X Protocol Version 11, Revision 0
DXVK version: Steam 1660960119
Wine/Proton version: Proton and Proton-Ge

Regression
Dont know

Further information (optional)
Does the issue reproduce with the LLVM backend (RADV_DEBUG=llvm) ?
LLVM Backend = yes

[shader_log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9461300/shader_log.txt)

[dmesg.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9461296/dmesg.txt)

[RenderDoc_app_2022.08.27_18.20.25.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9461305/RenderDoc_app_2022.08.27_18.20.25.log)

**Comment by bibitocarlos** [comment]
Mesa issue : https://gitlab.freedesktop.org/mesa/mesa/-/issues/7135

**Comment by doitsujin** [comment]
Does this only happen in certain locations?

I can't reproduce this on my 6900XT so far.

Also, not entirely sure why you included dmesg and a Renderdoc log, neither are useful to vkd3d-proton in any way. Also no idea what `shader_log` is but it doesn't look useful either. Generally, just post the `~/steam-xxxxxxx.log` file that's produced when setting `PROTON_LOG=1`.

**Comment by bibitocarlos** [comment]
It happens everywhere.
Steam log attached

[steam-1245620.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9464023/steam-1245620.log)

**Comment by bibitocarlos** [comment]
Closed, reinstalled the game, delete the shader cache and it works again.
