### ISSUE TITLE
MSAA rendering without line AA doesn't match D3D12

### ISSUE THREAD

**Issue by sherief** [HansKristian-Work/vkd3d-proton#1239]
I'm rendering lines with a PSO that has SampleDesc.Count = 4, RasterizerState.AntialiasedLineEnable = FALSE, and RasterizerState.MultisampleEnable = FALSE. On native D3D12, the lines aren't anti-aliased while on Proton the lines show anti-aliasing applied. Changing RasterizerState.AntialiasedLineEnable and RasterizerState.MultisampleEnable to TRUE causes native to match Proton.

Let me know what other info I can provide to help with this.

**Comment by HansKristian-Work** [comment]
> On native D3D12, the lines aren't anti-aliased.

What exactly does this mean? Is multisample coverage disabled, or is this the difference of "smooth lines" or not?

**Comment by doitsujin** [comment]
We do not implement D3D line rendering.

Is there any practical use case that requires this to be accurate?

**Comment by HansKristian-Work** [comment]
We implement the new line rasterization API which covers these I think.
