### ISSUE TITLE
Hitman 3 freezes to death with Nvidia Vulkan developer drivers

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#1248]
When I walk around in the level Whittleton Creek (Hitman 2 level), the game dies after a short time when using the latest 515.49.15 Vulkan developer driver. For whatever reason, this seems to happen much faster on Windows than on Linux. It seems to be stable with regular consumer Nvidia driver, afaict. When it dies with the Vulkan developer driver, the game's process keeps running with 1% CPU load, but the window becomes black and unresponsive.
Tested with vkd3d-proton 212ae62b53eb870ee53d2a28bf8c4786f4f749c3 & dxvk dxgi a9bdea72e9603de85411e3b41f8a49c9cbd11182 .

Graphics settings:
![Screenshot_20220926_231343](https://user-images.githubusercontent.com/13510490/192381802-ad647eb1-aa24-41fe-9335-6df937d2397e.png)

Proton log:
[steam-1847520.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9649690/steam-1847520.log)

RTX 3060 on Arch 5.19.11
Hopefully this is also reproducible with different levels.

**Comment by aufkrawall** [comment]
Not fixed with new 515.49.18 developer driver.

**Comment by HansKristian-Work** [comment]
Seems like a very plausible case of missing placed DSV initialization. Like Spiderman just ran into.

**Comment by HansKristian-Work** [comment]
I can reproduce this in Sapienza. Same error, but I really can't see how this is related to vkd3d-proton directly. There's no obvious error. I also reproduce this on Proton 7.0-4.

**Comment by HansKristian-Work** [comment]
With further investigation it seems like the game is trying to present with signal-after-wait, which causes a deadlock. This is puzzling and it's not the kind of issue that would only show up on a subset of drivers.

**Comment by HansKristian-Work** [comment]
Should be fixed now.

**Comment by aufkrawall** [comment]
Ya, can't reproduce the crash with latest vkd3d-proton and nvidia vulkan dev driver 525.47.04. Thanks.
