### ISSUE TITLE
Xenia Emulator has graphical glitches when running

### ISSUE THREAD

**Issue by Blad3forc3** [HansKristian-Work/vkd3d-proton#1256]
When running a game through the Xenia Emulator and using dx12 the screen has some graphical glitches

![194000215-c136863f-a633-4c47-b290-7d8cdee39664](https://user-images.githubusercontent.com/39629883/194080234-eeab5f40-28c3-4122-af43-d4e18b431c21.png)

**Comment by Evernow** [comment]
May be https://github.com/HansKristian-Work/vkd3d-proton/issues/1088

**Comment by Bitwolfies** [comment]
Can reproduce right down to the exact same effect. 
![Screenshot_20221115_182853](https://user-images.githubusercontent.com/65789901/202068865-8adaf54b-f5ef-4646-87f8-113dc7eee899.png)
Arch Linux, KDE, Wine staging 7.20, VKD3D-Proton 2.7, Kernel 6.0, GTX 3080, XORG, NV driver 5.25

**Comment by aqxa1** [comment]
I can reproduce this on Windows 11 as well (with vkd3d-proton). Would a renderdoc capture or apitrace be useful?

**Comment by Tatsh** [comment]
I cannot get it to run at all. Just crashes on launch even without a game argument. Without vkd3d-proton or even dxvk, the application functions without crashing but games do not appear to load.

Wine Staging 8.12
