### ISSUE TITLE
.dll build issue in windows

### ISSUE THREAD

**Issue by manianamitra** [HansKristian-Work/vkd3d-proton#1260]
I followed all the steps mentioned in the readme file to build d3d12.dll in windows pc (I need to build it for my own development work). But I am facing build error. Please refer to the log below. Any help would be appreciated in this regard.

C:/Strawberry/c/x86_64-w64-mingw32/include/objidlbase.h: In function 'Finish_AsyncIMultiQI_QueryMultipleInterfaces':
C:/Strawberry/c/x86_64-w64-mingw32/include/objidlbase.h:1419:12: error: too few arguments to function 'This->lpVtbl->Finish_QueryMultipleInterfaces'
     return This->lpVtbl->Finish_QueryMultipleInterfaces(This);
            ^~~~
In file included from ../libs/d3d12/main.c:24:0:
..\include/vkd3d_win32.h: At top level:
..\include/vkd3d_win32.h:60:10: fatal error: dxgi1_6.h: No such file or directory
 #include <dxgi1_6.h>
          ^~~~~~~~~~~

**Comment by Joshua-Ashton** [comment]
MinGW is too old.

**Comment by Joshua-Ashton** [comment]
If you want to build on Windows you can just use MSVC.
