### ISSUE TITLE
Hello sir plz make fix for Uncharted game getting error on 750ti graphic does not support dx 12 feature level

### ISSUE THREAD

**Issue by zubair47** [HansKristian-Work/vkd3d-proton#1270]
Sir Is there any chances your team make fix for ucharted launch error on 750ti .

**Comment by doitsujin** [comment]
That GPU does not meet the minimum requirements of the game even on Windows.

**Comment by jackbingow** [comment]
@doitsujin What about vulkan?

**Comment by jackbingow** [comment]
@mbriar vulkan version 1.2 is enough for translating calls?
