### ISSUE TITLE
games slowing down with reBAR enabled

### ISSUE THREAD

**Issue by kassindornelles** [HansKristian-Work/vkd3d-proton#1273]
i have a RX 560 that has only 4 GB's of VRAM, when reBAR is enabled all my dx12 games slow down when: switching scenarios or changing graphics settings

here is RE village with rebar enabled in bios:
![rebarenabled](https://user-images.githubusercontent.com/40970965/198139524-b592a369-009f-462d-bc57-bab6dac128e0.png)

here is with rebar disabled: 
![norebar](https://user-images.githubusercontent.com/40970965/198139574-66a132ee-0a88-4c9b-bdd0-4ff01c2a83a0.png)

here is with rebar enabled but with no_upload_hvv:
![noupload](https://user-images.githubusercontent.com/40970965/198139641-a4da8d8b-bdc0-4001-b7b6-d6132107f583.png)

edit1: theres also massive performance loss when changing a game from fullscreen to borderless full screen with rebar enabled

**Comment by aufkrawall** [comment]
My guess is VRAM pressure, which tends to get worse with rBAR.
