### ISSUE TITLE
Ghostbusters: Spirits Unleashed persists DX12 is not supported on my system (UE4 game)

### ISSUE THREAD

**Issue by dreamhunt** [HansKristian-Work/vkd3d-proton#1275]
Hello,
Ghostbusters: Spirits Unleashed persists DX12 is not supported on my system and I get this message:
![Screenshot_20221030_000706](https://user-images.githubusercontent.com/38666396/198852405-bb1084f4-75a3-454e-9093-43ff5f6135e1.png)
I can play all DX12 games but this. I tried with -dx11 and  -d3d11 flags, with `VKD3D_FEATURE_LEVEL=12_0` and `VKD3D_FEATURE_LEVEL=12_2` to no avail. Ofc I have VKD3D-Proton's d3d12 set to native. I even tried VKD3D-Proton's installer - no dice.

**Comment by HansKristian-Work** [comment]
There is no system information posted here.

**Comment by dreamhunt** [comment]
> There is no system information posted here.

Totally forgot it, I'm sincerely sorry.
Arch Linux up to datew ith X11
Intel 9900K
GTX 1080Ti, driver version 520.56.06

The whole log:
https://pastebin.com/JYnGJkGN

**Comment by mbriar** [comment]
There is nothing d3d12 related in the log at all, can you get another log with `WINEDEBUG=+loaddll VKD3D_DEBUG=trace` set?

**Comment by dreamhunt** [comment]
Yes, here it is, thank you:
[wine.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9913457/wine.log)

**Comment by mbriar** [comment]
Game doesn't even load dxgi, d3d12.dll, or vkd3d-proton, no idea what's wrong but probably not a vkd3d-proton bug directly.

**Comment by dreamhunt** [comment]
Yep, I can see it but I don't why. The game doesn't see it at all and doesn't call it in any way.

**Comment by Saancreed** [comment]
@dreamhunt What does `winecfg -v` say? If not `win10` then try setting it to that with `winecfg -v win10` and try launching the game again.

**Comment by dreamhunt** [comment]
I already tried it. It's on Win10. Thank you for your suggestion.

**Comment by Blisto91** [comment]
@dreamhunt Are you still having issues with this?

**Comment by dreamhunt** [comment]
Now with latest git the game just crashes so this issue is fixed I think.
