### ISSUE TITLE
UNCHARTED: Legacy of Thieves Collection

### ISSUE THREAD

**Issue by Pickthor** [HansKristian-Work/vkd3d-proton#1277]
Hello,

### Description of the problem
During loading, after a gold coin running and just after the logo picture, I have a black screen and few second after, the game crash... I need to stop the game into Steam GUI otherwise the black screen stay 

### System information:
- Fedora 36 up-to-date
- Cpu : AMD Ryzen 5 2600 Six-Core Processor
- GPU : NVIDIA GeForce GTX 1080 and Driver : 520.56.06
- Linux : 6.0.5-200.fc36.x86_64
- Wayland & X11 tested
- Proton : 7.0-4, Experimental and GE-Proton7-38
- launch options : without and DXVK_ASYNC=1 WINEDLLOVERRIDES="amd_ags_x64.dll=b" %command% or PROTON_ENABLE_NVAPI=1 %command%

### Log files
[steam-1659420.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9910723/steam-1659420.log)

Thanks a lot for you help

**Comment by HansKristian-Work** [comment]
I believe this is the spurious hang I've seen before (can also happen on Windows). But it seems to be audio related, not vkd3d-proton.

```
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771DF0)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771E50)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771EB0)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771F10)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771F70)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008771FD0)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008772030)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008772090)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (00000000087720F0)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (0000000008772150)->(0.891251)
1979.373:0134:01cc:fixme:mmdevapi:SAO_SetVolume (00000000087721B0)->(0.891251)
```
Is spammed over and over here.

**Comment by Blisto91** [comment]
@Pickthor Friendly ping. Are you still having issues?

**Comment by Pickthor** [comment]
Issues are solved with newer version than the tested one !
Thanks a lot !
