### ISSUE TITLE
Unable to start a number of titles on Intel/Mesa DG2

### ISSUE THREAD

**Issue by djdeath** [HansKristian-Work/vkd3d-proton#1288]
We're running into this error :

```
MESA: error: src/vulkan/runtime/vk_physical_device_features.c:1311: VkPhysicalDeviceMeshShaderFeaturesEXT.multiviewMeshShader not supported (VK_ERROR_FEATURE_NOT_PRESENT)
```

Seems like vkd3d-proton is trying to enable this feature we haven't fully worked out yet.
You probably want to check for that before trying to enable it?

Not reporting the extension makes it work for us.

**Comment by HansKristian-Work** [comment]
We don't enable the feature unless the driver exposes it. The GetPhysicalDeviceFeatures2 returned value is passed directly to vkCreateDevice() here, so I'm unsure how this is possible.

**Comment by djdeath** [comment]
Uh... that's awkward.

Could this be something related to having multiple GPU on my system?

I have an AMD RX6800, an Intel A380 and ADLP (integrated)

**Comment by HansKristian-Work** [comment]
Is this reproducible in the test suite?

**Comment by djdeath** [comment]
> Is this reproducible in the test suite?
What test would that be in?

**Comment by djdeath** [comment]
I guess any :)

No, test suite appears to work fine.

**Comment by djdeath** [comment]
I wanted to print out the device features using `export VKD3D_DEBUG=trace` but apparently that's not working in steam proton experimental

**Comment by HansKristian-Work** [comment]
It's possible there's some confusion with DXGI here and device selection. Does isolating the ICD with VK_ICD_FILENAMES fix it? I've never run into this before fwiw.

**Comment by HansKristian-Work** [comment]
For Steam, trace debug is disabled, so you'd want to build yourself with debugoptimized.

**Comment by djdeath** [comment]
> It's possible there's some confusion with DXGI here and device selection. Does isolating the ICD with VK_ICD_FILENAMES fix it? I've never run into this before fwiw.

Yeah, I'm running exclusively with VK_ICD_FILENAMES set.

Will build my own version and test.

**Comment by djdeath** [comment]
Okay apologies... The Mesa overlay layer is screwing with the features.

Since I wrote it I guess I get to fix it.
