### ISSUE TITLE
Cyberpunk crashes on the Cyberpunk logo after launching the game

### ISSUE THREAD

**Issue by Zeioth** [HansKristian-Work/vkd3d-proton#1290]
Cyberpunk crashes 3 seconds after launching the game (during the cyberpunk logo). I'm almost certain this is a game bug and not DXVK's fault, as one week ago I was able to play the game perfectly well. But just to be sure:

### Software information
* Cyberpunk
* No special args passed, just PROTON_LOG

### System information
- GPU: 6700XT
- Driver:  Mesa  22.2.3-1
- Wine version:  Proton experimental.
- DXVK version: v1.10.3 (most likely)

### PROTON_LOG
[steam-1091500.log](https://github.com/doitsujin/dxvk/files/9991635/steam-1091500.log)

### Apitrace file(s)
- WIP

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Zeioth** [comment]
Moved here from https://github.com/doitsujin/dxvk/issues/3050

**Comment by Zeioth** [comment]
Issues isolated. The problem is in mesa, the game works fine with AMD_VULKAN_ICD=AMDVLK but it crashes with AMD_VULKAN_ICD=RADV. Closing.

**Comment by HansKristian-Work** [comment]
VKD3D_CONFIG=host_import_fallback should work around it. The root cause is actually a kernel bug.
