### ISSUE TITLE
Forza Horizon 5 raytracing freezes game

### ISSUE THREAD

**Issue by rudi4463** [HansKristian-Work/vkd3d-proton#1291]
CPU: Ryzen 3900
GPU: Radeon RX6800
Distro: Fedora 37
Mesa Version 22.2.3 (I also tried building mesa git but the problem is the same)
VKD3D from proton experimental 2022/11/04

All settings, except raytracing, are set to low to ensure there are no other issues or bottlenecks.

The title and loading screen work normal. After the initial loading screen you normally get a view of your car rolling up to your house which is the first rendered scene. Sadly exactly that scene is when the loading screen is over and the game freezes with a black screen. The game also freezes when loading the benchmark but for that raytracing has to be set to ultra because the lower two options only render raytracing inside the showroom and not within races and since the benchmark is a race there isn't any raytracing inside the race with the lower two options.

I also tried it with AMDVLK Q4.2 but with that one instead of the game my entire system crashes.

Launch options used are: `gamemoderun RADV_PERFTEST=rt VKD3D_CONFIG=dxr11 PROTON_LOG=1 %command%`

I've seen people use `VKD3D_FEATURE_LEVEL=12_2` but that makes the game crash upon loading screen even without raytracing.

Proton Log: uuuuuhm i wanted to upload the proton log but it's 4,7GB big. Any help as to how i can submit any useful data? Compressing it as tar.xz sadly is still too big with 75MB. No matter what i try i can't get a log smaller than 4,3GB also it's hard to tell when the game finally did freeze completely because when enabling PROTON_LOG=1 the loading screens become extremely slow to the point where you can't tell if the game just froze or not with the game standing at a standstill for up to 40 seconds before moving again. The final freeze though is final since even waiting 20 minutes doesn't resolve it.

**Comment by Blisto91** [comment]
@rudi4463 Hi there. Could i get you to try this again with latest stable mesa and Proton Experimental?

**Comment by rudi4463** [comment]
Yeah sorry has long been fixed
