### ISSUE TITLE
Uncharted 4 Rectangles graphical bug

### ISSUE THREAD

**Issue by jackbingow** [HansKristian-Work/vkd3d-proton#1294]
OS:Ubuntu 22
GPU:AMD Radeon 530
Driver gpu:amd RADV
Steam=GE-Proton7-38
I don't know how to describe bug.maybe it anti aliasing or texture light issue or shader issue.
I have also white rectangles on characters and color rectangles on character creation screen with lutris in Cyberpunk 2077 1.50.
![issue](https://user-images.githubusercontent.com/109824205/201884261-a3143a26-92b5-4bde-843f-402544718854.jpg)

**Comment by HansKristian-Work** [comment]
> AMD Radeon 530

huh? Which GPU is this?

**Comment by mbriar** [comment]
Some 3rd Gen GCN low end mobile gpu https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_500_series

**Comment by mbriar** [comment]
Try `RADV_DEBUG=nodcc,nohiz,nocompute` and see if it helps, if it does narrow it down to one of those options. But yeah, there are a bunch of bugs that only happen on these older GPU, so likely a driver bug.

**Comment by Evernow** [comment]
> Bug was in ubuntu 20 and fully updated ubuntu 22. gpu identified as AMD ICELAND RADV.

Are you saying the Uncharted 4 graphical bug was fixed once you updated or that the GPU is identified differently once updated?
