### ISSUE TITLE
Marvel's Spider-Man: Miles Morales Artifacting

### ISSUE THREAD

**Issue by GalacticalEdge** [HansKristian-Work/vkd3d-proton#1301]
My system had an RX 6600 XT running Mesa 22.2 and right now, Marvel's Spider-Man: Miles Morales is artifacting.

During the intro mission, the game didn't artifacting, but now in free roam, the game looks like this

https://imgur.com/a/16GW28P

I tried Proton Experimental and GE, which have this issue, while 7.0-4 and 7.0-5 rc don't run at all.

**Comment by mbriar** [comment]
Since you mentioned that it works fine with Mesa 22.3, this can probably be closed?
