### ISSUE TITLE
dx12 games not starting on 525.160.11 driver , vkd3d master

### ISSUE THREAD

**Issue by TURING-V2** [HansKristian-Work/vkd3d-proton#1315]
As of commit 4735b542414b66829e27343c8ca980b48b43a746 ,30 Nov  
tested on CP2077 ,Dying Light 2 .  Downgrading to 520 driver works on latest commit.
Kernel: 6.0.10-gentoo
wine-ge-proton 7-34
1650Ti mobile
Sometimes it opens and freezes with half loaded mangohud screen.
v2.7 works on 525 driver , Is new swapchain patch has specific requirement ?
[cp2077_lutris_crash_Log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10125753/cp2077_lutris_crash_Log.txt)

**Comment by mbriar** [comment]
You can try the old swapchain code with `VKD3D_CONFIG=swapchain_legacy`, but I don't think that the new code has any new hard requirements.

**Comment by HansKristian-Work** [comment]
Make sure to use latest DXVK as well. We fixed a bug in DXVK DXGI that could affect stability with new swapchain.

**Comment by TURING-V2** [comment]
info:  DXVK: v2.0-26-g9f706667

**Comment by HansKristian-Work** [comment]
Does `VKD3D_CONFIG=swapchain_legacy` work?

**Comment by TURING-V2** [comment]
nope same log with legacy page fault 
[cp2077_lutris_crash_vkd3d-legacy.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10131400/cp2077_lutris_crash_vkd3d-legacy.txt)

**Comment by TURING-V2** [comment]
if ur games work on 525 driver then , i think driver changes for prime offload apps it was specified in the release notes

**Comment by HansKristian-Work** [comment]
d3d12 isn't even loaded in that log it seems. Is it crashing in the launcher or something?

**Comment by TURING-V2** [comment]
its not using launcher its started directly Cyberpunk2077.exe

**Comment by TURING-V2** [comment]
installed vkd3d again and this time logs shows vkd3d loaded and screen froze with and without swapchain_legacy flag.
from dmesg spammed 5 times
 NVRM: Xid (PCI:0000:01:00): 32, pid=12890, name=GameThread, Channel ID 00000028 intr1 00000008 HCE_DBG0 00001b00 HCE_DBG1 00000001
 info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 39). It seems like application has stopped creating new PSOs for the time being.
![screenshot](https://user-images.githubusercontent.com/29421472/205075187-d316f349-a771-4160-be37-acfbd36fef72.png)
[cp2077_lutris_crash_Log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10133095/cp2077_lutris_crash_Log.txt)
