### ISSUE TITLE
VK_KHR_present_{id,wait} causes device loss on Nvidia 525.60.11 on PRIME setups

### ISSUE THREAD

**Issue by Saancreed** [HansKristian-Work/vkd3d-proton#1317]
Attempting to launch Deep Rock Galactic in DX12 mode always results in a device loss.

DE: KDE Plasma / kwin X11
GPU: GTX 1660 Ti Mobile (PRIME render offload)
Driver: 525.60.11
Proton: experimental-7.0-20221129
Commit: 8c0f277b7c3880c6242c1aded189b1ae43ec161a (this is the current master, version bundled with Proton dies because of assert failure which has been fixed since then)

Log created with `PROTON_LOG=1 VKD3D_CONFIG=breadcrumbs`:  [steam-548430.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10143204/steam-548430.log)

When the error happens, an error is printed to dmesg:

```
NVRM: Xid (PCI:0000:01:00): 32, pid=32262, name=FSD-Win64-Shipp, Channel ID 00000028 intr1 00000008 HCE_DBG0 00001b00 HCE_DBG1 00000001
NVRM: Xid (PCI:0000:01:00): 32, pid=32262, name=FSD-Win64-Shipp, Channel ID 00000028 intr1 00000008 HCE_DBG0 00001b04 HCE_DBG1 02bb5010
```

**Comment by TURING-V2** [comment]
similar issue https://github.com/HansKristian-Work/vkd3d-proton/issues/1315#issuecomment-1333836687
have u tried VKD3D_CONFIG=swapchain_legacy ?
does all ur dx12 not working or this only ?

**Comment by K0bin** [comment]
@TURING-V2 No, it's not. That issue is about totally different games.

**Comment by Saancreed** [comment]
@TURING-V2 Still doesn't work with `VKD3D_CONFIG=swapchain_legacy`. However, I rolled back vkd3d-proton to whatever version Experimental had before 20221129 update and that one (3fdbec990d3dbbff63e66ab8e9fb1a226fabf4a1) still works so I'll try to bisect.

Would be funny if it turned out to be 3c2302276fe9112070a74d40cdb96b496f546662 here as well.

**Comment by Saancreed** [comment]
```
45e67a34ec1fec3d5ef152bb71d1d25d61b17e29 is the first bad commit
commit 45e67a34ec1fec3d5ef152bb71d1d25d61b17e29
Author: Hans-Kristian Arntzen <post@arntzen-software.no>
Date:   Tue Oct 18 12:08:43 2022 +0200

    vkd3d: Enable VK_KHR_present_wait.
    
    Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

 libs/vkd3d/device.c        | 14 ++++++++++++++
 libs/vkd3d/vkd3d_private.h |  4 ++++
 libs/vkd3d/vulkan_procs.h  |  3 +++
 3 files changed, 21 insertions(+)
```

Surely enough, latest master starts working just fine if I add `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait` to launch options.

**Comment by mbriar** [comment]
Hmm? The legacy swapchain with VKD3D_CONFIG=swapchain_legacy also shouldn't actually make use of VK_KHR_present_wait at all, so is it just enabling the extensions at all that breaks it? Sounds like a driver bug if so.

**Comment by Saancreed** [comment]
Indeed, the first bad commit also doesn't seem to make use of the extension so it would make sense that `VKD3D_CONFIG=swapchain_legacy` doesn't resolve it if the extension is enabled even if the new swapchain is not used.

I suppose I should send email to NV about this :/

**Comment by TURING-V2** [comment]
> @TURING-V2 No, it's not. That issue is about totally different games.

Allow me to shed some light , tried on another game Death Stranding same result opens black screen with half mangohud and freezes. dmesg spam NVRM Xid 32.
With `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait` Death Stranding and CP2077(deleting app local cache)  both starts working . with 525 driver latest vkd3d 
On 515 driver _without_ `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait ` Both games working fine .
Tried same results with Dying Light 2 . Any other dx12 u want me to test ?
I can say both are same issue Indeed A driver bug in Nvidia 525.60.11 .New Issue detailed report on there open-kernel-modules will maybe . wait for new driver )

**Comment by tjhexf** [comment]
Non prime setup, same issue. I'm the one mentioned by the Warframe issue

**Comment by HansKristian-Work** [comment]
Hm, I am also able to reproduce this under specific circumstances. It reproduces in my Granite engine as well, so it's not vkd3d-proton doing something weird.

- Desktop: Does not repro
- My laptop not connected to HDMI with nvidia-xconfig --prime (NV shows up in glxinfo). Does not reproduce, but everything tears.
- Laptop not connected to HDMI without xorg.conf, Intel shows up in glxinfo. Now it hangs immediately by just enabling the extension.

**Comment by HansKristian-Work** [comment]
parallel-rdp uses Granite, which uses present_wait, so that's expected I guess.

**Comment by tgurr** [comment]
Just updated to [525.60.13](https://download.nvidia.com/XFree86/Linux-x86_64/525.60.13/) which apparently still has this problem and additionally now the game started to crash for me with 
![Screenshot_20221210_183555](https://user-images.githubusercontent.com/414984/206868209-e69d3e8f-9b35-4511-bc55-4328f3727d8f.png)
either more or less right after entering the game or in the start/middle of a mission.
NVIDIA GeForce RTX 2060 SUPER with 8GB of VRAM - which was happily working before.

**Comment by Saancreed** [comment]
Fwiw latest NV Vulkan beta driver 525.47.04 has the following note in its changelog:

> Fixed a bug where usage of VK_KHR_present_id could cause applications to crash with Xid 32 errors [Linux]

And indeed, this version works even with ac7e7de701ad336887c1cb38f8adc4e588005962 reverted on top of current `master`.
