### ISSUE TITLE
The Witcher 3 crashes after the intro

### ISSUE THREAD

**Issue by shmerl** [HansKristian-Work/vkd3d-proton#1338]
The new version of the Witcher 3 (4.0) when run in DX12 mode crashes after starting the game and finishing or skipping the intro cut scene in Kaer Morhen.

I see such error when this happens:

```
01d8:info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 12). It seems like application has stopped creating new PSOs for the time being.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 12). It seems like application has stopped creating new PSOs for the time being.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 193). It seems like application has stopped creating new PSOs for the time being.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 2). It seems like application has stopped creating new PSOs for the time being.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 2). It seems like application has stopped creating new PSOs for the time being.
01d8:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
Assertion failed: !status, file dlls/winevulkan/loader_thunks.c, line 3145
```

* Tested with wine 8.0-rc1, current vkd3d-proton master, Mesa main (radv).
* Kernel: 6.1.0
* GPU: RX 6800 XT.

**Comment by HansKristian-Work** [comment]
Should be fixed already on master.

**Comment by shmerl** [comment]
I can confirm that it indeed works with latest master!

Performance is surprisingly bad though, but at least it's not crashing anymore.

**Comment by K0bin** [comment]
> Performance is surprisingly bad though, but at least it's not crashing anymore. I can look into performance more and open a separate bug if needed.

D3D12 performance in Witcher 3 seems to be bad on Windows too.

**Comment by jorgicio** [comment]
> I can confirm that it indeed works with latest master!
> 
> Performance is surprisingly bad though, but at least it's not crashing anymore. I can look into performance more and open a separate bug if needed.

Have you tried with FSR in DX12? I could it make it work with Proton Experimental Bleeding Edge, and setting FSR in Balanced may improve the performance.

**Comment by shmerl** [comment]
I haven't tried FSR, but point is that DX11 performance used to be way better and I don't see any major change in graphics quality. One shouldn't need upscaling for it to work well.
