### ISSUE TITLE
VKD3D_FEATURE_LEVEL=12_0 in windows

### ISSUE THREAD

**Issue by jackbingow** [HansKristian-Work/vkd3d-proton#1341]
Env variables
set VKD3D_FEATURE_LEVEL=12_0
game still says FEATURE LEVEL 12_0 is missing.
is there config file to not set env variable or bypass check in windows?

**Comment by K0bin** [comment]
It might actually try to use one of the FL12 features which would fail if your GPU doesn't support it. It's impossible to say more without logs.

**Comment by jackbingow** [comment]
@K0bin
is there config file like in dxvk to set maxfeaturelevel.
GPU supports 12_0 according to GPU-Z. But in windows 7 Max support is dx 11. I thought vkd3d-proton converts d3d12 call to vulkan ones. In Linux Env variable to fool game work.
In Windows how to pass varialble  VKD3D_FEATURE_LEVEL=12_0 to d3d12.dll?
 In main page of this repo mentions windows as test enviroment.
How to log in windows?

**Comment by K0bin** [comment]
Windows is not supported and if your GPU doesn't support a particular feature level, it also won't support the equivalent Vulkan features that VKD3D-Proton requires.

**Comment by jackbingow** [comment]
@K0bin In Windows how to pass env Variables for logging?

**Comment by Blisto91** [comment]
You can just set the env variables like you [normally would through Windows.](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)
