### ISSUE TITLE
Marvel's Guardians of the Galaxy flickering clouds in a cutscene

### ISSUE THREAD

**Issue by valters-tomsons** [HansKristian-Work/vkd3d-proton#1346]
At the beginning of the third chapter in the game, you're flying to a planet through some clouds which seem to flicker with black squares.

<details>
  <summary>Screenshots</summary>

![20221217171856_1](https://user-images.githubusercontent.com/4209639/208249439-752b30b9-0a85-4351-9fa2-15953b0478af.jpg)

![20221217170129_1](https://user-images.githubusercontent.com/4209639/208249435-5833cb6e-b045-4eb5-b96e-8072a6cb8361.jpg)

![20221217171855_1](https://user-images.githubusercontent.com/4209639/208249438-ec34edac-4eca-401c-b70b-50cea4a55741.jpg)

</details>

Tested with e8d00f7092260383778dfca37981fe097d787295 and d00d035321c9f817e058985e32fe6876ba746de6

GPU: RX 6700 10GB
Arch Linux / Mesa 22.2.3-1

Log: [steam-1088850.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10252076/steam-1088850.log)

**Comment by HansKristian-Work** [comment]
Is possible to share saves so it can be reproduced?

**Comment by valters-tomsons** [comment]
Just tested the with Mesa `22.3.2`, no longer seeing the artifacts.

---

Regardless, here is my save game. I've gotten a bit further than the scene in OP, so you'll have to progress on your own for a couple of minutes.

[gotgsavegame.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/10361508/gotgsavegame.zip)

1. Copy save game to `userdata\user-id\1088850\remote\`
2. Launch game, go to `Chapters` in main menu and select `Chapter 3` 
3. Once in-game, go to your room (go straight, then to left and the last door with green floating thing)
4. Interact with cards on the table
5. Keep pressing Space to skip dialogs, pick whatever choices when prompted
6. Shortly after the second choice prompt, a cut-scene will play where you're flying to a planet
7. Profit?

**Comment by Blisto91** [comment]
@valters-tomsons Is it correct that this issue is solved?
I wasn't able to reproduce either. (can only go back to mesa 22.3 with my gpu)
