### ISSUE TITLE
Horizon Zero Dawn crashing

### ISSUE THREAD

**Issue by adolfotregosa** [HansKristian-Work/vkd3d-proton#1349]
I really don't think it is vkd3d fault but am I alone ? Nvidia 525 driver , latest arch and proton, game simply freezes. Did anyone find a work around ?

**Comment by K0bin** [comment]
Please provide logs.

**Comment by adolfotregosa** [comment]
> Please provide logs.
Proton log
[steam-1151640.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10273255/steam-1151640.log)

**Comment by adolfotregosa** [comment]
Latest proton experimental seam to fix the issue. Closing
