### ISSUE TITLE
[Question] Future use of official microsoft shader compiler?

### ISSUE THREAD

**Issue by Ratatouilledummie** [HansKristian-Work/vkd3d-proton#1350]
Sorry for these question, but the project have plans to integrate support to use microsoft shader compiler instead the vkd3d compiler? https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2212
these compiler have support to generate SPIR-V code from HLSL, and sorry for the question

**Comment by mbriar** [comment]
vkd3d-proton does not handle HLSL at all, games usually ship shaders in DXBC or DXIL bytecode, which is the only thing you can use directly with d3d12. So this is not really useful.
