### ISSUE TITLE
[Question] Is the vkd3d-proton cache dependent on hardware?

### ISSUE THREAD

**Issue by begin-theadventure** [HansKristian-Work/vkd3d-proton#1351]
Or is it hardware agnostic like dxvk state cache?

**Comment by mbriar** [comment]
The cache relies on the vulkan driver's shader cache to do the actual caching and uses VK_EXT_shader_module_identifier to skip compilation if a pipeline is present in the cache. There is no point sharing it, if that's what you're asking.

**Comment by begin-theadventure** [comment]
Thank you for the answer.

**Comment by K0bin** [comment]
FWIW the DXVK state cache isn't fully hardware agnostic either.
