### ISSUE TITLE
Shadow of Tomb Raider Crashes with any Shadow Quality preset 

### ISSUE THREAD

**Issue by DashCruft** [HansKristian-Work/vkd3d-proton#1352]
As the title says, the game completely crashes by using VKD3D and any shadow quality setting in-game (except OFF). This issue doesn't occur on DX11 at all and functions just fine.

Here's the log when the crash occurs:
```
../src/vulkan/wsi/wsi_common_x11.c:1264: Swapchain status changed to VK_SUBOPTIMAL_KHR
../src/vulkan/wsi/wsi_common_x11.c:1264: Swapchain status changed to VK_SUBOPTIMAL_KHR
../src/vulkan/wsi/wsi_common_x11.c:1620: Swapchain status changed to VK_SUBOPTIMAL_KHR
../src/vulkan/wsi/wsi_common_x11.c:1264: Swapchain status changed to VK_SUBOPTIMAL_KHR
0834:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0aac:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
```

**Comment by mbriar** [comment]
Known issue on RADV
https://github.com/HansKristian-Work/vkd3d-proton/issues/1214#issuecomment-1236098535
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5828

Try AMDVLK maybe, it's not a vkd3d-proton bug as far as i'm aware.

**Comment by DashCruft** [comment]
Surprised it's been 11 months without an update. Although the Linux build of the game exists, it wouldn't be wrong to have support for possibly the future upcoming titles lacking the support for depth and stencil sparse images. I will open another issue in mesa.

**Comment by DashCruft** [comment]
Closing this since it's unrelated to VKD3D-Proton. I will keep it updated if anything occurs.
