### ISSUE TITLE
Root Constants issue

### ISSUE THREAD

**Issue by kingofthebongo2008** [HansKristian-Work/vkd3d-proton#1355]
Hello,
I have a signature which looks like this

#define MyRS_D3DStats "RootFlags( ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT ), " \
              "CBV(b0, visibility = SHADER_VISIBILITY_VERTEX, flags = DATA_STATIC_WHILE_SET_AT_EXECUTE ), " \
              "RootConstants(num32BitConstants=8, b0, visibility = SHADER_VISIBILITY_PIXEL), " \
	      "DescriptorTable(SRV(t0, numDescriptors = 1, flags = DATA_STATIC_WHILE_SET_AT_EXECUTE ), visibility = SHADER_VISIBILITY_PIXEL)," \
              "StaticSampler(s0, addressU = TEXTURE_ADDRESS_CLAMP,  addressV = TEXTURE_ADDRESS_CLAMP, addressW = TEXTURE_ADDRESS_CLAMP, filter = FILTER_MIN_MAG_MIP_LINEAR )"

On load i get break point here in the spir converter:

	if (member_index >= num_elements)
	{
		LOGE("Root constant CBV is accessed out of bounds. (%u > %u).\n", member_index, num_elements);
		return false;
	}

member index = 13, 
num_elements = 10

if i increase the num32BitConstants to 16 or 32, it works
If i convert this to cbv works also

The shaders are compiled with dxc

      <ShaderModel>6.0</ShaderModel>
      <AdditionalOptions>-Zi -all_resources_bound -Fd %(Filename).pdb</AdditionalOptions>

The pixel shader which uses the root constans is:

struct LitMaterialPixel
{
    float4   m_alpha_factor;
    float4   m_texture_factor;
};

ConstantBuffer<LitMaterialPixel>   	g_MaterialPixel  : register(b0);

**Comment by K0bin** [comment]
Could you upload the problematic shader or a simplified version that reproduces the issue?

**Comment by kingofthebongo2008** [comment]
[d3d_ui_stats_pixel.hlsli.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304859/d3d_ui_stats_pixel.hlsli.txt)
[d3d_ui_stats_vertex.hlsli.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304860/d3d_ui_stats_vertex.hlsli.txt)
[default_signature.hlsli.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304861/default_signature.hlsli.txt)
[myrs_stats_rs.hlsli.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304862/myrs_stats_rs.hlsli.txt)

**Comment by kingofthebongo2008** [comment]
This is the msbuild task which builds the shader, to h file, which is embedded into the executable

<ItemGroup>	
    <FxCompile Include="@(RootSignature)">
      <VariableName>g_%(Filename)</VariableName>
      <HeaderFileOutput>$(IntermediateOutputPath)\%(Filename).h</HeaderFileOutput>
      <ObjectFileOutput />
      <ShaderType>RootSignature</ShaderType>
      <ShaderModel>rootsig_1.1</ShaderModel>
    </FxCompile>
</ItemGroup>

<ItemGroup>	
    <FxCompile Include="@(VertexShader)">
      <VariableName>g_%(Filename)</VariableName>
      <HeaderFileOutput>$(IntermediateOutputPath)\%(Filename).h</HeaderFileOutput>
      <ObjectFileOutput />
      <ShaderType>Vertex</ShaderType>
      <ShaderModel>6.0</ShaderModel>
      <AdditionalOptions>-Zi -all_resources_bound -Fd %(Filename).pdb</AdditionalOptions>

    </FxCompile>
</ItemGroup>


<ItemGroup>	
    <FxCompile Include="@(PixelShader)">
      <VariableName>g_%(Filename)</VariableName>
      <HeaderFileOutput>$(IntermediateOutputPath)\%(Filename).h</HeaderFileOutput>
      <ObjectFileOutput />
      <ShaderType>Pixel</ShaderType>
      <ShaderModel>6.0</ShaderModel>
      <AdditionalOptions>-Zi -all_resources_bound -Fd %(Filename).pdb</AdditionalOptions>
    </FxCompile>
</ItemGroup>

**Comment by kingofthebongo2008** [comment]
[d3d_ui_stats_d3d12_pixel.h.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304872/d3d_ui_stats_d3d12_pixel.h.txt)
[d3d_ui_stats_d3d12_vertex.h.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10304873/d3d_ui_stats_d3d12_vertex.h.txt)

**Comment by kingofthebongo2008** [comment]
these are the two shaders, the problem first happens to the vertex shader, it does not get to the pixel shader,

proton version is from main pulled out two days ago

**Comment by HansKristian-Work** [comment]
I'll have a look, it might be possible that we don't properly check the stage visibility somewhere.

**Comment by HansKristian-Work** [comment]
I can reproduce it.
