### ISSUE TITLE
Battlefield V Sometimes tanks in performance. Single digit FPS.

### ISSUE THREAD

**Issue by LethalManBoob** [HansKristian-Work/vkd3d-proton#1370]
OS: Arch Linux x86_64
Kernel: 6.1.3-1-cachyos-bore
Resolution: 1920x1080 @ 144Hz
DE: GNOME 43.2
WM: Mutter (X11)
CPU: AMD Ryzen 7 5800X (8) @ 4.520645 
GPU: NVIDIA GeForce RTX 3070 
NVIDIA 525.78.01

It may be influenced by being on ultra. I recall having the same fps issues on dx11 a long time ago when post process was set above normal

**Comment by GalacticalEdge** [comment]
Did you add `PROTON_ENABLE_NVAPI=1`? It helps on Nvidia GPUs in Battlefield games

**Comment by LethalManBoob** [comment]
> Did you add `PROTON_ENABLE_NVAPI=1`? It helps on Nvidia GPUs in Battlefield games
I have enabled "ENABLE NVIDIA-NVAPI / DLSS" on lutris

**Comment by Blisto91** [comment]
@LethalManBoob Hi there. Are you still having and issues here? Sounds like it could be vram getting overfilled maybe?

**Comment by LethalManBoob** [comment]
> @LethalManBoob Hi there. Are you still having and issues here? Sounds like it could be vram getting overfilled maybe?

it wasnt a vram issue afaik but i reinstalled wirth ge-proton 22 and it hasent happned yet. ill keep this updated if it happens again

**Comment by shelterx** [comment]
You might want to close this since BFV is no longer working.

**Comment by LethalManBoob** [comment]
> You might want to close this since BFV is no longer working.

well i havent had the issue in a long time. but now that time will be forever considering ea introducing malware/spyware into their games. good riddence.
