### ISSUE TITLE
"fatal error: vkd3d_d3d12.h: No such file or directory" but the file it's on .gitignore

### ISSUE THREAD

**Issue by Toni500github** [HansKristian-Work/vkd3d-proton#1378]
i wanted to test some files on the `tests` folder, but when i try to compile some files, gives me this error and i looked up on `.gitignore`, on the local include folder, the `vkd3d_d3d12.h` header file it's there.

**Comment by Joshua-Ashton** [comment]
This file is built by the build system with widl, how are you trying to build?

**Comment by Toni500github** [comment]
didn't know about that tool, how can i build all the .idl files in just one command?

**Comment by HansKristian-Work** [comment]
This is confusing. Are you trying to build vkd3d-proton outside the meson build system? If that's the goal you're on your own. Look at ninja --verbose output to see what it's doing, but it's just calling widl I think.

**Comment by Toni500github** [comment]
> This is confusing. Are you trying to build vkd3d-proton outside the meson build system? If that's the goal you're on your own. Look at ninja --verbose output to see what it's doing, but it's just calling widl I think.

i'm so sorry if it's confusing, basically when i installed the `.dll` files on `WINEPREFIX`, i wanted to try some `tests` on it's folder, but when i compiled some, they gave the error that there is no such file on it's include folder, and when i remembered about the `widl` command, i wanted to complie every .idl files in just one command. so sorry if this issue it's useless

**Comment by Blisto91** [comment]
@Toni500github Did you figure out your issue?
