### ISSUE TITLE
Dead Space: Empty Save Slot icon seems to be random texture

### ISSUE THREAD

**Issue by K0bin** [HansKristian-Work/vkd3d-proton#1397]
![Screenshot_20230128_042808](https://user-images.githubusercontent.com/1131720/215240645-f4ee45ef-5f76-45dc-b7a4-7b5fb5bf7dd2.png)
![Screenshot_20230128_041242](https://user-images.githubusercontent.com/1131720/215240641-c6cf29e4-7d63-455b-af41-7dad3c0eb2a2.png)
![Screenshot_20230128_041805](https://user-images.githubusercontent.com/1131720/215240642-dec08061-d27e-43e4-bcbd-15d89f877458.png)
![Screenshot_20230128_042556](https://user-images.githubusercontent.com/1131720/215240644-8feaeb56-0956-49b4-b140-199b7438713e.png)

Nvidia RTX 3090 with 525.60.11.
Using e063e50d91846cb8cfa4d2e139f2a9e220768389 + my dxil-spirv PR to fix RT.

**Comment by rurigk** [comment]
It happens to me as well

Arch Linux
mesa-22.3.3-3
vulkan-radeon-22.3.3-3
AMD RX 6700 XT
