### ISSUE TITLE
Hogwarts Legacy - Missing textures on characters

### ISSUE THREAD

**Issue by DistantThunder** [HansKristian-Work/vkd3d-proton#1422]
Hi,
I'm reporting this because for what I've looked, the Windows / console versions don't seem to have this problem.

# System Information

```
System:
  Host: _HOST_ Kernel: 6.1.8-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc
    v: 12.2.1 Desktop: KDE Plasma v: 5.26.5 tk: Qt v: 5.15.8 wm: kwin_wayland
    dm: 1: LightDM note: stopped 2: SDDM Distro: Arch Linux
CPU:
  Info: 8-core model: AMD Ryzen 7 5800X bits: 64 type: MT MCP arch: Zen 3
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 4700 high: 4701 min/max: 2200/5006 boost: enabled cores:
    1: 4700 2: 4700 3: 4700 4: 4700 5: 4700 6: 4700 7: 4700 8: 4701 9: 4700
    10: 4700 11: 4700 12: 4700 13: 4700 14: 4700 15: 4700 16: 4700
    bogomips: 121600
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] vendor: XFX
    driver: amdgpu v: kernel arch: RDNA-3 pcie: speed: 16 GT/s lanes: 16 ports:
    active: DP-1 empty: DP-2,DP-3,HDMI-A-1 bus-ID: 28:00.0 chip-ID: 1002:744c
  Device-2: A4Tech USB Live camera type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 1-1.1:24 chip-ID: 09da:2690
  Display: wayland server: X.org v: 1.21.1.6 with: Xwayland v: 22.1.7
    compositor: kwin_wayland driver: X: loaded: amdgpu dri: radeonsi gpu: amdgpu
    display-ID: 0
  Monitor-1: DP-1 res: 2560x1440 size: N/A
  API: OpenGL v: 4.6 Mesa 23.1.0-devel (git-e37f458207) renderer: AMD
    Radeon Graphics (gfx1100 LLVM 15.0.7 DRM 3.49 6.1.8-zen1-1-zen)
    direct render: Yes

* Proton Experimental --> 1675282930 experimental-7.0-20230201
* VKD3D 2.x?

```

## Problem description

As said in the title, sometimes some or all of some character models including the player disappears/turns black. And depending if you reload the game or play with the camera, they pop back.

## Problem illustration
---

![2023-02-08_23-20](https://user-images.githubusercontent.com/3923810/217672587-b4c61434-0314-48ed-b9d1-31e4a7a47eb8.png)

![2023-02-08_23-21](https://user-images.githubusercontent.com/3923810/217672646-c8ee69df-d40b-4671-babb-57ad80660348.png)
-
![2023-02-08_23-22](https://user-images.githubusercontent.com/3923810/217672695-3af85dcf-6a6d-4dc7-86bc-c52e3025ab46.png)
---
## Logs

* VKD3D : [hl_debug.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/10690619/hl_debug.tar.gz)
* GFXRECON : https://transfert.free.fr/lI4pJ2

**Comment by Blisto91** [comment]
Hello there!

This is a known driver issue with radv and rdna3 cards. There is a mesa MR which which will work around the issue when merged https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21186

In the mean time you can also work around it by launching the game with `RADV_DEBUG=nodcc %command%`

**Comment by Blisto91** [comment]
MR has been merged into mesa main
