### ISSUE TITLE
Xenia and xenia-canary crash after opening the application

### ISSUE THREAD

**Issue by Fabxx** [HansKristian-Work/vkd3d-proton#1424]
Platform: Arch Linux (details of environment at end of log)

GPU: GTX 970 STRIX
CPU: i7-10700

tested with both vkd3d stable release, and compiled source code, the application crashes at launch with a unhandled page fault error, here are the screen and the log:

xenia-canary:
[log1.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10713797/log1.txt)

![image](https://user-images.githubusercontent.com/30447649/218262089-b39f879d-bf55-4676-b243-9bae03cfb7a5.png)

xenia:
[log2 (error buffer).txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10713822/log2.error.buffer.txt)
[log2 (info buffer).txt](https://github.com/HansKristian-Work/vkd3d-proton/files/10713823/log2.info.buffer.txt)

**Comment by doitsujin** [comment]
According to the log the crash happens inside wine's DXGI, not in any of our code.

Please try using DXVK's DXGI in combination with vkd3d-proton, current development code **requires** that anyway.

**Comment by Fabxx** [comment]
> According to the log the crash happens inside wine's DXGI, not in any of our code.
> 
> Please try using DXVK's DXGI in combination with vkd3d-proton, current development code **requires** that anyway.

how do i enable DXVK's dxgi inside the prefix when vkd3d-proton is installed?

**Comment by mbriar** [comment]
Just install DXVK like normal, make sure dxgi.dll is set to native.

**Comment by Fabxx** [comment]
> 

this fixed it, thanks for the help.
