### ISSUE TITLE
HDR support not working with Mass Effect Legendary Edition

### ISSUE THREAD

**Issue by ILOVEPIE** [HansKristian-Work/vkd3d-proton#1428]
I've gotten HDR enabled in gamescope and my display detects the HDR signal, but hogwarts legacy still keeps its HDR firmly disabled. Does anyone else have this problem?

**Comment by mbriar** [comment]
Are you using latest DXVK and Proton Experimental and also set DXVK_HDR=1?

**Comment by ILOVEPIE** [comment]
Yes, although Hogwarts Legacy is a directx 12 game I think.

**Comment by ILOVEPIE** [comment]
I also seem to have this problem with Mass Effect Legendary Edition too.

**Comment by ILOVEPIE** [comment]
Hogwarts legacy seems to be working now, but not Mass Effect Legendary Edition.

**Comment by ILOVEPIE** [comment]
Moving this to DXVK as Mass Effect is not a DX12 game.

**Comment by mbriar** [comment]
Many DX11 games will probably not work right now or ever because they use vendor libraries like nvapi or amdags to enable HDR.
