### ISSUE TITLE
[regression] Like a Dragon: Ishin! broken on experimental

### ISSUE THREAD

**Issue by Blisto91** [HansKristian-Work/vkd3d-proton#1436]
Like a Dragon: Ishin! doesn't launch on Proton experimental. Bisected to start with commit https://github.com/HansKristian-Work/vkd3d-proton/commit/6c8542f7d62e2f262ff14b84fa8ff15a02c01b4c
`VKD3D_SHADER_CACHE_PATH=0` can work around the issue

### Software information
Like a Dragon: Ishin!

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton experimental
- VKD3D-Proton version: https://github.com/HansKristian-Work/vkd3d-proton/commit/6c8542f7d62e2f262ff14b84fa8ff15a02c01b4c and above

### Log files
[steam-1805480.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10771797/steam-1805480.log)

**Comment by Blisto91** [comment]
MR for the issue https://github.com/HansKristian-Work/vkd3d-proton/pull/1438


> Side note, was gonna create its own issue for this but ill ask here first, is the game not making a cache file for anyone else? Neither of the exe's the game ship with have a cache file. Not sure if the game manages its own or something but the readme here implies VKD3D overrides games that mange their own by default.

I don't know anything about that personally so gonna leave that to the devs.

**Comment by Bitwolfies** [comment]
> MR for the issue #1438
> 
> > Side note, was gonna create its own issue for this but ill ask here first, is the game not making a cache file for anyone else? Neither of the exe's the game ship with have a cache file. Not sure if the game manages its own or something but the readme here implies VKD3D overrides games that mange their own by default.
> 
> I don't know anything about that personally so gonna leave that to the devs.

With this patch it is now creating the cache file, wonder what that was about.

**Comment by Blisto91** [comment]
The broken commit was about disk cache
