### ISSUE TITLE
GPU isn't fully loaded in CP2077

### ISSUE THREAD

**Issue by shmerl** [HansKristian-Work/vkd3d-proton#1442]
I just tested CP2077 with Sapphire Pulse RX 7900 XTX and noticed that in comparison with 6800 XT while performance is better, GPU is also not fully loaded, which potentially means performance isn't as good as it could be if GPU was loaded more.

Set up:
* resolution: 2560x1440
* CPU: Ryzen 9 5900X
* Settings: ultra, ray tracing off, no upscaling
* radv: Mesa main (git-ed76833705)
* vkd3d-proton master (git-7be64c2353)
* Wine 8.2

**6800 XT** (full GPU load)
![cp2077_6800xt_nort](https://user-images.githubusercontent.com/310927/221098569-9def3053-e7f8-4d00-9c3c-beff645dba79.jpg)

**7900 XTX** 75%-90% load (not sure what it depends on):
![cp2077_7900xtx_nort](https://user-images.githubusercontent.com/310927/221098637-12e027df-05ed-40ec-921e-caf084387b93.jpg)

Could it be an issue with vkd3d-proton not using resources better?

**Comment by mbriar** [comment]
Is this plain wine without esync/fsync? If yes, that would be an obvious place to start looking for what seems to be a cpu-bottleneck that is not necessarily caused by just vkd3d-proton.

**Comment by shmerl** [comment]
Yes, it's a plain Wine. Never had this issue before with 6800 XT though, and from what I've read the need for fsync is pretty rare and often it can make things only worse. Never heard of CP2077 needing it too.

**Comment by mbriar** [comment]
fsync being a benefit over esync is rare, either of those being a massive benefit over default wine-server sync is very common. Now you have more gpu headroom, so you can hit a cpu bottleneck more easily.

**Comment by shmerl** [comment]
I'll take a look. Did Wine land fsync support already behind some variable? Upstream kernels have needed interfaces already with futex2, right? I'm using 6.2.0.

**Comment by mbriar** [comment]
No, fsync isn't in upstream wine, but the required interface is in the kernel since 5.14 or something.

**Comment by shmerl** [comment]
Looks like Wine staging should have esync, I'll give it a try. What happened to upstreaming fsync, something didn't work out or it's not ready yet?

**Comment by Blisto91** [comment]
fsync and esync almost with certancy won't be upstreamed.
winesync/ntsync/fastsync (it's had a few names) might be at some point. But that's another matter.

As mbriar said a test with esync or fsync might be interesting.

**Comment by shmerl** [comment]
Hm, the game doesn't even start with current Wine staging. I'll try this a bit later, may be with upstream Wine with only esync or fsync patches applied.

**Comment by shmerl** [comment]
OK, build Wine 8.2 with just esync patches and enabled it. It does help!

![esync](https://user-images.githubusercontent.com/310927/221137027-ba4f7962-54e7-44d6-9bac-b5772131fb63.jpg)

Framerate went from 112 fps to around 150 fps. Though GPU load is still not shown as 100%.

**Comment by shmerl** [comment]
Also tested DX12 version of the Witcher 3 - esync also massively helps there. Thanks for the tip that it's still useful. I thought esync / fsync kind of was needed only for some rare edge cases.

**Comment by mbriar** [comment]
You can look at `perf top -s comm,dso,symbol -p $cp77_pid` i guess to see if anything sticks out why it's still cpu limited (best with symbols compiled in for vkd3d-proton and radv), but tbh, I wouldn't expect that every, or even most, games can max out a 7900XTX at only 1440p without RT.

**Comment by mbriar** [comment]
esync/fsync is basically a requirement for acceptable perf for any game that's highly multi-threaded. Win32 thread synchronization primitives are quite slow with default wineserver sync.

**Comment by shmerl** [comment]
Thanks, I'll close it since it's not a vkd3d-proton issue. Will look more with perf at some point.

**Comment by shmerl** [comment]
I figured out what was going on. Somehow FSR got enabled, that's why GPU wasn't loaded even with esync. Without FSR it gets full load.

**Comment by shmerl** [comment]
> winesync/ntsync/fastsync (it's had a few names) might be at some point. But that's another matter.

Where can I track this? It would be nice to have such improvident in the upstream.

**Comment by Blisto91** [comment]
https://repo.or.cz/linux/zf.git/shortlog/refs/heads/winesync4 and https://repo.or.cz/wine/zf.git/shortlog/refs/heads/fastsync4 (i think)

And LGD

**Comment by shmerl** [comment]
LGD?

**Comment by Blisto91** [comment]
The Linux Gaming Dev discord
