### ISSUE TITLE
d3d12core.dll dummy companion for the AgilitySDK

### ISSUE THREAD

**Issue by xpander69** [HansKristian-Work/vkd3d-proton#1456]
Discussed On discord, but basically:
WRC Generations fails to load AgilitySDK: https://github.com/ValveSoftware/Proton/issues/6288

```
284665.179:0110:0114:trace:file:nt_to_unix_file_name_no_root L"windows\\system32\\WindowsPowershell\\v1.0\\D3D12Core.dll" not found in /mnt/SSDGames/SteamLibrary/steamapps/compatdata/1953520/pfx/dosdevices/c:/windows/system32/WindowsPowerShell/v1.0
284665.179:0110:0114:warn:file:NtCreateFile L"\\??\\C:\\windows\\system32\\WindowsPowershell\\v1.0\\D3D12Core.dll" not found (c0000034)
284665.179:0110:0114:trace:module:LdrGetDllHandleEx L"D3D12Core.dll" -> 0000000000000000 (load path (null))
```

### Software information
WRC Generations – The FIA WRC Official Game (1953520)

launched with WINEDLLOVERRIDES="xinput1_3=n,b" to get past the input handling bugs

### System information
- GPU: RTX 3080
- Driver: 530.30.02
- Wine version:  Proton7,ProtonExp, GE-Proton7-50
- VKD3D-Proton version: 2.8 and latest master builds

### Log files
Log with PROTON_LOG=+module,+file

[steam-1953520.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10912842/steam-1953520.log)

**Comment by xpander69** [comment]
Posting here, so it wont get lost as discord message:

Not sure if this PR currently is broken (https://github.com/HansKristian-Work/vkd3d-proton/pull/1458) but with that the WRC Generations seems to load AgilitySDK just fine and launches the game window but seems to crash with shader compiler:

```
error: line 171: Block '750[%750]' is already a merge block for another header
  %main = OpFunction %void None %3
```

Shader dump file here: 
[wrcg_shaderdump.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/10951262/wrcg_shaderdump.zip)

Discussions on Proton github about the game: https://github.com/ValveSoftware/Proton/issues/6288#issuecomment-1464843848

**Comment by HansKristian-Work** [comment]
Merged now.
