### ISSUE TITLE
Do not create GlobalBuffer if we don't intend to use it

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#1461]
To improve churn on capture layers, we can improve memory allocator to:

- Not allocate GlobalBuffer for committed textures which we don't suballocate and we don't use explicit clear on.
- Allocate the global buffer without BDA and only use TRANSFER_DST usage if we still have to allocate it for purposes of just zerovram.

**Comment by doitsujin** [comment]
> Allocate the global buffer without BDA

what exactly is this supposed to improve?

**Comment by HansKristian-Work** [comment]
Mostly to make it more friendly to capture tools, since if BDA + aliasing is used, e.g. RenderDoc is forced to capture it. Should save several GB of memory during capture and replay.
