### ISSUE TITLE
Have an vkd3d proton version supporting Vulkan 1.2 ?

### ISSUE THREAD

**Issue by Augusto7743** [HansKristian-Work/vkd3d-proton#1464]
Hello.
Have an vkd3d proton previous version supporting Vulkan 1.2 ?
Thanks for reading.
Have an nice week.

**Comment by Blisto91** [comment]
Hello.

2.6 is the lat version released before the driver requirements were upped. https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.6

**Comment by Augusto7743** [comment]
hehehe .. you here too =)
well ... I see an chance for run simple D3D12 games in Linux using Geforce 600 Kepler.
If RE4 remake demo can run in version 2.6 for GF600 will be much funny.

Have an nice week =)

**Comment by K0bin** [comment]
Like I told you on the DXVK repo, your GPU isn't capable of running D3D12 games at the hardware level and there's nothing VKD3D-Proton or any other software can do.

**Comment by ViNi-Arco** [comment]
> well ... I see an chance for run simple D3D12 games in Linux using Geforce 600 Kepler.
If RE4 remake demo can run in version 2.6 for GF600 will be much funny.

Augusto if you want to play the RE4 Chainsaw Demo, your best option is to go for Windows, if the Kepler card you have is stronger than the [GTX 750](https://youtu.be/4wnE__bh3pw?t=1) you will play more or less fine

**Comment by K0bin** [comment]
@ViNi-Arco Kepler support for D3D12 is very limited and cannot run the game.

**Comment by ViNi-Arco** [comment]
Hi Kobin, is then Augusto does not have many options.
@Augusto7743  I played on Linux the RE4 Chainsaw Demo with an R7 260X 2gb with Proton 7.0-6 and Mesa 23.1-devel, ran relatively well at 1600x900+FSR2.0-Performance, if you do not have much conditions the R7 260X is a good starting point, I recommend looking at the RX 570 4gb-8gb vram, it is appearing with a good price

**Comment by Augusto7743** [comment]
Thanks for all replies.

GT 640 does 803.3 GFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gt-640-rev-2.c2377

GT 1030 does 1,127 GFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gt-1030.c2954

GT 1030 run RE4 demo in 45 FPS.
GT 1030 is more of half performance of GTX 670
GTX 670 does 2.634 TFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gtx-670.c362

However Geforce 600 not does D3D12.
For me analyzing the performance is as being possible run D3D12 software over Vulkan 1.2.

Geforce 600 Kepler not run RE4 in windows.

R7 260X does 1.971 TFLOPS and is Vulkan 1.2.
https://www.techpowerup.com/gpu-specs/radeon-r7-260x.c2465
Radeon use Mesa.

I not understand as was Radeon driver support since 2013.
Nvidia driver support is very good. Have video cards with driver support for more than 10 years.
My last Radeon was only less 3 years with last driver version having problems in few softwares.

**Comment by K0bin** [comment]
TFLOPS is a useless metric that completely ignores half of the GPU. The 1030 has architectural advantages that make it faster in practice and Kepler is missing important hardware features like bindless resources which D3D12 needs.

**Comment by Augusto7743** [comment]
In other words ...
GT 640 does 803.3 GFLOPS about 10 commands.
GT 1030 does 1,127 GFLOPS about exact same 10 commands plus more another 5 or 10.
More or less it ?

I when created that topic was to understand if was or not possible run D3D12 games using Vulkan 1.2 in Kepler.
After I had replied to understand some details about as work the convertion between D3D12 code in Vulkan and not for demanding any code for Kepler.
