### ISSUE TITLE
Resident Evil 4 Chainsaw Demo Raytracing not working

### ISSUE THREAD

**Issue by SamPurple22** [HansKristian-Work/vkd3d-proton#1466]
Raytracing not available in game. From Graphics menu, Presets you can choose the Raytracing preset, and then the Raytracing option is changed to Normal or High or Off. However you can't manually change it directly and there is no visual indication that Raytracing works.

As per https://gitlab.freedesktop.org/mesa/mesa/-/issues/8372 Raytracing with RADV works on the other Remake games, I tested at least Resident Evil remake 2 and 3.

### Software information
Resident Evil 4 Chainsaw Demo with launch options:
PROTON_LOG=1 VKD3D_DEBUG=trace VKD3D_LOG_FILE=$HOME/re4demo-vkd3d.log  RADV_PERFTEST=rt VKD3D_CONFIG=dxr11  mangohud %command%

### System information
- GPU: AMD 7900 XTX Sapphire Nitro+
- Driver: RADV, Mesa 22.3.6
- Wine version: Proton Hotfix
- VKD3D-Proton version: compiled from git  b7fb41beb66c2d918d72de6be85a3faea1568ca3

### Log files
Proton Log
[steam-2231770.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/10992316/steam-2231770.tar.gz)
VKD3D Log
[re4demo-vkd3d.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/10992319/re4demo-vkd3d.tar.gz)

Edit: Tried with Mesa from git: a455f803954 and added VKD3D_FEATURE_LEVEL=12_2 option also:

Log files:
[re4demo-vkd3d.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/10992546/re4demo-vkd3d.tar.gz)
[steam-2231770.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/10992548/steam-2231770.tar.gz)

**Comment by jkrhu** [comment]
Same issue on Nvidia hardware. RT is greyed out. You can choose a preset, but it doesn't actually enable RT.

Launch options: 
`gamemoderun PROTON_LOG=1 VKD3D_DEBUG=trace VKD3D_CONFIG=dxr11 VKD3D_FEATURE_LEVEL=12_2 PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 %command%`

System information:
GPU: Nvidia RTX 3060
Driver: 525.89.02
Proton Experimental

Log:

[RE4DemoVKD3DNVIDIATrace.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10996435/RE4DemoVKD3DNVIDIATrace.log)

**Comment by doitsujin** [comment]
Yeah, we don't know what libraries the game is using to determine DXR support, clearly not just D3D12 though (or it depends on some weird features we don't expose for some reason).

**Comment by K0bin** [comment]
It's possible to enable RT in the game when using VKD3D-Proton on Windows with VKD3D_CONFIG=dxr11 and VKD3D_FEATURE_LEVEL=12_2.

So it comes down to some other library.

**Comment by thegabriele97** [comment]
> It's possible to enable RT in the game when using VKD3D-Proton on Windows with VKD3D_CONFIG=dxr11 and VKD3D_FEATURE_LEVEL=12_2.
> 
> So it comes down to some other library.

Which Nvidia driver version do you use on windows?

**Comment by K0bin** [comment]
Latest Vulkan dev one.

**Comment by doitsujin** [comment]
This was recently confirmed to be a deliberate decision by the game; raytracing options are not available if it detects wine. Not much we can do here.

**Comment by Hadrianneue** [comment]
@doitsujin raytracing is available if you hide wine exports its somewhat working with amdvlk if you force SM/FL with vkd3d env vars, i was able to finish the demo with RT on. however an "assertion failed" error dialog does pop-up, which i can ignore and just keep playing.

Previous amdvlk would just crash after a while, i did open an issue on mesa issue tracker a while ago https://gitlab.freedesktop.org/mesa/mesa/-/issues/9559

**Comment by adamdmoss** [comment]
For anyone watching this issue, figured out that if you put `/WineDetectionEnabled:False` onto the launch options for RE4 then you can enable/disable raytracing and it works and there's an actual difference.  On NV, anyway.
