### ISSUE TITLE
Diablo IV Beta not launching

### ISSUE THREAD

**Issue by KlumzByte** [HansKristian-Work/vkd3d-proton#1471]
The upcoming Diablo IV has a running Open Beta this weekend.
On Windows 10 its currently possible to launch the game to show the in-game login menu, using parameter: "Diablo IV.exe -launch"

On Linux pop-os 22.04, using latest GE-Proton7-51 as Non-Steam game, this fails with a popup (i still think you can launch the game even with the popup on windows, this may not be the root issue):
![image](https://user-images.githubusercontent.com/5812155/225938824-af6b302c-0ab0-4a3c-877f-1f71c6146ab2.png)

I've gathered the proton logs here:
[steam-diablo-iv.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/11002577/steam-diablo-iv.zip)

glxinfo:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.85.05
[glxinfo.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/11002651/glxinfo.zip)

Screenshot of the files:
![image](https://user-images.githubusercontent.com/5812155/225940304-cdf4d335-83cc-4325-9153-378a54bd3d39.png)
![image](https://user-images.githubusercontent.com/5812155/225939533-a7af7d0c-1100-42a0-b757-f0aeb3c7edfe.png)

**Comment by doitsujin** [comment]
The game does not load d3d12.dll, this is unlikely to be a vkd3d-proton issue.

**Comment by KlumzByte** [comment]
Logs with MANGOHUD=0:
[steam-diablo-iv-3.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/11002925/steam-diablo-iv-3.zip)

**Comment by KlumzByte** [comment]
Using the same settings as the reddit post, I managed to get it running via Lutris.

**Comment by KlumzByte** [comment]
I can get it running using the following options via Lutris:

- lutris-GE-Proton7-19-x86_64
- DXVK v2.1
- VKD3D v2.8
- Esync = true
- Fsync = true

No need for DLL overrides

**Comment by KlumzByte** [comment]
Work fine here on EVGA 3080 RTX, been playing for 45 mins now in-game.

**Comment by GloriousEggroll** [comment]
Noting here since it hasn't been stated anywhere else yet. The No GPU Found issue was bisected to commit https://github.com/ValveSoftware/wine/commit/51ce414a1f41fcaa415c4d3b4edd6b96ba711a35

Confirmed reverting it on top of my current build works

**Comment by doitsujin** [comment]
Should also be noted that that commit is absolutely not the root cause of the problem and that reverting it **will** break a whole bunch of stuff.

**Comment by philippludwig** [comment]
> * lutris-GE-Proton7-19-x86_64

Too bad that this version is no longer available.

![image](https://user-images.githubusercontent.com/3770792/227631630-2532fc87-0384-439f-be08-8eeaa11fec5c.png)

**Comment by KlumzByte** [comment]
> > * lutris-GE-Proton7-19-x86_64
> 
> Too bad that this version is no longer available.
> 
> ![image](https://user-images.githubusercontent.com/3770792/227631630-2532fc87-0384-439f-be08-8eeaa11fec5c.png)

Try https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-40 or the newest https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-41 that should have a fix for Diablo IV.

**Comment by philippludwig** [comment]
Thank you very much for your replay, @KlumzByte. Sadly, even with version GE-Proton7-41 I get the "no GPU" message (I also have  dxvk 2.1 and vkd3d-proton 2.8).

**Comment by Blisto91** [comment]
You need proton experimental or newest GE for a propor fox to that.

**Comment by philippludwig** [comment]
Thanks for your replay. Sadly I can’t compile DXVK myself from master, because glslang-tools is not recent enough on Debian; so I am stuck with the DXVK 2.1 that lutris ships with. 

I tried playing with the NVAPI settings in lutris, but no luck. 

`dxgi.nvapiHack = False` is already set in dxvk.conf.

**Comment by Blisto91** [comment]
You can find a compiled CI build of dxvk here if that helps https://github.com/doitsujin/dxvk/actions/workflows/artifacts.yml?query=branch%3Amaster

**Comment by philippludwig** [comment]
Thanks. I added the latest build from that page to lutris and set the game options to use it, but still "no GPU found".

**Comment by Blisto91** [comment]
Which Wine build were you using?

**Comment by philippludwig** [comment]
As stated above, I currently use lutris-GE-Proton7-41-x86_64.

**Comment by Blisto91** [comment]
Derp. Hmm not sure. Would have to try myself in Lutris later.

**Comment by KlumzByte** [comment]
> As stated above, I currently use lutris-GE-Proton7-41-x86_64.

Try using steam with Proton Experimental, they have applied some fixes.

**Comment by philippludwig** [comment]
Already tried that. When I add the Diablo shortcut in Steam and run it with default settings, I get the same error. When I set it to Proton Experimental, I don’t even get the error, but this in the terminal:

```
Proton: Upgrading prefix from None to 7.0-101 (/home/philipp/.steam/steam/steamapps/compatdata/3761622820/)
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
ThreadGetProcessExitCode: no such process 7502
ThreadGetProcessExitCode: no such process 7500
ThreadGetProcessExitCode: no such process 7499
ThreadGetProcessExitCode: no such process 7498
ThreadGetProcessExitCode: no such process 7380
ThreadGetProcessExitCode: no such process 7505
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
ThreadGetProcessExitCode: no such process 7607
ThreadGetProcessExitCode: no such process 7544
ThreadGetProcessExitCode: no such process 7538
ThreadGetProcessExitCode: no such process 7532
ThreadGetProcessExitCode: no such process 7510
ThreadGetProcessExitCode: no such process 7507
ThreadGetProcessExitCode: no such process 7501
ThreadGetProcessExitCode: no such process 7497
pid 7503 != 7502, skipping destruction (fork without exec?)
Game process removed: AppID 0 "/home/philipp/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=3761622820 -- /home/philipp/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/philipp/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/philipp/.steam/steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  "env" "LUTRIS_SKIP_INIT=1" "lutris" "lutris:rungameid/21"", ProcID 7377 
ThreadGetProcessExitCode: no such process 7519
ThreadGetProcessExitCode: no such process 7379
ThreadGetProcessExitCode: no such process 7378
Uploaded AppInterfaceStats to Steam
```

It seems that by setting it to Proton Experimental, Steam now somehow believes that this is a steam game.

**Comment by GloriousEggroll** [comment]
> Thanks for your reply. Sadly I can’t compile DXVK myself from master, because glslang-tools is not recent enough on Debian; so I am stuck with the DXVK 2.1 that lutris ships with.
> 
> I tried playing with the NVAPI settings in lutris, but no luck.
> 
> `dxgi.nvapiHack = False` is already set in dxvk.conf.


You don't need to compile anything. Lutris already provides dxvk v2.1 and vkd3d-proton v2.8, (as well as the latest version of dxvk-nvapi).  I updated the runtimes for Lutris on thursday

**Comment by philippludwig** [comment]
I am using 470.161.03, the one that is included in debian.

**Comment by mbriar** [comment]
You can't run any game on recent versions of vkd3d-proton with ancient drivers such as this. It requires at least 510.47 for vulkan 1.3, and better the very latest for more features and bugfixes.

**Comment by dustContributor** [comment]
> I am using 470.161.03, the one that is included in debian.

**Don't** use Debian *stable* to game. You **will** have a bad time. Include the testing/unstable/experimental repositories to apt to install more recent versions of your drivers (or related tools if you're compiling like glsl-lang tools).

https://packages.debian.org/search?keywords=nvidia&searchon=names&suite=all&section=all

You can install 530.30 if you include experimental, for example.

Same thing with more recent versions of libvulkan-dev, glsllang-tools, mesa, and so on. For a couple years these have been hitting experimental/unstable within a couple of days of a new version been released (if not the same day).

https://packages.debian.org/search?keywords=glslang&searchon=names&suite=all&section=all

If you're worried all you have to do is to include the other repos, install what you need, and then comment them out in apt. Nothing else. But **don't** use Debian stable to play games. If you're going to use Debian, learn to cherry pick the more recent versions of the packages you need from the more recent repos.

**Comment by philippludwig** [comment]
> Don't use Debian stable to game. You will have a bad time.

Can’t confirm that, WoW runs flawlessly.

I installed the NIVIDA driver 525.89.02 (that is the current production version on the NVIDIA download site) and Diablo runs fine now. 

Thanks everyone for your help & patience.
