### ISSUE TITLE
Wo long: Fallen Dynasty crash when the game trying to play any kind of video, cutscene, tutorial video

### ISSUE THREAD

**Issue by xcloudx12345** [HansKristian-Work/vkd3d-proton#1473]
if u load directly into the map, it running fine, but crash when the game trying to show any kind of video like cutscene, tutorial video 

### Software information
Wo long: Fallen Dynasty

### System information
- GPU: RTX 2070
- Driver: beta 531.32 
- Wine version: 
- VKD3D-Proton version:  lastest

### Log files
Proton or Wine logs.

**Comment by mbriar** [comment]
This game uses d3d11 shared resources to play it's videos which can't work on windows with vkd3d-proton, it works fine on Linux with proton. Besides, there is pretty much no reason to ever use vkd3d-proton on windows anyways.

20 Mar 2023, 07:06 by ***@***.***:

**Comment by xcloudx12345** [comment]
because it improves the performance and frame rate of the game, so I want to test it, unfortunately having problems with the videos, If there is a way to disable all videos, it can be used as a temporary solution to improve the performance of the game.

**Comment by Blisto91** [comment]
I don't know besides deleting the videos if it ships them as seperate files.
As for the issue, like mbriar said shared resources isn't supported on Windows so there is not really a bug on that front.

**Comment by ManuLinares** [comment]
This game doesn't work for me on Linux.

System Arch Kernel: 6.3.5-arch1-1
nvidia-beta-dkms 535.43.02-1
wine-tkg-valve-exp-bleeding 8.0.45143.20230531-327
vkd3d latest

P.S.: Where does the OP mention that this is on Windows???


Log shows:
```
winegstreamer error: matroskademux0: Internal data stream error.
winegstreamer error: matroskademux0: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin0/GstDecodeBin:decodebin0/GstMatroskaDemux:matroskademux0:
streaming stopped, reason not-negotiated (-4)
winegstreamer error: matroskademux1: Internal data stream error.
winegstreamer error: matroskademux1: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin1/GstDecodeBin:decodebin1/GstMatroskaDemux:matroskademux1:
streaming stopped, reason not-negotiated (-4)
7398.849:012c:0384:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_global_flags: Unhandled global flags 0x11.
winegstreamer error: matroskademux2: Internal data stream error.
winegstreamer error: matroskademux2: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin2/GstDecodeBin:decodebin2/GstMatroskaDemux:matroskademux2:
streaming stopped, reason not-negotiated (-4)
winegstreamer error: matroskademux3: Internal data stream error.
winegstreamer error: matroskademux3: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin3/GstDecodeBin:decodebin3/GstMatroskaDemux:matroskademux3:
streaming stopped, reason not-negotiated (-4)
winegstreamer error: matroskademux4: Internal data stream error.
winegstreamer error: matroskademux4: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin4/GstDecodeBin:decodebin4/GstMatroskaDemux:matroskademux4:
streaming stopped, reason not-negotiated (-4)
winegstreamer error: matroskademux5: Internal data stream error.
winegstreamer error: matroskademux5: ../gstreamer/subprojects/gst-plugins-good/gst/matroska/matroska-demux.c(6095): gst_matroska_demux_loop (): /GstBin:bin5/GstDecodeBin:decodebin5/GstMatroskaDemux:matroskademux5:
streaming stopped, reason not-negotiated (-4)

```

**Comment by HansKristian-Work** [comment]
That doesn't look like a vkd3d-proton issue to me, but mfplat issue in custom Wine. Does it work in Proton?

**Comment by mbriar** [comment]
> P.S.: Where does the OP mention that this is on Windows???

The driver version given only exists on windows and wine field is blank. The game is known to work on proton, so your problem is most likely with the custom wine build used with an illegitimate version of the game.

**Comment by ManuLinares** [comment]
> > P.S.: Where does the OP mention that this is on Windows???
> 
> The driver version given only exists on windows and wine field is blank.

Thanks 👍

>

Will try to run the legitimate game (just to to specify this) tonight with proton.

**Comment by ManuLinares** [comment]
It works.

First I tried the steam version and it worked, so I wen back to try the illegitimate version but this time on Lutris with latest https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-7 and it worked.

I have no idea why https://aur.archlinux.org/packages/wine-ge-custom didn't though.
