### ISSUE TITLE
Metro Exudos Enhanced Edition - dxr not working with GPL

### ISSUE THREAD

**Issue by koloved** [HansKristian-Work/vkd3d-proton#1481]
When i use RADV_PERFTEST=gpl and start the game DXR not worked and everything is flat (too bright , wrong gamma)

Sorry if it wrong place to report the issue, maybe i should post it on here - https://gitlab.freedesktop.org/mesa/mesa

[![Watch the video](https://img.youtube.com/vi/wsDi1VThZ7Y/default.jpg)](https://youtu.be/wsDi1VThZ7Y)

### Software information
Metro Exudos Enhanced Edition, Ray-tracing ON 

### System information
- GPU: 6600xt
- Driver: 23.1 mesa-git
- VKD3D-Proton version: Proton Bleeding edge

### Log files
let me know if you need the logs, but i don't figure it out how to trace log in vkd3d

**Comment by mbriar** [comment]
Neither RADV nor vkd3d-proton enable rt support by default yet, you need to set RADV_PERFTEST=gpl,rt and VKD3D_CONFIG=dxr11.

**Comment by doitsujin** [comment]
well that's just how environment variables work, if you only set it to `gpl` (which your second example does) then raytracing support is disabled.

Anyway, closing, since there's no bug here.
