### ISSUE TITLE
ID3D12PipelineLibrary and The Last of Us: Part 1

### ISSUE THREAD

**Issue by Bitwolfies** [HansKristian-Work/vkd3d-proton#1497]
Forgive me if I'm mistaken, but looking at the readme, it's written as if any application that attempts to manage its own shader cache, by default is handed dummy data, with VKD3D managing its own cache like it would for applications that lack its support. Despite this, The Last of Us: Part 1 which does manage its own cache, still appears to do so, generating almost 200mb worth of a cache. It also begins to remake its cache if the folder is removed. 
![Screenshot_20230329_133420](https://user-images.githubusercontent.com/65789901/228660935-5fbf9264-495e-4a11-bfa7-4273d4452f8b.png)
Is this intended? Forgive me if this is something unrelated to the ID3D12PipelineLibrary. And thank you.

**Comment by Saancreed** [comment]
Yes, this 180 MiB is just a _lot_ of dummy data. The actual cache is somewhere else, e.g. on Nvidia in `~/.cache/nvidia/GLCache` or `~/.nv` if you don't have Shader Pre-Caching enabled in Steam settings and somewhere in `${steamapps}/shadercache/1888930/nvidiav1` (I think?) otherwise. That one should be _much_ bigger, over 3 GiB in size.

**Comment by Saancreed** [comment]
Nvidia driver deletes the cache once it goes over a certain size, which by default is something laughably small (1 GiB?). Does it grow while the game is running? Do you have `__GL_SHADER_DISK_CACHE=1` set as an environment variable for the game process?

**Comment by HansKristian-Work** [comment]
Working as intended. We still need to store dummy data in the library so we can validate the input as required. AMD Windows D3D12 does something similar actually.
