### ISSUE TITLE
The Last Of Us PART I AMDVLK issue

### ISSUE THREAD

**Issue by Hadrianneue** [HansKristian-Work/vkd3d-proton#1501]
game does not launch with AMDVLK, error message about GPU lacking D3D12, VKD3D_FEATURE_LEVEL does not help, launches fine with RADV

![image](https://user-images.githubusercontent.com/24306541/229270846-49f01659-39f7-4011-8bc7-e9c6c55b210e.png)

### Software information
Name of the game, settings used etc.

### System information
- GPU: RX 6500 XT 4GB
- Driver: mesa-git/AMDVLKQ4.4-3
- Wine version: Proton-GE 7-52
- VKD3D-Proton version: 2.8

### Log files
Proton or Wine logs.

**Comment by mbriar** [comment]
It most likely also needs VKD3D_SHADER_MODEL=6_6 (only available in latest vkd3d-proton master) because amdvlk is missing some features for that.

1 Apr 2023, 08:59 by ***@***.***:

**Comment by Blisto91** [comment]
Yes this is the same with all of AMD's Vulkan drivers, even the Windows one.
As said this is because the drivers are missing some features for it. You can work around it with the variable but don't expect it to go smoothly even from there. RADV is usually recommended.

**Comment by K0bin** [comment]
Why do you want to launch it with AMDVLK in the first place?

**Comment by Hadrianneue** [comment]
> It most likely also needs VKD3D_SHADER_MODEL=6_6 (only available in latest vkd3d-proton master) because amdvlk is missing some features for that.

no cigar, creating a dxvk.conf with a nvidia vendor id does skip that message but game still doesn't launch.

**Comment by K0bin** [comment]
> if you test it you will see that in some games its better than RADV.

With vkd3d-Proton? No, absolutely not.

**Comment by Hadrianneue** [comment]
> > if you test it you will see that in some games its better than RADV.
> 
> With vkd3d-Proton? No, absolutely not.

any game that AMDVLK doesn't crap the bed, if VRAM limited, AMDVLK will likely run better than RADV, Alan Wake Remastered, Returnal, Metro Exodus enhanced edition (mostly because of ray tracing, still impressive) to name a few.

i get your point that its usually bad or straight up doesn't work but i don't know why you would assume that though unless  you've been testing every single game on multiple GPUs...

btw AMDVLK can still be faster than RADV on some cases, check https://github.com/zmike/vkoverhead

**Comment by Blisto91** [comment]
> no cigar, creating a dxvk.conf with a nvidia vendor id does skip that message but game still doesn't launch.

Just launch it with `VKD3D_SHADER_MODEL=6_6` as a env var. Telling the game you are on Nvidia might make it crash because it tries to load Nvapi features or similar. Haven't tested.

**Comment by Hadrianneue** [comment]
> Note the env var was added only two days ago so Proton GE doesn't contain it yet. Either use Proton experimental or put latest vkd3d-proton master into your GE folder.

that did it, i was using Proton-GE
