### ISSUE TITLE
Rise of The Tomb Raider: graphical artifact when looking at some spots

### ISSUE THREAD

**Issue by SuperSamus** [HansKristian-Work/vkd3d-proton#1502]
In Rise of the Tomb Raider, when looking at some specific spots, you can see some graphical artifacts, which don't happen with the DX11 renderer.
They don't seem to be many, as this is the first one I found (I'm in the Glacial Caverns). I don't know if there are more.
![image](https://user-images.githubusercontent.com/40663462/229312435-f44e9b71-1e3c-421f-8815-8637e4a016dc.png)

### Software information
Rise of the Tomb Raider (Epic Games Store), on this spot it disappears when disabling lens flares.
Curiosity, I don't know if relevant: by playing with the DLSS to FSR mod, this area in general becomes artifacty (I was using the mod for a while, it's the first where it happens), even with lens flares off. Obviously, I tested without the mod's DLL files whether the artifacts still appear in this spot.

### System information
- GPU: AM RX 6700 XT
- Driver: Mesa 22.3.7 (amdgpu)
- Wine version: Wine-GE 7.37
- VKD3D-Proton version: 2.8

### Log files
Launched the game with `VKD3D_DEBUG=trace`, quickly got to the spot.
[rise.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/11130539/rise.zip)

**Comment by doitsujin** [comment]
Does this happen with a more recent Mesa version?

**Comment by SuperSamus** [comment]
Tried Mesa 23.0.1, same thing.
(Distro (NixOS) doesn't offer `mesa-git`, so I can't test any higher than that.)

**Comment by Blisto91** [comment]
Thank you for the issue.
Have bisected this to start appearing since commit https://github.com/HansKristian-Work/vkd3d-proton/commit/829c02bf90cb3fc7b4af58b0fa6e9c6ea06606b4

**Comment by doitsujin** [comment]
Looks like a game bug at a first glance, game renders and samples a texture at the same time, which at least to my knowledge isn't allowed in D3D12. You should be able to work around this by setting `RADV_DEBUG=nodcc`, but this will come at a performance cost.

**Comment by doitsujin** [comment]
Yeah, definitely a game bug. While it is possible to work around this on our end, it's very complicated to do and we reached the concensus that it's not really worth doing for this one game.

I'd recomment using either the environment variable above, or just using the D3D11 renderer (you might want to use Mesa 23.0 or newer and set `RADV_PERFTEST=gpl` to avoid stutter).

**Comment by Blisto91** [comment]
This has now been worked around on master
