### ISSUE TITLE
The Last of Us Part 1 PC: Can't change texture options

### ISSUE THREAD

**Issue by DDarknessOne** [HansKristian-Work/vkd3d-proton#1505]
- GPU: RTX 3070
- Driver: 531.41
- VKD3D-Proton version: vkd3d-proton-master-42e3adc29f5b522161e20d08a1dd230b650c59bb
- OS: Windows 11 22H2

Environment Variables:
- VKD3D_CONFIG=dxr11
- VKD3D_FEATURE_LEVEL=12_2

![texture](https://user-images.githubusercontent.com/91283578/229838985-ff79d2c7-841b-49ae-af76-cabf3843f85b.png)

**Comment by K0bin** [comment]
FWIW the crashes aren't related to VRAM.

It crashes on my 24GB 3090 too.

**Comment by Blisto91** [comment]
I'd you are using dxvk's dxgi then you'll might need to disable nvapiHack

**Comment by mbriar** [comment]
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/516320/-/ for the crashes on native d3d12.

**Comment by DDarknessOne** [comment]
> 

Thanks, crash fixed :)
