### ISSUE TITLE
Cyberpunk ray tracing doesn't work with latest update

### ISSUE THREAD

**Issue by rogerizo** [HansKristian-Work/vkd3d-proton#1507]
I crash either before making it past the splash screen or during the  loading screen.

### Software information
Cyberpunk 2077
Only experience crashes when enabling any ray tracing settings e.g psycho or the new path tracing toggle option.

### System information
- GPU: 4090
- Driver: 530.41.03
- Wine version:  proton hotfix
- VKD3D-Proton version:  2.8

### Log files
[trace.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11203383/trace.log)
[steam-1091500.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11203385/steam-1091500.log)

**Comment by jp7677** [comment]
Not sure, but these lines from nvapi logs might be related:

```
NvAPI_QueryInterface NvAPI_D3D12_GetRaytracingCaps: Not implemented method
NvAPI_QueryInterface NvAPI_D3D12_GetRaytracingAccelerationStructurePrebuildInfoEx: Not implemented method
NvAPI_QueryInterface NvAPI_D3D12_BuildRaytracingAccelerationStructureEx: Not implemented method
```

**Comment by K0bin** [comment]
@rogerizo Try with PROTON_ENABLE_NVAPI=0.

**Comment by Kamynsky** [comment]
VKD3D_CONFIG=dxr11,dxr,force_static_cbv PROTON_ENABLE_NVAPI=0 PROTON_HIDE_NVIDIA_GPU=0 VKD3D_FEATURE_LEVEL=12_2 %command% --intro-skip -skipStartScreen --launcher-skip

**Comment by rogerizo** [comment]
@Kamynsky  it works now with that disabled thanks, although performance is a lot worse than windows with around 50% performance loss from what i  have tested unfortunately.

**Comment by adamnv** [comment]
```
NvAPI_QueryInterface NvAPI_D3D12_GetRaytracingCaps: Not implemented method
NvAPI_QueryInterface NvAPI_D3D12_GetRaytracingAccelerationStructurePrebuildInfoEx: Not implemented method
NvAPI_QueryInterface NvAPI_D3D12_BuildRaytracingAccelerationStructureEx: Not implemented method
```
Some of these might be tough to implement fully and quickly, so I'm hoping the app can be appeased with at least declaring minimal caps.  But I suspect not. :(  I'll have a hack and see...

**Comment by Saancreed** [comment]
@adamnv I made an attempt that is supposed to implement them and claim that OMM-related stuff is unsupported but I probably made some not-so-obvious mistake, or it's not enough to get the game working again: https://github.com/Saancreed/dxvk-nvapi/pull/2

**Comment by adamnv** [comment]
> @adamnv I made an attempt that is supposed to implement them and claim that OMM-related stuff is unsupported but I probably made some not-so-obvious mistake, or it's not enough to get the game working again: [Saancreed/dxvk-nvapi#2](https://github.com/Saancreed/dxvk-nvapi/pull/2)

From a quick read of those diffs, that looks fine :(

**Comment by nukemiko** [comment]
According to [this patch note on Cyberpunk 2077 official website](https://www.cyberpunk.net/en/news/47875/patch-1-62-ray-tracing-overdrive-mode):

> Added a Ray Tracing: Overdrive preset which includes the Path Tracing technology. You can enable the Ray Tracing: Overdrive preset in Settings > Graphics > Quick Preset, or just Path Tracing separately in Settings > Graphics in the Ray Tracing section. To make sure Ray Tracing: Overdrive Mode works correctly on your PC, **update your NVIDIA Game Ready Driver to version 531.41 at minimum**.

Maybe you should just wait for your distro to release the NVIDIA graphics driver update...?

**Comment by adamnv** [comment]
I do recommend a driver update just on principle, but that won't solve this issue sadly.

**Comment by Saancreed** [comment]
Actually, I got another report that it does let Cyberpunk 2077 work again after latest update. I'll just cleanup the log spam and send a proper PR to upstream repo.

**Comment by adamnv** [comment]
That's great news!  I'll give it a test myself.

**Comment by adamnv** [comment]
Seems to work great - good work @Saancreed !

**Comment by eXt73** [comment]
I can confirm with the latest dxvk-nvapi it works ... but it strongly 'presses' RTX 4070 Ti - in DLSS 2.x mode Performance ... e.g. 27 fps :P
![Screenshot_20230412_225642](https://user-images.githubusercontent.com/20760088/231586494-160dfaf4-b7c4-490c-ba96-570216dc81c7.png)
![Screenshot_20230412_225626](https://user-images.githubusercontent.com/20760088/231586503-a4ce0742-8224-4b93-8841-92c45c232ee4.png)

**Comment by Emanem** [comment]
@eXt73 Hi, I'm curious to test it on my 4090 - could you please specify exactly what Proton version you are using, the drivers and the command line when executing the game?

Thanks!

**Comment by Kamynsky** [comment]
@Blisto91 Can confirm , all working nicely including DLSS , RT and PT
https://i.imgur.com/uZqusb1.jpg

**Comment by ndavd** [comment]
> Should just work with Proton bleeding edge and launching the game with `VKD3D_CONFIG=dxr11 %command%` afaik.

With which Proton version would it work?

**Comment by Blisto91** [comment]
The bleeding edge beta of Proton Experimental only for now.
Should arrive in regular experimental or GE next update

**Comment by ndavd** [comment]
what's the best way of installing that one?

**Comment by Blisto91** [comment]
In steam you can find Proton experimental in your library by searching for Proton. If you then go in to the properties of that one then under the beta tab you should be able to select Bleeding edge.

Be aware that bleeding edge means that its updated automatically each hour or so if there is new upstream commits in some of the Proton included projects. That means it haven't received much practical testing and have a higher chance of breaking from time to time than regular experimental. So i do not recommend it for regular usage unless you don't mind testing all the newest changes all the time.

**Comment by ndavd** [comment]
Oh I see thanks for the reply - I will use it for testing and then wait for the GE version

**Comment by TheDcoder** [comment]
Sorry for the necro-posting but this doesn't seem to be working with the latest [`Wine-GE-Proton8-14`](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-14) and bleeding edge vkd3d build that I grabbed from GitHub actions.

Should I make a new bug report with all the details?

**Comment by eXt73** [comment]
I was supposed to report a new post but I think I'll write here - now for about a month + the latest Nvidia drivers 535.98 Path Tracing doesn't work - trying to activate it results in the game crashing, turning it off and the debugging window appearing.
