### ISSUE TITLE
Vkd3d can no longer launch games from EA Desktop

### ISSUE THREAD

**Issue by Bill5122** [HansKristian-Work/vkd3d-proton#1515]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
EA origin is now end of life, and users are being forced to migrate to the EA desktop app.  In my testing on the latest git branch of vkd3d-proton it is not possible to launch any game from the client.  The Ea desktop client will be stuck on "Launching game" and after enough time the entire client will crash.  The commit that broke this appears to be https://github.com/HansKristian-Work/vkd3d-proton/commit/fbf03829ebaaf068f9166c668a7f1c9265999915 previous commits are able to launch games perfectly fine.  Games also launch fine from the v2.8 release.  

Tested games:  
Plants vs. Zombies: Garden Warfare 2
Plants vs. Zombies: Battle for Neighborville
Spore

### System information
- GPU: 5700xt
- Driver: Mesa 23.2.0-devel (git-3e22c3a8bc)
- Wine version: 8.5 staging
- VKD3D-Proton version: vkd3d-proton git fbf03829ebaaf068f9166c668a7f1c9265999915

### Log files
Proton or Wine logs.
[wine log](https://github.com/HansKristian-Work/vkd3d-proton/files/11234050/wine.log)

**Comment by K0bin** [comment]
Did you actually install d3d12core.dll into your Wine prefix?

**Comment by K0bin** [comment]
> wine: Call from 000000007B014094 to unimplemented function d3d12core.dll.D3D12GetInterface, aborting

vkd3d-Proton implements that, so d3d12core.dll is not correctly installed in your setup.

**Comment by Blisto91** [comment]
https://github.com/lutris/lutris/commit/7d1d514a1c0b21405324d725abad8c6308d19b1e
The support for this haven't made it to a release version yet so you'll have to use the git version or manually do something for the prefixes you want to use it in.

**Comment by Bill5122** [comment]
Closing, mbriar was correct with the issue being with lutris, thanks for the help all.
