### ISSUE TITLE
Metro Exodus EE: dxgi_vk_swap_chain_SetGammaControl - causing black screen?

### ISSUE THREAD

**Issue by Xathros1** [HansKristian-Work/vkd3d-proton#1517]
Running the game with env: RADV_PERFTEST=gpl,rt | VKD3D_CONFIG=dxr,dxr11

Main Menu:
![Bildschirmfoto vom 2023-04-16 22-20-52-min](https://user-images.githubusercontent.com/72621668/232340307-e0204428-83ea-40b6-9255-6bf826323ed1.png)

After some seconds:
![Bildschirmfoto vom 2023-04-16 22-21-10-min](https://user-images.githubusercontent.com/72621668/232340325-2d6de963-d7c4-48af-85e1-de936abaf8c4.png)

I noticed that it's spamming this
`5918.833:00d8:00dc:fixme:vkd3d-proton:dxgi_vk_swap_chain_SetGammaControl: iface 0000000000763250, NumControlPoints 1024, pControlPoints 000000000041c508 stub!`

### Software information
Metro Exodus Enhanced Edition

### System information
- GPU: AMD RX 7900 XT
- Driver: Running AMD Mesa driver 23.1.0 on AMD Radeon Graphics (gfx1100, LLVM 15.0.7, DRM 3.49, 6.2.10-1-default) (0x744c) (Flatpak Mesa-git)
- Wine version: wine_tkg-a141028d8d19d2218b42eee2702f4fab27710750
- VKD3D-Proton version: vkd3d-proton-2.8-1-f0697a8

### Log files
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/11243330/log.txt)

**Comment by pa5hgan** [comment]
GPU: AMD Radeon RX 7900 XTX
Driver: Kernel 6.3.0, Mesa 23.0.3, LLVM 16.0.2
Wine: Wine-GE-Proton7-43, Wine-8.7 (staging)
VKD3D: v2.8, v2.6, v2.5

Got same behavior, like all textures are converted into solid black color after few seconds or minutes of playing or staying in menu). The game is not frozen, sky is visible, there are colored points of some of light sources (for example two green dots from crosshair at  early beginning of the game).

**Comment by mbriar** [comment]
@pa5hgan what you're describing sounds more like https://gitlab.freedesktop.org/mesa/mesa/-/issues/8927

**Comment by pa5hgan** [comment]
@mbriar you're right, reverting to mesa 22.3.7 fixed the issue for me, thanks for the tip!

**Comment by Blisto91** [comment]
Fixed in mesa since commit https://gitlab.freedesktop.org/mesa/mesa/-/commit/d924281c78709f9b930e4392c7971b31ebf5bb79
