### ISSUE TITLE
Resident Evil 4 some object edges looks pixelated

### ISSUE THREAD

**Issue by kassindornelles** [HansKristian-Work/vkd3d-proton#1522]
Enabling CACAO in RE engine titles* make things look pixelated in object edges (not sure if the same happens on Windows)

Some low quality footage because youtube compression is a piece of ****
https://www.youtube.com/watch?v=lF7wkS49oPQ

### Software information
[RESIDENT EVIL 4](https://store.steampowered.com/app/2050650/Resident_Evil_4/)

other games affected:
RESIDENT EVIL 7 (the easiest one to see the issue on this list)
RESIDENT EVIL 2
RESIDENT EVIL 3
and maybe Village too, not sure about this one

### System information
- GPU: RX 6600
- Driver: RADV - Mesa 23.0.2
- Wine version: Proton 8.0-1
- VKD3D-Proton version: only god knows

**Comment by mbriar** [comment]
Is this the same as https://github.com/HansKristian-Work/vkd3d-proton/issues/1460 for the Demo? Maybe some more shader hashes need to be added to the quirk list..

**Comment by HansKristian-Work** [comment]
If they modified the shader slightly, that would explain it, yes ... Looks very much like the broken CACAO.

**Comment by kassindornelles** [comment]
did it ever got fixed for older games? 
i was getting the same issue with proton experimental last week on RE7

**Comment by mbriar** [comment]
All of these games received patches recently. I'm pretty sure CACAO wasn't even available in RE2 a year ago.

**Comment by kassindornelles** [comment]
> All of these games received patches recently. I'm pretty sure CACAO wasn't even available in RE2 a year ago.

yeah i'm aware of that, the ray tracing patches added CACAO
and is broken since the RT patches were released

**Comment by kassindornelles** [comment]
Looks like is fixed on main branch, so proton is probably using something older, but from what i've seen theres no workaround for the other RE engine games (re2, 3 and 7)
![image](https://user-images.githubusercontent.com/40970965/233226209-49cae260-ef1c-41fa-b7bb-2e7c690f627a.png)

**Comment by mbriar** [comment]
FWIW, i think the shader hashes are different for the older RE games, I tried this
```
diff --git a/libs/vkd3d/device.c b/libs/vkd3d/device.c
index c0883262..5faed388 100644
--- a/libs/vkd3d/device.c
+++ b/libs/vkd3d/device.c
@@ -590,7 +590,10 @@ static const struct vkd3d_shader_quirk_meta application_shader_quirks[] = {
     /* Wo Long: Fallen Dynasty (2285240) */
     { VKD3D_STRING_COMPARE_EXACT, "WoLong.exe", &wolong_quirks },
     /* Resident Evil 4 (2050650) */
+    { VKD3D_STRING_COMPARE_EXACT, "re2.exe", &re4_quirks },
+    { VKD3D_STRING_COMPARE_EXACT, "re3.exe", &re4_quirks },
     { VKD3D_STRING_COMPARE_EXACT, "re4.exe", &re4_quirks },
+    { VKD3D_STRING_COMPARE_EXACT, "re7.exe", &re4_quirks },
     { VKD3D_STRING_COMPARE_EXACT, "re4demo.exe", &re4_quirks },
     /* MSVC fails to compile empty array. */
     { VKD3D_STRING_COMPARE_NEVER, NULL, NULL },
```
for RE7 and it didn't fix it.

**Comment by HansKristian-Work** [comment]
Proton 8 has a slightly older vkd3d-proton from when we didn't have the workaround, so that is expected.

**Comment by kassindornelles** [comment]
just to update: i could not reproduce on RE3, i reproduced easily on RE2 and RE7 here :ok_hand:

**Comment by HansKristian-Work** [comment]
Fixed on master. RE2 and 7 were affected.
