### ISSUE TITLE
FSR 1.0 shader seems to be broken on RE2/RE3/RE7

### ISSUE THREAD

**Issue by kassindornelles** [HansKristian-Work/vkd3d-proton#1527]
FSR 1.0 in those 3 games got added in the Ray Tracing Update, FSR 1.0 Ultra Quality looks worse or equal to 70% resolution scale in the game settings.
Seems like even Resident Evil 4 remake FSR 1.0 is broken, the only one that actually works and outputs a good image with FSR 1.0 is Resident Evil: Village

70% res:
![70percentress](https://user-images.githubusercontent.com/40970965/233402368-8ea01e65-a6d3-4d60-ac87-bfcb5a14016b.png)

FSR 1.0 Ultra Quality:
![fsrultraquality](https://user-images.githubusercontent.com/40970965/233402395-b1189085-c27f-4f25-b3b0-a60d9f513439.png)

### Software information
[Resident Evil 2](https://store.steampowered.com/app/883710/Resident_Evil_2/), [Resident Evil 3](https://store.steampowered.com/app/952060/Resident_Evil_3/) and [Resident Evil 7](https://store.steampowered.com/app/418370/Resident_Evil_7_Biohazard/)

### System information
- GPU: RX 6600
- Driver: RADV - mesa 23.0.2
- Wine version: Proton 8.0-1
- VKD3D-Proton version: 2.8

**Comment by kassindornelles** [comment]
Example of working FSR 1.0 on Resident Evil Village:

70%
![70rev](https://user-images.githubusercontent.com/40970965/233411733-fbdd62da-161d-4cbf-967a-473b8dac778f.png)


Ultra quality:
![ultrarev](https://user-images.githubusercontent.com/40970965/233411756-960eb0d2-10ef-4302-8b0e-8ca8fee4db46.png)

**Comment by HansKristian-Work** [comment]
Closed as not a bug after all, or?

**Comment by kassindornelles** [comment]
> Closed as not a bug after all, or?

yeah i checked windows and they just dont do sharpening
