### ISSUE TITLE
Observation of the VKD3D-Proton commits up until Apr 19, 2023

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#1531]
For testing I built vkd3d-proton with the recent commits up until Apr 19, 2023.
I understand that it might not be production ready but I noticed odd behavior in Xorg with a 144hz display on Nvidia RTX 3060Ti.

I ran some benchmark tests on AC Valhalla and I get +100FPS spikes all along the benchmark run according to the AC valhalla benchmark results. I also experienced more stutter, both in the benchmark and while playing. 
The release version do not do this, I have a more constant FPS around 80.

**Comment by K0bin** [comment]
> and I get +100FPS spikes

You mean milliseconds, not FPS, right?

**Comment by shelterx** [comment]
Nope, FPS spikes. Really weird.

**Comment by shelterx** [comment]
It's almost like it's some sync issue. I will check tomorrow but I don't think the FPS spikes were visible in MangoHud. Only in the actual Valhalla benchmark FPS counter/results.

**Comment by shelterx** [comment]
Ok, so the FPS fluctuations are only in the Valhalla benchmark stats, not actually in MangoHud at all, it causes the rendering to appear jerky. So it's some odd false positive. Either the game tries to run at higher FPS but something is keeping it down, or it's some sync issue like I said before.
I have no idea, just spewing out some theories.

**Comment by shelterx** [comment]
vkd3d-proton-2.8-1-b7fb41b:
![valhalla-k62-nv510-bore](https://user-images.githubusercontent.com/8688458/233582801-5e3b6ec0-265f-4e03-a047-a4856c5e17d7.png)

vkd3d-proton as of 2023-04-21:
![valhalla-k62-nv510-bore-new-vkd3d](https://user-images.githubusercontent.com/8688458/233583295-474681ca-7915-4980-8024-ba1f47f2125f.png)

You might think, wow that's an FPS increase.... the thing is that it jumps up to over 100 FPS then down to around 70-80 FPS within a small amount of time. And like I said, it's only visible in the Valhalla benchmark.

**Comment by Blisto91** [comment]
If possible would you be able to bisect when this change occurs?

**Comment by shelterx** [comment]
Maybe, I know the vkd3d-proton build that's in GE-Proton7-55 have the same issue, That's a git build from 2023-04-10. GE-Proton7-55.
And the other working version I have seems to be from 2023-03-13.

**Comment by shelterx** [comment]
> If possible would you be able to bisect when this change occurs?

Found it! It's commit 9ca8741f892fd4e577786a8b636682fe41429a3b I verfied it by compiling the latest commits but removing this specific one!

**Comment by K0bin** [comment]
Ah, in that case the game simply receives data that is wrong from VKD3D-Proton.

The actual frame times aren't impacted and the extension does cause crashes on some systems, so it will stay that way for now.

**Comment by shelterx** [comment]
It does feel a lot smoother now tho', so maybe the game misbehaves when it's receiving the wrong info?

**Comment by K0bin** [comment]
Unlikely, at worst the input latency will be slightly higher.

**Comment by shelterx** [comment]
The majority of the stuttering is gone tho'. It seems to behave like vkd3d-proton-2.8-1-b7fb41b now.

**Comment by shelterx** [comment]
Should I close this or keep it for reference, I know for a fact it causes more stutter in AC Valhalla (yea, Valhalla might be a bad choice considering all other issues with this game but it's the game I currently play the most). But I haven't compared anything else.

**Comment by shelterx** [comment]
It was because KHR_present_wait was disabled as discussed eariler, this game did not like that at all. But on newer drivers that extension is available again. Closing.
