### ISSUE TITLE
please add a enviroment variable to switch between original d3d12.dll and vkd3d . it is ok when it switch after windows reboot

### ISSUE THREAD

**Issue by benni-r1** [HansKristian-Work/vkd3d-proton#1532]
Can you do that ?. this avoid to change manual the file to change between d3d12.dll and vkd3d . it is good enough when a reboot need do. I like use windows 11 and vkd3d if it work too.

**Comment by HansKristian-Work** [comment]
What? Are you replacing system32 d3d12.dll on Windows? Don't.

**Comment by benni-r1** [comment]
currently not. I think this also usefull when have the vkd3d in game folders . so when set the enviroment variable to vkd3d to off then the d3d12.dll in all the game program folder is ignore and original d3d12 is use. and if there is a little windows dx12 switcher GUI program is also nice and let more developers test it

**Comment by Blisto91** [comment]
Do note vkd3d-proton is a project aimed for Linux where this is already possible with env vars or wine GUI. Making something like that a GUI switcher UI is very much outside of scope to be in project.

Also please please don't ever consider replacing Windows system files on Windows itself if that was ever a thought.

**Comment by HansKristian-Work** [comment]
> so when set the enviroment variable to vkd3d to off

which environment variable are you referring to?

**Comment by mbriar** [comment]
> which environment variable are you referring to?

One that doesn't exist yet that OP wants you to add.

**Comment by HansKristian-Work** [comment]
I don't see the point in adding a .dll swapper or anything like that. The Windows Explorer is good enough I think.

**Comment by benni-r1** [comment]
a dll swapper can swap in all games you have to original  or vkd3d. this is usefull when have more games installed. but ok, if it is more work to add such a new enviroment variable then let it. on windows it try first open the dll in program folder. if the env var is set use original, the vkd3d return with fail to windows dll loader and then windows open the builtin dll

**Comment by HansKristian-Work** [comment]
Env-vars are really clunky and painful on Windows and I really don't want to end up in a situation where you have to start thinking if you're really using vkd3d-proton or not when debugging games. Either way, closing this issue as we don't intend to support this.

**Comment by benni-r1** [comment]
ok, i thought about it and a good solution is use windows symlinks. so i can in all games add a link to 1 place where i have the current vkd3d. then i need only rename it so all programs did not find it. when a new vkd3d build come i need not update the files in all games . i only add the symlink to the game
