### ISSUE TITLE
Dead Island 2 low framerate on in-game menus/inventory

### ISSUE THREAD

**Issue by Hadrianneue** [HansKristian-Work/vkd3d-proton#1533]
### SETUP
So i have Dead Island 2 setup via [legendary](https://github.com/derrod/legendary), nothing especial, dxvk-git and vkd3d-git, however i did need to install [mf-install](https://github.com/z0z0z/mf-install) otherwise game would freeze, and still "flashes green" on intro menus but nothing too distracting...

### ISSUE
~~Game runs fine but as soon as i open my inventory, or a workbench or in-game UI related menu (pause menu doesn't seem to create issues however) the framerate just tanks and doing it again worsens even further, going back to main menu and loading again seems to fix the issue, i got a capture, attached bellow.~~

**EDIT** The issue i'm actually reporting here is the low framerate on in-game menus (inventory, workbench, etc) and by keep opening these menus in succession - which is common when managing inventory - seems to ever so slightly increase vram usage.

### Software information
Dead Island 2 (EGS)

### System information
- GPU: RX 6500 XT
- Driver: Mesa-git/RADV
- Wine version: Wine-GE 7-41
- VKD3D-Proton version: 2.8 git

### Log files
[di2.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11298655/di2.log)
[GFXReconstruct capture](https://drive.google.com/file/d/1rpuXc0UX7WAY5cyzNcbYVAM0M6e0ejpQ/view?usp=sharing)

**Comment by mbriar** [comment]
Sounds like the typical symptom of running out of vram, especially looking at your GPU.

**Comment by Hadrianneue** [comment]
> Sounds like the typical symptom of running out of vram, especially looking at your GPU.

perhaps, that is what i also thought and likely the issue, but lord this is aggressive then, i changed to FSR2 performance to reduce vram usage and open the menu a couple of times, just enough to trigger this issue, and look at the numbers (check out the framerate on the top-left corner:

![1](https://user-images.githubusercontent.com/24306541/233719655-2d50b874-5e3f-47b8-b4bd-fd37ed58b97a.png)
![2](https://user-images.githubusercontent.com/24306541/233719661-8a745047-5a14-4fd2-8d27-d5ee2e6f3986.png)

**Comment by mbriar** [comment]
Is this with resizable BAR?

**Comment by Hadrianneue** [comment]
> Is this with resizable BAR?

lol no, its an old sandy bridge xeon (i7 3770 equivalent) DDR3, PCI-E 3.0x, so extra bandwidth limited, however Windows does not have these issues.

**Comment by mbriar** [comment]
Then it looks like the 256MiB CPU-visible VRAM heap is getting oversubscribed, maybe RADV_PERFTEST=nosam,dmashaders can help.

**Comment by mbriar** [comment]
> Windows does not present these issues.

windows always does significantly better under any kind of VRAM pressure.

**Comment by Hadrianneue** [comment]
> Then it looks like the 256MiB CPU-visible VRAM heap is getting oversubscribed, maybe RADV_PERFTEST=nosam,dmashaders can help.

No difference, i was very aware of these issues with this GPU, disabling [!6833 (merged)](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6833) does not help at all, in fact the game thoroughly dislikes that...

The only reason i'm reporting this its because there may be something funky here, these menus run very poorly, even if i reduce resolution and vram usage bellow 3GB, they already run like crap, and keep opening consecutively,  keeps increase vram usage and when that threshold of 85% vram / 5% GTT is crossed the framerate just tanks...

**Comment by Hadrianneue** [comment]
Also recorded some flickering that occurs when bringing up the inventory, since its semi-transparent, you can see the flickering around the sofas
[di2-flickering-inventory-menu.webm](https://user-images.githubusercontent.com/24306541/233797140-9101c340-f3d0-49bb-a0e0-9489cb1ce264.webm)

**Comment by Hadrianneue** [comment]
i'm closing this to stop polluting the issue tracker as its not descriptive enough and generally happens on more games and  most likely its not related to vkd3d directly....
