### ISSUE TITLE
VKD3D-Proton might need to improve streaming

### ISSUE THREAD

**Issue by GalacticalEdge** [HansKristian-Work/vkd3d-proton#1545]
### Software information
In games that use VKD3D-Proton, I've noticed that they tend to have slower streaming than native DirectX 12. This is mostly noticable in games that do a lot of streaming, but here are some games that do a lot of streaming I've tested that have this issue:

- Forza Horizon 4
- Forza Horizon 5
- Spider-Man Remastered
- Spider-Man: Miles Morales 

What I noticed about these games is that they use DX12 and have streaming issues (such as slowdowns) under VKD3D-Proton. So I thought these four games could possibly help us solve this issue in VKD3D-Proton.

### System information
- GPU: RX 6600 XT
- Driver: 22.3.5
- Wine version: Proton 8.0 and Experimental
- VKD3D-Proton version: 2.8

I also encounter this issue on my Steam Deck. Others on both Linux desktop and Steam Deck have reported the same issues with those games.

**Comment by doitsujin** [comment]
What's a good, fast, and consistent way to reproduce this?

In general, resource streaming is implemented by the game and doesn't involve an awful lot of D3D12 beyond allocating some memory and recording a copy command, so the improvements we could make on our side are extremely limited.

The only thing I can really see going wrong for some games is our heuristic to put upload heaps into VRAM, and the fact that we have to manually clear new allocations to zero. You could try if setting `VKD3D_CONFIG=no_upload_hvv` improves anything, but that may degrade overall performance as well.

**Comment by Blisto91** [comment]
@GalacticalEdge friendly ping.

**Comment by Blisto91** [comment]
@GalacticalEdge Another friendly ping
