### ISSUE TITLE
Regression: Assassins Creed Valhalla low quality world

### ISSUE THREAD

**Issue by Blisto91** [HansKristian-Work/vkd3d-proton#1551]
Ever since commit https://github.com/HansKristian-Work/vkd3d-proton/commit/7f20e3efde44cb3c06461b60fc35108f54fe811e the Assassins Creed Valhalla world and characters appear blocky/jagged as if everything is a lower resolution than it is set to.
The benchmark is a quick and easy way to test it.

So far this is only known to be an issue with radv as another user on Discord also see it on their Steam Deck but not their Nvidia PC.
I was unable to launch the game with amdvlk and amdgpu-pro does not like me lately.

<details>
  <summary>Screenshots</summary>
  
#### Working 1080p
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/8140e765-1aed-4ba6-ac20-b0ac709290e7)

#### Broken 1080p
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/366bc2ee-55d3-435e-9316-8f3f432659f2)

#### Broken 720p
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/a3f17b3a-de63-417b-9f5d-3778b5cd9aa4)

</details>

### Software information
Assassins Creed Valhalla.
Settings do not affect the issue but it might be more noticeable at lower resolutions like 720p or 1080p. Tho haven't personally tested higher.

### System information
- GPU: 7900xtx
- Driver: Mesa git
- Wine version: Proton Experimental & BE
- VKD3D-Proton version: Every version since https://github.com/HansKristian-Work/vkd3d-proton/commit/7f20e3efde44cb3c06461b60fc35108f54fe811e

### Log files
[vkd3d-proton.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/11436842/vkd3d-proton.txt)

**Comment by doitsujin** [comment]
Investigating, but things are strongly pointing towards some sort of RADV issue so far.

**Comment by doitsujin** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9005

**Comment by shelterx** [comment]
Can't say I noticed this with an Nvidia card, so yes, it got to be an AMD issue.

**Comment by Blisto91** [comment]
Will be fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23050 & https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23052

**Comment by doitsujin** [comment]
Closing since both RADV MRs got merged.
