### ISSUE TITLE
[Request] Limit FPS setting

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#1553]
Can you please add an option to limit the FPS, like dxvk has?
There are scenarios where you want to limit the FPS without using an external program (like mangohud etc).

**Comment by foundObjects** [comment]
+1, I've been wanting the same feature

**Comment by Vektor8298** [comment]
+1

**Comment by seathasky** [comment]
+1

**Comment by shelterx** [comment]
@HansKristian-Work Any chance we're getting this soon?

**Comment by seathasky** [comment]
Considering this post was made a year ago, doubtful

**Comment by mbriar** [comment]
DXVK only has this option to work around broken games so that they work out of the box. As far as i know, there are no d3d12 games that need this. So i don't see why you absolutely need this in vkd3d-proton instead of using one of yhe plentiful other options to limit fps

**Comment by shelterx** [comment]
True, but if I don't want to use VSync and have the FPS slightly below my screen refresh rate, the only option I have is to use Mangohud. Which's nice and all but it adds another layer that really isn't needed. The Nvidia driver does not support FPS limiting on Linux like it does in Windows, otherwise I would have limited it on driver level.

**Comment by mirh** [comment]
After some [heavy ass cargo-fu](https://www.pcgamingwiki.com/w/index.php?title=Special%3ACargoQuery&tables=Infobox_game%2C+API%2C+Video%2C+&fields=Infobox_game._pageName%3DGame%2C+API.Direct3D_versions%3DD3D+version%2C+Video.120_FPS%3DType+of+HFR+woe&where=API.Direct3D_versions+HOLDS+LIKE+%2712%25%27+AND+%28Video.120_FPS%3D%27false%27+OR+Video.120_FPS%3D%27limited%27+OR+Video.120_FPS%3D%27hackable%27%29&join_on=Infobox_game._pageName%3DAPI._pageName%2C+API._pageName%3DVideo._pageName&group_by=&having=&order_by%5B0%5D=&order_by_options%5B0%5D=ASC&limit=&offset=&format=) the game [Judgement](https://www.pcgamingwiki.com/wiki/Judgment#Video) would actually seem to need this. Maybe [WRC9](https://www.pcgamingwiki.com/wiki/WRC_9:_FIA_World_Rally_Championship#Video) too. 
And nothing can ever be perfect I mean... So even though in the year of the lord 2024 most games don't have special problems (or if not any they have a halfway decent built-in cap) the list is only destined to grow.

**Comment by shelterx** [comment]
Implemented in https://github.com/HansKristian-Work/vkd3d-proton/pull/2014
