### ISSUE TITLE
DXR options not available in Far Cry 6

### ISSUE THREAD

**Issue by FreezyLemon** [HansKristian-Work/vkd3d-proton#1562]
The in-game options for DXR Reflections and Shadows are greyed out:

![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/13467374/9c7711de-a40e-4b19-aa83-2f961746e6e2)

Everything else works.

### Software information
Far Cry 6, launched through Ubisoft Connect, configured in Lutris.

Added environment variables `VKD3D_CONFIG=dxr,dxr11` and `RADV_PERFTEST_RT=rt` to try and enable DXR support, but the game doesn't seem to detect DXR support.

### System information
- GPU: AMD Radeon RX 6900 XT
- Driver: Mesa 23.0.3 (also tried amdvlk 2023.Q2.1)
- Wine version: lutris-GE-Proton8-4
- VKD3D-Proton version: 2.8

### Log files
[fc6.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11512113/fc6.log)

**Comment by Blisto91** [comment]
Took a while until after I'd tested this to seemingly work for myself to notice you've written `RADV_PERFTEST_RT=rt`. The name for the var should just be `RADV_PERFTEST` so in full with the value it's `RADV_PERFTEST=rt`

**Comment by FreezyLemon** [comment]
Oh. That is slightly embarrassing. Yeah, it works now.

Thanks for the help!
