### ISSUE TITLE
World of Warcraft - Dragon Flight 10.1 No 3D accelerator found with 2.9 release

### ISSUE THREAD

**Issue by SteveEbey73742** [HansKristian-Work/vkd3d-proton#1565]
[gx.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11524938/gx.log)
When installed, the 2.9 release causes WoW Retail Client to report that no 3D accelerator can be found.  Removing 2.9 and installing 2.8 works fine.

### Software information
WoW DragonFlight 10.1, 

### System information
- GPU:Nvidia GTX 950 2Gig Vram
- Driver:530.41.03
- Wine version: 8.8 Staging
- VKD3D-Proton version: 2.9

### Log files
Proton or Wine logs.

**Comment by Blisto91** [comment]
Logs please.
Are you using dxvk along side?

**Comment by mbriar** [comment]
You probably forgot to install d3d12core.dll or to set an override to native for it

**Comment by SteveEbey73742** [comment]
@mbriar that is already set, as stated, 2.8 works. Added log for 2.8 to my comment.  Will install 2.9 and see if it generates a log.  

@Blisto91 I do have dxvk installed for Classic.

**Comment by mbriar** [comment]
Vkd3d-proton proton 2.8 didn't come with d3d12 core.dll and thus didn't need it to be installed or overridden. Relying on d3d12core.dll is new in 2.9.

21 May 2023, 17:37 by ***@***.***:

**Comment by SteveEbey73742** [comment]
@mbriar Are you saying that 2.9 has a D3D12core.dll that I need to install? The override is set in wine.

**Comment by Blisto91** [comment]
Yes 2.9 ships both a d3d12.dll and a d3d12core.dll

**Comment by SteveEbey73742** [comment]
@Blisto91 When the install script ran, it looks like it copied the d3d12core.dll to wine. Do you think I need to remove DXVK?

**Comment by Blisto91** [comment]
No. dxvk (it's `dxgi.dll`) just needs to be 2.1 or above.

Can you run the game from a terminal and attach the output? As a extra you can run it together with `WINEDEBUG=+loaddll` so we can also see the dll's loaded.

**Comment by SteveEbey73742** [comment]
@Blisto91 Apparently my DXVK was 2.0.  Removed it and game runs now with 2.9.  Going to upgrade to Geforce rtx 4060 as my family is getting me a father's day gift.  I am happy to just continue, as I believe part of the issue is my older 950 that may part of the problem.

**Comment by Blisto91** [comment]
Glad do hear your got it working :+1: 
Note that vkd3d-proton and dxvk development is somewhat tied together on some fronts, so i'd advise using it along side dxvk (2.1 minimum) if you run in to any issues. But if it's working now thats good ofc.

**Comment by mbriar** [comment]
Vkd3d-proton 2.9 requires at least dxvk 2.1 as stated in the changelog.

**Comment by SteveEbey73742** [comment]
I will install dxvk 2.1, just to be in compliance. Going to close this issue now, and appreciate all the help.

**Comment by SteveEbey73742** [comment]
Notice that 2.8 and 2.9 were taking long time to load, and reverted to dx11.  Installed 2.7 vkd3d-proton, and completely removed DXVK. Attached file shows that DX12 was used, and the login screen came up instantly.  
[Wow-gx-log-showing-dx12-with-version-2-7-vkd3d proton.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/11525617/Wow-gx-log-showing-dx12-with-version-2-7-vkd3d.proton.txt)

My question is why does an older vkd3d-proton let my card run dx12 but the newer ones do not?

**Comment by SteveEbey73742** [comment]
5/21 16:37:17.366  Bad CM2Light*: 000000000607fc28  Could this be the root of the problem, and what does it point to?

**Comment by mbriar** [comment]
Newer versions of vkd3d-proton *need* DXVK to be installed. The logs you posted look pretty useless because they contain no wine or vkd3d-proton output at all, if you're still having trouble, set `WINEDEBUG="+loaddll"` and `VKD3D_DEBUG=warn` and post a log with that.

**Comment by TerohsLab** [comment]
Yeah somehow retail WoW really doesn't like 2.9

Running it on Manjaro KDE
6.3.x Kernel
530.41 NVidia 2060

Trying to run the game via Lutris with Lutris-GE-Proton8-6.

With 2.8 the game launches perfectly fine, with 2.9 it fatal errors after the blizzard launcher.

> Started initial process 134630 from gamemoderun /home/node/.local/share/lutris/runners/wine/lutris-GE-Proton8-6-x86_64/bin/wine /home/node/Gaming/Games/Battle.net/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch WoW
> Start monitoring process.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> fsync: up and running.
> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> [0522/041828.557:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> [0522/041829.127:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
> [0522/041829.256:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> [0522/041831.860:ERROR:angle_platform_impl.cc(40)] rx::SwapChain11::reset(615): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x80004005
> [0522/041831.861:ERROR:gl_surface_egl.cc(787)] EGL Driver message (Critical) eglCreateWindowSurface: Bad allocation.
> [0522/041831.861:ERROR:gl_surface_egl.cc(1394)] eglCreateWindowSurface failed with error EGL_BAD_ALLOC
> [0522/041831.861:ERROR:in_process_command_buffer.cc(450)] ContextResult::kSurfaceFailure: Failed to create surface.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> wine client error:54c: write: Bad file descriptor
> wine client error:43c: write: Bad file descriptor
> Initial process has exited (return code: 0)
> wine: Call from 000000007B013D6E to unimplemented function d3d12core.dll.D3D12GetInterface, aborting
> ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by Blisto91** [comment]
Again. Could we get full logs please. Together with `WINEDEBUG="+loaddll"` and also `VKD3D_DEBUG=warn` if vkd3d-proton doesn't print anything.

<details>
  <summary>Screenshot from AMD setup</summary>
  
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/d8b3d38f-1c67-4d14-845e-092a383a683e)
</details>

**Comment by mbriar** [comment]
> wine: Call from 000000007B013D6E to unimplemented function 

This means that is issue is what I said in my very first reply and that you didn't install d3d12core.dll correctly.

**Comment by TerohsLab** [comment]
Oh ok ... thats probably the issue then. I'm still on Lutris 0.5.12.

**Comment by Blisto91** [comment]
Did you guys figure this out? :slightly_smiling_face:

**Comment by SopaDeMacaco-UmaDelicia** [comment]
I'm launching WoW from Steam with Proton Experimental, the game also doesn't allow me to choose DX12 renderer. Arc A770 Mesa Git btw.

**Comment by mbriar** [comment]
On Intel it's probably a different problem (but also very unlikely to be a vkd3d-proton bug) but post a proton log if you want something better than wild guesses.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
> On Intel it's probably a different problem (but also very unlikely to be a vkd3d-proton bug) but post a proton log if you want something better than wild guesses.

It is vkd3d problem, proton 7 does expose DX12 option in World of Warcraft, proton experimental does not.

**Comment by mbriar** [comment]
Post the log.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
[WoW-Proton.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11582820/WoW-Proton.log)
Here, WoW doesn't allow it to launch in dx12 mode, it straight goes to dx11.

**Comment by mbriar** [comment]
> 9258.862:0668:066c:err:vkd3d-proton:vkd3d_init_device_caps: Lacking support for single texel alignment.

It's because d2ad4f2532d68bd introduced more strict feature checks and that fails on Intel without: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23263

**Comment by Blisto91** [comment]
Workaround for the Intel ANV issue 
https://github.com/HansKristian-Work/vkd3d-proton/pull/1576

**Comment by Blisto91** [comment]
A new Proton Experimental has been pushed with the Intel ANV work around

**Comment by SopaDeMacaco-UmaDelicia** [comment]
> A new Proton Experimental has been pushed with the Intel ANV work around

Thanks, it worked, but I updated to latest mesa git where ingle texel alignment was enabled. Sadly the performance in dx12 is worse than in dx11 mode, I guess anv is not there yet compared to radv.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
Also, sorry for a bit offtop but the game doesn't allow me to enable Variable Rate Shading. It says I need a capable of shader model 6 videocard. Is that a VKD3D problem or ANV?

**Comment by Blisto91** [comment]
Vkd3d-proton likely as the issue is known also with amd radv. We are not sure exactly what the game is looking for as we haven't gotten it working yet by faking various stuff.

**Comment by csutcliff** [comment]
There was a wow forum post recently where they said that the lack of "barycentrics" in the driver was causing the game to default to Shader model 5.0 There was a change on 24th May and it will now go to SM6.0 but not 6.5 which I believe is what is required for VRS?

my gx.log shows:

`GpuInfo: sm:dx_6_0, rt:DXR 1.1, vrt:2, bary:0, mesh:1 pull:1`

**Comment by Blisto91** [comment]
@csutcliff thank you for the hint. Will check it out.

@SteveEbey73742 @TerohsLab Friendly ping. Did you figure out your original issues?

**Comment by Blisto91** [comment]
@csutcliff Hey nice. Even without the radv barycentric MR it looks like with the new update i'm able to use RT Shadows and VRS out of the box now just with `VKD3D_CONFIG=dxr11 RADV_PERFTEST=rt`

**Comment by csutcliff** [comment]
@Blisto91 strange, that enables RT shadows for me but VRS is still "unsupported for graphics related reasons"

**Comment by Blisto91** [comment]
What is your GPU

**Comment by csutcliff** [comment]
> What is your GPU

6900XT, currently mesa-git and vkd3d-proton git but same with latest release version of both.

> You could try along with VKD3D_FEATURE_LEVEL=12_2 or VKD3D_SHADER_MODEL=6_6 or both just to see if that does anything.

Neither made a difference.

**Comment by Blisto91** [comment]
hm. odd

**Comment by SteveEbey73742** [comment]
@Blisto91 nope, have not tried. I will be upgrading to GTX 4060 ti after father's day, june 18.  I plan to install the latest versions of DXVK and VKD3D at that time, per the instructions given here, to see if that works.  My current gtx950 is probably too old for some of the advanced features that seem to be enabled in 2.9.  I am able to use 2.7 for DX12 in retail and classic.  I may try VKD3D 2.7 with my new card, to have a baseline to start with, before I install the latest DXVK and VKD3D.

**Comment by TerohsLab** [comment]
@Blisto91 For me it was because of an outdated Lutris install 0.5.12 which couldn't handle the new linking stuff. 

I reverted back to 2.8 of vkd3d which fixed all my issues playing via Lutris.

Once 0.5.13 Lutris landed in my distro i've been playing on vkd3d 2.9 with no issues at all.

**Comment by SteveEbey73742** [comment]
My RTX 4060 ti works with dxvk 2.2 and vkd3d 2.9 setting dxr11 does ray tracing and dx12.

**Comment by Blisto91** [comment]
Yay! 🎉
