### ISSUE TITLE
Are PROTON_ENABLE_NVAPI or VKD3D_CONFIG still needed?

### ISSUE THREAD

**Issue by luisalvarado** [HansKristian-Work/vkd3d-proton#1573]
My current Steam parameters are the following:

__GL_THREADED_OPTIMIZATIONS=1 PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr11 mangohud gamemoderun %command%

My question is more in regards if this parameters are still needed since the 2.9 brings so many changes. Just to be up to date with Hans work.

**Comment by mbriar** [comment]
I'm 99% sure __GL_THREADED_OPTIMIZATIONS=1 never did anything for vulkan. With regards to PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr11 nothing has changed, but proton does enable PROTON_ENABLE_NVAPI=1 by default for some titles.

**Comment by Blisto91** [comment]
dxr11 is now a alias for dxr which also enable 1.1 now. But besides that no.

**Comment by luisalvarado** [comment]
Wow, thank you so much guys. That would clean up the parameters a lot. I will cite this on my future videos so others can learn. Thanks again.
