### ISSUE TITLE
Forza Horizon 4 Lego Speed Champions Ground Texture bug

### ISSUE THREAD

**Issue by GalacticalEdge** [HansKristian-Work/vkd3d-proton#1574]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
I played the Forza Horizon 4's Lego Speed Champions DLC on my Steam Deck using the stable branch and I noticed the ground textures have a odd graphical bug as seen below

UPDATE: I've noticed some surfaces exhibiting the same behavior in the Great Britain map. It did not happen before, so maybe there's been a regression in VKD3D-Proton?

UPDATE 2: I noticed the same behavior with Proton 8.0-2. To add, this happens on snow surfaces, so maybe that needs to be fixed?

![20230524201140_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/31458662/5121b1cb-fb1b-40ed-a590-07a81716e5d1)

### System information
- GPU: Steam Deck
- Driver: Mesa 23.1
- Wine version: Proton Experimental
- VKD3D-Proton version: 2.9

**Comment by GalacticalEdge** [comment]
> I'm guessing they mean the small white pixels that are present in the dirt/grass area. You have to view the full image to kinda notice, tho it does look like some kind of bug yes.

Yes, that is what I am talking about. Sorry for not being more clear on that.

**Comment by Blisto91** [comment]
It just seems to be the game as i reproduce the same white dots with the native d3d12 game on Windows.

![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/5c62839f-7487-4923-9a97-5d819f950bd2)
