### ISSUE TITLE
535.54.03 Screen tearing in Wayland session

### ISSUE THREAD

**Issue by jkrhu** [HansKristian-Work/vkd3d-proton#1596]
Hi!

After upgrading to the latest stable 535.54.03 driver I've noticed screen tearing in games running through DXVK and VKD3D-Proton. These are all V-synced and running in a Wayland session. I've reported it to Nvidia already, but normal desktop use is unaffected, that's why I'm curious. Is this something that will be fixed through enabling KHR_present_wait or it's purely another driver bug? 

### Software information
Every VKD3D-Proton or DXVK game

### System information
- GPU: Nvidia RTX 3060
- Driver: 535.54.03

**Comment by HansKristian-Work** [comment]
This cannot be a bug on our end. KHR_present_wait is not going to fix tearing.
