### ISSUE TITLE
Steam SDK initialization failed

### ISSUE THREAD

**Issue by Pednick** [HansKristian-Work/vkd3d-proton#1597]
I'm trying to play Horizon Zero Dawn with wine using vkd3d-proton, but when I try to run it an error appears: "Steam SDK initialization failed, game will now quit."

**Comment by Blisto91** [comment]
Are you trying to play the Steam version outside of Steam?

**Comment by Pednick** [comment]
> Are you trying to play the Steam version outside of Steam?

Yes

**Comment by mbriar** [comment]
Definitely not a vkd3d-proton problem then and you'd need to use something like a steamapi emulator to make this work. This is not the place to ask for support with this.

**Comment by Blisto91** [comment]
> Yes

Well there is your issue then.
