### ISSUE TITLE
Unreal Engine 5.2 Demo by MAWI fails to start after Selection Screen.

### ISSUE THREAD

**Issue by fakhraldin** [HansKristian-Work/vkd3d-proton#1598]
Unreal Engine 5.2 Demo namely Redwood Forest by MAWI GmbH crashes after start selection screen.
I also opened an issue bug report for UE5.1 here.:
https://github.com/HansKristian-Work/vkd3d-proton/issues/1599

### Software information
MAWI Redwood Forest | Unreal Engine 5.2 Nanite | Demo
A public Demo for issue reproduction can be obtained from their promotion website.
https://youtu.be/-XW0wRN9tk0
Settings: Default, untouched

### System information
- GPU: RX 6600
- Driver: Mesa 23.1.2
- Wine version:  lutris-GE-Proton8-8-x68_64
- VKD3D-Proton version: 2.9

### Log files

[winelogUE5.2.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/11835514/winelogUE5.2.txt)
Screenshot from the error message of the app.:
https://abload.de/img/bildschirmfotovom2023heieu.png
<a href="https://abload.de/image.php?img=bildschirmfotovom2023heieu.png"><img src="https://abload.de/img/bildschirmfotovom2023heieu.png" /></a>

**Comment by doitsujin** [comment]
Are we sure that this isn't just failing to find DXC or something? There are no obvious vkd3d errors in the log, certainly no shader-related ones.

**Comment by fakhraldin** [comment]
Maybe it is RADV related then. I am not sure. Those Demos are primarily targeted to run on nvidia gpus. I don't have any nvidia gpus to countercheck VKD3D on them.

**Comment by fakhraldin** [comment]
After installing mesa-git, the UE5.1 Demo by MAWI works now, probably due to this fix.:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/91505132423bcf8949034ef277b8bee4e1936855

I marked the UE5.1 issue as solved with an updated winelog here.:
https://github.com/HansKristian-Work/vkd3d-proton/issues/1599#issuecomment-1635585150

For more background infos about the probable cause for the fix read this thread.:
https://github.com/HansKristian-Work/vkd3d-proton/issues/1451

----

The UE5.2 Demo though starts now with mesa-git, but crashes after a couple of seconds.

**Comment by fakhraldin** [comment]
Can be closed. No more crashes at start up finally.

**Comment by fakhraldin** [comment]
Can be closed. No more crashes at start up finally.
