### ISSUE TITLE
DiabloIV Patch 1.0.3.42936 crash to desktop

### ISSUE THREAD

**Issue by darksidewalker** [HansKristian-Work/vkd3d-proton#1615]
Short grey Loading Screen (1s) than crash to desktop, no error notification.
Battle-Net-Launcher starts, but game won't run at all now.

### Software information
DiabloIV Version 1.0.3.42936 (latest of now)

### System information
- GPU: Nvidia RTX 2070S
- Driver: 530.41.03
- Wine version: Lutrix-GE-Proton-8.8
- VKD3D-Proton version: 2.9

### More Tests
Tested Wine 8.8 staging, and other lower Wine Versions
Tested VKD3D 2.8, 2.6
Fully updated system
Worked as of 2 days ago with the oder D4 Version

### Log files
[lutris-d4.log](https://github.com/HansKristian-Work/vkd3d-proton/files/11925293/lutris-d4.log)

**Comment by wu-yue** [comment]
Try latest master branch VKD3D-Proton.  I'm using 745895291269e319e2cf611ffc952ac72c715616 and the game works normally.

**Comment by darksidewalker** [comment]
Did it with vkd3d-proton - build: 745895291269e31 and it does crash.
Can you provide more info? I build the latest branch and put the DLL's inside Lutris runtimes and selected lutris to use the folder. Anything else?

**Comment by wu-yue** [comment]
Maybe it's not VKD3D-Proton's issue. I'm playing here right now.

**Comment by darksidewalker** [comment]
I got the problem the "video-hybrid-amd-nvidia-prime" 2023.03.23 with ryzen do not work now. Changed to video-nvidia            2023.03.23 and can  play now.
The question is why out of a sudden...
