### ISSUE TITLE
A Plague Tale Requiem no longer detects ray tracing support with enable_experimental_features turned on

### ISSUE THREAD

**Issue by adolfintel** [HansKristian-Work/vkd3d-proton#1616]
### Software information
A Plague Tale Requiem, Version 1.5.1 from GOG

### System information
- GPU: AMD 6900xt
- Driver: Mesa, current master
- Wine version: Wine-GE-Proton8-8
- VKD3D-Proton version: current master

As I was mentioning in #1437, when using `VKD3D_CONFIG=enable_experimental_features` the game no longer detects ray tracing support.

I also noticed that the game now works with `VKD3D_FEATURE_LEVEL=12_2` (it used to require 12_0) so I did some more testing:
* defaults: works properly, RT detected and "works" (about as well as you'd expect from this game)
* 12_2 and no experimental features: also works properly, RT detected and "works"
* 12_2 and experimental features: RT not detected, game works properly
* 12_2 and experimental features, RT turned on in the game's config file: game freezes at intro

**Comment by mbriar** [comment]
Without VKD3D_CONFIG=dxr it shouldn't detect any ray tracing, does it work if you set VKD3D_CONFIG=dxr,enable_experimental_features?

**Comment by adolfintel** [comment]
Of course, why am I so stupid? I put VKD3D_CONFIG=dxr11 in /etc/environment months ago and totally forgot about it until now.
Embarrassing...
