### ISSUE TITLE
Cyberpunk 2077 2.0 Xid 31 crashes

### ISSUE THREAD

**Issue by HamilcarR** [HansKristian-Work/vkd3d-proton#1635]
Since 1.62 , the game crashes in 5 min to 10 min . No matter which version of proton , wich version of GE proton , experimental , hotfix , the game crashes. 
It is the only game that crashes in this manner , I do not have any problem on other games , on any settings. 

If you check the logs , there's this error that is shared between the two : 
```
01bc:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
01bc:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
01bc:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
01bc:err:vkd3d_queue_flush_waiters: Failed to submit queue(s), vr -4.
```

Also , on protonDB , you'll notice that most people who experience this crash have a 20xx RTX... 

### Software information
Cyberpunk 2077 , any setting. 

### System information
- GPU: RTX 2060 , Nvidia 
- Driver: 535.86.05 
- Wine version: wine-8.12
- VKD3D-Proton version:  8.0-2 , GE Proton-8-1

### Log files
GE proton 8-1 :
[steam-1091500.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12135711/steam-1091500.log)

Proton 8.0-2 : 
[steam-1091500.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12135717/steam-1091500.log)

**Comment by Dahipppo1555** [comment]
Hi, can you look into your "dmesg" when it crashes ?
because this issue can be dupe of `https://github.com/HansKristian-Work/vkd3d-proton/issues/1510`

**Comment by HamilcarR** [comment]
@Dahipppo1555 You are right , I have : 
[ 2466.946427] NVRM: Xid (PCI:0000:01:00): 31, pid=8479, name=GameThread, Ch 0000011f, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_GCC faulted @ 0x6330_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ

What is the cause of this bug ?

**Comment by K0bin** [comment]
> What is the cause of this bug ?

Impossible to say without lots of painful debugging.

**Comment by Zenzi0** [comment]
Maybe the post about Witcher 3 freezing a few minutes into gameplay is related.

https://github.com/HansKristian-Work/vkd3d-proton/issues/1638

**Comment by eXt73** [comment]
NVRM error: Xid (PCI:XXXX:XX:XX): 109 appears most often

**Comment by conor42** [comment]
I see no improvement on a Tesla T4 from disabling KHR_present_wait. A fast way to reproduce the bug is open and close the map.  If it doesn't crash within a few seconds of closing the map, repeat. You must be moving either on foot or in a car, but on foot doesn't result in the Vulkan device lost error -4, while in a car usually does.

**Comment by TheWinterFrostbite** [comment]
Game plays fine until you drive a car and open up any kind of menu with a hotkey (inventory, map, quests).

Dmesg shows:
`NVRM: Xid (PCI:0000:0a:00): 31, pid=37878, name=GameThread, Ch 00000057, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_GCC faulted @ 0x4df0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ`

The vkd3d errors in the proton log show:
`err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4

Driver: 535.43.09
GPU: RTX 2080Ti
Kernel: 6.5.5
VKD3D: vkd3d-proton@089df9ca
Proton: GE 8-15
Vulkan: 1.3.262
Distro: Gentoo
DE: i3 version 4.21-126-g30131ed6+
CPU: Ryzen 9 5950x

**Comment by HamilcarR** [comment]
someone has found a workaround by using an older driver version : 
https://forums.developer.nvidia.com/t/cyberpunk-2077-1-62-1-63-crashes/260799/14?u=bensalem.amine321

I haven't tested this claim since my kernel version doesn't allow me to install older versions of nvidia drivers , but it seems the version 510.108.03 prevents the Xid 31 crashes , at the cost of not being able to run DLSS and a 10% perf decrease.

**Comment by TheWinterFrostbite** [comment]
I have been playing for a few days now using VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait on driver 535.43.09 and the frequency of my crashes has gone down. The game still has a tendency to crash when mixing menus with driving, but I am able to get anywhere from 10 minutes to 3 hours of gameplay before I get the Xid error, making it difficult to diagnose. I am unsure if disabling VK_KHR_present_wait had an actual effect on stability, or if the game just stabilized after a bit of the shader cache had accumulated.

**Comment by HamilcarR** [comment]
hmm , I don't think so , I remember disabling present_wait and it didn't really change anything.

**Comment by ODeadlock** [comment]
Despite it not being directly related, I did a quick test with the nv_dgcc_enable branch that enables VK_NV_device_generated_commands_compute with the latest vulkan beta driver 535.43.10. This shows no significant improvement to the crashing.

Driver: 535.43.10
GPU: RTX 2080Ti
Kernel: 6.5.5
VKD3D: https://github.com/HansKristian-Work/vkd3d-proton/commit/01f62c874ca5f580f8c6c3e202189f2eb55aaaa9
Proton: GE 8-15
Vulkan: 1.3.262
Distro: Gentoo
DE: i3 version 4.21-126-g30131ed6+
CPU: Ryzen 9 5950x

**Comment by HamilcarR** [comment]
The crash is now resolved with the 545 beta driver . closing the issue .
