### ISSUE TITLE
Resident Evil 4 Remake: Reflection glitches in some areas

### ISSUE THREAD

**Issue by mbriar** [HansKristian-Work/vkd3d-proton#1636]
In some areas in RE4 Remake, specifically at the end of chapter 10, in the area where you use the liquid nitrogen to fight the monster, the light reflected from some glass surfaces is glitching out. This does not happen with native d3d12 on windows.
Turning off Anti-Aliasing makes the glitch much more severe, but it still happens with AA set to TAA+FXAA.

Here is a savegame to reach the relevant spot ([path to put it](https://www.pcgamingwiki.com/wiki/Resident_Evil_4_(2023)#Save_game_data_location)), load the save in chapter 10, second slot after the autosave: https://mega.nz/file/WyJXwIpI#K4cY3R6IjM5OpsKbia_ZV7uo-CiU-rSPX-3swUl9Gww

Here is a video that shows how to reach the spot where the glitch happens from the save location and what it looks like: https://mega.nz/file/O2o2AIqQ#Qi7DPNqAfSZlAfMoEIyD2uuDjPV3sb9Fo6wIr5liSec

Same spot on windows running on the same hardware and settings that doesn't show the glitch: https://mega.nz/file/CvIilajD#ddxhbg-f-XxvNpnxBKZQZGGtu61SMnjVMUVnvOIAz5Y

Vulkan renderdoc capture of the glitch: https://mega.nz/file/eyxjjTCB#R-9hW12bw4I_i1Mxd_ZmaxY8-BSd0BzKakyT9gmkICI

### Software information
Resident Evil 4 Remake, most settings max, Anti-Aliasing off

### System information
- GPU: 6700XT
- Driver: Mesa main and AMDVLK
- Wine version: Proton Experimental 
- VKD3D-Proton version: db608963e43416a

### Log files
[re4_vkd3d_log.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/12139657/re4_vkd3d_log.zip)

**Comment by runar-work** [comment]
Great that you managed to capture this. I'm unable to replay the capture with my RX 7600 since I'm missing an extension (VK_KHR_fragment_shader_barycentric), and save game transfer doesn't work either. However, I happened to find a location in the very beginning of chapter 2 where a light fixture causes the same issue when the light is reflected in surrounding puddles (also on the other side of walls). Looks like some compute shader shenanigans.

**Comment by mbriar** [comment]
VK_KHR_fragment_shader_barycentric should be supported on the rx 7600 when using recent Mesa main, but the capture might still not work for you due to gpu generation differences. But if you found another spot to repro, thanks fine too 👍

**Comment by kassindornelles** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/pull/1648 didnt fix it for me

**Comment by mbriar** [comment]
This is fixed now in master with the workaround. Although I have to wonder how it works on native drivers with fp16, even on those that are older than the game itself and I guess unlikely to ship workarounds.

**Comment by HansKristian-Work** [comment]
> This is fixed now in master with the workaround. Although I have to wonder how it works on native drivers with fp16, even on those that are older than the game itself and I guess unlikely to ship workarounds.

The game uses min16float, so it's likely native never used fp16 for those. The shaders are very spammy with FConv in general which should guide a compiler to not use FP16 in the first place. But proving that is too much work.

**Comment by logashoff** [comment]
Experiencing this issue with Mesa 25.1.0-devel and Proton Experimental

**Comment by MilesRdz** [comment]
I'm running into this issue as well.
<details><summary>System Specs</summary>
<p>
Computer Information:
Manufacturer: ASRock
Model: A520M-ITX/ac
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5700X 8-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4665 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
BMI1: Supported
BMI2: Supported
F16C: Supported
FMA: Supported
Operating System:
"CachyOS" (64 bit)
Kernel Name: Linux
Kernel Version: 6.18.3-2-cachyos
X Server Vendor: The X.Org Foundation
X Server Release: 12401009
X Window Manager: KWin
Steam Runtime Version: steam-runtime_1.0.20251202.187498
Client Information:
Version: 1766451605
Browser GPU Acceleration Status: Enabled
Browser Canvas: Enabled
Browser Canvas out-of-process rasterization: Enabled
Browser Direct Rendering Display Compositor: Disabled
Browser Compositing: Enabled
Browser Multiple Raster Threads: Enabled
Browser OpenGL: Enabled
Browser Rasterization: Enabled
Browser Raw Draw: Disabled
Browser Skia Graphite: Disabled
Browser Video Decode: Enabled
Browser Video Encode: Disabled
Browser Vulkan: Disabled
Browser WebGL: Enabled
Browser WebGL2: Enabled
Browser WebGPU: Disabled
Browser WebNN: Disabled
Video Card:
Driver: AMD AMD Radeon RX 9060 XT (radeonsi, gfx1200, LLVM 21.1.6, DRM 3.64, 6.18.3-2-cachyos)
Driver Version: 4.6 (Compatibility Profile) Mesa 25.3.3-arch1.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 119 Hz
VendorID: 0x1002
DeviceID: 0x7590
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 3840 x 2160
Desktop Resolution: 3840 x 2160
Primary Display Size: 62.99" x 35.43" (72.24" diag), 160.0cm x 90.0cm (183.5cm diag)
Primary VRAM: 16384 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 64223 Mb
VR Hardware:
VR Headset: None detected
No VR configuration with trackers detected
Most number of trackers in a session: 0
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 951819 MB
Largest Free Hard Disk Block: 927627 MB
Storage:
Number of SSDs: 2
SSD sizes: 2048G,1000G
Number of HDDs: 0
Number of removable drives: 0
</p>
</details>

**Comment by logashoff** [comment]
Can anyone who uses Windows confirm this is a game engine bug and not Mesa or Proton issue?

https://github.com/user-attachments/assets/958e533c-7c4d-4bbb-a26c-fc0f76e216aa
