### ISSUE TITLE
Scorn (GOG) crashes after start

### ISSUE THREAD

**Issue by rtentser** [HansKristian-Work/vkd3d-proton#1644]
Steam version of the game runs out of the box with proton-experimental. GOG version fails with wine & wine-ge.

### Software information
Scorn (1.2.2.0).

### System information
- GPU: RX 6600:
- Driver: mesa 23.1.5
- Wine version: wine-8.13, wine-ge 8.13
- VKD3D-Proton version: 2.9, 2.9.r92.gdb608963

### Log files
Different errors with upsteam wine and ge:
[wine-ge.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12269770/wine-ge.log)
[wine.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12269771/wine.log)

**Comment by Blisto91** [comment]
Looks like a decompiler error. The game on Steam will probably install and set the Windows native versions.
Dunno the specific version need but installing `d3dcompiler_42`, `d3dcompiler_43`, `d3dcompiler_46` or `d3dcompiler_47` through winetricks will probably make it work.

**Comment by rtentser** [comment]
Thank you, 43 solved this problem. Now the game throws some UE4 exception.
![Screenshot_20230806_215700](https://github.com/HansKristian-Work/vkd3d-proton/assets/34958119/c241f482-ddb8-4eaf-bf69-995f1ec5e67a)
[wine-ge.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12269880/wine-ge.log)

**Comment by Blisto91** [comment]
Cool. 
I can also see that you are using wines own `dxgi.dll`.
You'll have to install dxvk alongside vkd3d-proton as the dxgi it provides is the officially supported one. Other ones likely won't work since last version.

**Comment by rtentser** [comment]
Yeah, that did the trick. Thanks for you help! It's my first time with vkd3d in custom prefixes, so i didn't know about dxvk dependency. Now i see, it's in readme.

**Comment by Blisto91** [comment]
np. Hope the game works for you now and is fun.
