### ISSUE TITLE
The Last of Us Part I - Wrong GPU or CPU utilization

### ISSUE THREAD

**Issue by kr1spy2115** [HansKristian-Work/vkd3d-proton#1669]
The performance in the game with VKD3D-proton is limited to like 80% of windows DX12 performance. Tried every proton or mesa versions and nothing changed.

Windows - High: 65 fps
Linux - High: 50 fps
GPU load was around 85% on Linux and 95-99% on Windows and CPU load was around 60-75% on Linux and ~95% on Windows during testing.

Software information
The Last of Us Part I - 1080p 120 Hz

System information
GPU: RX 6600 XT
CPU: i3-12100f
Driver: Mesa 23.1.6-23.1.2
Linux kernel: 6.4
Wine version: Proton Experimental / Proton GE 8.13-8.11
VKD3D-Proton version: bundled with Proton

**Comment by Blisto91** [comment]
Post a Proton log for good measure.
How is your overall vram usage when running the game. Does launching with `VKD3D_CONFIG=no_upload_hvv` change anything?

**Comment by kr1spy2115** [comment]
[steam-12271807113394651136.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12432781/steam-12271807113394651136.log)
I'm getting around 7 GB VRAM usage and changing textures settings dont do anything.
Command `VKD3D_CONFIG=no_upload_hvv` changes nothing

**Comment by Blisto91** [comment]
Could you try to run the game without `amd_ags_x64` set as builtin as a quick test as i've seen a report of fps and frametime issues with it for this game. If you didn't set it yourself via the launch options then run the game with `WINEDLLOVERRIDES="amd_ags_x64=n"`

**Comment by Blisto91** [comment]
Ye the second thing was just if you hadn't set it yourself. Thanks for checking i will do some poking.

**Comment by kr1spy2115** [comment]
thanks for help, is there any way to make game think it has like more VRAM without the dll override?

**Comment by K0bin** [comment]
> GPU load was around 85% on Linux and 95-99% on Windows and CPU load was around 60-75% on Linux and ~95% on Windows during testing.

So the game is just CPU limited.

**Comment by Blisto91** [comment]
Reproduced the issue.

> thanks for help, is there any way to make game think it has like more VRAM without the dll override?

Don't know actually.

**Comment by kr1spy2115** [comment]
> > GPU load was around 85% on Linux and 95-99% on Windows and CPU load was around 60-75% on Linux and ~95% on Windows during testing.
> 
> So the game is just CPU limited.

on windows yes, but removing dll override fixed cpu usage or whatever it was and now cpu is like "unlocked" and im getting now avg 100 fps from cpu when i use lowest cpu settings

**Comment by VladimirMrzv** [comment]
Another bug with textures loading with big delay.
link to my video 
https://www.youtube.com/watch?v=_48u89AJKA4

With Ultra graphics setting delay is longer, but in low without delay.
Also  WINEDLLOVERRIDES="amd_ags_x64.dll=b"  help to load textures more fast

**Comment by VladimirMrzv** [comment]
WINEDLLOVERRIDES="amd_ags_x64=n" also helps to load textures, without it they are blurry

**Comment by Blisto91** [comment]
@kr1spy2115 The game now have AGS builtin on Proton Experimental Bleeding Edge by default as the performance drop have received a fix. Are you able to verify that it is fine now?

**Comment by kr1spy2115** [comment]
> @kr1spy2115 The game now have AGS builtin on Proton Experimental Bleeding Edge by default as the performance drop have received a fix. Are you able to verify that it is fine now on Bleeding Edge?

will do, thanks for info

i will play with this around today

**Comment by kr1spy2115** [comment]
> @kr1spy2115 The game now have AGS builtin on Proton Experimental Bleeding Edge by default as the performance drop have received a fix. Are you able to verify that it is fine now on Bleeding Edge?

my friend tested it and it works great now, no problems with it
