### ISSUE TITLE
Starfield - "Graphics card does not meet the minimal specifications requirements." Error Messageon GTX 1080 Ti

### ISSUE THREAD

**Issue by kleinermob** [HansKristian-Work/vkd3d-proton#1680]
Starfield doesn't start and results in this Error Message, same error happened with Proton too and under Windows too with VKD3D.

-Distro: Arch Linux
- GPU: NVIDIA GeForce GTX 1080 Ti
- Driver: 535.104.05-2
- Wine version: lutris-GE-Proton8-14
- VKD3D-Proton version: v2.9

fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:err:hid:udev_bus_init UDEV monitor creation failed
00d4:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
00d4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00d4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00d4:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FCD0 1 C) semi-stub
00d4:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FCD0 1 C) semi-stub
0118:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0118:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0118:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0118:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000034FCA8, 000000000021FAC0: stub!
00d4:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000091D5D8, 0000000001B2FAA0: stub!
info:  Game: Starfield.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3fd0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce GTX 1080 Ti:
info:    Driver : NVIDIA 535.104.5
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 17965 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: Starfield.exe
info:  DXVK: v2.2
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3fd0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce GTX 1080 Ti:
info:    Driver : NVIDIA 535.104.5
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 17965 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
1109.891:00d0:00d4:info:vkd3d-proton:vkd3d_instance_apply_application_workarounds: Program name: "Starfield.exe"
1109.891:00d0:00d4:info:vkd3d-proton:vkd3d_instance_deduce_config_flags_from_environment: shader_cache is used, global_pipeline_cache is enforced.
1109.891:00d0:00d4:info:vkd3d-proton:vkd3d_config_flags_init_once: VKD3D_CONFIG=''.
1109.891:00d0:00d4:info:vkd3d-proton:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
1109.891:00d0:00d4:info:vkd3d-proton:vkd3d_instance_init: vkd3d-proton - build: 6365efeba253807.
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_memory_info_upload_hvv_memory_properties: Topology: Device heaps are split. Assuming small BAR situation. Using HOST_COHERENT only.
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device does not support VK_EXT_mutable_descriptor_type (or VALVE).
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1109.972:00d0:00d4:fixme:vkd3d-proton:d3d12_device_caps_init_feature_options1: TotalLaneCount = 3584, may be inaccurate.
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Remapping VKD3D_SHADER_CACHE to: vkd3d-proton.cache.
1109.972:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
1109.978:00d0:0134:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
1109.978:00d0:0134:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
1109.978:00d0:0134:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.143 ms.
1109.978:00d0:0134:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Failed to map read-only cache: vkd3d-proton.cache.
1109.978:00d0:0134:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
1109.995:00d0:00d4:info:vkd3d-proton:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
1109.995:00d0:00d4:info:vkd3d-proton:vkd3d_instance_init: vkd3d-proton - build: 6365efeba253807.
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_memory_info_upload_hvv_memory_properties: Topology: Device heaps are split. Assuming small BAR situation. Using HOST_COHERENT only.
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device does not support VK_EXT_mutable_descriptor_type (or VALVE).
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.066:00d0:00d4:fixme:vkd3d-proton:d3d12_device_caps_init_feature_options1: TotalLaneCount = 3584, may be inaccurate.
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Remapping VKD3D_SHADER_CACHE to: vkd3d-proton.cache.
1110.066:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
1110.072:00d0:013c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
1110.072:00d0:013c:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
1110.072:00d0:013c:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.140 ms.
1110.072:00d0:013c:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Failed to map read-only cache: vkd3d-proton.cache.
1110.072:00d0:013c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
1110.090:00d0:00d4:info:vkd3d-proton:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
1110.090:00d0:00d4:info:vkd3d-proton:vkd3d_instance_init: vkd3d-proton - build: 6365efeba253807.
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_memory_info_upload_hvv_memory_properties: Topology: Device heaps are split. Assuming small BAR situation. Using HOST_COHERENT only.
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device does not support VK_EXT_mutable_descriptor_type (or VALVE).
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
1110.159:00d0:00d4:fixme:vkd3d-proton:d3d12_device_caps_init_feature_options1: TotalLaneCount = 3584, may be inaccurate.
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Remapping VKD3D_SHADER_CACHE to: vkd3d-proton.cache.
1110.159:00d0:00d4:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
1110.165:00d0:0144:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
1110.165:00d0:0144:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
1110.165:00d0:0144:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.137 ms.
1110.165:00d0:0144:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Failed to map read-only cache: vkd3d-proton.cache.
1110.165:00d0:0144:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
00d4:fixme:imm:ImeSetActiveContext himc 000000000001005C, flag 0x1 stub!
00dc:fixme:imm:ImeSetActiveContext himc 0000000000010026, flag 0 stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"#32770"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092BFD8, 0000000001B2FAA0: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Static"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092E8A8, 0000000001B2F940: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Button"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092E928, 0000000001B2F940: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Static"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092E9A8, 0000000001B2F940: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Static"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092C058, 0000000001B2FAA0: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Button"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000092EA28, 0000000001B2FAA0: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Static"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 0000000000937E38, 0000000001B2FAA0: stub!
0124:fixme:oleacc:find_class_data unhandled window class: L"Button"
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
0124:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
0124:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0124:fixme:uiautomation:nc_provider_GetPatternProvider 0000000000925C20, 10002, 0000000001B2ECA0: stub
0124:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 0000000000925B90, 10002, 0000000001B2ECA0: stub
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 0000000000937EB8, 0000000001B2FAA0: stub!
0124:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0124:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0124:fixme:uiautomation:msaa_fragment_get_FragmentRoot 0000000000937F38, 0000000001B2FAA0: stub!
0124:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
0124:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
0124:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 0000000000925B90, 10002, 0000000001B2ECA0: stub
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0

**Comment by Blisto91** [comment]
Try with latest master if you can https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/6039056917
Though even then the game is known to crash on the current latest Nvidia drivers.

Also please attach logs as text files or links so they don't fill the whole page.

**Comment by kleinermob** [comment]
Many people also have the same issue with the 1080 Ti 
https://github.com/ValveSoftware/Proton/issues/7064#issuecomment-1703270854

same issue with latest master
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12507246/log.txt)

```
❯ ls /usr/share/vulkan/icd.d/
.rw-r--r-- 140 root 22 Aug 17:00  nvidia_icd.json
```

**Comment by Blisto91** [comment]
I'm not a dev so just taking a guess here from some poking around. 
[From what i can tell](https://vulkan.gpuinfo.org/displayreport.php?id=23471#extensions) the 1080 TI doesn't support the `VK_NV_compute_shader_derivatives` extension and it's `computeDerivativeGroupLinear` feature for some reason which means vkd3d-proton won't advertise shader model 6.6.

You could try to launch with `VKD3D_SHADER_MODEL=6_6` but i don't know if it would work even outside the Nvidia driver related crashes which are present at the moment.

**Comment by kleinermob** [comment]
Awesome! It actually starts up now.

**Comment by LrrrAc** [comment]
This fixed it for my 1070 as well!

**Comment by kleinermob** [comment]
![Bildschirmfoto_2023-09-03_22-59-20](https://github.com/HansKristian-Work/vkd3d-proton/assets/42699035/077e75da-545f-489c-b4a8-dc6c0c2234cf)
works fine now, 535.104.05-2 doesnt work, but 530.41.03-1 works fine.

**Comment by Blisto91** [comment]
Cool that's good to hear. I don't know if there is a technical reason that Extension isn't supported on pascal.
But seems like the game doesn't care too much so far.

**Comment by Hexality** [comment]
> Awesome! It actually starts up now with VKD3D_SHADER_MODEL=6_6

where do I set this, command line?

**Comment by Blisto91** [comment]
In your Steam library right click on the game and select Properties. The text field should be in the General tab.

Remember to end with `%command%` like so `VKD3D_SHADER_MODEL=6_6 %command%`

**Comment by Hexality** [comment]
> If using Steam then in your Steam library right click on the game and select Properties. The Launch Options text field should be in the General tab.
> 
> Remember to end with `%command%` like so `VKD3D_SHADER_MODEL=6_6 %command%`

does that work on the windows side of things on only Linux/BSD?

**Comment by Blisto91** [comment]
If you mean setting it via the games launch options in Steam by using `%command%` then no that is not a thing in Windows Steam.
But yes `VKD3D_SHADER_MODEL` works fine when set as a regular environment variable on Windows too.

**Comment by HansKristian-Work** [comment]
Considering this resolved. If Pascal does not expose all the requires SM 6.6 features, only way is to use the shader model hack override.

**Comment by DiegoSof2** [comment]
> This fixed it for my 1070 as well!

I also have a 1070 but my game crashes when I click on new game

**Comment by DiegoSof2** [comment]
> If using Steam then in your Steam library right click on the game and select Properties. The Launch Options text field should be in the General tab.
> 
> Remember to end with `%command%` like so `VKD3D_SHADER_MODEL=6_6 %command%`

Is it possible to use this type of parameter in lutris?

**Comment by Blisto91** [comment]
Yes.
Right click on game (or what ever launcher) in Lutris -> Configure -> System Options tab -> Click Add at "Environment Variables a the bottom -> Key is `VKD3D_SHADER_MODEL` and Value is `6_6`

**Comment by DiegoSof2** [comment]
> Yes. Right click on game (or what ever launcher is used) in Lutris -> Configure -> System Options tab -> Click Add in the "Environment Variables" section at the bottom -> Key is `VKD3D_SHADER_MODEL` and Value is `6_6`

It didn't work, on steam the parameter works but not on lutris

![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/105827698/b5ed650d-60c1-40be-8811-a5c2744ada6c)
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/105827698/ba6a4152-799c-4faf-9d8d-7b57b873d82f)

**Comment by Blisto91** [comment]
Sorry i don't use Lutris much.
What is your GPU and driver?

**Comment by DiegoSof2** [comment]
> Sorry i don't use Lutris much. What is your GPU and driver?
> 
> Edit: Make sure dxvk and vkd3d is turned on in the settings. Also instead of using lutris own runner it might be an idea to try wine-ge (lutris-GE-Proton)

In fact, I've tried everything drive 525, 530, 535, all versions of Proton, Kenel 6.5 and 6.1, I managed to get to the start menu with VKD3D_SHADER_MODEL on Steam but I can't get past that, the only thing I haven't tried is using a non-dkms drive because it breaks my hyprland GUI

**Comment by dumpsters** [comment]
Getting the same error on **windows** with a 5500XT, driver 23.9.1
Setting VKD3D_SHADER_MODEL it just logs this
[Starfield_dxgi.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12570091/Starfield_dxgi.log)

**Comment by mbriar** [comment]
There is no point to even try running this with vkd3d-proton on AMD windows, the AMD vulkan driver is missing extensions it requires, VK_NV_device_generated_commands specifically.

**Comment by PrincessAkira** [comment]
> There is no point to even try running this with vkd3d-proton on AMD windows, the AMD vulkan driver is missing extensions it requires, VK_NV_device_generated_commands specifically.

So thers no equivalent or a way to get around that at all? Does AMD need to implement smth?

**Comment by PrincessAkira** [comment]
Bet AMD wont add this to their Vulkan Driver on Windows then.
Was nice till hope was shattered

**Comment by Blisto91** [comment]
This should not need a override on Pascal anymore with latest vkd3d-proton master
See https://github.com/HansKristian-Work/vkd3d-proton/pull/1883 for more info

**Comment by K0bin** [comment]
@PrincessAkira @dumpsters 

AMDs Windows driver can't really run VKD3D-Proton anyway. And there isn't really any reason to do so either...
