### ISSUE TITLE
Jusant, text rendering issue

### ISSUE THREAD

**Issue by simifor** [HansKristian-Work/vkd3d-proton#1688]
Some game text has some weird lines in the middle
![Jusant   2023-09-05_14:03:11](https://github.com/HansKristian-Work/vkd3d-proton/assets/70454800/f834f955-04f0-4615-9d8a-a4ef2d4ffe9b)
Here is how it should look like https://youtu.be/eaZAHWZcYMM?feature=shared&t=813

### Software information
Jusant, all low and all maximum has no effect on the bug

### System information
- GPU:amd rx 6600
- Driver: mesa 23.1.6-4/ mesa-git 1cef1f02
- Wine version: 8, from using proton 8.0-3 and proton experimental bleeding edge
- VKD3D-Proton version: 2.9 /2.10 (from proton)

### Log files
[steam-2357010.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12528140/steam-2357010.log)

**Comment by mbriar** [comment]
This is actually a game bug, it happens on native windows d3d12 too, at least on amd.

**Comment by HansKristian-Work** [comment]
Thanks for verifying. Guess we can close this as not our bug.
