### ISSUE TITLE
Missing textures everywhere in starfield.

### ISSUE THREAD

**Issue by XxRiKxX** [HansKristian-Work/vkd3d-proton#1695]
I am using arch linux.
kernel - 6.5.1-1 -cachyso
mesa-version - 23.3 git
vkd3d - latest
wine-version - proton ge 8.14
I have a i5-9400f, rx570(4gb) and I have the vulkan-radeon and lib32 of it installed.
I have tried with every settings from low to ultra. the body of the characters dont show up. just the suit, floating eyeballs and hair. many terrain and object textures are missing too. this issue does not seem to be related to vram as I have seen the same problem with rx580 8gb and also some people are running it just fine with nvidia 1060 3gb. I dont know if this is related to vkd3d but still creating a issue here in case it is. Thanks.

**Comment by doitsujin** [comment]
Known issue on Polaris GPUs, probably not our bug.

**Comment by Blisto91** [comment]
Doing some searching i found it might a game issue as it seems like it can appear on Windows too. Could be that it bugs out easier on Linux.
https://www.reddit.com/r/Starfield/comments/166ylgc/starfield_random_missing_textures_smooth_playable/
https://www.reddit.com/r/Starfield/comments/169cmbp/starfield_missing_textures/

**Comment by XxRiKxX** [comment]
can I do anything to fix it? I have tried older mesa as well.

**Comment by Blisto91** [comment]
Don't know. My rdna3 card have only reproduced a issue that might or might not be related a couple of times and it wasn't nearly as bad. Also don't know what the exact trigger is if there is one.
Might have to see if a game update solves it.

**Comment by XxRiKxX** [comment]
there was a update on game. can anyone tell me if its fixed? I dont have it downloaded at the moment

**Comment by Blisto91** [comment]
I don't think anything is known besides what is written in the mesa issue and comments https://gitlab.freedesktop.org/mesa/mesa/-/issues/9784

**Comment by XxRiKxX** [comment]
after using ACO_DEBUG=noopt, the game works fine, but the shader compies everytime I launch the game and I have a ssd it takes more than 10 minutes every time
