### ISSUE TITLE
Starfield won't launch on Intel ARC GPUs

### ISSUE THREAD

**Issue by Mil-UwU** [HansKristian-Work/vkd3d-proton#1701]
Starfield will not launch on Intel ARC cards via vkd3d. The error is the usual graphics card does not meet the minimum specifications requirements that a lot of nvidia users were seeing. I have tried the shader model 6_6 env var with no change on both Windows 11 and Ubuntu 22.04.

The game *does* launch on the card natively on Windows, but performance is abysmal and plagued with crashing due to driver issues that are still unresolved.
The game *does not* launch on Windows via vkd3d, with the same minimum specifications error as on Linux.

The general Intel ARC usage strategy on Windows for A LOT of games is to just work around problematic drivers with DXVK and VKD3D so if this issue can be overcome it has the potential to make ARC Windows users happy too. Not saying its the same problem, or even that it would be any better if it worked, but the hope is there. I've been assured it *does* work on Nvidia cards on Windows.

Under Windows, I tried using a dxvk config to fake the GPU model via DXGI to both an AMD and Nvidia card. I have no idea if that affects VKD3D but I tried it and it changed nothing.

I don't know exactly what vulkan extensions are required, so perhaps someone can look at the log and it'll be as simple as driver sux unluck.

### Software information
Starfield (STEAM) Build ID: 12128396 (the recent patch).

### System information
- GPU: Intel ARC A770 16GB
- Driver: 
      Linux: Mesa 23.1.7 - kisak-mesa PPA
      Windows: Intel 4676 / 4824
- Wine version: PROTON 1694112709 experimental-8.0-20230907
- VKD3D-Proton version: 
      Linux: Proton included version 
      Windows: VKD3D v2.10 with DXVK v2.3 also.

Linux logs attached below, happy to provide anything further required from either OS.

[steam-1716740.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12611472/steam-1716740.log)
[vulkaninfo.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12611473/vulkaninfo.txt)
[glxinfo.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12611474/glxinfo.txt)

**Comment by mbriar** [comment]
It would need both https://gitlab.freedesktop.org/mesa/mesa/-/issues/5003 and https://gitlab.freedesktop.org/mesa/mesa/-/issues/6883 to be resolved to launch on Intel on linux. So yes, driver issue.

**Comment by Mil-UwU** [comment]
Running the vulkaninfo tool on Windows provides the output below, is this a case of the official Intel windows driver missing the same extension also?

[vulkaninfo-win.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12617211/vulkaninfo-win.txt)

**Comment by mbriar** [comment]
While the intel windows vulkan driver supports sparse resources, it doesn't support VK_NV_device_generated_commands, which is required by Starfield. This extension is only supported by nvidia and radv on linux.

**Comment by Blisto91** [comment]
Also lacking `VK_EXT_shader_image_atomic_int64` for shader model 6.6 from what I can tell from the log.

**Comment by HansKristian-Work** [comment]
Nothing we can do here.

**Comment by cheako** [comment]
The situation with this has changed.
The MM worked and I was able to configure things like keybindings and the settings keep.  Starting a game, however, crashes.  It looks like there is a segfault in `d3d12core.dll`

[steam-1716740.log](https://github.com/user-attachments/files/19869307/steam-1716740.log)
[1745413456_err.txt](https://github.com/user-attachments/files/19869336/1745413456_err.txt)

**Comment by cheako** [comment]
`Proton: 1745411970 experimental-bleeding-edge-9.0-188737-20250423-pa7ab8b-we919c8-dcb4461-vb8c415`

```text
line(5987): Unhandled exception: page fault on read access to 0x0000000000000139 in 64-bit code (0x006ffff779eb4d).
2:21 PM 
I'm guessing it's a deference of something that's just supposed to be used as the value???
2:21 PM 
6008 =>0 0x006ffff779eb4d in d3d12core (+0x1deb4d) (0x0000007d26f6b0)
```

See the full log in my last post.

**Comment by cheako** [comment]
Any comments on this?

**Comment by mbriar** [comment]
While the errors you're getting might have changed somewhat, the Intel linux driver is still missing extensions the game requires to run https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31384. Not much point in even trying until that changes.

**Comment by cheako** [comment]
The game has been patched, so all prior testing that would support this conclusion are now invalid...  For every time they release a patch, it's an obvious thing to do to test if prior conditions and requirements still hold.  I've tested with/without the extension and the results are the same, I've also tested git-main+dgc merged and the results are the same.  It's clear there is a pointer deference issue in your library, at a minimum you could track that down and we can see what happens if that deference works as it's supposed to.
