### ISSUE TITLE
Disney Speedstorm (1537830): minor stuttering during gameplay

### ISSUE THREAD

**Issue by ranplayer** [HansKristian-Work/vkd3d-proton#1716]
Disney Speedstorm has some minor stuttering during the races (I suppose related to shader compilation since they fade away eventually). Is VKD3D working with GPL ?

### Software information
Name: Disney Speedstorm (1537830)
Settings: Maxed out at 1080p

### System information
- GPU: RX 6700 XT
- Driver: Mesa 23.1.8
- Wine version: Proton 8.0-4 (RC)
- VKD3D-Proton version: from Proton's build

### Log files
- [steam-1537830.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/12764905/steam-1537830.tar.gz)

**Comment by mbriar** [comment]
Vkd3d-proton does support gpl for some edge cases already. Pipeline compilation in general already behaves almost the same between vulkan and d3d12, and vkd3d-proton will show shader stuttering in the same cases where it would also show on native windows, and there is nothing you can do about it.

**Comment by ranplayer** [comment]
I see... since I haven't got any more stuttering with D3D9-11 games using Mesa 23.1.X, I thought the same would apply for D3D12 as well. Thanks for the explanation.
