### ISSUE TITLE
hilariously patchy bald npc in starfield

### ISSUE THREAD

**Issue by bluedinosaur139** [HansKristian-Work/vkd3d-proton#1730]
Describe the bug:

this only seems to effect proton ge 8-16 and only in starfield ofc because its bethesda
sometimes quest npc are hiliariously patchy bald like they got into a fight with a weed whacker and lost.
other times i saw the marshall of the rangers turn pitch black on his face but only when close like conversation close, as soon as you move a few feet away the regular texture fades back in, and somewhere inbetween he looks like a burnt hotdog, this is just funny asf but if you can be bothered to fix that crappy game please do !!!!

Manjaro linux with 7800x3d asus b650 tuf gaming wifi 32 gb 6400 oc ram and a 6900 xt, with a 4 tb gen 4 nvme
2.it takes this god tier rig to get a stable 60 fps and some cities like akila are more like 40 lmao this is on ultra at 2k no upscaling or vrs or vsynch, VRR is ON!!!!!
i used proton up qt to get this ge 8-16 version then enabled it by default in steam compatibility
Starfield is the only game with this issue and is the main reason i use ge proton versions, keep up god's work bruddah!
main issue is just some textures failing to load on npc, there is also the odd green flash of light from reflections too but not sure if thats on amd or proton or bethesda lol

Expected behavior

Perfect frames with no texture load in issues, it does go away if i switch to proton experimental, once again its only this starfield, the worst optimized pc game in history with the issue, cant stress that enough

Platform:Manjaro linux, kde desktop, steam, PC
System: Manjaro x 86 - 64 bit
Version: ge proton 8-16
How did you install ProtonUp-Qt?: using manjaro app store with aur support enabled, v 2.8.2

Additional context

it made me laugh hard as hell both times and i thanked god for a hilarious bug, but nevertheless i thought i would let you know

Terminal command : flatpak run net.davidotek.pupgui2

and the OUTPUT:
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitanFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)

**Comment by HansKristian-Work** [comment]
There's a bunch of other issues regarding Starfield already. This issue description is unhinged enough that I'll just close it as a duplicate.

**Comment by bluedinosaur139** [comment]
hey, unhinged? do you have to be the example of why linux users always have this attitude?
