### ISSUE TITLE
Starfield hangs again on NV 535.43.11 Vulkan dev driver and bleeding edge vkd3d-proton

### ISSUE THREAD

**Issue by giantplaceholder** [HansKristian-Work/vkd3d-proton#1731]
Starfield, previously kind of fixed with the release of 535.43.10 Vulkan dev driver, is broken again. 

This time I've installed 535.43.11 Vulkan dev released yesterday, in order to check whether DGCC improvements mentioned in the NVIDIA's release log had any effect on the performance. Instead, the game hangs again, just like it did before 535.43.10 release. The only difference is that this time I can actually send KILL to the process, without resorting to soft-resetting the whole system.

The behavior is consistent: I've tried running the same Wine version and the same vkd3d-proton version on 535.43.10, and had no issues with the game crashing.

With that said, there's at least two reports from Pascal and Turing users whom are stating that game runs fine for them on 535.43.11 (see https://forums.developer.nvidia.com/t/starfield-does-not-launch-on-most-nvidia-gpus-on-linux-and-not-at-all-on-pascal-gpus/265483/115 and below). Other users, in turn, confirm that 535.43.11 broke things for them.

Can it be clarified whether this is an issue on NV or vkd3d-proton's side?

### Software information
Starfield v1.7.33

### System information
- Kernel: 6.5.5-1
- GPU: RTX 3070 Ti
- Driver: 535.43.11
- Wine version:  8.17-Staging-Tkg (Fsync enabled), Proton 8.0-4 and GE-Proton 8.16
- VKD3D-Proton version: bleeding edge (https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/6433361481)

### Log files
[starfield_817-tkg_vkd3d_be.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12836898/starfield_817-tkg_vkd3d_be.txt)

Additional logs from another NV user running RTX 3070: https://forums.developer.nvidia.com/t/starfield-does-not-launch-on-most-nvidia-gpus-on-linux-and-not-at-all-on-pascal-gpus/265483/117

**Comment by ODeadlock** [comment]
Starfield no longer crashes on an RTX 2080 Ti after the release of the Vulkan beta driver 535.43.10, however performance was incredibly poor and virtually unchanged from version 525. With the release of 535.43.11, the games framerate has increased drastically and is smooth and stutter free. All testing was performed on the nv-dgcc-enable branch. However, this behavior appears vary between GPU architectures. Some users with Pascal cards report that they are still able to launch the game on 535.43.11 but the same cannot be said for Ampere.

Additionally, there appears to be artifacting with certain objects under certain conditions that was not present during 525. For example, the large rocks on the horizon as well as the metallic gas container right side rapidly flicker in and out when moving the camera around, making it tricky to capture a screenshot of:
![FastScreenshot-10-07-01-2023](https://github.com/HansKristian-Work/vkd3d-proton/assets/16617624/7869bdca-23f5-43f3-8229-228eaa8fee73)

### Software information
Starfield v1.7.33

### System information
Kernel: 6.5.5
GPU: RTX 2080 Ti
Driver: 535.43.11
Wine version: GE-Proton 8.16
VKD3D-Proton version: https://github.com/HansKristian-Work/vkd3d-proton/commit/01f62c8

###  Log files
[steam-1716740.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12838439/steam-1716740.log)
[StarfieldVKD3D.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12838441/StarfieldVKD3D.log)

**Comment by HansKristian-Work** [comment]
I also get instant GPU hang on 535.43.11 on 3070. I've reported this to NV.

**Comment by pppbb** [comment]
The same on 4080.

**Comment by pppbb** [comment]
> The same on 4080.

In my case game hangs just after pressing the load key.

Anybody on 40 series ?

**Comment by extract** [comment]
I got instant GPU hang and also following Xid crash once I pressed continue in 535.43.11 with a 3080.

`NVRM: Xid (PCI:0000:09:00): 109, pid=207127, name=Starfield.exe, Ch 000000ee, errorString CTX SWITCH TIMEOUT, Info 0x2c073`

**Comment by HansKristian-Work** [comment]
.15 driver is out so this is outdated.
