### ISSUE TITLE
Talos Principle 2 Demo (UE5): random glitchy frames when picking up items

### ISSUE THREAD

**Issue by adolfintel** [HansKristian-Work/vkd3d-proton#1732]
I'm testing the Talos 2 demo that just came out and while the game runs well and it's stable, I've noticed some random glitchy frames when picking up objects like the jammer shown here.

I'd love to provide a renderdoc trace of this issue but it's so random and it only lasts a frame, I don't know how to catch the exact moment.

I tried messing around with mesa settings and vkd3d settings but nothing seems to make a difference.

Here's a video of the problem: [video](https://downloads.fdossena.com/issues/talos2glitch.mkv)

And a screenshot:
![2023-10-07 09-01-30](https://github.com/HansKristian-Work/vkd3d-proton/assets/16307689/f1a93005-98b7-4695-a155-fcbae00ff463)

### Software information
Talos Principle 2 Demo from Steam: https://store.steampowered.com/app/835960/The_Talos_Principle_2/

### System information
- GPU: AMD 6900XT
- Driver: Current Mesa master
- Wine version: Proton experimental, current master
- VKD3D-Proton version: Current master

**Comment by mbriar** [comment]
Should probably be tested on windows if it's not just a game bug.

**Comment by adolfintel** [comment]
It doesn't happen on windows with the latest AMD driver. Sorry I forgot to mention it

**Comment by adolfintel** [comment]
Quick update: turning Global Illumination down to medium gets rid of it. It disables nanite so it's probably related to that.

**Comment by RodoMa92** [comment]
Works fine on my Deck, although with not really good framerate. It fails on my RX580, claiming that it doesn't support SM6. Is this a MESA limitation, GPU limitation or what?

**Comment by adolfintel** [comment]
@RodoMa92 I've seen people having this issue on windows too so it could just be a game bug. What version of mesa are you using?

**Comment by RodoMa92** [comment]
Heck, that was quick!

Yeah, trying mesa-git now, I'm on arch with 23.2 installed. This claims support up until 6.7, but it's not clear on what hardware are supported all of the features itself.

**Comment by RodoMa92** [comment]
Nope, no luck. Same problem.

**Comment by RodoMa92** [comment]
Yea, forgot to update. Solved the issue by actually forcing RADV instead of AMDVLK that as usual was ignoring my override. All good now.

**Comment by adolfintel** [comment]
@RodoMa92 ah, that explains it, AMDVLK isn't quite ready for prime time yet. You're going to have the random glitchy frames though with RADV.

I haven't been able to find a workaround yet, hopefully one of the vkd3d devs can shed some light on this issue.

**Comment by HansKristian-Work** [comment]
Does not reproduce for me on RX 6800. Can you try https://github.com/HansKristian-Work/vkd3d-proton/pull/1746 with VKD3D_CONFIG=disable_uav_compression ?

**Comment by adolfintel** [comment]
@HansKristian-Work 
Just tested it with the latest mesa master and the latest vkd3d master since that PR was merged and it doesn't seem to work for me, the glitches are still there.

I also don't see the VK_EXT_image_compression_controls in vulkaninfo so that option is probably not doing anything, do I need to enable it somehow?

**Comment by mbriar** [comment]
It's not merged yet: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25681

**Comment by adolfintel** [comment]
I thought it was merged already :( oh well

I built that PR and the current vkd3d master but the glitch is 100% still happening even with disable_uav_compression,disable_depth_compression,disable_color_compression. I can see that the game is using the right DLL and the extension is visible in vulkaninfo. Am I missing something?

[Here's a video](https://downloads.fdossena.com/issues/talos2_glitch2.mkv) of the worst spot I could find, in the south area, I'm pretty sure it's somehow related to the outline shader. I can provide a save file if you don't want to play through the whole demo.

Also, as someone has pointed out in a mesa issue, dmesg is full of page faults from amdgpu when running Talos 2, it could be releated.

@HansKristian-Work can you test it again making sure that the game is actually set to ultra? It has a nasty habit of changing settings by itself or not applying them until it's restarted
