### ISSUE TITLE
d3d12 bricked on nvidia driver version 535.113.01

### ISSUE THREAD

**Issue by flafin** [HansKristian-Work/vkd3d-proton#1734]
i installed the vkd3d-proton but games don't work with it, i got nvidia geforce gtx 1650 it supports directx12 but all games are running only d3d11, when i start any game with D3D12 it just crashes on the start and its with every directx 12 games
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: Oregon-Win64-Shipping.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3eb0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 15.0.7, 256 bits)
info:  NVIDIA GeForce GTX 1650:
info:    Driver : NVIDIA 535.113.1
info:    Memory Heap[0]: 
info:      Size: 4096 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 5862 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  Intel(R) UHD Graphics (CML GT2):
info:    Driver : Intel open-source Mesa driver 23.0.4
info:    Memory Heap[0]: 
info:      Size: 5862 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
00dc:fixme:system:QueryDisplayConfig (00000002 0000000000B9E358 0000000001AA7D10 0000000000B9E35C 0000000001AA7D60 0000000000000000): semi-stub
00dc:fixme:system:QueryDisplayConfig (00000002 0000000000B9E358 0000000001AA7D10 0000000000B9E35C 0000000001AA7D60 0000000000000000): semi-stub
info:  DXGI: Hiding actual GPU, reporting vendor ID 0x1002, device ID 73df
23244.012:00d8:00dc:info:vkd3d-proton:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.10.0.
23244.012:00d8:00dc:info:vkd3d-proton:vkd3d_instance_init: vkd3d-proton - build: 88e4f300cc0b5b6.
23244.024:00d8:00dc:fixme:vkd3d-proton:d3d12_find_physical_device: Could not find Vulkan physical device for DXGI adapter.
23244.056:00d8:00dc:info:vkd3d-proton:vkd3d_memory_info_upload_hvv_memory_properties: Topology: UMA-like topology. Using DEVICE_LOCAL | HOST_COHERENT for UPLOAD.
23244.056:00d8:00dc:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Enabling single descriptor set path for MUTABLE.
23244.056:00d8:00dc:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device supports VK_EXT_mutable_descriptor_type.
23244.056:00d8:00dc:info:vkd3d-proton:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
23244.056:00d8:00dc:fixme:vkd3d-proton:d3d12_device_caps_init_feature_options1: TotalLaneCount = 1024, may be inaccurate.
23244.056:00d8:00dc:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Remapping VKD3D_SHADER_CACHE to: vkd3d-proton.cache.
23244.056:00d8:00dc:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.103 ms.
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.122 ms.
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.024 ms.
23244.060:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
00dc:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
00dc:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01d0:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000000030ADFE10
00dc:fixme:system:QueryDisplayConfig (00000002 0000000000B9B2EC 0000000001ADEFD0 0000000000B9B350 0000000001AEC530 0000000000000000): semi-stub
00dc:fixme:win:RegisterTouchWindow hwnd 0000000000010078, flags 0 stub!
00dc:fixme:imm:ImmReleaseContext (0000000000010078, 0000000000000000): stub
0088:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
0088:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
23244.181:00d8:00dc:info:vkd3d-proton:dxgi_vk_swap_chain_init: Creating swapchain (1920 x 1080), BufferCount = 3.
23244.181:00d8:00dc:info:vkd3d-proton:dxgi_vk_swap_chain_init_sync_objects: Ensure maximum latency of 3 frames with KHR_present_wait.
23244.181:00d8:00dc:info:vkd3d-proton:dxgi_vk_swap_chain_init_waiter_thread: Enabling present wait path for frame latency.
warn:  DXGI: MakeWindowAssociation: Ignoring flags
23244.274:00d8:01bc:info:vkd3d-proton:dxgi_vk_swap_chain_recreate_swapchain_in_present_task: Got 3 swapchain images.
23244.311:00d8:0130:fixme:vkd3d-proton:rs_desc_from_d3d12: Ignoring MultisampleEnable 0x1.
23244.316:00d8:01b4:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  439
  Current serial number in output stream:  449

**Comment by Blisto91** [comment]
Do you mean that only that driver version fails?

What happens if you force only the Nvidia driver excluding Intel `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`

**Comment by flafin** [comment]
when i run the game like wine Oregon.exe -d3d12 or any other game that uses -d3d12 it wont launch and auto exit thats about it, if i dont install vkd3d-proton i get the error ""DX12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument."
no change after adding "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json"

**Comment by flafin** [comment]
adding VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json worked :) :) thanx i am gona kill zominbes!!!
