### ISSUE TITLE
Starfield: heavy LOD shimmering \ pop-in (NV 535.43.13, vkd3d-proton with nv-dgcc-enabled patches)

### ISSUE THREAD

**Issue by giantplaceholder** [HansKristian-Work/vkd3d-proton#1736]
Some LOD's are shimmering \ popping in and out when running Starfield with NV 535.43.13 driver and vkd3d with DGCC-related patches. No such shimmering is observed when using vkd3d 2.10 release -- but that nullifies performance gain seen with vkd3d with aforementioned patches.

The issue appears once changes from nv-dgcc-enable branch are applied to the master branch -- or if I'm using a Github Actions build straight out of that branch.

This issue can be observed pretty much everywhere, but is most easily noticed within New Atlantis location.

### Software information
Starfield v.1.7.36.0

### System information
- GPU: RTX 3070 Ti
- Driver: 535.43.13
- Wine version: Proton Experimental (bleeding edge), Wine 8.17-Staging-Tkg
- VKD3D-Proton version: bleeding edge + patches applied from [nv-dgcc-enable](https://github.com/HansKristian-Work/vkd3d-proton/tree/nv-dgcc-enable) branch and [dgc-preprocess-hoist](https://github.com/HansKristian-Work/vkd3d-proton/tree/dgc-preprocess-hoist) branch. 

### Log files
[game.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12880340/game.log)

### Video capture of the issue

https://github.com/HansKristian-Work/vkd3d-proton/assets/4792863/971d8529-536d-430b-9ec2-c645c55268a7

**Comment by HansKristian-Work** [comment]
To be clear, with .13 and no dgcc, the flicker is not there?

**Comment by runar-work** [comment]
Looks like this was introduced in .11, then. I could reproduce the same glitch in .13 with an RTX 4070 and a DGCC build, but I couldn't reproduce it when I tested with 535.43.10.

**Comment by runar-work** [comment]
Yeah, I double-checked that it was the same build as with the glitches in .13.

**Comment by runar-work** [comment]
Turing, yeah. There's an NV workaround for the crashes in .11 and I can confirm that the flickering happens there too in New Atlantis. 

I didn't have any particular trouble in .10, except for a briefly flickering single tree that I couldn't reproduce again.

Other issues didn't seem to be related to DGCC on NV and I could also reproduce on the deck, like trees appearing in the sky (partly visible in the video posted above) which simply stopped happening at some point despite reloading old saves where it previously appeared. Another general glitch was a texture glitch which happens only in certain spots/angles (shown below).

https://github.com/HansKristian-Work/vkd3d-proton/assets/78347897/9a91d051-fbde-4482-9afc-5d411926cd83

**Comment by runar-work** [comment]
Ah, my mistake then (I mixed up Quadro and RTX). It is an RTX 4070.
