### ISSUE TITLE
UE5: RX 5700XT GPU crash when playing UE5 (DX12) games.

### ISSUE THREAD

**Issue by MekaDragon** [HansKristian-Work/vkd3d-proton#1738]
I'm experiencing hard GPU crashes while playing UE5 games via VKD3D. The computer freezes, screen goes black and then returns with an artifacted image. PC is completely frozen and I have to hard reboot it.

I've been researching as far as I can with games and demos of my Steam library and this is what I got:

UE5 games:
The Talos Principle 2 (DX12) - Crashes.
Robocop: Rogue City (DX12) - Crashes.
The Thaumaturge (DX12) - Crashes.
Jusant (DX12) - Crashes.
IfSunSets (DX12) - Crashes.
Luto (DX12) - Not crashing
This Bed We Made (DX11) - Not crashing.
Demonologist (DX12) - Crashes.
Demonologist (DX11) - Not crashing.

UE4 games:
ABZU (DX11) - Not crashing.
Gord (DX12) - Not crashing.
Luna Abyss (DX11) - Not crashing.

Non UE5 games:
Hitman 2 (both DX11 and DX12) - Not crashing.
Civilization VI (DX11) - Not crashing.
Resident Evil 4 + DLC (DX12) - Not crashing.

### System information
- GPU: AMD RX 5700XT
- Driver: mesa-vulkan-drivers.x86_64 23.3.0-git.20231012.ed2cac0.fc38
- Wine version: I've tried several versions of Proton (7.0-6, 8.0-4, GE8-16, experimental and hotfix).
- VKD3D-Proton version: 2.10 (and the versions that are shipped with previous Proton versions I've tried with).

### Log files
I attached into the issue the Proton log and a journalctl log from yesterday experiencing the same crash.
[steam-2581470.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12893861/steam-2581470.log)
[journal log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/12893862/journal.log.txt)
![PXL_20231012_205724259](https://github.com/HansKristian-Work/vkd3d-proton/assets/60288442/cfddadbd-cb9a-4874-ab89-f5e4c5e42692)

**Comment by runar-work** [comment]
Did the hangs seem to happen randomly or is there some specific way to reproduce? 

In the Talos demo I had consistent hangs with the RX 5700 XT in the puzzle "versatile contraption" when repeatedly putting down and picking up the jammer, on Mesa main and Proton Experimental. I have some UMR dumps from this which point to a specific shader, so I can check out some of the other games and see if it's the same issue.

**Comment by MekaDragon** [comment]
@runar-work 

These are sometimes random, but there are some places that definitely triggers this constantly. "Versatile Contraption" puzzle was a crash-fest for me as well, so it looks like it's the same issue.

Try downloading Robocop: Rogue City demo and when you reach that room, just shoot randomly and zoom in and zoom out for a while and it should trigger.

With The Thaumaturge as well when you are in the town and you swap between XeSS, FSR2 and TAS for a while, it would happen again.

But yes, it's random as well, you can keep playing one of those games and almost 100% of the times, it crashes within 15 minutes or less.

**Comment by adolfintel** [comment]
@runar-work Talos 2 has those glitches almost every time you're near an item if you look closely, I think it has to do with that outline thing it shows around objects and how it interacts with the new lighting system. It doesn't happen on windows though so it should be fixable.

**Comment by runar-work** [comment]
I've reproduced hangs in Robocop and Thaumaturge so far. I got the same UMR dumps from the GPU timeouts in the Robocop demo as I got in the Talos 2 demo, so it's definitely the same hang in my case.

The hangs in Thaumaturge are similar, but not identical. Sometimes the hangs happen during gameplay, other times during loading screens, so there might be different cases. Robocop had two slightly different variants of UMR dumps, at least.

I didn't see any hangs in the IfSunSets demo after about half an hour, though it could've been that I didn't move into the problematic areas in that time. I did get some random graphical glitches there after about 15-20 minutes. Apart from this, I haven't seen any graphical glitches in the other games so far.

![20231016165004_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/78347897/82a107dc-59be-4269-ad0d-57d0da41a1a9)

I've gathered logs and dumps from multiple hangs in each of the three games here:
[robocop_thaumaturge_talos2_demos_umr_dumps.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/12919011/robocop_thaumaturge_talos2_demos_umr_dumps.zip)

**Comment by runar-work** [comment]
Running with `RADV_DEBUG=nodcc` fixes the hangs for me where I would otherwise get hangs reliably in Talos 2 (with the jammer in versatile contraption) and Thaumaturge (in the second fight in the village).

**Comment by MekaDragon** [comment]
Oh! I have to try it but I'm in a work trip right now. I will return tomorrow so I can try it as well.

I've looked at the documentation to know what does that mean.
nodcc: disable Delta Color Compression (DCC) on images.

How can this affect gaming?

Thanks a lot again for your help, @runar-work!

**Comment by mbriar** [comment]
> How can this affect gaming?

Disabling DCC will reduce GPU-bound performance.

**Comment by MekaDragon** [comment]
So I've tried launching some UE5 over DX12 games with RADV_DEBUG=nodcc %command% launch option and... so far so good! It looks like DCC is the culprit. And I don't feel that performance is degraded as far as I can see.

I'm going to test even more, and will play The Talos Principle 2 with this workaround. Thanks a lot @runar-work.

@HansKristian-Work maybe with this workaround and logs you can detect the source of the problem really fast.

**Comment by HansKristian-Work** [comment]
This should be fixed with the Mesa revert that fixed Talos Principle 2 demo.
