### ISSUE TITLE
Scribblenauts Unlimited crash on startup

### ISSUE THREAD

**Issue by zorbathut** [HansKristian-Work/vkd3d-proton#1740]
Scribblenauts Unlimited crashes before displaying a window - the classic "hit play, Steam says it's playing, Steam changes its mind" issue.

While this does happen on one computer, it doesn't happen on another I have. Both computers are running up-to-date Manjaro; the biggest difference between the two is that the working one has an NVidia card and the broken one has an AMD card.

It looks like the main problem is this repeated spam of shader compilation errors:

```
527.206:0188:018c:fixme:d3dcompiler:D3DCompile2 Ignoring flags 0x101.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Shader log:
527.206:0188:018c:err:d3dcompiler:D3DCompile2     <anonymous>:22:34: E5000: syntax error, unexpected KW_SAMPLER_STATE
527.206:0188:018c:err:d3dcompiler:D3DCompile2 
527.206:0188:018c:fixme:d3dcompiler:D3DCompile2 Ignoring flags 0x101.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Shader log:
527.206:0188:018c:err:d3dcompiler:D3DCompile2     <anonymous>:81:1: E5000: syntax error, unexpected KW_TECHNIQUE
527.206:0188:018c:err:d3dcompiler:D3DCompile2 
527.206:0188:018c:fixme:d3dcompiler:D3DCompile2 Ignoring flags 0x101.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Failed to compile shader, vkd3d result -4.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 Shader log:
527.206:0188:018c:err:d3dcompiler:D3DCompile2     <anonymous>:46:8: E5005: Function "tex2Dlod" is not defined.
527.206:0188:018c:err:d3dcompiler:D3DCompile2 
```

There's three separate errors, each of which show up multiple times; I've included one copy of each. Each one does have that `fixme: ignoring flags` prefix.

I'm not sure how to troubleshoot this further; I'm happy to test stuff or even rig up custom builds, please let me know what I can do to assist.

### Software information
Scribblenauts Unlimited - https://store.steampowered.com/app/218680/Scribblenauts_Unlimited/

### System information
- GPU: AMD Radeon RX 6600
- Driver: radv 23.1.9
- Wine version: 
- VKD3D-Proton version: Tried with 7.0, 8.0, and Experimental; 7.0 displays different errors but I suspect it's just a different in output

### Log files

[steam-218680-7.0.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12907879/steam-218680-7.0.log)
[steam-218680-8.0.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12907880/steam-218680-8.0.log)
[steam-218680-experimental.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12907881/steam-218680-experimental.log)

**Comment by mbriar** [comment]
D3DCompile2 is for the HLSL to DXBC compilation step, and that's not handled by vkd3d-proton. You should report that to wine instead. In the meantime, it'll probably work if you install native d3dcompiler_47 with winetricks.

**Comment by zorbathut** [comment]
Oops! Sorry for the misfiled bug, I'll go send that off to the right people and give d3dcompiler_47 a try :) Thank you!

**Comment by zorbathut** [comment]
Updates for anyone who sees this in the future:

* d3dcompiler_47 works great, I installed it via protontricks to make my life a little easier.
* The Wine bug report guide kinda scared me off of reporting since I'm running it through Proton.
* https://github.com/ValveSoftware/Proton/issues/378 fix reported here, though!

(Also dropped a note on protondb, though it's not public yet.)

If you're reading this, I hope this solves https://xkcd.com/979/ for you :)
