### ISSUE TITLE
Starfield: LODs, textures and models are not loading (nv-dgcc-enable branch, NV 545.23.06 beta)

### ISSUE THREAD

**Issue by giantplaceholder** [HansKristian-Work/vkd3d-proton#1742]
Game is outright broken with most of the objects, models, LODs and textures (except ground LOD) failing to load.

This behavior is exclusive to 545.23.06 beta driver released on Oct 17th.

I've tested two vkd3d builds, both build around 8AM CET Oct 18th:
 
1) straight out of the master, no changes whatsoever
2) custom, with nv-dgcc-enabled branch merged with master

On 545.23.06 with regular build game renders the picture properly (and stutters as much as on 535.43.10), and with custom build it does not. 

On 535.43.13 game renders the picture correctly with both vkd3d builds (sans the issue described in https://github.com/HansKristian-Work/vkd3d-proton/issues/1736), with frame times being much more consistent on a custom build than on the master.

On 545.23.06 game also crashes a lot (trace log is captured from such a run). 

The video capture also ends with a GPU hang, mid-animation. Had to terminate the game manually.

### Software information
Starfield v1.7.36.0

### System information
- GPU: RTX 3070 Ti
- Driver: 545.23.06 
- Wine version: Proton-experimental (bleeding edge), Wine-8.17-Staging
- VKD3D-Proton version: bleeding-edge (master with nv-dgcc-enable branch merged onto it)

### Log files
[game.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12995177/game.log)
[game.2.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12995637/game.2.log)
[trace.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12995208/trace.log)

### Video capture

This clip was captured within the New Atlantis location a few meters away from Constellation Lodge. Nothing loaded except the ground LOD: no models of NPCs, no models of the environment (like benches, trees, etc), no textures, no nothing. Collisions are still there, though.

https://github.com/HansKristian-Work/vkd3d-proton/assets/4792863/cb61f64f-9e9b-4622-9ffd-2333ae16c2af

**Comment by runar-work** [comment]
With a DGCC build, RTX 4070 and 545.23.06 I also get the same graphical issues and frequent Xid 31s (faulting at 0x0_00000000 every time). Breadcrumbs yielded different results each time, so it seems random where it hangs. Enabling descriptor QA checks didn't turn up anything, though it did work around the problem (both hangs and glitches).

I did get some objects far in the distance and scan silhouettes, though they get cut off when overlapping terrain further away, so maybe some kind of depth test issue?
![20231018154752_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/78347897/2dca6737-8830-4b84-95c5-926211f86477)
