### ISSUE TITLE
Teardown Experimental branch (with DX12 enabled) hangs GPU

### ISSUE THREAD

**Issue by f1nniboy** [HansKristian-Work/vkd3d-proton#1752]
### Software information
Teardown, experimental branch. DX12 enabled in the settings

### Other information
The main menu & in-game editor work fine, until you try to load into a map. I have tried all render settings, but they all hang my GPU:
```
GpuWatchdog[6159]: segfault at 0 ip 00007fee2a992b86 sp 00007fee139503a0 error 6 in libcef.so[7fee264ef000+7770000] likely on CPU 14 (core 28, socket 0)
...
[drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, but soft recovered`
```

### System information
- GPU: RX 7900 XT
- Driver: Mesa 23.2.1
- Wine version: Proton Experimental, Proton-GE 8-21
- VKD3D-Proton version: 2.10.0

### Log files
[steam-1167630.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13189322/steam-1167630.log)
[vkd3d-debug.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/13189324/vkd3d-debug.txt)

**Comment by runar-work** [comment]
Also had the same problem with RTX 4070 and 535.43.15, so it happens on Nvidia too. I got some breadcrumbs from that Xid 109 and then reproduced the hang with an RX 7600 to get a UMR dump as well. Descriptor QA checks didn't turn up anything.

[UMR_logs.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/13204039/UMR_logs.zip)

**Comment by pixelcluster** [comment]
As a temporary workaround, it seems like the game works when you set SteamDeck=1 (i.e. putting `SteamDeck=1 %command%` in the launch arguments field, or simply playing on Deck).
