### ISSUE TITLE
Is it possible to disable EXTENSIONS on Windows?

### ISSUE THREAD

**Issue by izyspania** [HansKristian-Work/vkd3d-proton#1759]
I want to use VKD3D_DISABLE_EXTENSIONS=VK_EXT_mesh_shader on windows10/11 , is it possible to do it? If yes , how?

**Comment by izyspania** [comment]
So i should just add VKD3D_DISABLE_EXTENSIONS=VK_EXT_mesh_shader there?
 In Alan Wake 2 textures wont load on a Vega GPU: 
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/93366907/f30e84d8-13f7-4fc1-a640-60fa6fb4de56)

**Comment by K0bin** [comment]
Vega doesn't support mesh shaders anyway. So VKD3D_DISABLE_EXTENSIONS=VK_EXT_mesh_shader will do nothing.

**Comment by HansKristian-Work** [comment]
Why are you using vkd3d-proton on Windows exactly? Vega is also below min-spec for the game anyways.

**Comment by izyspania** [comment]
Yes , but it works with them disabled but it seems that it doesnt want to disable them on Vega GPUs, i saw a topic here that disabling them fixes the textures: https://github.com/HansKristian-Work/vkd3d-proton/issues/1754

**Comment by izyspania** [comment]
So what can be the problem with missing textures on Windows then? Using DX12 seems to work , but very bad ofc using vkd3d also works but with broken textures on Vega GPUs and seems to work just fine on NVIDIA 10 series.

**Comment by mbriar** [comment]
> So what can be the problem with missing textures on Windows then

AMD's vulkan driver being broken, as usual. Only few games work correctly with vkd3d-proton on the AMD windows vulkan driver.

**Comment by izyspania** [comment]
> > So what can be the problem with missing textures on Windows then
> 
> AMD's vulkan driver being broken, as usual. Only few games work correctly with vkd3d-proton on the AMD windows vulkan driver.

Yeah , it makes sense now.

**Comment by izyspania** [comment]
Some logs from testing it with different AMD GPUs.

info:  Game: AlanWake2.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7fff2fa0d510
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 6650 XT:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 16054 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[1]: 
info:      Size: 8176 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[12]: Property Flags = 0xc1
info:      Memory Type[14]: Property Flags = 0xc7
info:  AMD Radeon RX 6650 XT:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 16054 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[1]: 
info:      Size: 8176 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[12]: Property Flags = 0xc1
info:      Memory Type[14]: Property Flags = 0xc7
info:  AMD Radeon RX 6650 XT:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 16054 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[1]: 
info:      Size: 8176 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[12]: Property Flags = 0xc1
info:      Memory Type[14]: Property Flags = 0xc7
warn:  DXGI: MakeWindowAssociation: Ignoring flags
err:   wsi: parseColorimetryInfo: Failed to get parse edid.
err:   DXGI: Failed to parse display metadata + colorimetry info, using blank.
info:  Setting display mode: 1920x1080@165
info:  Setting display mode: 1920x1080@165
info:  Setting display mode: 1920x1080@165
info:  Setting display mode: 1920x1080@165
warn:  CreateDXGIFactory2: Ignoring flags
info:  AMD Radeon RX 6650 XT:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 16054 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe

**Comment by K0bin** [comment]
- Those logs contain nothing out of the ordinary.
- vkd3d-Proton does not support Windows.
- vkd3d-Proton does not support the AMD Windows driver.
- Alan Wake 2 is known to not work on Windows with vkd3d-Proton because of shared fences.

**Comment by izyspania** [comment]
Seems to work with Adrenalin 23.9.1 driver.

**Comment by RareMv** [comment]
OP, given the game seems to reach even 60 fps on 5700 XT on Linux, as opposed to Window's ~30, you'd be better of trying it on Linux.

Polaris GCN4 seems to be absolutely DOA on this game, but Vega reaches ~17 fps on 1080p Low, FSR2 Quality? You'd probably reach 30 on Linux, maybe with a more agresive upscale. You should give it a shot.

**Comment by izyspania** [comment]
Thanks

> OP, given the game seems to reach even 60 fps on 5700 XT on Linux, as opposed to Window's ~30, you'd be better of trying it on Linux.
> 
> Polaris GCN4 seems to be absolutely DOA on this game, but Vega reaches ~17 fps on 1080p Low, FSR2 Quality? You'd probably reach 30 on Linux, maybe with a more agresive upscale. You should give it a shot.
> 
> VKD3D doesn't really work on AMD GPUs on Windows, as opposed to Nvidia, for some reason.

Thanks
