### ISSUE TITLE
Assassin's Creed Valhalla - Application is attempting to use more elements in a typed buffer than supported by device

### ISSUE THREAD

**Issue by IvanCharcos** [HansKristian-Work/vkd3d-proton#1783]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
Lutris 0.5.13
DXVK 2.3
VKD3D 2.10

### System information
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Arc(tm) A770 Graphics (DG2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 24.0~git2311170600.7f6d3b~oibaf~j (git-7f6d3b8 2023-11-17 jammy-oi
OpenGL Core:     4.6 (Core Profile) Mesa 24.0~git2311170600.7f6d3b~oibaf~j (git-7f6d3b8 2023-11-17 jammy-oibaf-ppa)
OpenGL ES:       OpenGL ES 3.2 Mesa 24.0~git2311170600.7f6d3b~oibaf~j (git-7f6d3b8 2023-11-17 jammy-oibaf-ppa)
Vulkan Version:  1.3.204
Vulkan Drivers:  Intel(R) Arc(tm) A770 Graphics (DG2) (1.3.267)

### Log files
Please attach Proton or Wine logs as a text file:
[game.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13398866/game.log)

**Comment by HansKristian-Work** [comment]
> 395185.630:0380:0384:fixme:vkd3d-proton:vkd3d_buffer_view_get_aligned_view: Application is attempting to use more elements in a typed buffer (268435456) than supported by device (134217728).

Nothing we can do about that. Most likely it is caused by lack of descriptor buffers, causing us to have to allocate larger views.

**Comment by shelterx** [comment]
@HansKristian-Work Could this cause degraded performance? I'm not sure what this game is doing (lot's of shader compilation?) but I'd say there is a ~20-30FPS loss in Linux for some reason, with Nvidia, tried two different cards, the numbers (loss) were the same.

**Comment by mbriar** [comment]
@shelterx nothing in this issue affects nvidia or AMD in any way, and lots of shader compilation also wouldn't cause lower average fps.

**Comment by shelterx** [comment]
@mbriar 
Ok, its something else then. Different kernels or proton/vkd3d versions doesn’t make any difference tho’. Fastsync (ntsync) helped slightly but not much. Thanks for replying.

**Comment by IvanCharcos** [comment]
Closing this since the application now opens
