### ISSUE TITLE
VKD3D Proton works in WINE ?

### ISSUE THREAD

**Issue by Augusto7743** [HansKristian-Work/vkd3d-proton#1784]
Hello.
Thanks for reading my topic.
VKD3D Proton works in WINE without any issues or is only for Steam Proton ?

Have an nice week.

**Comment by Blisto91** [comment]
Hi again Augusto 👋 

vkd3d-proton works fine in regular Wine provided you also have dxvk installed in there as it relies on it's `dxgi.dll`.

**Comment by Fabxx** [comment]
Yes it works under wine. You can get it via the command: `winetricks vkd3d`

Also, make sure that you update winetricks databases first with command:

`sudo winetricks --self-update`, this will disable auto updating but it will make sure you'll get the lastes packages. 

As Blistro91 mentioned, It is recommended to install DXVK along winetricks with:

`winetricks dxvk vkd3d`

For instance i have been using xenia under it and it works fine

**Comment by Blisto91** [comment]
Love that installing `vkd3d` through winetricks actually disables `vkd3d` and instead installs `vkd3d-proton`. Not confusing at all heh.

**Comment by Fabxx** [comment]
> Love that installing `vkd3d` through winetricks actually disables `vkd3d` and instead installs `vkd3d-proton`. Not confusing at all heh.

yeah a package rename would be helpful to not confuse users

**Comment by Augusto7743** [comment]
Thanks.
