### ISSUE TITLE
Resident Evil 3 Remake Crash

### ISSUE THREAD

**Issue by mixalis1987** [HansKristian-Work/vkd3d-proton#179]
When starting the game and progressing to the menu the game will crash/freeze on black screen before being able to see the menu. 
I thought it would be good to mention this.
( Resident evil 2 remake works great on MAX settings! Awsome )

System information:
Nvidia: 1080ti Driver: 440.82
CPU: AMD Ryzen 9 3900X
OS: Manjaro XFCE

Anything you need I will be happy to provide.

**Comment by doitsujin** [comment]
Is this a regression? RE3 was working just fine when I last tested it.

Also, please provide at least Proton log files.

**Comment by mixalis1987** [comment]
Are you using a steam proton or a custom one? I tested with steams proton and GE version, both crash on black screen before getting to the main menu.
Hope the log helps. 
Log:
[steam-952060.log](https://github.com/HansKristian-Work/vkd3d/files/4874875/steam-952060.log)

**Comment by mixalis1987** [comment]
@doitsujin Was the log helpful?

**Comment by GloriousEggroll** [comment]
Last i tried it had problems with custom overlays. If you have something like mangohud enabled disable it. Other than that I just double checked here and it ran fine on dx12/vkd3d

**Comment by mixalis1987** [comment]
Works with vkd3d 2.0 now.

**Comment by ngoquang2708** [comment]
> Works with vkd3d 2.0 now.

Isn't it still need MF?

**Comment by mixalis1987** [comment]
Yes but the crash I posted was before hitting the menu and not when
starting the game.
Now with vkd3d 2.0 it looks like it's going to crash because when it's just
about to start the start menu, it takes a few seconds. ( before would
completely freeze with no error on a black screen and re3 mouse ) With dxvk
it's a smooth transition into the start menu.
But with vkd3d now, game looks to function like normal.
