### ISSUE TITLE
Vague details on what "Force enable DXR" means.

### ISSUE THREAD

**Issue by Weather-OS** [HansKristian-Work/vkd3d-proton#1792]
What does it do? Doesn't VKD3D 2.11 already enable DXR If VKRT Is present?

**Comment by mbriar** [comment]
Explanation is right there in the release notes:

```
There are some special cases where DXR is not enabled by default. The only such current example is
"Hellblade: Senua's Sacrifice" on Deck which force-enables DXR if it is supported, even on Deck.
```

So "Force enable DXR" enables it even for a few special cases for which it is still disabled by default.
