### ISSUE TITLE
After enabling DXR by default the game "The Callisto Protocol" crashes with message "Assertion failed!" when I try continue game

### ISSUE THREAD

**Issue by NTMan** [HansKristian-Work/vkd3d-proton#1796]
After enabling DXR by default the game "The Callisto Protocol" crashes with message "Assertion failed!" when I try continue game.
`VKD3D_CONFIG=nodxr` workaround this issue.

![Screenshot from 2023-12-01 01-13-36](https://github.com/HansKristian-Work/vkd3d-proton/assets/200750/91a22e9d-ac1a-45c6-8f9c-bb92eb0baca5)

### System information
- GPU: Radeon 7900XTX
- Driver: Mesa-git https://gitlab.freedesktop.org/mesa/mesa/-/commit/f3d99e35353434ca56334c672dbd5dca3eb27c67
- Wine version: experimental-bleeding-edge-8.0-66235-20231129-p3015ba-w0f81e2-d91f7f4-v04eb45-unstripped
- VKD3D-Proton version: 2.11.0

### Log files
[steam-1544020.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/13517450/steam-1544020.zip)
[steam-1544020-nodxr.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/13517452/steam-1544020-nodxr.zip)

**Comment by RiantAnda** [comment]
I can confirm this issue on mesa 23.2, there is also a proton report at: https://github.com/ValveSoftware/Proton/issues/6362

Tried out AMDVLK 2023.Q4.2, but issue remains.
