### ISSUE TITLE
Ashes of the Singularity Escalation crashes on startup on Win11

### ISSUE THREAD

**Issue by lampard2a4** [HansKristian-Work/vkd3d-proton#1797]
Dear Hans,

I was trying to play Ashes Escalation in Vulkan, and I was surprised to find that when using D3D11.dll from DXVK 2.3, it worked. But when I switched to D3D12.dll and D3D12core.dll from vkd3d-proton, it crashed on startup.

Did I deploy vkd3d-proton incorrectly? Is there a guideline on how to use it on Windows? Or are there any bugs?

### Software information
Ashes of the Singularity Escalation 3.13.46785.0, DX12 mode, borderless fullscreen.

### System information
- GPU: AMD Radeon 780M
- Driver: 31.0.23002.65
- Wine version: Not applicable for Win11
- VKD3D-Proton version: 2.11
- DXVK version: 2.3

### Log files

[AshesEscalation_DX12_d3d11.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13515651/AshesEscalation_DX12_d3d11.log)
[AshesEscalation_DX12_dxgi.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13515652/AshesEscalation_DX12_dxgi.log)

AshesEscalation_DX12_dxgi
info:  Game: AshesEscalation_DX12.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7fffe0d1d510
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon 780M Graphics:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 5888 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[12]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 12911 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[14]: Property Flags = 0xc7
err:   wsi: parseColorimetryInfo: Failed to get parse edid.
err:   DXGI: Failed to parse display metadata + colorimetry info, using blank.
info:  AMD Radeon 780M Graphics:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 5888 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[12]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 12911 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
info:      Memory Type[10]: Property Flags = 0x7
info:      Memory Type[14]: Property Flags = 0xc7
info:  Game: AshesEscalation_DX12.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7fffe0d1d510
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon 780M Graphics:
info:    Driver : AMD proprietary driver 2.0.283
info:    Memory Heap[0]: 
info:      Size: 5888 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:      Memory Type[8]: Property Flags = 0x1
info:      Memory Type[12]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 12911 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[11]: Property Flags = 0xe
info:      Memory Type[13]: Property Flags = 0xc6
info:      Memory Type[15]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7

AshesEscalation_DX12_d3d11
info:  D3D11InternalCreateDevice: Maximum supported feature level: D3D_FEATURE_LEVEL_12_0
info:  D3D11InternalCreateDevice: Using feature level D3D_FEATURE_LEVEL_12_0
info:  Device properties:
info:    Device : AMD Radeon 780M Graphics
info:    Driver : AMD proprietary driver 2.0.283
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_hdr_metadata
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_pipeline_library
info:    VK_KHR_swapchain
info:    VK_KHR_win32_keyed_mutex
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    wideLines                              : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 1
info:    shaderResourceMinLod                   : 1
info:    sparseBinding                          : 1
info:    sparseResidencyBuffer                  : 1
info:    sparseResidencyImage2D                 : 1
info:    sparseResidencyImage3D                 : 1
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 1
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 1
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 1
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 0
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_depth_bias_control
info:    depthBiasControl                       : 0
info:    leastRepresentableValueForceUnormRepresentation : 0
info:    floatRepresentation                    : 0
info:    depthBiasExact                         : 0
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 1
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 1
info:    extDynamicState3SampleMask             : 1
info:    extDynamicState3LineRasterizationMode  : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 1
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 0
info:  VK_EXT_line_rasterization
info:    rectangularLines                       : 0
info:    smoothLines                            : 0
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 1
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_swapchain_maintenance1
info:    swapchainMaintenance1                  : 0
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 1
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 1
info:  VK_KHR_maintenance5
info:    maintenance5                           : 0
info:  VK_KHR_present_id
info:    presentId                              : 0
info:  VK_KHR_present_wait
info:    presentWait                            : 0
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  VK_KHR_win32_keyed_mutex
info:    extension supported                    : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:    Sparse   : 0
info:  Memory type mask for sparse resources: 0xf
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries not supported
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

**Comment by mbriar** [comment]
Intel is probably even worse, but nvidia should probably work.
