### ISSUE TITLE
World of Warcraft Dragonflight dx12 crash

### ISSUE THREAD

**Issue by HonkinWaffles** [HansKristian-Work/vkd3d-proton#1813]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
World of Warcraft 
Graphics API: Dx12
Graphics Preset: Ultra
RTX: Off
Max FPS: 170 

### System information
- GPU: 6900xt
- Driver: OpenSource
- Wine version: ge-8-25
- VKD3D-Proton version: v2.11

### Log files
Please attach Proton or Wine logs as a text file: 
[WoW Crash Log](https://github.com/HansKristian-Work/vkd3d-proton/files/13697831/WoW.Crash.Log)

### Additional notes:
I noticed specifically during one of the new riding races for the Xpac pre-order mount that 1 specific spot would cause a crash. The system would recover from the crash but the game was done. After a bunch of troubleshooting done the issue would go away by disabling `XKD3D` which resulted in being forced to use dx11 which runs poorly. After some additional testing, revering to `v2.10` resolved the issue. I confirmed this by going back to `v2.11` and it crashed in the same spot, then switched back to `v2.10` and experienced no crash.

**Comment by Blisto91** [comment]
Are you able to show via a screenshot or online map where the crash usually happens? Will help when looking in to the issue.

**Comment by HonkinWaffles** [comment]
> Are you able to show via a screenshot or online map where the crash usually happens? Will help when looking in to the issue.

After hitting this checkpoint the crash happens. 
https://i.imgur.com/2EPTd98.png


Map location of the checkpoint:
https://i.imgur.com/bcO5faL.png

As I mentioned this is specifically the new race added for the war within pre-order bonus

**Comment by Blisto91** [comment]
@HonkinWaffles I've been unable to reproduce a crash so far during this race on my RX 6800 with vkd3d-proton 2.11. Which driver version do you use?

**Comment by Blisto91** [comment]
@HonkinWaffles Friendly ping

**Comment by HonkinWaffles** [comment]
Hey sorry about that.

I think we can probably close this, I tried with the most recent update and things were working fine.
