### ISSUE TITLE
[Question] Memory allocation failed, falling back to system memory.

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#1814]
I noticed I get `vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.` in the logs.
It's a bit unclear what the warning actually means. Is that normal for Nvidia RTX 3060Ti?

**Comment by doitsujin** [comment]
This generally just means that you're running out of VRAM, the fallback mechanism is necessary for games not to crash but **will** cost performance. Whether or not this is expected depends on which game you're getting this with and with what settings, games wanting more than 8GB isn't unheard of these days.

Can you post a log file?

**Comment by shelterx** [comment]
@doitsujin
I just happen to see it when fiddling around with REBAR on/off and ingame settings, because I was wondering why the performance hit was so big in AC Valhalla in Linux compared to Windows.
Here's the log file from that game:
[vkd3d.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13842036/vkd3d.log)

I only have time right now to provide a log from that specific game but I saw the same behavior for another game too..

Some screenshots from the game showing vram usage:
![vram](https://github.com/HansKristian-Work/vkd3d-proton/assets/8688458/d36523aa-803f-41f9-9aa8-af36de4d1606)
![ingame-vram](https://github.com/HansKristian-Work/vkd3d-proton/assets/8688458/dfdeff06-2857-49dc-8779-16f0f51bff51)

**Comment by shelterx** [comment]
Also, the game performance is bad. High graphics settings on Linux gives about the same results as Ultra High on Windows. Which's a bit weird because most games that I have tried runs about the same as on Windows, but not this game.
I don't think it's because of the system memory issue, something else is bottlenecking here.

**Comment by shelterx** [comment]
Closing this, seems to be a VRAM OOM issue really which's weird since I had a 8GB card and as far as i know there were memory left to allocate. But Linux vram management very good so if you have other apps running, it might eat up vram and then vkd3d uses system memory instead. If you launch the game with minimal programs running the message dissappers.

**Comment by felixpelletier** [comment]
I'm having that issue with Far Cry 6. `nvidia-smi` tells me I still have 5GB free, but I still get that message. Performance is really bad even with an i9-13900k and an RTX 3080, so I'm suspecting this. FarCry6.exe still manages to use 4GB of VRAM though.

**Comment by shelterx** [comment]
@felixpelletier Yeah, could still be some memory detection issue, I mean, I'm pretty sure I had enough memory when I started Valhalla, and as seen in the screenshots, only 6,3GB of my VRAM is in use.
Btw, `nvtop` is a nice utility to check VRAM usage.

**Comment by shelterx** [comment]
However nvtop and mangohud shows the same VRAM usage. nvidia-smi seems to show what's actually in use (not omly allocated. there's a 400Mb difference here between nvtop and nvidia-smi). So I'm not exactly sure what to trust in this scenario.

**Comment by shelterx** [comment]
I am still not sure what's going on here, if it's a normal message when ReBar is enabled.
Because I still saw this message in Valhalla and also Ready or Not when I had VKD3D_DEBUG=warn set. I have 12Gb of vram now since i changed graphics cards.

**Comment by shelterx** [comment]
Disabling Rebar in bios makes the message go away. However it may decrease performance in some titles, while some titles seem to benefit from it.
Same message occurs in windows too with vkd3d-proton so it's not Linux specifc.
