### ISSUE TITLE
Proton much faster

### ISSUE THREAD

**Issue by DocMAX** [HansKristian-Work/vkd3d-proton#1819]
I have a strange issue where Cyberpunk 2077 is at ~15 FPS with wine+dxvk+vkd3d but with Proton i get about ~50FPS.
It got better with WINEESYNC=1, to 33 fps. But still much slower.
Any hints?

Software information
Cyberpunk

System information

    GPU: AMD RX570
    Driver: Kernel 6.6.8-arch1-1
    Wine version: wine-ge-custom GE.Proton8.25-1, also tried wine, wine-staging 8.21
    DXVK version: dxvk-bin 2.3-1
    VKD3D version: vkd3d-proton-bin 2.11.1-1

Apitrace file(s)
    i get no output

Wine Log
[wine.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13778422/wine.log)

**Comment by RiantAnda** [comment]
Just a random thought by seeing the ESYNC improvement:
You could try FSYNC, if you already have the right kernel.
`WINEFSYNC=1` and `WINEFSYNC_FUTEX2=1` (not sure if the latter is still needed)

**Comment by DocMAX** [comment]
Sorry, yes. It seems enabling ESYNC in wine helps a lot.
