### ISSUE TITLE
NVIDIA driver regression v545 (The Last of Us crash)

### ISSUE THREAD

**Issue by Anuskuss** [HansKristian-Work/vkd3d-proton#1820]
**GPU:** NVIDIA GeForce RTX 2060 v545.29.6
**Proton:** Proton-GE v8.25 (Heroic Games Launcher v2.11.0)

It works when I downgrade back to v535(.113.01) but doesn't since v545. None of the `VKD3D_CONFIG` flags do anything. Hopefully a workaround can be found (I don't wanna waste my time by reporting this to NVIDIA).

There's a internal log file (`drive_c/users/user/Saved Games/The Last of Us Part I/user-data.txt`) which appears different every single time but so does the crash (sometimes no window spawns, sometimes it's just white, sometimes I see the intro loading screen which crashes at different times). Although I once saw this in there:
```
assert-msg: Failed to CreateComputePipelineState with error: 0x80004005 - Aufruf fehlgeschlagen.
assert-expr: HALT
assert-func: ndgi::AssertHResultSuccess
assert-file: ndlib/render/ndgi/win/ndgi-win.cpp
assert-line: 983
active-jobs: Thread Idle, Thread Idle, Thread Idle, Thread Idle, Thread Idle, Thread Idle, GameInitInternal, Thread Idle
active-tasks: 
last-gpu-crash-hresult-code: 0x80004005
last-gpu-crash-hresult-string: E_FAIL
```

[steam-heroic-0.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13782361/steam-heroic-0.log)
[vkd3d.log](https://github.com/HansKristian-Work/vkd3d-proton/files/13782362/vkd3d.log)

**Comment by shelterx** [comment]
When does it crash?
It works fine for me with Wine-GE-Custom 8.25 and vkd3d version 2.11.1.

**Comment by Anuskuss** [comment]
Wine-GE crashes even earlier (before the "Report Problem" window by the game I usually get). Now I get a "Program Error" window (which I have never seen before ever) which states
> **The program tlou-i.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience.**
This can be caused by a problem in the program or a deficiency in Wine. You may want to cehck the [Application Database](https://appdb.winehq.org) for tips about running this application.

[backtrace.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/13806253/backtrace.txt)

I don't think it's the kernel either (v6.6.8) but it sucks that it seems like it's only happening to me (I may have seen a single similar report but I don't know).

@shelterx Which launcher do you use?

**Comment by shelterx** [comment]
> @shelterx Which launcher do you use?

A local Bottles installation (no flatpak crap).
Have you checked the Valve Proton issue thread for TLOU?

**Comment by mhmarf** [comment]
For what is worth, I too had lots of problems with TLOU though I'm on AMD. Game would always crash to desktop on steam and on lutris it would give the "no dx12 card" error if I used WINEDLLOVERRIDES="amd_ags_x64.dll=b"... finally I went to proton experimental folder, found amd_ags_x64.dll there and replaced the same file in the game folder with it and removed the WINEDLLOVERRIDES evn var alltogether and it fixed my problem...

**Comment by Anuskuss** [comment]
That thread is dead. I think most people have already finished that game or don't care anymore (meaning it could affect more people than just me but it's not being reported). I don't know, guess I'll keep my Windows dualboot for now.

**Comment by shelterx** [comment]
Weird, it just works here with RTX3060Ti, I can't help you much but when I had problems initially when the game was released, it was due to vcredist and/or wine mono.

**Comment by Blisto91** [comment]
If you believe a driver regression is involved then please report it to Nvidia

**Comment by Anuskuss** [comment]
Solved this issue by increasing the `nofile` limit (from 1024 to 2048). I have no idea why it works on the old driver and why it doesn't work now but hopefully this info will help somebody one day (if you're using a `systemd` based distro you might have to set it in `/etc/systemd/user.conf` instead of `/etc/security/limits.conf`).
