### ISSUE TITLE
The Finals fails to launch on Intel Arc with DX12

### ISSUE THREAD

**Issue by Vinjul1704** [HansKristian-Work/vkd3d-proton#1832]
The Finals fails to launch on Intel Arc with DX12 (default). After the initial EAC splash screen, the main game window opens and stays as a black screen for a few seconds, before simply closing. During that black screen, the CPU usage spikes and after a handful attempts of launching the game, it doesn't even get to the black screen anymore and simply crashes right after the EAC splash screen.

Using the `-dx11` launch argument works to get the game running, however there is no graphics API selection offered by the game itself and it's unclear if that option is intended to be enabled and might go away at some point.

According to other [Proton reports](https://github.com/ValveSoftware/Proton/issues/7317), it seems to work fine with DX12 on other GPUs.

### Software information
The Finals (2073850), default settings

### System information
- GPU: Intel Arc A380
- Driver: mesa-tkg-git 24.1.0_devel.183215.b9ad22d24ee-1
- Proton version: Experimental (Bleeding Edge)

### Log files
Proton Log with DX12: https://gist.github.com/Vinjul1704/032f920f99c11103bf4a7e015d757308

**Comment by mbriar** [comment]
If it works on AMD/Nvidia, you should probably rather report this issue on the Mesa bugtracker and not here. However, this is probably just another case of any game supporting XeSS upscaling crashing on Intel on linux if you don't report a non-Intel vulkan verdor. Try `force_vk_vendor="-1"` as environment variable.

**Comment by Vinjul1704** [comment]
> If it works on AMD/Nvidia, you should probably rather report this issue on the Mesa bugtracker and not here. However, this is probably just another case of any game supporting XeSS upscaling crashing on Intel on linux if you don't report a non-Intel vulkan verdor. Try `force_vk_vendor="-1"` as environment variable.

Thanks, looks like `force_vk_vendor="-1"` does indeed work. I'll make a Mesa report as well then, as you suggested.

**Comment by mbriar** [comment]
You can close this one, there is nothing that vkd3d-proton can do about it.
