### ISSUE TITLE
Commit bb3948f558f4a9d3afa757e81ed51dc66d8dc9c7 breaks Talos Principle 2

### ISSUE THREAD

**Issue by adolfintel** [HansKristian-Work/vkd3d-proton#1838]
The game crashes immediately at the Croteam logo or right before it, I bisected the issue to commit bb3948f558f4a9d3afa757e81ed51dc66d8dc9c7.

### Software information
The Talos Principle 2 (835960), openbeta branch (build 13182664)

### System information
- GPU: AMD Radeon RX 6900XT
- Driver: Mesa 24.1, current master
- Wine version: Proton 8.0 experimental, current master
- VKD3D-Proton version: Current master, no special settings used

### Log files
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/13997077/log.txt)

**Comment by Blisto91** [comment]
Hi there. 
Is it correct hat you have two radv versions on system at the the same time? I see your GPU gets listed both with 23.2.99 and 24.0.99.
It suggests you have a extra ICD. Might not make a difference here, but just to be sure.

**Comment by adolfintel** [comment]
Yeah, looks like there were a bunch of .old files and folders from SEPTEMBER!

I can't believe I didn't notice it sooner 🤦‍♂️
