### ISSUE TITLE
World of Warcraft Classic Season of Discovery - DX12 Anti-Aliasing Crash

### ISSUE THREAD

**Issue by RepH3x** [HansKristian-Work/vkd3d-proton#1839]
World of Warcraft Season of Discovery (this is the only version I really play, so this may be present on other versions, I am just unaware) crashes for me specifically when I receive an honorable kill from player vs. player combat. I have not experienced any other crashes besides this, which happens 100% of the time when triggered from an honorable kill.

This crash does not occur for me when anti-aliasing is turned off while on DX12.
This crash does not occur for me when DX11 is used instead of DX12. I can use full anti-aliasing on DX11 without crashing while attempting to trigger the crash.

### Software information
World of Warcraft Classic Era, specifically Season of Discovery if that matters. 

Graphics Settings:
DirectX12, Anti-Aliasing - Advanced, Image-Based Techniques - CMAA, Multisample Techniques - 'Color 8x / Depth 8x', Multisample Alpha-Test - True

### System information
- GPU: NVIDIA RTX 3080TI
- Driver: 535.146.02
- Wine version: wine-ge-8-25-x86_64
- VKD3D-Proton version: v2.11.1

### Log files
attached 
[wowcrash.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/14016798/wowcrash.txt)

**Comment by HansKristian-Work** [comment]
Blisto made a gfxreconstruct trace, I've sent a bug report to NVIDIA.
