### ISSUE TITLE
Wine 9.0 VKD3D support

### ISSUE THREAD

**Issue by SteveEbey73742** [HansKristian-Work/vkd3d-proton#1846]
Does this version of VKD3D improve upon what has been released in Wine 9.0?

**Comment by Blisto91** [comment]
vkd3d-proton is mostly different project from the original upstream vkd3d by now and have [different priorities](https://github.com/HansKristian-Work/vkd3d-proton#priorities). So for a large part of the code it doesn't build upon upstream vkd3d directly anymore.

**Comment by HansKristian-Work** [comment]
vkd3d-proton and vkd3d are completely different projects by now, so yes.

**Comment by SteveEbey73742** [comment]
@HansKristian-Work  Thank you for the clarification. I have your vkd3d running on a rtx 4060 ti with 8 gig, and the graphics in WoW are amazing.
