### ISSUE TITLE
msfs2020 long black startup in dx12

### ISSUE THREAD

**Issue by rariema** [HansKristian-Work/vkd3d-proton#1847]
Hello HansKristian, can you help me with this?

Game: MSFS2020 
runs fine via dxvk (dx11). Would be nice to have FSR2, though
Steps to reproduce: set renderer in game or via UserOpt.conf to DX12 "PreferD3D12 1"

Symptoms: Starts "forever", screen stays black, lots of ram needed.
If it finishes loading, menü is not visible, if i manage to start a flight, game somehow renders, but very slow (~10% of dxvk, ~5fps)
![Screenshot_20240125_135313](https://github.com/HansKristian-Work/vkd3d-proton/assets/157708640/2c34ffc1-663a-4c02-b4db-96301349c78a)
![Screenshot_20240125_140802](https://github.com/HansKristian-Work/vkd3d-proton/assets/157708640/d549fe32-036c-40c0-b3d4-de36dd932522)

### Software information
microsoft flight simulator 2020 (msfs2020)

### System information
- GPU: radeon rx6600
- Driver: mesa23.3/vulkan-radeon/6.7.1-arch1-1
- Wine version: proton-GE 8.27
- VKD3D-Proton version: 2.11 

### Log files
[steam-1250410.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14052642/steam-1250410.log)

**Comment by doitsujin** [comment]
Looking into this, the game imports a 16GB (yes, that's right, **giga**bytes) host allocation into D3D12 via `OpenExistingHeapFromAddress`, which subsequently causes queue submissions to be extremely slow in the Linux kernel and also explains the insane memory usage.

Unfortunately, this really isn't something we can work around on our end, so the only thing you can really do here is keep using D3D11 for the time being.

**Comment by rbriemann** [comment]
Thx!
Its not what i hoped for, but at least it makes somehow sense now, where the insane GTT usage comes from (had to increase this, cause the default 16GB weren't enough).

So i burry my hopes till MSFS2024 comes out - DX12 renderer is in beta since ages and does not seem to be worked in much.

**Comment by rariema** [comment]
Some progress:

Game starts "fine" with Proton 9beta11 (+sim beta 15)
The insane memory consumption is gone.

Loading time still slower the dx11 but okish.
Menu and Hud still missing. Game runs ~1/4th the dxvk framerate now

![Screenshot_20240225_142534](https://github.com/HansKristian-Work/vkd3d-proton/assets/157708640/f1acb5b3-cd57-4dbc-ad06-aa3fc97bb9b0)
![Screenshot_20240225_142652](https://github.com/HansKristian-Work/vkd3d-proton/assets/157708640/f7af3995-8fc7-4b24-8f10-a4a8da17a4aa)
![Screenshot_20240225_143017](https://github.com/HansKristian-Work/vkd3d-proton/assets/157708640/ce409fd7-da0c-4d2f-9237-d71d81296b1d)

**Comment by rariema** [comment]
since recently, msfs2020 is running fine with vkd3d!
![Screenshot_20241103_201615](https://github.com/user-attachments/assets/d8df867b-dd00-4b84-b8cf-f180fcaab45f)
