### ISSUE TITLE
The Finals game crash

### ISSUE THREAD

**Issue by motpol** [HansKristian-Work/vkd3d-proton#1848]
### Software information
Steam
The Finals 1.5.5 (2073850)
All settings set to low except view distance (epic) and textures (high). Ray tracing off (static).

### System information
- GPU: Nvidia Geforce 3080 10GB
- Driver: 535.154.05
- Wine version: Proton Hotfix (20240122)
- VKD3D-Proton version: 2.11.1

### Log files
Log file to big to attach here, 27MB.
https://privatebin.net/?273fcc06915a2b70#Gqgejrgg5sD1mrYCRxM9eFMW2cqhp3L5ANXCFoQPHaHK

### Description
*This game has EAC activated, but no word on it from changelog.
The game starts and plays well sometimes, however there are times where the game crashes when loading a map, after some restarts of the game it just runs. Seems a bit random, sometimes it runs great with good performance and no crashes othertimes it doesn't run at all after the main menu. I have tried different game settings and proton versions too, latest proton hotfix seems to run best.

**Comment by SuperSamus** [comment]
Does doing the following fix the issue?
https://github.com/HansKristian-Work/vkd3d-proton/issues/1420#issuecomment-1422701022

**Comment by motpol** [comment]
> Does doing the following fix the issue? [#1420 (comment)](https://github.com/HansKristian-Work/vkd3d-proton/issues/1420#issuecomment-1422701022)

No now it crashed under gameplay. Which has happened before too.

![Screenshot from 2024-01-26 14-57-22](https://github.com/HansKristian-Work/vkd3d-proton/assets/5430534/63903270-d059-4c9b-814a-41fcf0bc3b39)

**Comment by HansKristian-Work** [comment]
`162403.197:01d0:04e4:warn:vkd3d-proton:vkd3d_acceleration_structure_convert_inputs: Application is using IndexBuffer = 0 and IndexFormat != UNKNOWN. Likely application bug.` Seems suspect, why is it trying to use RT when RT is disabled.

**Comment by HansKristian-Work** [comment]
Are you on a system with AVX512 support? There are some known crashes with that and there's a workaround to disable AVX512 in kernel boot.

**Comment by motpol** [comment]
> Are you on a system with AVX512 support? There are some known crashes with that and there's a workaround to disable AVX512 in kernel boot.

No, I cant find informasion that my CPU supports that.
I did enable resizable-bar in BIOS a few weeks ago, so I'm gonna disable that now and try.
Also gonna futher increase "vm.max_map_count" from 1000000 to 2147483642 and make it permanent.
Gonna test more to day and come back with logs if I have issues.


### Spec
R7 5800x
16 GB ram
Asus 450f motherboard

**Comment by motpol** [comment]
> `162403.197:01d0:04e4:warn:vkd3d-proton:vkd3d_acceleration_structure_convert_inputs: Application is using IndexBuffer = 0 and IndexFormat != UNKNOWN. Likely application bug.` Seems suspect, why is it trying to use RT when RT is disabled.

Could had been that I turned off RT from the menus before looking for a game.

**Comment by motpol** [comment]
Still have the same issue after making previous adjustment and deleted compdata-GAMEID folder.
Played a round, went fine. Restarted the game, and crashed when loading a map.

https://privatebin.net/?bbe100a9f9553750#86Yh7Srf8L6nKiSPkuZDUxJsohR25ZLMja9zdNFpQepF

**Comment by motpol** [comment]
Its not crashing for me anymore as of game update 1.6(.1) and/or latest Proton Hotfix. There are some frametime instabilities causing a smal stutter in video/audio.
