### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by telans** [HansKristian-Work/vkd3d-proton#187]
```
VKD3D_TEST_DEBUG=2 VKD3D_TEST_PLATFORM=wine d3d12
d3d12: 2508835 tests executed (4 failures, 7 skipped, 71 todo, 5 bugs).
```

```
d3d12:5587:Test 22: Test failed: Got 0xffff7fff, expected 0xffff8000 at (0, 0, 0).
d3d12:5861:Dim 0, Test 20: Test failed: At layer 0, (0,0,0), expected 0xffff8000, got 0xffff7fff.
d3d12:5861:Dim 1, Test 20: Test failed: At layer 0, (0,0,0), expected 0xffff8000, got 0xffff7fff.
d3d12:5861:Dim 2, Test 20: Test failed: At layer 0, (0,0,0), expected 0xffff8000, got 0xffff7fff.
```

Test 20 and 22 seem to be `test_create_graphics_pipeline_state` and `test_create_fence` respectively, but running them doesn't produce failures.

Stripped "Test succeeded.", [d3d12_tests.log](https://github.com/HansKristian-Work/vkd3d-proton/files/4883648/d3d12_tests.log)

Anything to care about?

**Comment by HansKristian-Work** [comment]
Some failures are expected, I don't think the test suite ever ran clean.

**Comment by doitsujin** [comment]
Yes, we're aware of that. Which tests fail also depends on which driver you're running.

**Comment by HansKristian-Work** [comment]
Nothing particular to do here any time soon, so closing.
