### ISSUE TITLE
Shadow of the Tomb Raider (Epic Version) crashes on DX12 mode

### ISSUE THREAD

**Issue by mmbossoni** [HansKristian-Work/vkd3d-proton#1924]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
Name of the game, settings used etc.

### System information
- GPU: AMD RX 6750XT
- Driver: mesa 24.0.2
- Wine version: GE-Proton8-32
- VKD3D-Proton version: VKD3D built from 3d6aef38c68577667746b0c33ea2950aeb209036
### Log files
[steam-heroic-ShadowoftheTombRaider.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14471238/steam-heroic-ShadowoftheTombRaider.log)

**Comment by mbriar** [comment]
It doesn't work on AMD due to this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5828

Apparently a workaround is to disable shadows (or set them to lowest?) in the game's graphics options.
