### ISSUE TITLE
Ratchet & Clank: Rift Apart - some textures aren't streamed in high resolution

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#1936]
What looks to be like decals may appear quite blurry, e.g. before the rift to pub/arena in the "Zurkies" level.

Linux VKD3D-Proton + RADV:
![1895880_20240310175159_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/316a0d9a-cfc6-410b-8fe9-90110f96d100)

Windows D3D12:
![RiftApart_2024_01_19_17_41_25_268](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/36695716-fd4a-40dc-97a2-f7bbe6abdcce)

### Software information
Ratchet & Clank: Rift Apart, latest Steam version, 1440p TAA max. settings (RT off).

### System information
- GPU: RX 7800 XT
- Driver: recent mesa git-master 
- Wine version: Proton Experimental
- VKD3D-Proton version: bd1af875a7ad476271fb7d8e345c81003e1a8197

### Log files

Is spammed with stuff like

`7395.685:0124:0128:warn:vkd3d-proton:vkd3d_get_image_allocation_info: Padding allocation requirements. Requested alignment 65536 < 262144 (dim 3, 512 x 512 x 1, 7 levels, 1 samples, fmt #62, flags #0).
`

[steam-1895880.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14551058/steam-1895880.log)

**Comment by Blisto91** [comment]
Sorry yeah I did see your previous message and noted it but haven't gotten to give it a proper deep look yet besides taking a quick peek at the same rubble ingame back then without immediately seeing anything.

**Comment by doitsujin** [comment]
Probably an issue with VRAM budget reporting as usual, unfortunately we don't really have source access to any of these resource streaming systems to figure out why they are all going horribly wrong.

The message spam is benign.

**Comment by aufkrawall** [comment]
When you delete the DS DLLs, it doesn't stream textures in highest resolution on either platform. I haven't checked if they then look exactly the same on Windows D3D12 vs. VKD3D-Proton RADV, but I think it wouldn't be that interesting when the goal is to get the proper resolution on VKD3D _with_ DS.

**Comment by aufkrawall** [comment]
There apparently was some change in VKD3D-Proton that has fixed it, as the issue is gone with recent build shipped by Proton Experimental or when using vkd3d-proton git-master (With 2.12 DLLs, the issue is still there.):
![1895880_20240605195509_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/4c60ebc7-40b0-4393-8ca0-b6003be7220f)
