### ISSUE TITLE
Question: why isn't vkd3d merged with dxvk?

### ISSUE THREAD

**Issue by Tiagoquix** [HansKristian-Work/vkd3d-proton#1937]
Hello. I would like to ask a question.

Considering that the dxvk and vkd3d projects have, in essence, very similar objectives, why aren't the two projects combined into one? Wouldn't it be possible to make dxvk also run DirectX 12(.1)?

Forgive me for my possible ignorance in asking this question, but it's a genuine question I have. From what it seems, the two projects share many similarities.

Thanks in advance.

**Comment by HansKristian-Work** [comment]
Because the implementations are completely different and there's very little overlap between D3D11 and 12 in implementation.

**Comment by K0bin** [comment]
D9VK and DXVK got merged because D9VK builds on the foundation of DXVK. That's not the case for vkd3d-Proton.
