### ISSUE TITLE
Unreal Editor for Fornite : Menu disappear

### ISSUE THREAD

**Issue by mrdev023** [HansKristian-Work/vkd3d-proton#1995]
When i click on menu, it disappearing immediatly https://drive.google.com/file/d/1QLO_xkxr8LWnw4N2KUhsITo0kq1Ojicw/view?pli=1

### Software information

UEFN with default install configuration

### System information
- GPU: Nvidia RTX 2080ti
- Driver: 550.78
- Wine version: Proton: 1713387109 UMU-Proton-9.0-200-2
- VKD3D-Proton version: 2.11.1

### Log files

[steam-default.log](https://github.com/HansKristian-Work/vkd3d-proton/files/15369471/steam-default.log)

**Comment by mrdev023** [comment]
same bug with dxvk. I don't know if is a vkd3d bug ...

**Comment by Blisto91** [comment]
If it also happens with wined3d or regular vkd3d (non vkd3d-proton) then it likely isn't.

**Comment by mrdev023** [comment]
I close this https://bugs.winehq.org/show_bug.cgi?id=56654
