### ISSUE TITLE
Arma Reforger: map is invisible when using "hardware antialiasing" option

### ISSUE THREAD

**Issue by OlegAckbar** [HansKristian-Work/vkd3d-proton#2001]
### Software information
"Hardware antialiasing" option causes the map to not draw in Arma Reforger. Disabling this option makes the map visible again
Here's a screenshot with "Hardware antialiasing" set to "x2":
![Снимок экрана_20240528_201128](https://github.com/HansKristian-Work/vkd3d-proton/assets/9915567/0016e5a3-4483-4371-971d-6c3f2eef6233)
Here's a screenshot with "Hardware antialiasing" disabled:
![Снимок экрана_20240528_201117](https://github.com/HansKristian-Work/vkd3d-proton/assets/9915567/853cf64f-8f07-4986-8c5d-ffb28d91042f)

### System information
- GPU: RX 6700 XT 
- Driver: Mesa 24.1.0-arch1.1 RADV
- Wine version: GE-Proton9-5
- VKD3D-Proton version: 2.12.0+

### Log files
[steam-1874880.log](https://github.com/HansKristian-Work/vkd3d-proton/files/15473536/steam-1874880.log)

**Comment by doitsujin** [comment]
Does this even work on Windows? I can reproduce this locally, but the game's MSAA impementation is completely broken, it doesn't set up pipelines correctly, tries to render to images with different sample counts at the same time, and seems to fuck up various copies and resolves. I'm not surprised that this isn't working, but I don't know to which extent we can work around all of these app bugs.

**Comment by OlegAckbar** [comment]
@doitsujin I can't test it on Windows myself but I found this video https://youtu.be/f1SJCPcTtG4
It's from the 3rd of December but you can see that at 0:11 that he's using x8 hardware antialiasing and at 5:40 his map works fine.

**Comment by doitsujin** [comment]
Figured out that the game hits some broken-ass fallback path with vkd3d-proton due to a missing format support bit somewhere, investigating.

**Comment by OlegAckbar** [comment]
I would like to thank you for solving this issue so quickly. Now map indeed works with a hardware antialiasing option. However, another problem showed up. With hardware AA option map appears in low gamma, no such problem with hardware AA turned off.
Here's a screenshot with hardware AA turned off:
![Снимок экрана_20240529_184650](https://github.com/HansKristian-Work/vkd3d-proton/assets/9915567/d0f133b2-2f34-401a-a651-54c434bbbf9f)
Here's when it's turned to x2
![Снимок экрана_20240529_184632](https://github.com/HansKristian-Work/vkd3d-proton/assets/9915567/c2215c12-6f57-4118-b271-2688a996b8e5)

**Comment by doitsujin** [comment]
Thanks for the heads-up, this is a bug in our resolve code where in one specific edge case we do not properly account for sRGB images. I'll have a fix shortly.

For future reference, please re-open the issue or file a new one for visibility.

**Comment by OlegAckbar** [comment]
Ok, #2004 indeed fixes the issue. Once it's merged issue should be closed I think?
