### ISSUE TITLE
Glitchy hair rendering with VRS in Senua's Saga: Hellblade 2

### ISSUE THREAD

**Issue by runar-work** [HansKristian-Work/vkd3d-proton#2003]
When VRS is enabled in Senua's Saga: Hellblade 2, there are hair rendering glitches on certain NPCs. 

![screenshot-2024-05-28-15-50-21](https://github.com/HansKristian-Work/vkd3d-proton/assets/78347897/9a7361c3-3439-435a-b382-8aaf24c21b86)

Original report: https://github.com/ValveSoftware/Proton/issues/7754#issuecomment-2132070672

### System information
- GPU: RTX 3070
- Driver: I tested with 550.78 and 555.42.02
- Wine version:  1716845527 experimental-bleeding-edge-9.0-99996-20240527-p01a60c-w7374ef-d7df801-v32ca00
- VKD3D-Proton version: https://github.com/HansKristian-Work/vkd3d-proton/commit/32ca00164e74cbbe500117b2d54a9aae5bd4ba80

### Captures

[Renderdoc capture](https://1drv.ms/u/c/d2b63e38109cf46c/Ef3ykW2mzNVFhdbRF13X4TYBCfOXiFpeaRr4XGUAurXMmA?e=JK6ds1)

**Comment by K0bin** [comment]
I took a quick look at it. It reproduced with the renderdoc but I couldn't see anything wrong with the problematic draw.

Looking at the first draw where these black squares show up:

 - shader outputs are roughly the same between an affected pixel and a neighboring unaffected one
 - depth test & stencil test are both fine
 - No discard/demote in the fragment shader
 - Shading rate of the pipeline: 1x1, combine ops: Keep, Max
 - It doesn't write the shading rate in either the vertex or fragment shader
 - no TCS, TES or GS shader
 - the affected pixels match up with non-zero pixels in the shading rate attachment (values are from 1, 4, 5)
 - unaffected (correct) pixels match up with black (zero) pixels in the shading rate attachment

![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/1131720/bdc5d0b4-a343-439a-89b1-983b078659d4)
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/1131720/4756f604-1672-4b22-a6da-d3efbd809909)
