### ISSUE TITLE
Ghost of Tsushima - Particle effects and bloom

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#2013]
Particles looks exaggerated/too much bloom.
Settings: Very High

Some areas in game also have too much bloom going on. Like Kukai's falls.

GPU: Nvidia RTX 4070
Driver: 555.42.02
Wine: Proton Experimental
VKD3D-Proton version: Proton Experimental

Not sure if a vkd3d log will help, I will provide one if needed.

**Comment by K0bin** [comment]
Please provide some comparison pictures and ideally some instructions on how to reproduce the issue.

**Comment by shelterx** [comment]
Mmmm maybe I was seeing things. The game has day/night cycles so things change a bit. But I did a comparison and now I didn't notice any significant difference in the area I'm currently in.
I'll leave the issue open for now and update if I spot anythng obvious.

**Comment by shelterx** [comment]
There's "weird" bloom in places in Windows too. I'll make a new issue if I encounter something out of the ordinary.
