### ISSUE TITLE
VKD3D-Proton 1.1-3029 not works for Death Stranding Director's Cut on Proton/Proton-GE

### ISSUE THREAD

**Issue by AlvaroDavi5** [HansKristian-Work/vkd3d-proton#2019]
When I starts Death Stranding Director's Cut from my Steam client on Ubuntu, the screen became black with glitchs and then the game crash without log error. The only logs that I received using another Proton versions is: `An Access Violation (C0000005h) has occurred in thread 'Main' at instruction location 00000001419A4004h`.
But the DS Standart Edition works on Heroic Games Launcer with Wine-GE-Proton8-26 and the DS Director's Cut works perfectly on Windows 11 (I had dual boot).

### Software information
**Game:** Death Stranding Director's Cut
Tested resolutions: 1600x900 and 1280x720
Steam game lauch options: `gamemoderun mangohud PROTON_LOG=1 %command%` (also tested without launch options)
Game settings: 
[settings.cfg.txt](https://github.com/user-attachments/files/15881141/settings.cfg.txt)

### System information
- OS: Ubuntu 20.04 LTS x64
- GPU: AMD ATI Radeon Vega 8 Picasso
- CPU: AMD Ryzen 5
- Driver: amdgpu
- Vulkan Version: 1.2.131
- Wine version: tested with Proton Experimental, Proton 9.0-2, Proton 7.0-6, Proton GE 7-42 and Proton GE 9-7
- VKD3D-Proton version: **1.1-3029** - _vkd3d-proton (vkd3d-1.1-3029-g4735b542)_ (from `GE-Proton7-42/files/lib64/wine/vkd3d-proton/version`)

### Error occurrence print
![Screenshot from 2024-06-14 11-51-55](https://github.com/HansKristian-Work/vkd3d-proton/assets/52904236/43c83550-99ea-4e66-b187-2c857b2444c7)

### Log files
[steam-1850570.log](https://github.com/user-attachments/files/15881126/steam-1850570.log)

**Comment by Blisto91** [comment]
I think the pretty old Vulkan driver might be playing a role here. Would be good if you could get it updated.

**Comment by AlvaroDavi5** [comment]
@Blisto91 I tried it, but looks like AMD don't provides a updated driver for my integrated GPU: AMD ATI Radeon Vega 8 (mobile) "Picasso" 😢

**Comment by mbriar** [comment]
You can get updated drivers for ubuntu from here https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

A newer version of ununtu would also come with updated drivers by default.

**Comment by Blisto91** [comment]
Your GPU should still be fully supported by latest mesa drivers afaik. I'd recommend reaching out somewhere for some help in trying to update them if you are having trouble yourself (i don't use Ubuntu myself).

Looking at your log i am getting a bit confused. It almost looks like upstream vkd3d is getting loaded from a file in your games folder? If that is the case then note that this repository is not for upstream vkd3d as that is a separate project.

**Comment by AlvaroDavi5** [comment]
@mbriar Thanks, I'm updating the drivers now. As soon as it's  finish I come be back with an update.

**Comment by AlvaroDavi5** [comment]
Unfortunately, just updating drivers doesn't work 😢

**Comment by Blisto91** [comment]
Could you try to delete the d3d12 and dxgi DLL you have in the game folder and then see again

**Comment by AlvaroDavi5** [comment]
@Blisto91 I will try it.

**Comment by AlvaroDavi5** [comment]
@Blisto91 @mbriar Thank You so much.
After delete d3d12.dll and dxgi.dll the game started and until then runs perfectly with Proton GE 9-7
