### ISSUE TITLE
Kingdom Hearts -HD 1.5+2.5 ReMix- New Game videos do not work

### ISSUE THREAD

**Issue by AJuujarvi** [HansKristian-Work/vkd3d-proton#2021]
The intro video after starting a new game on Kingdom Hearts as part of the Kingdom Hearts -HD 1.5+2.5 ReMix-
 collection only displays a black screen. Audio displays correctly. This only happens when the game is not detected as a Steam Deck. The intro video is using NV12 by default, and is using X8R8G8B8 for when a Steam Deck is detected.

### Software information
Kingdom Hearts -HD 1.5+2.5 ReMix- was the only one tested, and only on the first game. I have a feeling it will affect the intro video in all the games in this collection, with a good chance Kingdom Hearts HD 2.8 Final Chapter Prologue and Kingdom Hearts III + Re Mind (DLC) also having the intro videos.

Default settings.

### System information
- GPU: AMD 7900XT
- Proton version: experimental-bleeding-edge-9.0-102532-20240613-pc167f9-wa4bf20-da8710f-vb4eb56

### Log files
This log file has additional media channels used.

[Exp-Desktop-Detected-Blackscreen-at-video-steam-2552430_1.log](https://github.com/user-attachments/files/15930768/Exp-Desktop-Detected-Blackscreen-at-video-steam-2552430_1.log)

**Comment by DistantThunder** [comment]
I have videos with Proton 9.0-2 (probably, they were not encoded yet by Steam until a few days ago) but I also do have frequent AMDGPU crashes. No idea if VKD3D is related...

**Comment by shelterx** [comment]
Probably not vkd3ds fault. Try proton-ge if all else fails
