### ISSUE TITLE
Horizon Zero Dawn GOG crashes on start

### ISSUE THREAD

**Issue by ianare** [HansKristian-Work/vkd3d-proton#2022]
Trying to run Horizon Zero Dawn from GOG, the game doesn't run at all, I just get a dialog box asking to send a bug report.

When I run the game using Wine DLLs (not vkd3d-proton), I get a loading screen displayed then crash with the following `fixme` messages:
```
vkd3d:0130:fixme:d3d12_command_list_ResourceBarrier Aliasing barriers not implemented yet.
vkd3d:0130:fixme:d3d12_command_list_DiscardResource iface 00000000130856D0, resource 00000000131DEA20, region 0000000000000000 stub!
```

With vkd3d-proton I don't even get the loading screen.

### Software information
- Game: Horizon Zero Dawn Complete Edition GOG version 7517962
- OS: KDE Neon, Plasma 6.1

### System information
- GPU: AMD Radeon RX 6700 XT 12GB 
- Driver: Mesa 24.1.2 - RADV NAVI22
- Wine version: wine-staging 9.10
- VKD3D-Proton version: Compiled on tag v2.13

### Log files
[game.log](https://github.com/user-attachments/files/15936359/game.log)
[vulkaninfo.log](https://github.com/user-attachments/files/15936361/vulkaninfo.log)

**Comment by mbriar** [comment]
You need to install DXVK to the prefix as well because vkd3d-proton relies on DXVK's dxgi.dll

**Comment by ianare** [comment]
That did it, thank you so much for the quick reply!
