### ISSUE TITLE
heavy artifacts in ghost of tsushima

### ISSUE THREAD

**Issue by XxRiKxX** [HansKristian-Work/vkd3d-proton#2033]
gpu rx 570
drivers mesa vulkan radeon
distro arch
proton ge 9.7

objects are appearing out of nowhere and floating at certain camera angles and also heavy flickering. sometimes the entire screen is getting covered. tried with mesa tkg git as well.

**Comment by HansKristian-Work** [comment]
This is a known issue on Polaris specifically, and it's extremely hard to debug. Does it reproduce for you if you do VKD3D_DISABLE_EXTENSIONS=VK_EXT_descriptor_buffer ?

**Comment by mbriar** [comment]
I think you should leave the bug report open, it should work without using workarounds.

**Comment by HansKristian-Work** [comment]
That is true, but it is a Mesa bug, not vkd3d-proton. We've ruled out everything else from vkd3d-proton side.
