### ISSUE TITLE
Pioneers of Pagonia - no options for Multisample AA on AMDGPU

### ISSUE THREAD

**Issue by Mershl** [HansKristian-Work/vkd3d-proton#2043]
### Software information
Pioneers of Pagonia

### System information
- GPU: AMDGPU RX7900XTX
- Driver: mesa-git (26th of June)
- Wine version: Wine and Proton-GE-9-7 tested on separate prefixes
- VKD3D-Proton version: https://github.com/HansKristian-Work/vkd3d-proton/commit/0dc4917b78599083b1336162c3378f8bbebd7b98

### Screenshot
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/520251/039724be-fccc-4adf-971a-fb67c2720eb9)

Same hardware on Windows shows the options OFF, 2x, 4x, 8x.

### Log files
[pagonia_wine_msaa.log](https://github.com/user-attachments/files/16120750/pagonia_wine_msaa.log)

**Comment by doitsujin** [comment]
Known issue, iirc the game only allows you to enable MSAA if MSAA is supported with tiled resources, even though the game does not use tiled resources at all, and RADV doesn't really support that.

**Comment by doitsujin** [comment]
Looked at it again for a related reason, turns out it was actually even more silly than that. The game requires support for `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_2` to expose MSAA even though it does not use the feature, and we cannot support it.

**Comment by RalfKornmannEnvision** [comment]
The issue here is that someone decided that D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_2 is although the indicator for depth buffer downsample support. As we use it and have no fallback by now we need to check for it and disable MSAA if not present

**Comment by doitsujin** [comment]
Interesting, I wasn't aware of that - especially since we've seen games rely on all the fun `ResolveSubresourceRegion` things without checking for that bit.

Either way, since we support depth/stencil resolves just fine I added an app profile in the PR above.

**Comment by Mershl** [comment]
Hi @doitsujin,

Since the game got its full release I decided to give it a new playthrough. This time on a Nvidia setup. Either a game update or the NVIDIA GPU seems to have brought back this issue.

nvidia 590.48.01 + vkd3d @ bd3f5e3d245c3ad2c775e51a5f6118a0197f9650

log: [steam-2155180.log](https://github.com/user-attachments/files/26833549/steam-2155180.log)

```
vkd3d-proton:vkd3d_instance_apply_application_workarounds: Program name: "Pioneers of Pagonia.exe" (hash: 88c9c244d27cb5fc)
vkd3d-proton:vkd3d_instance_apply_application_workarounds: Detected game Pioneers of Pagonia.exe, adding shader quirks for specific shaders.
```

<img width="1994" height="334" alt="Image" src="https://github.com/user-attachments/assets/1147854d-a048-4b29-a483-fc34c16354b4" />

**Comment by doitsujin** [comment]
Yes, we had to revert the workaround because it was leading to GPU hangs for unknown reasons. It's just going to have to remain unsupported unfortunately.
