### ISSUE TITLE
Armored Core VI crashing to desktop randomly

### ISSUE THREAD

**Issue by MekaDragon** [HansKristian-Work/vkd3d-proton#2047]
After 6 hours with no problems, suddenly Armored Core VI is starting to crash to desktop without any warning.

### Software information
The game is Armored Core VI. Settings to medium (makes no difference as far as I can tell). Tested lots of Proton versions to no avail (7, 8, 9, experimental and hotfix).

### System information
- GPU: AMD RX 5700XT
- Driver: mesa-vulkan-drivers.x86_64 24.2.0-git.20240711.4b36668.fc40
- Wine version: tested lots of Proton versions to no avail (7, 8, 9, experimental and hotfix).
- VKD3D-Proton version: as I tested Proton 7 to experimental, I tested VKD3D from 2.10 to 2.13, the latest one.

### Log files
This is the string that always shows when crashing if I take a look at the logs:
warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised

I also can see LOTS of strings like this, being repeated constantly:
warn:vkd3d-proton:d3d12_resource_validate_texture_alignment: Invalid resource alignment 0x1000 (required 0x10000).
warn:vkd3d-proton:d3d12_device_GetResourceAllocationInfo3: Invalid resource desc.

I attach here the last log I got:
[proton log.tar.gz](https://github.com/user-attachments/files/16228198/proton.log.tar.gz)

**Comment by HansKristian-Work** [comment]
That warning spam isn't necessarily pointing to an issue. The crash is also in the game process which makes this very difficult to narrow down. Are you sure you're not doing overclocks or anything that could cause system instability?

**Comment by MekaDragon** [comment]
@HansKristian-Work no, I'm not overclocking my system. Also, I have SAM disabled (it caused some crashes here and there).

Now I'm trying to play with Easy AntiCheat disabled to check if it's more stable. If it occurs again, I'll upload another log.

If I can help you with more information, don't hesitate to ask! I'm not a developer, but I want to help as much as I can.

**Comment by MekaDragon** [comment]
@HansKristian-Work  So I disabled Easy AntiCheat by renaming the executable and played offline for several hours. It hasn't crashed for those hours... but now did again. I think EAC isn't helping, now it's a lot better, but it has happened again.

I attach you the new log in case you can see anything there. I can see the EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) is showing again.

[steam-1888160.tar.gz](https://github.com/user-attachments/files/16334404/steam-1888160.tar.gz)

**Comment by MekaDragon** [comment]
After lots of testing, I can confirm this was a problem on my end.

Somehow, undervolting a bit my CPU was causing this problem. I can't fathom why, but that's what it was causing the issue.

I just loaded my motherboard's optimized settings and now it's running fine.

Sorry and thank you a lot.
