### ISSUE TITLE
World of Warcraft full driver crash when using certain abilities

### ISSUE THREAD

**Issue by Valhrafnaz** [HansKristian-Work/vkd3d-proton#2052]
After the update to the pre-expansion patch for TWW, WoW now crashes when using abilities that project textures unto the ground to indicate the area of effect. Using DX11 emulation via DXVK does not produce any such crashes. The crash seems to be so extreme that the driver is unable to restart properly and requires a full system reset.

potentially relevant envs:

VKD3D_CONFIG=breadcrumbs
VKD3D_DEBUG=trace
STAGING_SHARED_MEMORY=1
__GL_SHADER_DISK_CACHE=1
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

### Software information
World of Warcraft 11.0.0 (over multiple builds, most current one tested is 55846)
Settings maxed out, attempted to disable Frame Overlap and Advanced Work Submit to no avail. MSAA turned off due to visual bug with transparent textures, so CMAA 2 is used instead. FidelityFX CACAO on, low latency on build-in, VRS standard, no raytracing, Vsync disabled.
EndeavourOS/Arch

### System information
- GPU: RX 7800 XT
- Driver: Mesa Gallium 24.1.4-arch1.2
- Wine version: tested with Proton-GE 9-11, Proton-GE 9-10, wine-ge-8-26
- VKD3D-Proton version: 2.12 via Lutris
ReBar/above 4G decoding enabled.

### Log files
[vkd3d.log](https://github.com/user-attachments/files/16427035/vkd3d.log)
[wine.log](https://github.com/user-attachments/files/16427046/wine.log) (from Lutris)
[gx.log](https://github.com/user-attachments/files/16427066/gx.log) (from world of warcraft itself)

**Comment by Valhrafnaz** [comment]
Further point of clarification is that not all projected texture abilities seem to be affected, only those with variable, draggable boxes like Breath of Eons or Astral Alignment with the requisite talent, which seems awfully specific.

**Comment by Blisto91** [comment]
Hi there.
I have tried to reproduce this issue both on a RTX 4080 and a 7900xtx but haven't been able to so far.
I've tried with Breath of Eons using the settings you mentioned and messing around with them further. Also using the same mesa version and vkd3d-proton (the one mentioned in the log not to one you typed).

**Comment by Valhrafnaz** [comment]
That is very strange, thank you for trying to replicate. The issue persists into mesa 24.1.5-arch1.2 and latest version of the game. It has been consistent between versions, and exactly only in D12 mode. The moment I attempt to cast the spell, the game freezes, the driver crashes and the system effectively locks up, according from what I can divine from journalctl everything seems to start to throw kernel panics once the driver restarts. Visually, the game gets stuck in the frame before drawing the actual targeting rectangle on the ground, so I assume something about that action specifically causes the crash, but I am unable to gather from the logs what that might be. Given the minimalist nature of EndeavourOS, is there a chance there's something misconfigured on my end? I have the mesa repo, as well as vdpau, vaapi, vulkan-radeon and mesa-vulkan-layers installed.

**Comment by Blisto91** [comment]
Which kernel version do you use

**Comment by Valhrafnaz** [comment]
standard arch, currently 6.10.4-arch2-1

**Comment by Valhrafnaz** [comment]
The issue has now subsided for me, and since there hasn't been an update to vkd3d-proton in the mean time, I assume it was only my system configuration that was the issue. It seems like something had at some point installed the amdvlk driver, which was taking precedence only for certain applications. (I figured this out while troubleshooting gamescope). Uninstalling seems to have fixed this issue, but I am not 100% certain that this ended up being the culprit.

**Comment by Blisto91** [comment]
Glad it started working
