### ISSUE TITLE
Hunt: Showdown 1896 has received an update to use DirectStorage and now doesn't load it's assets

### ISSUE THREAD

**Issue by TakinaLisa** [HansKristian-Work/vkd3d-proton#2066]
Just today Hunt: Showdown received an update to a new engine, and according to the devs game now utilises DirectStorage.
According to game logs, Hunt can't load it's assets/*.pak files anymore, as shown by many warnings in the Game.log file. Those warnings do not appear for Windows players able to launch the game.
Players on Windows running their games off external drives report similar issues, which confirms suspicions of DirectStorage being in use.

### Software information
Hunt: Showdown 1896 on Steam

### System information
- GPU: Sapphire Radeon RX 6700 XT
- Driver: Mesa 24.1.5-arch1.3
- Wine version: Proton Experimental bleeding-edge
- VKD3D-Proton version: 

### Log files
[steam-594650.log](https://github.com/user-attachments/files/16626784/steam-594650.log)
[Game.log](https://github.com/user-attachments/files/16626790/Game.log)

**Comment by doitsujin** [comment]
Looks like I/O errors which vkd3d-proton has absolutely nothing to do with.

If they hard-require some feature that fails even on some native Windows environments then the only way to fix this is to implement DierctStorage from scratch within Proton, but again, that's entirely unrelated to D3D12.

**Comment by TakinaLisa** [comment]
Closing this issue then
