### ISSUE TITLE
"The Texas Chain Saw Massacre" crashes some time after loading into a match

### ISSUE THREAD

**Issue by Tiagoquix** [HansKristian-Work/vkd3d-proton#2069]
### Software information
Game: https://store.steampowered.com/app/1433140/The_Texas_Chain_Saw_Massacre/

Using ReShade, MangoHud and GameMode.
Game defaults to DX12 (uses Unreal Engine, either 4 or 5; I'm not sure).

Everything on lowest settings (except render quality, which is 100%). 60 FPS limit.

Game crashes after some time in a match due to out of video memory error:
![image](https://github.com/user-attachments/assets/ae3e35c5-24ed-46f4-a3ab-400e77c4655e)

Issue is always reproducible.

I have almost 150+ hours playing this game with DXVK (`-dx11` launch option) and have not had a single crash.

--------------------------

However, being brutally honest, this game has many bugs (gameplay etc.) due to bad code from the developers, and some of them are related to graphics/rendering.

On Steam Forums, there are a lot of people complaining about the same issue:
https://steamcommunity.com/app/1433140/discussions/search/?q=out+of+memory&gidforum=4555968543720476925&include_deleted=1

So I believe the culprit are the developers (possibly for a bad DX12 implementation). But since this does not happen with DXVK, I'm reporting it here.

### System information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: Proprietary 555.58.02
- Wine version: https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton9-11
- VKD3D-Proton version: `ebe7279e7960d204f5b1bd3d89408929140cdd0f vkd3d-proton (vkd3d-1.1-4112-gebe7279e)` (https://github.com/HansKristian-Work/vkd3d-proton/commit/ebe7279e7960d204f5b1bd3d89408929140cdd0f)

### Log files
Proton log: https://0.jaegers.net/?63dbbd0513b21651#DC4unTqSHFHDH9bTKXS475mDrR1Wcq6SsDKVCogc9RFW

**Comment by HansKristian-Work** [comment]
GPU: NVIDIA GeForce GTX 1050 Ti

I kinda think that is it w.r.t. memory woes ...

**Comment by TheComputerGuy96** [comment]
Are you using an Intel 13th/14th generation CPU? If that's not the case, then it's definitely some game/driver/vkd3d bug
