### ISSUE TITLE
Hunt: Showdown 1896 crashing only in explicit area of map

### ISSUE THREAD

**Issue by hcwf** [HansKristian-Work/vkd3d-proton#2098]
Since the new Hunt: Showdown update and recent bugfix the game crashes as soon as I come near the "Deadfall Timber" area on the map.
This can also be seen in reports as this one: https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-2307753656
Switching to `radeon-vulkan` from `amdvlk` as suggested by other users did not work for me, I face the same problems on both drivers.
Previous to the latest bugfix the GPU would crash completely, forcing a restart. After the newest update only the game itself, Steam and a couple other apps crash, while others are unaffected.

### Software information
Hunt: Showdown 1896, Version 2.0.0.5.312 & 2.0.0.5.314

### System information
- GPU: AMD Radeon RX 7900 XTX
- Driver: Mesa 24.1.5
- Wine version: Proton Hotfix
- VKD3D-Proton version: 2.13

### Log files
[steam-594650-a.log](https://github.com/user-attachments/files/16804054/steam-594650-a.log)
[steam-594650-b.log](https://github.com/user-attachments/files/16804055/steam-594650-b.log)
[steam-594650-c.log](https://github.com/user-attachments/files/16804058/steam-594650-c.log)

**Comment by runar-work** [comment]
I was not able to reproduce this hang with RADV on RX 7600, but AMDVLK would hang consistently near the Deadfall Timber area. I see both drivers mentioned in your Proton log, so maybe that's why it still hangs?

**Comment by hcwf** [comment]
> I was not able to reproduce this hang with RADV on RX 7600, but AMDVLK would hang consistently near the Deadfall Timber area. I see both drivers mentioned in your Proton log, so maybe that's why it still hangs?

Thank you, that's insightful. I thought I had already forced RADV as my only driver, but clearly, simply having AMDVLK installed is a cause for problems.
Could you tell me how you successfully switch to RADV? I've always used the environment variable `AMD_VULKAN_ICD=RADV` and my tests with vulkantools showed that the drivers were being used correctly.

**Comment by runar-work** [comment]
Strange, your method worked fine for me. I had the opposite setup with RADV as default and manually specified AMDVLK, so I installed AMDVLK so it would be the default on startup and used `AMD_VULKAN_ICD=RADV` to select RADV, and I got into Deadfall Timber without a hang that way. I'm on Mesa 24.2.2, but I've also tested 24.1.5 to check if that made a difference.

**Comment by Blisto91** [comment]
`AMD_VULKAN_ICD` have been buggy for some in the past i believe https://github.com/GPUOpen-Drivers/AMDVLK/issues/331.
A alternative method, besides uninstalling amdvlk, is `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_DRIVER_FILES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json`

**Comment by hcwf** [comment]
Thank you guys for your input. I decided to uninstall AMDVLK because of the interference and it works now, no more crashes!
It must have been some strange mixup and I'm still confused how AMDVLK was chosen for this game.
