### ISSUE TITLE
Skull & Bones crashes on launch on nvidia gpus

### ISSUE THREAD

**Issue by Lifeismana** [HansKristian-Work/vkd3d-proton#2099]
### Software information
Skull and Bones (2853730) 
Cross-post of this proton compat report https://github.com/ValveSoftware/Proton/issues/8018 since the game is using dx12 so i assume vkd3d is causing the crash
The game crashes right after launch just after showing a black screen for 2 seconds.
This appear to be an problem specific to nvidia gpus since protondb has a report of it working on an amd gpu (but not on steam)  and the game is working "fine" (performances aren't great) on Steam Deck
This behaviour seems to be similar to Star Wars Outlaws' crash https://github.com/HansKristian-Work/vkd3d-proton/issues/2092 and since these are both Ubisoft games, i can easily bet it's the same issue (although they aren't using the same engine Ubisoft Anvil vs Snowdrop)

### System information
- GPU: 2080
- Driver: nvidia-open 560.35.03
- Wine version: proton experimental
- VKD3D-Proton version: 6f4f9d0 (assuming i'm looking at the correct branch in proton's github)

### Log files
[steam-2853730.log](https://github.com/user-attachments/files/16808501/steam-2853730.log)

**Comment by Lifeismana** [comment]
Gave https://github.com/HansKristian-Work/vkd3d-proton/pull/2096 a try but it doesn't seem to help (assuming i built it correctly)
[steam-2853730.log](https://github.com/user-attachments/files/16808603/steam-2853730.log)
Since it's reported as fixing the crash of outlaws, i guess this crash isn't the same cause

Since a protondb report mentions proton 8.0-5 as fixing things i also gave it a try but it seems like i'm not as lucky, the only thing that improves is the intro showing up for a few seconds

**Comment by shelterx** [comment]
Fwiw I tried the demo, I get similar logs as @Lifeismana. Game tries to open a window after the initial loading banner, then crashes. I'm not sure if it's vkd3d-proton that's causing the crash, to my untrained eye I don't see anything obvious.
Apparently the game _might_ run with proton 8 but with mixed results, some says it needs to be in fullscreen.

Also tried with dxvk-nvapi disabled, no difference.

Proton 9
vkd3d-proton https://github.com/HansKristian-Work/vkd3d-proton/commit/a2a7c023a1846124c6598875e44046c9d2eb4912
NVIDIA-SMI version  : 550.40.71
NVML version        : 550.40
DRIVER version      : 550.40.71
CUDA Version        : 12.4

**Comment by Lifeismana** [comment]
my current random theory is that the error isn't linked to vkd3d and instead is caused by the game doing some incorrect access for their "LightingDevices" config since the config file at `/steamapps/compatdata/2853730/pfx/drive_c/users/steamuser/Documents/Skull And Bones/SkullAndBones.ini` has a config about that at the end of the file & i have an msi motherboard but that kinda seems unlikely since it appears to be an nvidia gpu only problem

An other thing i gave a try was to disable my integrated gpu but same as the rest, it didn't fix anything

**Comment by shelterx** [comment]
@Lifeismana game sort of works with proton 8............
I can't get it to use the full screen area tho'

**Comment by shelterx** [comment]
@HansKristian-Work It's a regression in vkd3d-proton, seems to work fine with [2.11.1](https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.11.1)

**Comment by HansKristian-Work** [comment]
We'll need someone to bisect then.

**Comment by shelterx** [comment]
@Lifeismana if you can, try a more recent proton and make a backup of vkd3d in both lib and lib32 and replace it with 2.11.1 (proton-<version)/files/lib/wine/ and proton-<version)/files/lib64/wine/)

@HansKristian-Work yeah, between 2.11.1 and 2.12 :(

**Comment by shelterx** [comment]
Ok, so....... it's this commit https://github.com/HansKristian-Work/vkd3d-proton/commit/0eb04f89c560e28acd352f05b727ad4c6ddb5b45

Disabling the extension with VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2 makes the game run on newer versions too.

**Comment by runar-work** [comment]
Nice. Got the same commit here too on the RTX 3070.

**Comment by doitsujin** [comment]
Are there any overlays enabled? Might just be the Ubisoft thing hooking Vulkan functions in broken ways again.

**Comment by Lifeismana** [comment]
is there any way to force disable ubisoft's overlay ? (it's indeed there)

**Comment by Lifeismana** [comment]
just tested, disabling the overlay in ubisoft's settings doesn't fix the crash with VK_NV_low_latency2 enabled

**Comment by shelterx** [comment]
Disabling the overlay did not help, I did it through the ubisoft connect settings.

**Comment by Lifeismana** [comment]
running the game via steam, the only thing needed is setting this as launch option `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2 %command%`

**Comment by HansKristian-Work** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/pull/2125 might work around it.

**Comment by shelterx** [comment]
> #2125 might work around it.

Aye, it does
