### ISSUE TITLE
Potential bug with EI and StartInstanceLocation

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#2100]
Developer reported a buggy case where:

- ExecuteIndirect with push constant update is used.
- Instanced VBO is used.
- StartInstanceLocation is used in the indirect indexed draw call.
- It is expected that instanced VBO is offset correctly.
  - This does not seem to happen on Deck.

We probably need test coverage here.

**Comment by hakzsam** [comment]
@HansKristian-Work This bug exists since RADV implemented NV DGC (https://gitlab.freedesktop.org/mesa/mesa/-/commit/2d2591bbb7f1204e35f5120701166efb7a87d1e2).

I'm wondering why Stable/Beta on Deck is different then.

**Comment by hakzsam** [comment]
Nvm, this commit is fine, I missed "Fixed bug". I think I know when the regression started.

**Comment by hakzsam** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30971 fixes it and everything makes sense. I will backport it on Beta channel.
