### ISSUE TITLE
WoW TWW: Shadow image of game in top left corner

### ISSUE THREAD

**Issue by J4nsen** [HansKristian-Work/vkd3d-proton#2107]
Hi,
when playing the newest WoW expansion, I noticed a strange mirror image in the top left quarter of the screen. It disappears if I turn down "Compute Effects" to low. Does not happen on DX11.
![Bildschirmfoto_20240901_210124](https://github.com/user-attachments/assets/104c6948-86e4-4da4-b16d-dbcc8ba6edb4)

### Software information
World of Warcraft: The War Within
DX12, Max Settings (Slider on 10)

### System information
- GPU: GeForce RTX 3090
- Driver: 560.35.03
- Wine version: wine-ge-8-26-x86_64
- VKD3D-Proton version: 2.13.0

### Log files
[wow_d3d12bug.txt](https://github.com/user-attachments/files/16830196/wow_d3d12bug.txt)

**Comment by tangosox** [comment]
Same problem. DX12 (vkd3d) first DX11 second (dxvk) with Lutris running proton(latest) but can't figure out how to get exact version from that.
![dx12](https://github.com/user-attachments/assets/ca346012-f635-49a7-9c7d-1accae27f5a8)
![dx11](https://github.com/user-attachments/assets/40fd5526-5883-4f60-b7c5-0787ecf84209)

**Comment by HansKristian-Work** [comment]
Is MSAA turned on by any chance?

**Comment by J4nsen** [comment]
I just tested it. I've turned all antialiasing techniques off and the shadow is still there

**Comment by J4nsen** [comment]
But perhaps WoW isn't applying it correctly. The picture still looks relatively smooth and after a reload the antialiasing settings are back to FXAA and MSAA (Color 4x/Depth 4x). Is there another way to force them off?

**Comment by J4nsen** [comment]
Sorry for the spam:

Ok, its MSAA related. Restarting Wow helped. If MSAA is off, the shadow is gone. If it is set to 2x/2x it spans the left half of my screen, on 4x4x its the top left quarter.

**Comment by Blisto91** [comment]
The AA settings are a bit finicky with applying correctly while the game is running yes. Worth keeping in mind.

**Comment by HansKristian-Work** [comment]
Sounds like WoW went even further in using breaking MSAA behavior then ...

**Comment by HansKristian-Work** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/pull/2111 might work around it.

**Comment by HansKristian-Work** [comment]
That's just the game being stupid afaik.

**Comment by J4nsen** [comment]
Is it possible that the change to vkd3d shouldn't have caused this, or is it just WoW being WoW?
I'm happy to do more testing, but I'm also okay with it being the latter.

**Comment by HansKristian-Work** [comment]
I've heard people report that it's Wow being weird and you might have to restart the game to make MSAA options stick.

**Comment by Blisto91** [comment]
@J4nsen Sorry you are correct, there actually is a regression on master that made the options not show. I didn't think so much of it earlier since they have acted weird for me at times.
Can you give this a try and see if the original issue still shows? https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10704567272

**Comment by J4nsen** [comment]
Yep, MSAA settings are back on this branch :)

**Comment by Blisto91** [comment]
Does the original reported issue still show?

**Comment by HansKristian-Work** [comment]
I just rebased https://github.com/HansKristian-Work/vkd3d-proton/pull/2111 after merging the regression fix.

Does that take care of the issue with MSAA on?

**Comment by J4nsen** [comment]
Yes, looks good. MSAA works, I can select the different MSAA modes and the shadow image is gone :)

Thanks to all of you. I greatly appreciate your work on linux gaming <3
