### ISSUE TITLE
Breadcrumbs?

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#2112]
The instructions isn't very clear, Ive compiled vkd3d-proton with debug and -Denable_trace=true and set VKD3D_CONFIG=breadcrumbs but it doesn't give me any breadcrumbs information. What am I missing?

**Comment by HansKristian-Work** [comment]
That's how it's supposed to work. Did you enable vkd3d-proton logging?

**Comment by shelterx** [comment]
```
VKD3D_CONFIG=breadcrumbs
VKD3D_DEBUG=trace
VKD3D_LOG_FILE=/tmp/vkd3d.log
```
If this is correct, I need to look at it again. But see the -D define for breadcrumbs was used when compiling it so I don't know...
` "command": "i686-w64-mingw32-gcc -Ilibs/vkd3d/libvkd3d-proton.a.p -Ilibs/vkd3d -I../libs/vkd3d -I../include/private -Iinclude -I../include -I../khronos/Vulkan-Headers/include -I../khronos/SPIRV-Headers/include -Ilibs/vkd3d-common/libvkd3d_common.a.p -I. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -D_GNU_SOURCE '-DPACKAGE_VERSION=\"2.13\"' -D_WIN32_WINNT=0x600 -DVKD3D_ENABLE_BREADCRUMBS -fvisibility=hidden -msse -msse2 -Wvla -Wno-format -Wno-missing-field-initializers -Wno-unused-parameter -Wdeclaration-after-statement -pthread -MD -MQ libs/vkd3d/libvkd3d-proton.a.p/vkd3d_main.c.obj -MF libs/vkd3d/libvkd3d-proton.a.p/vkd3d_main.c.obj.d -o libs/vkd3d/libvkd3d-proton.a.p/vkd3d_main.c.obj -c ../libs/vkd3d/vkd3d_main.c",
`

**Comment by HansKristian-Work** [comment]
Does the vkd3d-proton log say breadcrumbs are enabled?

**Comment by shelterx** [comment]
No nothing, it just says the breadcrumbs flag is set on  VKD3D_CONFIG but nothing about it actually using it.
But if all the above is correct I probably fucked something up. But I tried to get it to work several times, I'll have another go at it tomorrow and report back.

**Comment by mbriar** [comment]
Does it even use the build you compiled? You can check the git hash in the log.

**Comment by shelterx** [comment]
> Does it even use the build you compiled? You can check the git hash in the log.

Yeah, that much I know. I use selfcompiled git versions all the time.

**Comment by shelterx** [comment]
User error... *walks in shame*, apparently I had vkd3d proton files in the game directory too. I forgot to remove them.
