### ISSUE TITLE
(Not a game issue) - Failing to Compile from Source

### ISSUE THREAD

**Issue by jrugia** [HansKristian-Work/vkd3d-proton#212]
Before the project was forked I was compiling the native library without issues. I've been trying to adapt to the new build method and while I did get far, it seems I'm now stuck at the actual compiling part.

What I've done so far:

Updated my Meson package to 0.55
Downloaded all vkd3d source including the subprojects and their own 3rd party requirements.

It seems the project is halting at the 'dxil-spirv' part, any idea what might be the cause?

Thanks in advance

![1](https://user-images.githubusercontent.com/13750621/87762234-12965f80-c813-11ea-91dc-145bf82aecd5.jpg)

![2](https://user-images.githubusercontent.com/13750621/87762243-1629e680-c813-11ea-955d-588a0ef4a129.jpg)

**Comment by telans** [comment]
you need a newer gcc probably

**Comment by HansKristian-Work** [comment]
Please try to build https://github.com/HansKristian-Work/dxil-spirv in isolation and report a bug there if it fails to compile on GCC 6. It's probably just missing an `#include <stddef.h>` somewhere.

**Comment by Joshua-Ashton** [comment]
I don't see why not being able to compile on GCC 6.3 is an issue that we need to address at all.
GCC 6.3 came out in ``December 21, 2016`` which is almost 4 years old at this point...

**Comment by HansKristian-Work** [comment]
Should be a trivial `#include <stddef.h>` fix, which is fixed now on dxil-spirv master. If that's not enough, I have no easy way to test on GCC 6, and I don't really care.
