### ISSUE TITLE
Palworld: Black screen on modern NVIDIA GPUs

### ISSUE THREAD

**Issue by Zeabyte** [HansKristian-Work/vkd3d-proton#2121]
### Software information
Game: Palworld
Launch arguments: -dx12

### System information
- GPU: NVIDIA GeForce RTX 4070
- Driver: 560.35.03-3.fc40 (also tested stable 555 and 550)
- Wine version: GE-Proton9-13
- VKD3D-Proton version: shipped with GE-Proton9-13 (built around Sep 4 from master)

### Log files
log level: warn
[vkd3d.log](https://github.com/user-attachments/files/16970620/vkd3d.log)

When starting the DX12 Version of Palworld on my Nvidia GPU, all I will get is a black screen. The game itself - apart from rendering - seems to be working, as I can right click and get a Wine web context menu. (Palworld starts with a "What's new" embedded html popup).

I have attached a vkd3d log that repeatedly shows the following error, until I quit the application:
`0210:err:dxgi_vk_swap_chain_recreate_swapchain_in_present_task: Failed to create swapchain, vr -3.`

From [ProtonDB](https://www.protondb.com/app/1623730) I could gather that this is most likely an NVIDIA-only issue.

**Comment by doitsujin** [comment]
`VK_ERROR_INITIALIZATION_FAILED` on swap chain creation really sounds like a massive driver issue, do any other D3D12 games work for you at all?

I remember some people running into this problem well over a year ago but I do not remember what the solution to that was.

**Comment by Zeabyte** [comment]
Thanks so much for looking into this.

Weirdly enough I have zero problems with any D3D12 games that I can think of. I can perfectly play Deep Rock Galactic, Cyberpunk 2077, Apex Legends and Forza Horizon 4. Even Star Wars Outlaws is working fine-ish.

**Comment by doitsujin** [comment]
Don't know then, only thing that would come to mind is perhaps setting `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2` (or `PROTON_ENABLE_NVAPI=1` as a more nuclear option) since there's a non-zero chance something is preventing the module from loading, but that would still smell like a setup issue or anti-cheat memes with the nvidia driver or something.

**Comment by Zeabyte** [comment]
Sadly those env vars produced the same result. I think that this is - as often - the typical NVIDIA bug that will be hidden inside the proprietary drivers for years to come. Still, thank you for your invaluable work!

**Comment by shelterx** [comment]
There are some suggestions on protondb you can try. Like this one, PROTON_ENABLE_NGX_UPDATER=0 %xommand%

**Comment by runar-work** [comment]
I haven't been able to reproduce this issue here for some reason. I've tested with RTX 3070 on 6.10.9-arch1-1, 560.35.03 and combinations of x11 and Wayland, Proton GE and Experimental, flatpak and system packages.

**Comment by Zeabyte** [comment]
> There are some suggestions on protondb you can try. Like this one, PROTON_ENABLE_NGX_UPDATER=0 %xommand% More here: https://www.reddit.com/r/linuxquestions/comments/19d4lyj/comment/kpp1kp2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> 
> But the general consensus seems to be that it doesn't work with Nvidia (but used to?).
> 
> (I don't have the game so I can't test it)

Thanks, but I have already tested anything you can find on ProtonDB or Reddit to no avail.

**Comment by Zeabyte** [comment]
> I haven't been able to reproduce this issue here for some reason. I've tested with RTX 3070 on 6.10.9-arch1-1, 560.35.03 and combinations of x11 and Wayland, Proton GE and Experimental, flatpak and system packages.

Interesting. What else could be the culprit?

**Comment by runar-work** [comment]
Can you add your Proton log as well? It might have some more info in it.

The only other thing I can think of is if you have an iGPU. It did launch on my Raphael iGPU with flatpak if I didn't force the Nvidia driver via `VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json` when launching steam, though the game also launched fine on the iGPU. I have had other games give me that same swapchain error when launching on the iGPU in the past, though.

**Comment by runar-work** [comment]
Did you add the option before launching Steam or after? I also get the same failure to launch a window if I try to use that inside Steam as a launch option, but it works for me if I do something like `VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json flatpak run com.valvesoftware.Steam`. On my system I need a separate package for that file (nvidia-utils), but I don't know how that works on Fedora.

**Comment by Zeabyte** [comment]
> Did you add the option before launching Steam or after? I also get the same failure to launch a window if I try to use that inside Steam as a launch option, but it works for me if I do something like `VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json flatpak run com.valvesoftware.Steam`. On my system I need a separate package for that file (nvidia-utils), but I don't know how that works on Fedora.

I think you might have found the problem here. I have just found out with `nvtop` that my iGPU spikes to 100% when launching the game while the dGPU seems to have the usual Desktop workload.

I have tried `VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json flatpak run com.valvesoftware.Steam` on Fedora, but the game still seems to use the iGPU. Is there any other way to force the use of my dGPU?

**Comment by Blisto91** [comment]
You can try `DXVK_FILTER_DEVICE_NAME="4070"`

**Comment by Zeabyte** [comment]
> You can try `DXVK_FILTER_DEVICE_NAME="4070"`

I cannot believe it... I have tried everything from icd to NVIDIA Prime and forgot that env var.
You are awesome! Everything works correctly now and I have learnt so much! Thanks to everyone in this thread. You are all awesome!
