### ISSUE TITLE
God of War Ragnarok crashing on Arc GPU

### ISSUE THREAD

**Issue by exalented** [HansKristian-Work/vkd3d-proton#2133]
### Crash window:
![image](https://github.com/user-attachments/assets/365871cb-e2e3-4222-b29b-c155ca0fab7d)
The game pops a blank black window, then shortly after, crashes before getting to the menus.
### Software information
God of War Ragnarok
Tried installing vcrun2022 into bottle.
If I use DXVK+vkd3d-proton on Windows tge same behaviour happens. Without these technologies the game boots fine.
### System information
- **_No rebar accessible_**.
- Kernel: 6.10.10-arch1-1
- GPU: Sparkle Intel Arc A750 8GB
- Driver: Mesa 24.2.3-arch1.1
- Wine version: wine 9.18-1, UMU-Proton-9.0-2
- VKD3D-Proton version: 
```
$ vkd3d-compiler --version
vkd3d shader compiler version 1.11 using vkd3d-shader 1.11
..
multilib/lib32-vkd3d 1.11-1
extra/vkd3d 1.11-1
aur/vkd3d-proton-bin 2.13-1
```
### Environment:
- Sway 1.9/wlroots 0.18.1/Vulkan rendering backend/XWayland
- `VKD3D_CONFIG=dxr,force_static_cbv,single_queue,force_host_cached` (makes no difference)
`SteamDeck=1 %command%` (makes no difference)
### Log files:
Wine log:
[gowr.log](https://github.com/user-attachments/files/17122155/gowr.log)

**Comment by mbriar** [comment]
Have you tried `force_vk_vendor=-1` since the game supports XeSS? Either way most likely a driver bug.

**Comment by exalented** [comment]
I have. The application does the same thing.

**Comment by hammadnadeemx** [comment]
I have the exact same problem. I am running ubuntu 24.04 and use a radeon 7900xtx. Here is the lutris log. `crsLibraryPath: ./
wine: using kernel write watches, use_kernel_writewatch 1.
File 'C:\Program Files\God of War Ragnarok\/sl.common.dll' is signed by NVIDIA and the signature was verified.
File 'C:\Program Files\God of War Ragnarok\/sl.dlss.dll' is signed by NVIDIA and the signature was verified.
File 'C:\Program Files\God of War Ragnarok\/sl.dlss_g.dll' is signed by NVIDIA and the signature was verified.
File 'C:\Program Files\God of War Ragnarok\/sl.pcl.dll' is signed by NVIDIA and the signature was verified.
File 'C:\Program Files\God of War Ragnarok\/sl.reflex.dll' is signed by NVIDIA and the signature was verified.
3831.360:0110:0114:info:vkd3d-proton:vkd3d_instance_apply_application_workarounds: Program name: "GoWR.exe" (hash: c3138817688b3022)
3831.360:0110:0114:info:vkd3d-proton:vkd3d_instance_deduce_config_flags_from_environment: shader_cache is used, global_pipeline_cache is enforced.
3831.360:0110:0114:info:vkd3d-proton:vkd3d_config_flags_init_once: VKD3D_CONFIG=''.
3831.361:0110:0114:info:vkd3d-proton:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.12.0.
3831.361:0110:0114:info:vkd3d-proton:vkd3d_instance_init: vkd3d-proton - build: 7460c70de0dff08.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_memory_info_upload_hvv_memory_properties: Topology: No more than 1 device local heap, assuming ReBAR-style access. Using DEVICE_LOCAL | HOST_COHERENT for UPLOAD.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x218.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Enabling fast paths for advanced ExecuteIndirect() graphics and compute.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device supports VK_EXT_mutable_descriptor_type.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device supports ultra-fast path for descriptor copies.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_get_bindless_flags: Device supports packed metadata path for descriptor copies.
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
3831.404:0110:0114:info:vkd3d-proton:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
3831.405:0110:0114:info:vkd3d-proton:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_caps_init_feature_options1: TotalLaneCount = 6144, may be inaccurate.
3831.405:0110:0114:info:vkd3d-proton:d3d12_device_determine_ray_tracing_tier: DXR support enabled.
3831.405:0110:0114:info:vkd3d-proton:d3d12_device_determine_ray_tracing_tier: DXR 1.1 support enabled.
3831.405:0110:0114:info:vkd3d-proton:d3d12_device_caps_init_feature_level: DX Ultimate supported!
3831.405:0110:0114:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Remapping VKD3D_SHADER_CACHE to: vkd3d-proton.cache.
3831.405:0110:0114:info:vkd3d-proton:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x1c.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x31.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x35.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x21.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x22.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x1c.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x31.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x35.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x21.
3831.405:0110:0114:fixme:vkd3d-proton:d3d12_device_CheckFeatureSupport: Unhandled feature 0x22.
3831.406:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
3831.406:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
3831.406:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.153 ms.
3831.407:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.250 ms.
3831.407:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.021 ms.
3831.407:0110:0240:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
3831.407:0110:024c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.407:0110:024c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.412:0110:024c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.412:0110:024c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.476:0110:0114:fixme:vkd3d-proton:d3d12_command_queue_init: Ignoring flags 0x1.
3831.477:0110:0114:fixme:vkd3d-proton:d3d12_command_queue_init: Ignoring flags 0x1.
3831.521:0110:0114:info:vkd3d-proton:dxgi_vk_swap_chain_init: Creating swapchain (1920 x 1080), BufferCount = 3.
3831.521:0110:0114:info:vkd3d-proton:dxgi_vk_swap_chain_init_sync_objects: Enabling frame latency handles.
3831.521:0110:0114:info:vkd3d-proton:dxgi_vk_swap_chain_init_sync_objects: Ensure maximum latency of 3 frames with KHR_present_wait.
3831.522:0110:0114:info:vkd3d-proton:dxgi_vk_swap_chain_init_waiter_thread: Enabling present wait path for frame latency.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.527:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.528:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.529:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.529:0110:0114:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
3831.542:0110:0258:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.


!!!

Application Crashed here (0xc06d007e) :

g_StructuredData data_start 0x77adffd0 bytes_used 3075 max_size 65536
Initial process has exited (return code: 32256)
Monitored process exited.
Exit with return code 32256`

**Comment by hammadnadeemx** [comment]
Rune cracks dont work on Linux. You will have to use the original game files and some steam emu or the no psn mod. Have a look at the last post on this forum https://cs.rin.ru/forum/viewtopic.php?f=41&t=141113&start=30   
![image](https://github.com/user-attachments/assets/ef9cd3a6-5c5a-4242-bf4f-f48fef8c5665)

**Comment by maxchisto** [comment]
might be unrelated, but are you using i915 or xe driver?
Black Myth Wukong Benchmark doesn't start for me when on xe driver. could be the same problem.

**Comment by exalented** [comment]
Starting the game with the i915 driver vs the Xe driver yields the same results. https://www.kernel.org/doc/html//next/gpu/rfc/xe.html
