### ISSUE TITLE
Investigate possible regression in RE2 with standalone build on GTX 1060.

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#214]
Need to repro a black screen on 450.57 with GTX 1060 (unsure if Pascal specific, probably not) using standalone build.

**Comment by Joshua-Ashton** [comment]
Works fine for me on RTX 2060 Super in both Windowed and Fullscreen.

![image](https://user-images.githubusercontent.com/21316711/87844611-b127cc80-c8b6-11ea-901a-853c0ccc3f47.png)

**Comment by HansKristian-Work** [comment]
Yes, we were never able to reproduce any shenanigans, except for vertex buffer robustness behavior. Don't think this issue is valid anymore.
