### ISSUE TITLE
AC Valhalla doesn't run well with Nvidia exposed.

### ISSUE THREAD

**Issue by shelterx** [HansKristian-Work/vkd3d-proton#2148]
I'll leave it here in case anyone have any ideas.
AC Valhalla does not run smooth when Nvidia GPU is exposed.
Frametimes are higher, the FPS goes up and down and it's almost like it's skipping frames. This is especially noticeable in the benchmark.

PROTON_HIDE_NVIDIA_GPU=1 fixes all that. Not sure if the game selects a different render path or what's actually going on.
I have tried disabling VK_NV_raw_access_chains (is it even used with this game?) and dxvk-nvapi, but that did not change anything.

**Comment by doitsujin** [comment]
Does `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2` fix this too?

Reporting a different GPU doesn't really change what any of our code does, it's just going to be a game thing either way.

**Comment by robotman40** [comment]
> Disabling low latency extension did nothing. I also tried an older vkd3d version, did not change a thing either.
> 
> I think the game is just happy with AMD...... Which's fine, it solves the biggest issue with this game for me, why it was so inconsistent.

Even on Windows, this game runs better on AMD, so I guess the game uses a special codepath for Nvidia that is poorly optimized?

**Comment by shelterx** [comment]
Well, actually it does the same under Windows with vkd3d-proton. it's very inconsistent from what I remember. Under native DX12 it's flawless.

The 550.40.75 vulkan dev driver totally broke AC Valhalla (vertex explosions) but other games worked fine... so I don't know why it broke this specific game.

**Comment by shelterx** [comment]
I basically tried everything else there is to try. I guess it's the game itself. And spoofing AMD works, The game doesn't have any nvidia specific options anyway.

I've mentioned the workaround on the issue page for the game at Valve so other people can see it.

**Comment by shelterx** [comment]
I know I closed this but I remember from a while back when VK_KHR_present_wait was disabled for Nvidia GPUs, the game ran like absolute horseshit. I was told it shouldn't affect things having it disabled but it did, it caused even more stutter.
So I tried VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait today and indeed, the stutter got even worse and FPS was jumping around even more.

I also tried VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait in some other games and those seemed unaffected.

So I thought it might be related to VK_KHR_present_wait somehow, but then again, why does PROTON_HIDE_NVIDIA_GPU remove all stutter?

**Comment by shelterx** [comment]
FYI @doitsujin & @HansKristian-Work 
Something happened with the recent vkd3d-proton commits, game runs much better with Nvidia exposed now for some reason, the insane FPS jumping/frame skipping is gone.. I still feel like hiding Nvidia produces slighty better frametimes tho'.

Don't know if it was the upload heap changes or this https://github.com/HansKristian-Work/vkd3d-proton/commit/17aeb5c919c33acbce4e0c347a8b8a1286201ee5

I even had to go back and verify with the 2.13 release and that produces wonky results, latest git does not... but I don't think it was because of todays changes.

Keep up the good work!
