### ISSUE TITLE
vkd3d shader mode 6.6 very slow 

### ISSUE THREAD

**Issue by howdev** [HansKristian-Work/vkd3d-proton#2150]
remnant 2 can only run with shader model 6.6. Using 1080p FSR or Xess when first startup in the menu is 60fps. After game loaded it was 36fps, without moving, fps drops to 12fps and stayed there. I exit to the menu, and the menu also runs 20fps. something is wrong. so much errors in the log

I tried Everspace 2 using VKD3D_SHADER_MODEL=6_6 and same issue happens, very slow even with upscaling. I tried shader model 6_5 DX12 on Everspace 2 and runs well. I removed the launch options and Everspace 2 still runs well 40fps. 
### Software information
Remnant 2
### System information
- GPU:  GTX1650
- Driver: 550.107.02
- Proton version: 9.0-3
- VKD3D-Proton version: 2.13

### Log files
[steam-1282100.log](https://github.com/user-attachments/files/17264690/steam-1282100.log)

**Comment by doitsujin** [comment]
Shader Model 6.6 is required for Unreal Engine to use Nanite, so yeah, it's entirely expected that disabling that and only rendering low-detail geometry improves performance.

You're probably running out of VRAM on top of that, 4GB cards unfortunately aren't going to do as well on Linux as they would on Windows.

**Comment by mbriar** [comment]
> After game loaded it was 36fps, without moving, fps drops to 12fps and stayed there

Yes, this pretty much perfectly describes what happens when you run out of vram.

**Comment by howdev** [comment]
thank you, unfortunately, this is the case then.

**Comment by howdev** [comment]
this problem is caused by the driver. Many owners of 30 and 40 series with 6GB and 8GB VRAM had problems with many games when VRAM fills to near 100%. 
It is not caused by proton or vkd3d. so can close this issue.
