### ISSUE TITLE
Assasin's Creed Valhalla - logs spammed with Invalid plane index 0 for format 0.

### ISSUE THREAD

**Issue by Lifeismana** [HansKristian-Work/vkd3d-proton#2165]
PROTON_LOG=1 's logs are getting spammed with the following warning:
`warn:vkd3d-proton:vk_image_aspect_flags_from_d3d12: Invalid plane index 0 for format 0.`
a 1.5 hour game session made the log file 5GB, so i assume that warning is happening  on every frame

### Software information
Assasin's Creed Valhalla
It starts as soon as the game launches
Disabling ubisoft's overlay doesn't stop that, neither does disabling MangoHud 

Since that log spam doesn't happen with Skull & bones which uses the same engine, i'd assume this is a game specific issue

Game is launched with `PROTON_LOG=1 %command%`
### System information
- GPU: 2080
- Driver: 560.35.03
- Wine version: Proton experimental
- VKD3D-Proton version: 3452d126a8eb82fa3f59c3832016471a85f09b40 (according to proton's experimental_9.0 branch)

### Log files
(this isn't the 5GB log file)
[steam-2208920.zip](https://github.com/user-attachments/files/17423883/steam-2208920.zip)

**Comment by Zorrototo** [comment]
I just noticed the exact same issue with Hunt Showdown in Steam with Proton Experimental.
[steam-594650.tar.gz](https://github.com/user-attachments/files/17613166/steam-594650.tar.gz)

**Comment by doitsujin** [comment]
This is already fixed upstream.
