### ISSUE TITLE
AC:Valhalla GPUsage issues (latest DXvk/VKd3d builds).

### ISSUE THREAD

**Issue by gkoulou96** [HansKristian-Work/vkd3d-proton#2167]
I can launch the game on DX12 fine, when i switch to Vulkan in a futile effort to fix perf, i get "Unable to initialize graphics system. GPU does not support DX12.", on GTX 1080 @ 565.90. Any possible solutions?

**Comment by Blisto91** [comment]
You have to use dxvk's dxgi.dll (and maybe d3d11.dll) too.
fwiw vkd3d-proton does not work very well with the Pascal generation so you are not likely to get more performance.

**Comment by gkoulou96** [comment]
Managed to get it to work, but it freezes after loading screen with the character.

**Comment by Blisto91** [comment]
Try latest master i guess https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/11389632572

**Comment by gkoulou96** [comment]
I suspect GPU usage skyrockets and might just runs out of memory or sth, is there any workaround?

**Comment by Blisto91** [comment]
You could try making a file called `dxvk.conf` next to the exe and insert `dxgi.maxDeviceMemory = 4000` which would tell the game you only have 4GB of vram. Though the game might just ignore it or not be able to lower it anyway.

**Comment by gkoulou96** [comment]
The issue is persistent, i already limited my vram usage but it freezes no matter what

**Comment by shelterx** [comment]
The game runs better in DX12 aanyway so I don't really see the point in using vkd3d-proton in Windows.

**Comment by gkoulou96** [comment]
In DX12 it is very inconsistent and choppy, capped at 45fps (forcing gpusage) on vkd3d feels more stable but also almost unplayable. Odyssey @ 90fps in dxvk felt like butter.

**Comment by shelterx** [comment]
@gkoulou96 
Perhaps you can run MSI Afterburner or similar and see how much VRAM it uses...

**Comment by gkoulou96** [comment]
@shelterx 
It uses approx 4gb of VRAM, half of my 1080, how does that help in determining the problem and fixing it?

**Comment by shelterx** [comment]
@gkoulou96 lower graphics settings , how much does it use in dx12?

**Comment by gkoulou96** [comment]
Set everything on lowest settings and still, freezes all the time!

**Comment by gkoulou96** [comment]
Cpu usage is almost half, I run it on an add, it’s a gpu/driver/vkd issue.

**Comment by shelterx** [comment]
Yeah, well, vkd3d-proton, Nvidia and AC Valhalla isn't really a good match. However it's better now than it used to be with current master of vkd3d-proton, at least in Linux.
I've tried vkd3d-proton in Windows with AC Valhalla before and for me, DX12 is significantly better, that's why I keep telling you to use DX12 instead.
Also,I think @Blisto91 already answered your question too:
> fwiw vkd3d-proton does not work very well with the Pascal generation so you are not likely to get more performance.
