### ISSUE TITLE
Random graphical bugs in god of war ragnarok

### ISSUE THREAD

**Issue by hammadnadeemx** [HansKristian-Work/vkd3d-proton#2174]
High or low settings, I get these random white triangles of varying sizes that pop up in various places on screen. Higher graphical settings increases the frequency but it also happens in low settings. Its annoying and unplayable for me. When I open the logs from lutris, there is a recurring message:

260.316:00dc:028c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
274.572:00dc:022c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
275.229:00dc:028c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
275.580:00dc:022c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 45). It seems like application has stopped creating new PSOs for the time being.
276.573:00dc:028c:fixme:vkd3d-proton:d3d12_device_GetCustomHeapProperties: Unhandled heap type 0x5.
The effect worsens when tessellation is set to ultra. Lowering it reduces the frequency but its not correct. Any idea what is causing this ?

### Software information
God of war ragnarok updated to the latest version.

### System information
- GPU: AMD Radeon 7900xtx nitro+
- Driver: The version of radv that ships with ubuntu 24.04lts no changes to the system drivers (system updated)
- Wine version: Proton-ge-914
- VKD3D-Proton version: 2.13

### Log files
[gowrlog.txt](https://github.com/user-attachments/files/17530337/gowrlog.txt)

https://github.com/user-attachments/assets/101a1ce6-af92-484f-98e5-ce9814e932e8

**Comment by hammadnadeemx** [comment]
its visible in the menu where the random white reflections on the floor are more noticeable.

**Comment by doitsujin** [comment]
Can you try current master?

The error messages are harmless (but should also go away now since we do support GPU upload heaps now).

**Comment by runar-work** [comment]
It worked fine on Arch Mesa (24.2.5) and I could reproduce the glitchy terrain on 24.0.5, so I bisected it and found the fix in [this Mesa commit](https://gitlab.freedesktop.org/mesa/mesa/-/commit/21f8410191378165219b3dbd6374064fc18a625c). Turns out it's the same bug as this one https://github.com/HansKristian-Work/vkd3d-proton/issues/1982.

**Comment by hammadnadeem-aai** [comment]
So that means either wait for Mesa to be updated in Ubuntu or use a ppa to get a newer version ?

**Comment by runar-work** [comment]
Yeah, as long as you're on 24.1.3 or newer it should be fine.

**Comment by hammadnadeemx** [comment]
I have used a ppa to update mesa to the latest version and the glitch no longer happens ! Thanks for the feedback.
