### ISSUE TITLE
FSR3.1 Frame Generation Buggy.

### ISSUE THREAD

**Issue by artivision** [HansKristian-Work/vkd3d-proton#2175]
On all games that i tested like **The Last Of Us** or **Silent Hill 2** FG 100Fps is choppier than Native 60Fps. That is also present on Windows to but to much less degree. Different presentation modes, Freesync, Vsync, Compositors, don't help.

**Comment by mbriar** [comment]
Maybe because of https://gitlab.freedesktop.org/mesa/mesa/-/issues/11759

**Comment by doitsujin** [comment]
It's not buggy, there's nothing actionable in this issue so I'm going to close it.
