### ISSUE TITLE
Silent Hill 2 remake heavily stutters.

### ISSUE THREAD

**Issue by artivision** [HansKristian-Work/vkd3d-proton#2176]
Silent Hill 2 remake heavily stutters even at lowest settings, usually 50-80Fps but once per 10 seconds drops to 10Fps. Dxvk mode works correctly with 10% less performance overall.

**Comment by Blisto91** [comment]
Please fill out the issue template

**Comment by HansKristian-Work** [comment]
Getting really tired of extremely low signal-to-noise ratio on your issues. Learn to file issues before you spam repositories.
