### ISSUE TITLE
Red Dead Redemption 1: Framerate issues on cutscenes

### ISSUE THREAD

**Issue by Faugus** [HansKristian-Work/vkd3d-proton#2178]
The framerate during gameplay is perfectly fine, but during cutscenes is stuttery and unstable.
Here's a video: https://youtu.be/T8AN4rGZVZo
- I also tested on Windows and it's flawless, so it's not a problem with the game.
- I tried different kernel versions, like 6.11.5, 6.10.7 and CachyOS Kernel 6.11.5-3, which comes with power management patches to fix https://gitlab.freedesktop.org/drm/amd/-/issues/3618#note_2625963.
- I tried Proton 9, Proton Experimental and GE-Proton 9-16.

Ryzen 7 5700X3D / Radeon RX 7900 XT
Arch Linux
Mesa 24.2.5-1
Proton 9.0-3, Proton Experimental, GE-Proton 8-16

Log: [steam-0.log](https://github.com/user-attachments/files/17563844/steam-0.log)

**Comment by Faugus** [comment]
Update:

Setting `VKD3D_CONFIG=no_upload_hvv` fixes the issue.

**Comment by Leopard1907** [comment]
That env var also works for me.

7900xtx, Mesa stable.

**Comment by shelterx** [comment]
Works for Nvidia too, RTX 4070
