### ISSUE TITLE
Ashes of Creation Alpha 2 

### ISSUE THREAD

**Issue by DrAcePhD** [HansKristian-Work/vkd3d-proton#2186]
I am attempting to get Ashes of Creaiton running on Linux. The game is currently in its second Alpha cycle and does not currently have native linux support, and I don't think it's a high priority for the devs right now. I first tried to install the game using lutris because I have found that it is easier to manage the runners and all the Vulkan options that way, but I couldn't get it to work. I could get the launcher to install and then launch the game but I kept running into the same problem described in the attached logs when i tried to launch the game - the game would launch and I would get audio (the menu music) but it would fail trying to connect to the game servers. Lutris would get to this point without thinking the game had been installed so it forced my to abort the install and delete all the files whenever I tried to close it

I was able to install the launcher in my .wine prefix using winetricks and the launcher mostly works - the authentication pop-out window isn't rendering properly but it functions perfectly so I can still log in and launch the game. When the game launches it does the same thing I describe above. I'm still very new to linux but reading the logs it seems the issues it _somehow_ related to vkd3d/Vulkan but I have no idea beyond that. Any help would be appreciated

### Software information
- Game: Ashes of Creation Alpha 2

### System information
- OS: Nobara 40 (GNOME Edition) x86_64
- GPU: NVIDIA GeForce RTX 4090
- Driver: 565.57.01
- Wine version: WineHQ Staging (9.20 (Staging))
- VKD3D-Proton version: vkd3d-proton-2.13

### Logs
[logs.txt](https://github.com/user-attachments/files/17607097/logs.txt)

**Comment by mbriar** [comment]
I don't see anything in the logs that indicates a problem on the vkd3d-proton side. And it seems like the main issue is the game not connecting to it's online servers? That's definitely unrelated to vkd3d-proton.

**Comment by Blisto91** [comment]
Ijuwt to clarify the issue this is about is with the launcher right not the actual game?

During my own messing around with getting it running on Linux I've found that while using dxvk with the launcher it renders properly if I set `d3d9.deferSurfaceCreation = True` so would be nice if you could confirm that.
To do it make a file called `dxvk.conf` next to the launcher exe and insert it.
Alternatively you can set it with an environment variable DXVK_CONFIG=`d3d9.deferSurfaceCreation = True`

**Comment by DrAcePhD** [comment]
> Just to clarify the issue this is about is with the launcher right not the actual game?
> 
> During my own messing around with getting it running on Linux I've found that while using dxvk with the launcher it renders properly if I set `d3d9.deferSurfaceCreation = True` so would be nice if you could confirm that. To do it make a file called `dxvk.conf` next to the launcher exe and insert it. Alternatively you can set it with an environment variable `DXVK_CONFIG="d3d9.deferSurfaceCreation = True"`

No, my issue is that when I get the game to launch it gives me the connecting wheel over the main menu for a minute or two then says "Pending Service Connection. Code:32"

There are a few reasons I think this is related to vkd3d. First, people in the main Ashes of Creation discord server reported this error as being related to DirectX 12 issues. Second in the logs the error that occurs when I get to this point is "fixme:vkd3d-proton:vk_samples_from_dxgi_sample_desc: Unhandled sample count 0." And it repeats this a few times until it eventually says "info:vkd3d-proton:vkd3d_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 15). It seems like application stopped creating new PSOs for the time being."

I am super out of my depth so I could very well be totally off the mark but to me that looks like _something_ is up with vkd3d.

I will try to change the dxvk config stuff like you said to see if that fixes the (seperate) issues I've had with the launcher & report back - right now the only thing that isn't working in the launcher is the authentication pop-out window, and it works - just the windows isn't showing anything. I can still hover the cursor to find the text fields and input login info blind and it works that way

**Comment by DrAcePhD** [comment]
I was replying on my phone and hit the wrong button

**Comment by mbriar** [comment]
Those vkd3d-proton log messages are harmless.

**Comment by Blisto91** [comment]
Yes they should be fine. I very much doubt vkd3d-proton is involved in the error.
I haven't even been able to get past the launcher login yet. Will probably do a quick test on Windows later.
Note that it could be very likely that they haven't enabled EAC support on Linux.

**Comment by DrAcePhD** [comment]
So you think it might just be EAC preventing the connection?

**Comment by Blisto91** [comment]
Don't know no. Also i don't know if that is actually the case. Could just be a Wine issue

**Comment by DrAcePhD** [comment]
I'm being told the code that pops up when the connection fails means that a driver or service for a driver has failed, unclear if this would include DirectX

**Comment by DrAcePhD** [comment]
The people in the AoC alpha 2 bugs/issues channel seem convinced that the issues is between DirectX 12 and UE5 but couldn't get more specific than that. This seems like something we should be able to drill down on by sifting through the logs but I am extremely out of my depth here. Is there something specific I could look for in the logs to try and narrow down the issue/confirm that this isn't a vkd3d issue?

**Comment by Blisto91** [comment]
Dunno. I believe i am the only person affiliated with the team (tester not a dev) that even have access and i haven't been able to log in let alone install the actual game yet on Linux.

**Comment by DrAcePhD** [comment]
I'm a tester as well. If this isn't a vkd3d issue I feel like I should close this thread but @Blisto91 if you want to get into the weeds, find me out of the AoC discord server and send me a DM. I was able to log in and install and I'd love to see if you get the same issue I'm having
