### ISSUE TITLE
vkd3dhud

### ISSUE THREAD

**Issue by qemuduewr** [HansKristian-Work/vkd3d-proton#2198]
Is it possible to make vkd3dhud for displaying the frame rate?Although there is MangoHUD, it is more troublesome to deploy separately, and some display FPS software will occupy a part of the system resources

**Comment by Blisto91** [comment]
Hi there. 
It is an idea that the devs aren't opposed to do at some point, but it haven't been a priority so far.

See also https://github.com/HansKristian-Work/vkd3d-proton/issues/346
