### ISSUE TITLE
Pascal and VKD3D

### ISSUE THREAD

**Issue by Tiagoquix** [HansKristian-Work/vkd3d-proton#2208]
It's no secret that NVIDIA Pascal cards don't perform very well with VKD3D. While they perform somewhat OK on DX12 on Windows, the same can't be said about VKD3D.

I personally own one and can attest that games tend to crash every so often due to (apparently) VRAM management not being so good, resulting in the graphics card making the game crash.

With this I mind, I was thinking:
Would it be feasible to somehow "redirect"/fall back DX12 to DX11 whenever possible in the scope of both DXVK and VKD3D? Or, at least, give a warning about performance issues in an user-friendly way such as an auto-generated log when a Pascal card is detected?

Currently, users with Pascal cards facing problems with DX12 that don't know the specifics of Proton and all of its components (dxvk, wine, vkd3d etc.) may assume their PC isn't capable of running a specific game, when, in reality, the problem is the graphics card not handling DX12 very well.

Thanks for your attention.

**Comment by K0bin** [comment]
> Would it be feasible to somehow "redirect"/fall back DX12 to DX11 whenever possible in the scope of both DXVK and VKD3D?

No, that's not possible. The only thing you could do is report that the system does not support D3D12 and pray that this makes the game fall back to D3D11 but that is obviously a terrible workaround that just breaks games.

**Comment by HansKristian-Work** [comment]
> is the log file to be generated next to the game executable

no-one is going to read that unless they already know what to look for.

There isn't anything meaningful we can do here other than educating the user base.

**Comment by gabriele2000** [comment]
> on-screen warning for compiling shaders.

It can be enabled though, it's there.
Personally I enabled it globally, it's very useful.

**Comment by K0bin** [comment]
> It can be enabled though, it's there.

Only for DXVK, not for vkd3d-Proton.
