### ISSUE TITLE
Snow Plowing Simulator Slows, Freezes, and Crashes on Steam Deck

### ISSUE THREAD

**Issue by codeweaverwill** [HansKristian-Work/vkd3d-proton#2210]
Snow Plowing Simulator slows the Deck to a crawl during initial loading, briefly utilizing 100% GPU, before eventually crashing. This does not occur on my desktop (AMD, Arch, KDE/X11) or ROG Ally (AMD Ryzen Z1 Extreme, Windows 10).

### Software information
Snow Plow Simulator, default settings

### System information
Steam Deck OLED
- GPU: Steam Deck APU
- Driver: Mesa 24.0.5 (git-6c30d44613)
- Wine version: Proton experimental-bleeding-edge-9.0-134748-20241112-p6d92d3-w680d20-d8dc1fe-v816509
- VKD3D-Proton version: 8165096

### Log files
Log attached with +dxgi and VDK3D_DEBUG=trace
[steam-2096030.log](https://github.com/user-attachments/files/17739304/steam-2096030.log)

Relevant section:
```
radv/amdgpu: Not enough memory for command submission.
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
```

Crash error message from in game attached (likely unhelpful)
![gamescope_012](https://github.com/user-attachments/assets/72da8d13-039c-48d6-91c7-dcd918fde59d)

**Comment by doitsujin** [comment]
Not seeing anything DXVK related in the log like your quote would suggest, but this sounds like Deck just runs out of memory? Should be visible in the performance metrics.

**Comment by Blisto91** [comment]
```
radv/amdgpu: Not enough memory for command submission.
25053.272:012c:01e4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
25053.274:012c:01e4:warn:vkd3d-proton:d3d12_device_mark_as_removed: Device 000000000f940080 is lost (reason 0x887a0005, "VK_ERROR_DEVICE_LOST").
25053.274:012c:01e0:err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
```

**Comment by doitsujin** [comment]
Yeh that's what I'm referring to. Can't really do much if the game just exhausts memory to the point where we can't even queue up a GPU submission.

**Comment by codeweaverwill** [comment]
This seems to be confirmed as a general game memory issue with this game and some others. Thank you and apologies.
