### ISSUE TITLE
Cyberpunk 2077 performance is reduced since commit bcfc25c9

### ISSUE THREAD

**Issue by Sporif** [HansKristian-Work/vkd3d-proton#2215]
Cyberpunk 2077 performance is reduced, especially during holocalls. 

Toggling the MangoHud overlay on during holocalls seems to increase the fps somewhat (but performance is still not at the expected level).

The commit that caused this issue is [bcfc25c9](https://github.com/HansKristian-Work/vkd3d-proton/commit/bcfc25c90aff70a9f6ed2299231d1105fdec4b71).

### Software information
Cyberpunk 2077, run with these [graphics settings](https://imgur.com/a/Duj0e9C). I also have gamescope, ReShade, and MangoHud enabled but the issue still exists with all of them disabled.
 
### System information
- GPU: AMD RX 7900 XTX
- Driver: Mesa 24.2.7
- Wine version: Proton 9.0-3
- VKD3D-Proton version: 2.13.r92.gcf34c0bd
- Distribution: Arch Linux
- Kernel: 6.11.8-1-custom

### Log files
[steam-14489251341945274368.log](https://github.com/user-attachments/files/17787588/steam-14489251341945274368.log)

These are performance logs taken using MangoHud with a holocall initiated in the middle of the run. You can see that the affected commit causes a drop in performance overall, but a severe drop during the holocall.

[cf34c0bd](https://github.com/HansKristian-Work/vkd3d-proton/commit/cf34c0bd47ffcee6aa4a49168ebb47936bbb3f9c): [Cyberpunk2077_2024-11-14_19-35-45.csv](https://github.com/user-attachments/files/17787591/Cyberpunk2077_2024-11-14_19-35-45.csv)
[bcfc25c9](https://github.com/HansKristian-Work/vkd3d-proton/commit/bcfc25c90aff70a9f6ed2299231d1105fdec4b71): [Cyberpunk2077_2024-11-14_19-40-33.csv](https://github.com/user-attachments/files/17787592/Cyberpunk2077_2024-11-14_19-40-33.csv)

**Comment by doitsujin** [comment]
What is holocall?

Is there a way to visualize the CSV files or get any useful numbers out of them? What kind of performance delta are we talking about?

**Comment by mbriar** [comment]
> Is there a way to visualize the CSV files

![cp1](https://github.com/user-attachments/assets/fc1f4899-831c-4ed6-aa82-46b7f0adc07c)

**Comment by doitsujin** [comment]
Need a **fast** way to repro in game then.

**Comment by Sporif** [comment]
[Call](https://www.ign.com/wikis/cyberpunk-2077/How_to_Call_Someone) any contact (they have to actually answer the phone). Usually one of the [fixers](https://cyberpunk.fandom.com/wiki/Fixer#Notable_Fixers_in_the_2070s) will do.

**Comment by Blisto91** [comment]
Savegame where you have to do a holocall as soon as you load in for quick reproduction:
[Cyberpunk holocall.tar.gz](https://github.com/user-attachments/files/17800840/Cyberpunk.holocall.tar.gz)
Extract in to `compatdata/1091500/pfx/drive_c/users/steamuser/Saved Games/CD Projekt Red/Cyberpunk 2077/`

**Comment by doitsujin** [comment]
Can't reproduce with the savegame above, in both cases it's sitting at pretty much exactly 100 FPS when starting the call, tad more without the call.

**Comment by doitsujin** [comment]
Can reproduce now, but only when starting a new game with raytracing enabled.

**Comment by HansKristian-Work** [comment]
This seems related to a kernel performance bug on amdgpu. Guess we'll have to find a workaround ...

**Comment by HansKristian-Work** [comment]
This should be fixed now on master.

**Comment by Sporif** [comment]
Yes, it's fixed. Thanks!
