### ISSUE TITLE
How can I use the DLLs compiled from vkd3d-proton in Wine?

### ISSUE THREAD

**Issue by baikaishiuc** [HansKristian-Work/vkd3d-proton#2219]
I am a beginner with Wine and currently using it to run Photoshop 23.

I noticed that vkd3d seems to lack support for Tiled Resource, which causes
Photoshop’s compatibility check to fail in displaying the correct GPU
information.

I found that vkd3d-proton appears to implement this feature, so I compiled
vkd3d-proton and copied the resulting d3d12.dll and d3d12core.dll directly
into Wine’s directory. I also ensured that the required d3d12.dll was
loaded correctly.

However, when launching Photoshop, it crashes when using certain swapchain
features.

Setting aside the swapchain crash for now, is my approach of directly using
the d3d12.dll generated by vkd3d-proton correct?

Do I need to copy dxgi.dll from DXVK as well to work with vkd3d-proton?

**Comment by Blisto91** [comment]
Hi there.
Yes vkd3d-proton is dependent on the dxgi.dll that dxvk provides so that also needs to be used.

**Comment by baikaishiuc** [comment]
> Hi there. Yes vkd3d-proton is dependent on the dxgi.dll that dxvk provides so that also needs to be used.

Yeah, thank you , it now work.

There are other crashes, but they seem to be seperate issue.
