### ISSUE TITLE
Extreme amount of visual artifacts in Helldivers 2

### ISSUE THREAD

**Issue by obj-obj** [HansKristian-Work/vkd3d-proton#2223]
Most of the time when launching Helldivers 2, there are a ton of visual artifacts. What's weird is that these artifacts are different every time the game is launched, and sometimes the game will launch without any visual artifacts at all.

![image](https://github.com/user-attachments/assets/a11821ab-9a33-4a79-9e73-c915589bd710)
![image](https://github.com/user-attachments/assets/a7e2c69a-95fa-4e04-a40d-8d56da7da7ea)
![image](https://github.com/user-attachments/assets/7d92a516-5d2b-4b8f-b8b5-7ee63131633a)
![image](https://github.com/user-attachments/assets/174be8aa-ddd9-41cb-a75d-168d90fbcec7)
![image](https://github.com/user-attachments/assets/00ef390f-1166-43c7-8231-87cdfe840957)

### System information
- GPU: 7900 GRE
- Driver: AMDGPU / Mesa
- Wine version: Proton Experimental
- VKD3D-Proton version: Whatever is in experimental right now (don't know the exact version)

### Log files
[steam-553850.log](https://github.com/user-attachments/files/17883537/steam-553850.log)

**Comment by HansKristian-Work** [comment]
This seems to be a kernel bug. Which kernel version are you on?

**Comment by HansKristian-Work** [comment]
Do you have a PRIME setup somehow? Is there an iGPU in your system as well?

**Comment by obj-obj** [comment]
> This seems to be a kernel bug. Which kernel version are you on? EDIT: 6.11 from the log.

Just tested after updating to 6.12.1, and the issue seems to be gone. Maybe it was fixed in the kernel?

**Comment by HansKristian-Work** [comment]
No, we just implemented a workaround. The kernel bug doesn't always reproduce.

**Comment by GrabbenD** [comment]
> The kernel bug doesn't always reproduce.å

Is Clear Page Tracking [regression](https://gitlab.freedesktop.org/drm/amd/-/issues/2419#note_2564732) being tracked anywhere?

**Comment by Billli11** [comment]
@GrabbenD https://gitlab.freedesktop.org/drm/amd/-/issues/3812

**Comment by GrabbenD** [comment]
Patch for upstream VRAM cleaning regression is available but needs testing:

https://gitlab.freedesktop.org/drm/amd/-/issues/3812#note_2792626

Note when testing this, make sure to use either the stable release of `vkd3d` or rollback the current `-git` workaround from: [vkd3d-proton#3b94153](https://github.com/HansKristian-Work/vkd3d-proton/commit/3b941536c1e7dd11861d995df45d1d7f7d338966)
