### ISSUE TITLE
Star Wars: Battlefront II (2017) UI Corruption

### ISSUE THREAD

**Issue by jkrhu** [HansKristian-Work/vkd3d-proton#2244]
The game UI elements exhibit corruption when playing in DX12.
![SWBFUI](https://github.com/user-attachments/assets/3d62b10b-27b4-4146-a619-3a1fab3d7168)
Here's a video for you - https://youtu.be/VgEkuxkny7E?si=LUOnRZ2ZeauVLgyZ
### Software information
Star Wars: Battlefront II, High settings, DX12

### System information
- GPU: RTX 3060
- Driver: 565.57.01
- Wine version: 1732205522 experimental-9.0-20241121b
- VKD3D-Proton version: vkd3d-proton 2.14.0 - build: 657f81b0f6da25f

### Log files

[SWBFII-VKD3DLOG.txt](https://github.com/user-attachments/files/18014173/SWBFII-VKD3DLOG.txt)
[SWBFII-PROTONLOG.txt](https://github.com/user-attachments/files/18014174/SWBFII-PROTONLOG.txt)

**Comment by Blisto91** [comment]
Hi there and thank you for the issue.

I took a look at this and it appears to be a game bug. I can make it happen the same on native Windows.
There seems to be some alt-tab shenanigans going on as i can make the issue go away by doing a quick alt-tab out and in. Ditto it is also a way to make it happen again after that.

**Comment by jkrhu** [comment]
I appreciate you taking the time to test this Blisto! I've noticed usually the HUD elements or menu will glitch out and thats not that annoying or noticeable most of the time, but these scope overlays are bugged as hell. I think we can close this as it's not a vkd3d-proton bug.
