### ISSUE TITLE
Tessellation shaders not translated correctly (DXBC)

### ISSUE THREAD

**Issue by alexfs** [HansKristian-Work/vkd3d-proton#227]
When a hull shader (DXBC) contains CLIP_DISTANCE and CULL_DISTANCE parameters in the input signature, the generated SPIRV is incorrect.
Getting the following crash with Intel Mesa drivers:
./src/compiler/nir/nir_lower_clip_cull_distance_arrays.c:54: get_unwrapped_array_length: Assertion `glsl_type_is_array(type)' failed.

My assumption that clip and cull vars are not translated as an array type?

**Comment by doitsujin** [comment]
Can you *please* give us a test case to reproduce all the different issues you're encouterning with?

**Comment by alexfs** [comment]
Binary DXBC is attached. It might be looking a bit weird because the container DXBC was reconstructed from the SHDR code section and input/output signatures provided by the windows driver APIs. Obviously for that particular reason I don't have the shader source code.

[hull.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/4995815/hull.zip)

**Comment by Joshua-Ashton** [comment]
Bit late in looking into this, but what was attached wasn't valid DXBC.
