### ISSUE TITLE
Bad memory leak

### ISSUE THREAD

**Issue by alexfs** [HansKristian-Work/vkd3d-proton#248]
To reproduce: 
1. Run demos/gears
2. Download memory monitor script from here: [https://raw.githubusercontent.com/pixelb/ps_mem/master/ps_mem.py](url)
3. Run memory monitor: 
sudo ps_mem.py -w 1 -t -p `pidof gears`
4. Observe memory goes up every tick

Bad commit: 2e0ce6a

**Comment by doitsujin** [comment]
What exactly is the problem? Memory usage stays the same with latest `master` for me.

**Comment by alexfs** [comment]
Well, In my project the host literally runs out of memory in less than half an hour. I managed to reproduce this memory leak just by running gears sample, memory usage increases on every render frame loop. The leak might be related to my driver or hardware combination (Intel / Mesa 20.1.5), vulkaninfo attached. By reverting the patch memory usage stays stable.
[vulkaninfo.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/5086407/vulkaninfo.zip)

**Comment by doitsujin** [comment]
I haven't tested this on Intel (we can't support ANV at the moment anyway), but it works fine on AMD (both RADV and proprietary) and Nvidia.

**Comment by Blisto91** [comment]
@alexfs Friendly ping. Is this still an issue? 🙂

**Comment by macos-fuse-t** [comment]
Nope, you can close this
