### ISSUE TITLE
World of Warcraft - Shadowlands/PTR

### ISSUE THREAD

**Issue by SveSop** [HansKristian-Work/vkd3d-proton#252]
It seems as WoW ptr (9.0.x) works if you use wine-staging-5.15 (or possibly 5.14) patched with your D3D12 patches and compile it having mingw-w64 (as per winehq recommendation i guess).

vkd3d also works fine, or atleast aswell as it does on live.

Is there plans on implementing raytracing for RTX cards or its like? I think i saw you had a raytracing branch here tho.

The WoW logs sais this:
```
8/22 17:05:10.049  Choosing gpu by name: "NVIDIA GeForce RTX 2070"
8/22 17:05:10.049  D3d12 Device Create
8/22 17:05:10.101  DXGI_FORMAT_B8G8R8A8_UNORM UAV support: false
8/22 17:05:10.101  Ray Tracing Support: None
8/22 17:05:10.101  Variable Rate Shading Supported: false
8/22 17:05:10.532  NotifyOnDeviceCreate
8/22 17:05:10.556  D3d12 Device Create Successful
8/22 17:05:10.556  <IsGPUDriverOutOfDate> No
```
I kinda thought `DXGI_FORMAT_B8G8R8A8_UNORM` was supported? But maybe not "UAV" :)

PS. Interested in testing experimental branches if you want me to.

**Comment by doitsujin** [comment]
> Is there plans on implementing raytracing for RTX cards or its like?

https://github.com/HansKristian-Work/vkd3d-proton/issues/154

**Comment by SveSop** [comment]
Hmm.. Seems to be "enabled" with nVidia drivers for Win10 with my GTX970 card tho.. (452.06 driver)
Windows 10 gx.log:
```
8/24 16:23:38.611  Choosing gpu by name: "NVIDIA GeForce GTX 970"
8/24 16:23:38.611  D3d12 Device Create
8/24 16:23:38.781  DXGI_FORMAT_B8G8R8A8_UNORM UAV support: true
8/24 16:23:38.781  Ray Tracing Support: None
8/24 16:23:38.781  Variable Rate Shading Supported: false
8/24 16:23:39.266  NotifyOnDeviceCreate
8/24 16:23:39.266  D3d12 Device Create Successful
8/24 16:23:39.266  <IsGPUDriverOutOfDate> No
```
Wine + dxvk 1.7.1 (dxvk's dxgi without vkd3d d3d12) running D3D11
gx.log
```
8/24 16:43:20.332  Choosing gpu by name: "GeForce RTX 2070"
8/24 16:43:20.783  NotifyOnDeviceCreate
8/24 16:43:20.817  Dx11 Device Create Successful
8/24 16:43:20.817  <IsGPUDriverOutOfDate> No
```

Maybe just some weird reporting from WoW? Or.. nVidia up to their usual antics of unsupported stuff :)

**Comment by doitsujin** [comment]
VKD3D explicitly disables UAV support for this particular format even if the Vulkan driver supports it (which Nvidia's does).

It's quite possible that the MSDN docs are just wrong or out of date, wouldn't be the first time, but it's optional anyway so right now there's no good reason to change it.
