### ISSUE TITLE
Resident Evil 2 hangs

### ISSUE THREAD

**Issue by K0bin** [HansKristian-Work/vkd3d-proton#259]
Resident Evil 2 has a tendency to freeze up at (unfortunately) seemingly random points.

It's not a CPU side deadlock, I'm getting DEVICE_LOST errors:

```
err:vkd3d_wait_for_gpu_timeline_semaphores: Failed to wait for Vulkan timeline semaphores, vr -4.
err:d3d12_swapchain_queue_present: Failed to blit swapchain buffer, vr -4.
err:d3d12_swapchain_present: Failed to queue present, vr -4.
err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
```

At first, it looked like it was related to those puzzles:
![grafik](https://user-images.githubusercontent.com/1131720/91575277-a6496880-e947-11ea-9e2d-4cca49e9f28f.png)
That weird triangle only showed up when it started freezing and wasn't there before. 

But then after restarting those worked fine and the game just hung up without doing anything or while being in the inventory.

Additionally, the key is completely white when examining it in the inventory:
![grafik](https://user-images.githubusercontent.com/1131720/91576096-e9a3d700-e947-11ea-95df-1c7395b2216e.png)

Here's my saves: https://drive.google.com/file/d/1c33aKonn1UbFbBiXA9shhMoR1F-LAL3h/view?usp=sharing
I've managed to reproduce it with the Leon save that has a save count of 4. That save also has the white key in the inventory. It unfortunately seems to take some running around to trigger the issue for me.

Windows, Nvidia GTX 1070, driver 451.98, VKD3D: 630b70cbbda51e9f324c7e5d1bc71019c0a6fe83

Here's the output of running the game with validation layers:
https://drive.google.com/file/d/1iY_8hec9gUyKcia7AnOxDlF8kIstM6XU/view?usp=sharing
Note that I didnt manage to reproduce the hang while writing the validation errors to a file. I did another run with the validation layers and managed to get a hang but didnt get any validation error that wasn't in that log file anyway.

* It seems to violate a bunch of PipelineLayout limits.
* There's an issue with barriers (it expects VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL so probably doing a transfer command).
Appears to come from the swapchain blit.
* It exceeds the allocation limit.
* When exiting the game it destroys a semaphore that's still being used.

I realize this is next to impossible to debug, I'm just opening this so it doesn't get lost.

**Comment by RoyShapiro** [comment]
I can add, that in my case all the items are displayed incorrectly (glitchy texture \ wrong shader) when Examined in the inventory, but do not have the problem when equipped by a character, if they can be so equipped (e.g. weapons).
Also when looking at the models in the Extras menu after completing the game, the same models (weapons, e.t.c.) also have the same glitch. Some of the monsters, Birkin in his final form, for example, also seem to be Partially affected, as the train carriage he is in, which is part of his model, seems to have bogus glitchy textures, exhibiting the same general behavior.

I also have the same problem with random freezes.

Windows 8.1, Nvidia RTX 2070, 451.67 (Yes, I know, I should've tested on Linux!)

**Comment by mixalis1987** [comment]
Same issue with me. I can freez just before the main menu loads and the objects like the key or bullets can be plain white like the picture, or in the case of green plants they can just be a garbled mess.

**Comment by K0bin** [comment]
The hangs are caused by running out of device memory because the game never stops creating buffer views.

As to the incorrect texturing when examining items, that's fixed by my PR #263.

**Comment by RoyShapiro** [comment]
@K0bin Thank you so much! Not only does this fix the RE2 inventory completely, it also seems to fix most of the disappearing object issues in Horizon Zero Dawn! The thing appears playable now! You're a hero!

**Comment by doitsujin** [comment]
Closing since the PR has been merged.

**Comment by K0bin** [comment]
I basically reported two problems in this issue and only the broken rendering is fixed. The game does still hang.

**Comment by HansKristian-Work** [comment]
I made a more focused issue https://github.com/HansKristian-Work/vkd3d-proton/issues/266, leaving this closed.
