### ISSUE TITLE
RE2: VkBufferView creation can overflow available memory

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#266]
The hashmap approach has some flaws if apps create objects which cannot be reused. See https://github.com/HansKristian-Work/vkd3d-proton/issues/259

**Comment by K0bin** [comment]
Here's the kind of buffer views that cause the problems in RE2:
`create buffer view dxgi format: 0, structure stride: 4, element size: 4, size: 96, offset: 0 flags: 0` (logged in 
`vkd3d_create_buffer_view_for_resource`)

**Comment by fsyy** [comment]
in this thread they say this patch is the cause for crashing Horizon Zero Dawn every 10-20 minutes

https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-691735117
https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-691812754

didn't try it myself but wanted to mention it here.

**Comment by RoyShapiro** [comment]
Here to confirm that reverting the following commits:

daf9f5c69fb69ab87672e61ee6c71ec2fb16d218
5a9d132b20de854f751d4c606c9546e6c34f5c4c
73d578e5abe5658bd8f9cca330a2f7a8f48e0465
684c658e22930f3f77488f77afb590d6889920a4

as suggested by @intersectRaven in the comment linked in the previous post has allowed me to progress much further in Resident Evil 2's The 4th Survivor mode, specifically to the point where I was genuinely defeated by the enemies and then manually quit the game successfully. That is, I did not encounter the freeze we are discussing here. Previously (without reverting the commits) I could reliably reproduce the freeze every time within 5-7 minutes of gameplay at max.

I did, however, notice, that during gameplay the fps has steadily decreased from around 50 fps in the main menu on launch to around 30 fps in the main menu when I quit after gameplay.

**Comment by RoyShapiro** [comment]
@Emanem recently did an analysis of this issue, it may help: https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-713530577
Also, I've tried compiling with SSBO enabled, both the WIP and the current master, and in RE2 I get the same, visualy, kind of crash as I did before, only _faster_. The framerate has also suffered significantly (lost about 15-20 fps compared to non-SSBO version), and, in the WIP version (https://github.com/HansKristian-Work/vkd3d-proton/pull/298) , I was getting objects, including parts of the level, appearing and disappearing out of view at odd angles.
Running Nvidia, driver version _452.06_ (so, not the latest & greatest).

**Comment by doitsujin** [comment]
Do note that the SSBO path is (and has always been) effectively disabled on Nvidia GPUs due to driver/hardware limitations.

**Comment by RoyShapiro** [comment]
@doitsujin Thank you for the information!
The GPU used is specifically an Asus DUAL-RTX2070-8G, in non-SSBO builds I used to get ~51fps in cutscenes (intro to the 4th survivor of Re2) and ~29-~45 fps during gameplay. With SSBO I get ~40 fps in the same cutscene and ~21-27 fps during gameplay, with occasional drops below 20. Everything else, besides vkd3d build version is the same for both tests.
Specific game settings attached in case they are somehow useful: [re2_config.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/5426751/re2_config.zip)

> ...is effectively disabled on Nvidia GPUs right now due to driver/hardware limitations ... We are already working on a proper solution that can deal with broken games, but these things take time.

Thanks, good to know!
_On the side note, it's funny how Nvidia drivers seem to be causing issues these days, I'm far more used to having issues with AMD drivers ever since it was still ATI._

**Comment by Emanem** [comment]
@doitsujin Thanks for the feedback - out of curiosity, did I get it right that in case of H:ZD with the cache we are exhausting resources on the driver side?
If this is the issue, how do you guys plant to tackle it? Really curious from a technical perspective.

@RoyShapiro True - Nvidia used to have better drivers with more resilient functionality, now it appears that these days such drivers are not great...

**Comment by doitsujin** [comment]
> If this is the issue, how do you guys plant to tackle it? Really curious from a technical perspective.

Basically we'll have to enable SSBOs for everyone, but implement indexing and bound checking manually in order to deal with alignment issues. It's a pain in the arse, but that's the only way to avoid creating buffer views like crazy.

**Comment by doitsujin** [comment]
Haven't tested RE2/3 yet, but https://github.com/doitsujin/vkd3d/tree/offset-buffers should (in theory) work.
