### ISSUE TITLE
A Wine build failure with vkd3d-proton lib integration enabled.

### ISSUE THREAD

**Issue by Kerrung** [HansKristian-Work/vkd3d-proton#301]
It started since the official VKD3D 1.2 version was added to the Wine upstream. See here: https://github.com/Frogging-Family/wine-tkg-git/issues/176

**Comment by Tk-Glitch** [comment]
Upstream Wine is not compatible anymore and will not be compatible again with vkd3d-proton, as already explained in the issue you linked. You need to uninstall your vkd3d-proton packages and use vkd3d-proton standalone or upstream vkd3d (non-proton).

**Comment by SveSop** [comment]
Or, what i kind of prefer myself - Use upstream-vkd3d (non-proton) as linux lib -> Build wine (whatever version) -> Build standalone vkd3d-proton -> Use standalone vkd3d-proton as a drop-in replacement with override in your game's wineprefix.

Will then work just the same as DXVK does 👍

**Comment by HansKristian-Work** [comment]
We've renamed so files so conflicts cannot happen. Linking directly against Wine in build type is not supported, although swapping so files might work, although keep in mind it is not officially supported.
