### ISSUE TITLE
fedora 32 compilation failed

### ISSUE THREAD

**Issue by tuxtergames** [HansKristian-Work/vkd3d-proton#312]
Hi folks,
Anyone here there's any idea how to compile in Fedora, there's no reference on issues topics, any help will be appreciate.
I'll leave a terminal output

[terminal output.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5425740/terminal.output.log)

**Comment by Joshua-Ashton** [comment]
The README states to use MinGW 7 or greater. You are using MinGW 6.
