### ISSUE TITLE
Aquanox Deep Descent crashes on startup with DX12 enabled

### ISSUE THREAD

**Issue by shmerl** [HansKristian-Work/vkd3d-proton#317]
Aquanox Deep Descent is using Unreal Engine and should support DX12.

I tested GOG version of the game with Wine-staging 5.20 and latest vkd3d-proton master enabled (dxvk is also enabled in the prefix).

To use DX12, the binary is launched with -dx12 parameter:

```
wine ANX.exe -dx12
```

The game crashes before showing anything. Here is the output:

```
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2560, may be inaccurate.
24:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:debug_vk_memory_property_flags: Unrecognized flag(s) 0xc0.
224:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2560, may be inaccurate.
224:fixme:d3d12_rtv_desc_create_rtv: NULL resource RTV not implemented.
...
224:fixme:d3d12_rtv_desc_create_rtv: NULL resource RTV not implemented.
wine: Unhandled page fault on write access to 0000000000000000 at address 00007FF178385874 (thread 02f0), starting debugger...
```

**Comment by shmerl** [comment]
For the reference, with dxvk (without adding `-dx12`) it starts fine.

**Comment by doitsujin** [comment]
Can you provide a log with `VKD3D_DEBUG=trace`?

**Comment by shmerl** [comment]
It's weird, I was able to start the game one time at least until the logo videos, and then it got stuck. I think the problem is caused not by vkd3d, but by some other issues in Wine-staging.

I see something like:

```
0338:err:ntdll:RtlpWaitForCriticalSection section 000000007BC66540 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 0338, blocked by 0104, retrying (60 sec)
```

**Comment by shmerl** [comment]
I'll close this for now, until I'll dig more into it.

**Comment by doitsujin** [comment]
> 560:fixme:shader_is_dxil: Failed to parse shader, vkd3d result -3.

There's definitely something weird going on here, I'll take a look when I have time.
