### ISSUE TITLE
Take a pass over test suite and sort out tests which are "known" to fail for the time being.

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#331]
There's a certain number of tests which is kind of known to fail at the moment. This creates mild annoyance when trying to test. We should look at the failing tests and figure out what we can do to get 0 failure runs on vkd3d-proton. That way, it's much easier to track regressions.

**Comment by Joshua-Ashton** [comment]
fwiw there are a bunch of tests that fail on native D3D12:

[test_results_windows.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/5453131/test_results_windows.txt)

**Comment by doitsujin** [comment]
Do these also fail with WARP?

Pretty sure the tiled resource tests all worked fine on both AMD and NV when we implemented that stuff.

**Comment by Joshua-Ashton** [comment]
How do I run the tests with WARP?

I can detach the GPU from the VM and use the basic display adapter + spice but I feel like that's too much work and there's probably an easier way...

**Comment by HansKristian-Work** [comment]
--warp should do it, there's also --validate.
