### ISSUE TITLE
Rename enable_standalone_d3d12

### ISSUE THREAD

**Issue by Joshua-Ashton** [HansKristian-Work/vkd3d-proton#335]
I always forget whether its enable_d3d12_standalone or enable_standalone_d3d12 -- we should probably just make this enable_d3d12.

**Comment by K0bin** [comment]
Why not just `standalone`?

**Comment by Joshua-Ashton** [comment]
I don't think that's necessarily clear enough because technically vkd3d native, etc *is* standalone. You can use it without anything.

This makes it simpler as it just says ``enable_d3d12`` which implies wouldn't be built otherwise -- which is true.

**Comment by Saancreed** [comment]
How about defaulting this options to `True` if target machine is Windows instead?

**Comment by HansKristian-Work** [comment]
Yes. I agree on that. There is very little reason to not build the standalone dll when targeting Windows.
