### ISSUE TITLE
Look into Watch Dogs: Legion DXIL shaders

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#341]
The game is exclusively using DXIL and we're triggering some errors in dxil-spirv.

**Comment by screwylightbulb** [comment]
I just picked this up and running it in dx11 mode for the moment, but would love to use dx12 instead. Let me know if you need any testing/logs/whatever. (nvidia)

**Comment by artemyto** [comment]
The game loads menu with current master, but this loading lasts forever, can't actually play the game.
![Screenshot_2021-03-10_17-08-43](https://user-images.githubusercontent.com/43519305/110642420-0f961800-81c4-11eb-8f9c-5dfe74200cea.png)

**Comment by artemyto** [comment]
I tried these artifacts: https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/639219243

What information can I provide which may be useful?

**Comment by screwylightbulb** [comment]
I get this:
976:err:vkd3d_dxil_log_callback: dxil-spirv: There is no candidate for ladder merging.

And an infinite amount of this:
972:fixme:d3d12_command_list_ResourceBarrier: NULL resource for pResourceAfter. Won't be able to transition images away from UNDEFINED.

**Comment by screwylightbulb** [comment]
I've been routinely trying this with newer vkd3d builds, and the game also had a huge update yesterday. Now I am not actually getting the option to use dx12 at all any more. Trying now with a few flags.

**Comment by Oschowa** [comment]
Probably worth retesting this on master, there were a bunch of dxil fixes since the last report here.

**Comment by artemyto** [comment]
The game works with current master

**Comment by gardotd426** [comment]
The game works, but enabling ray tracing causes an instant hang. 

Checking the shader dumps with `spirv-val --scalar-block-layout` gives nothing.

Here's the log grabbed with `VKD3D_DEBUG=trace` 

[vkd3d.log](https://github.com/HansKristian-Work/vkd3d-proton/files/7533693/vkd3d.log)

(Also for anyone on Nvidia, DLSS doesn't even get exposed as an option, it's grayed out. But that's not a vkd3d issue)
