### ISSUE TITLE
Take a pass over README and verify it is up-to-date.

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#344]

**Comment by Joshua-Ashton** [comment]
What do we do about ANNOUNCE and AUTHORs also.

I feel like we could ditch ANNOUNCE but I don't know if that would be considered "rude"?

I mean... I don't think we are announcing our releases via a http 1.0 plain text page served by a git repo so it's just going to be outdated as frog.

**Comment by HansKristian-Work** [comment]
Could move ANNOUNCE to ANNOUNCE.vkd3d-1.1 perhaps to make it clear it is inherited from upstream and doesn't reflect current vkd3d-proton. Removing it is pretty rude, yes.

For AUTHORS, I think we should just add me, @doitsujin and @Joshua-Ashton and call it a day.

**Comment by DadSchoorse** [comment]
> Could move ANNOUNCE to ANNOUNCE.vkd3d-1.1 perhaps to make it clear it is inherited from upstream and doesn't reflect current vkd3d-proton. Removing it is pretty rude, yes.

Why is it rude? It's not up to date information anymore and the file would get completely rewritten for a new release anyway.

**Comment by Joshua-Ashton** [comment]
Yeah, fwiw they removed the old one when upstream released 1.2 and replaced it entirely.

I kinda don't see how it's just rude to remove it given that information now.

**Comment by HansKristian-Work** [comment]
Ok, I wasn't sure what the etiquette here was. Guess we can remove it then.
