### ISSUE TITLE
Consider memory alignment workaround for Polaris

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#348]
When querying alignment for Polaris cards in the D3D12 API, we might observe more than 64k alignment. This can break HZD apparently. D3D12 applications can assume 64k alignment. A potential workaround would be to always return 64k and deal with the misalignment in CreatePlacedResource instead (which we do already). The alternative, better workaround would be to fall back to sparse resources since we're guaranteed 64k there, but RADV does not support that at this time.

**Comment by doitsujin** [comment]
Fixed in be4391b972267ba02885b5e2eab8f1176a77660b.
