### ISSUE TITLE
DIRT 5 (1038250) - Title requires "Shader Model 6.0 wave operations".

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#376]
### Description:
**_DIRT 5_** (1038250) fails to launch immediately after launch with the following error message:

| Windows w/ VKD3D-Proton (2.0) |
| ---- |
| ![Dirt 5 - 1038250 - SM 6 0 Waves Operations is not supported](https://user-images.githubusercontent.com/761853/98685394-4d2d8600-2335-11eb-8e8e-602265ab018e.png) |

This issue was only confirmed on Windows due to Proton 5.13-2-RC1 and Wine-Staging 5.21 both failing with an "Unhandled page fault" error.

The issue was confirmed on both VKD3D-Proton 2.0 and master (d4d14df).

Please let me know if any additional information is required or if additional testing is needed.

#### Notes:
- If using DXVK's DXGI, IDXGIFactory7 is required by the game and therefore requires DXVK-git (https://github.com/doitsujin/dxvk/commit/54a4e91dad1ad3e633c5b43da8f8a5a2e3b18f73).

### Software information
[DIRT 5](https://store.steampowered.com/app/1038250/DIRT_5/) (385800)

### System information
OS: Windows 10 Pro 1909
GPU: Nvidia GeForce GTX 1060
Beta Drivers: 457.17
Wine version: N/A
VKD3D-Proton version: 2.0 / Master (d4d14df)

### Log files
Trace Log: [Dirt_5_VKD3D.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5517907/Dirt_5_VKD3D.log)

```
3508:trace:d3d12_device_QueryInterface: iface 0000000002218f70, riid {74eaee3f-2f4b-476d-82ba-2b85cb49e310}, object 000000000014ef00.
3508:warn:d3d12_device_QueryInterface: {74eaee3f-2f4b-476d-82ba-2b85cb49e310} not implemented, returning E_NOINTERFACE.

**Comment by Joshua-Ashton** [comment]
``{74eaee3f-2f4b-476d-82ba-2b85cb49e310}`` = ``ID3D12DeviceDownLevel`` for ``D3D12On7``

**Comment by doitsujin** [comment]
Yeah we don't really support these right now.

**Comment by doitsujin** [comment]
Actually, looks like our feature reporting is just broken. We should have everything that's necessary but WaveOps is reported as 0, even though we clearly support these.

**Comment by ZereoX** [comment]
Hi @doitsujin,

With https://github.com/HansKristian-Work/vkd3d-proton/pull/378/commits/fd59a62149787914fd5babc0886acee8be39e350 applied to master, the game still throws out an error message at launch, but does indeed no longer complain about wave operations.

The following error is now shown:
![DIRT 5 - 1038250 - Error](https://user-images.githubusercontent.com/761853/98719258-87128280-235d-11eb-8007-2fe9ca350807.png)

Trace Log: [DIRT 5 - 1038250 - fd59a62.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5519600/DIRT.5.-.1038250.-.fd59a62.log)

Please let me know if there is any other information or attachment I can provide that could be of help.
Thanks.

**Comment by Joshua-Ashton** [comment]
Notable section:

```
1360:trace:d3d12_device_CreatePipelineState: iface 0000000002138f30, desc 000000000014dff8, riid {765a30f3-f624-4c6f-a828-ace948622445}, pipeline_state 0000000023117868.
1360:warn:create_shader_stage: Failed to compile shader, vkd3d result -4.
1360:warn:hresult_from_vkd3d_result: Invalid shader bytecode.
```

**Comment by Joshua-Ashton** [comment]
Would you be able to run with ``VKD3D_SHADER_DEBUG=trace``?

**Comment by ZereoX** [comment]
Hi @Joshua-Ashton,

Here is the log with `VKD3D_SHADER_DEBUG=trace` set: [DIRT 5 - 1038250 - fd59a62 with Shader Trace.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5519675/DIRT.5.-.1038250.-.fd59a62.with.Shader.Trace.log)

**Comment by doitsujin** [comment]
Did you build vkd3d with DXIL support?

**Comment by HansKristian-Work** [comment]
I'll add logging callbacks to dxil-spirv so we can actually log it properly to file.

**Comment by ZereoX** [comment]
Hi @HansKristian-Work, 
As written, the issue is resolved, however the game is still failing due to the error mentioned above: https://github.com/HansKristian-Work/vkd3d-proton/issues/376#issuecomment-724905490

Should I open a separate ticket or is there any additional information I can provide here at the moment?
