### ISSUE TITLE
Regression in Everspace 2 (colors "wrong")

### ISSUE THREAD

**Issue by Corben78** [HansKristian-Work/vkd3d-proton#387]
With Proton 5.13-2 RC and now the released version of Proton 5.13 the colors on the DX12 renderpath in Everspace 2 (currently closed beta) have changed. Before (e.g. Proton 5.13-1, 5.0-10) the colors where correct, just the performance was subpar. Now with 5.13-2 the performance improved a lot, but the colors have changed.

It now looks like this with DX12:
https://steamuserimages-a.akamaihd.net/ugc/1680367456958732460/673443D970F0823865DE47CFBFD7D77D6256E6C0/

It should look the same as with DX11 (launch parameter -dx11):
https://steamuserimages-a.akamaihd.net/ugc/1680367456958733458/9F37F7D3729858844A785362262F56370A8369A1/

My specs: Ubuntu 18.04.5 LTS, nVidia driver 455.38.

**Comment by doitsujin** [comment]
Can you please bisect this? Screenshots alone don't really give us anything to work with and "closed beta" sounds like there's no way for us to actually test this oursevles.

**Comment by Corben78** [comment]
Would it be helpful to get you a steam key? If so, how many would you need?

I'm not familiar with bisecting those issues yet, so I'd either need help with that or time to dig into it.

**Comment by Corben78** [comment]
Looks like this got fixed with one of the recent updates. Proton 5.13-4 has good performance with Everspace 2 on the DX12 renderer and the colors are correct.
