### ISSUE TITLE
Death Stranding: icons turn black when you tilt the map

### ISSUE THREAD

**Issue by ngoquang2708** [HansKristian-Work/vkd3d-proton#398]
You can watch it [here](https://youtu.be/qaXvFhQoVo8) (YouTube link).
Log with VKD3D_DEBUG=warn: [DeathStranding-vkd3d.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/5553231/DeathStranding-vkd3d.zip).

Screenshots:

Map - Normal:
![map-normal](https://user-images.githubusercontent.com/9676278/99403016-9628a000-291c-11eb-9b0a-936abb5ec877.jpg)

Map - Tilted:
![map-tilted](https://user-images.githubusercontent.com/9676278/99403080-a6407f80-291c-11eb-9407-1d5069fdda6e.jpg)

**Comment by doitsujin** [comment]
What's your hardware and GPU driver?

**Comment by ngoquang2708** [comment]
My laptop CPU is Intel Core i5-9300H CPU, GPU is NVIDIA GeForce GTX 1650 driver version 455.38 running PRIME Offload.
I run the game through Steam Proton, version 5.13-2. Currently I disable Steam Runtime since it cannot use the GPU (https://github.com/ValveSoftware/steam-runtime/issues/295).
To access the map, you press Tab in the game. To tilt it, hold Alt then move your mouse.

**Comment by HansKristian-Work** [comment]
I can reproduce it on 1660ti. Somehow, after I leave the map, geometry starts to disappear:
![Screenshot from 2020-11-17 14-41-06](https://user-images.githubusercontent.com/17786731/99397357-3eba0e00-28e3-11eb-87d3-00ee1800deda.png)

**Comment by HansKristian-Work** [comment]
The map issue reproduces on RADV as well.

**Comment by HansKristian-Work** [comment]
Game screws up R32_UINT vs RAW buffer types, which triggers a mismatch. Falling back to pure texel buffers works around the issue.
