### ISSUE TITLE
Fix 64-bit modifiers test

### ISSUE THREAD

**Issue by hakzsam** [HansKristian-Work/vkd3d-proton#419]
Invalid SPIR-V found for ps_dmodifier.

error: line 62: GLSL.std.450 NClamp: expected types of all operands to be equal to Result Type
  %42 = OpExtInst %double %1 NClamp %41 %float_0 %float_1

See test_shader_instructions().

**Comment by Joshua-Ashton** [comment]
Thanks for catching -- will look into this after I sleep. :)
