### ISSUE TITLE
Assassins Creed Valhalla: State of things.

### ISSUE THREAD

**Issue by ofcaah** [HansKristian-Work/vkd3d-proton#422]
Hello! First and foremost, thank you for your excellent work.

Thanks to it I manged to successfully launch and play AC Valhalla on following platform:
Debian/x11, Linux 5.9.0-3-amd64, GeForce GTX 1080 Ti, driver version 455.45.01. Current VKD3D-Proton, Wine 5.22 in form of 5.22-Proton-TKG. Game started with Lutris.

While playable, there are issues that I've noticed, that I'm reporting with hope it'll lead you to some bugs. Please note, that game looks fine and there are no artifacts/glitches that I noticed compared to playing on Geforce Now (windows 2016 server, Nvidia Tesla GPU).

1) Slow game play.
This doesn't mean low frame rate. It means game runs slow, as if some timing was off. It may be a "feature" to some, since it makes combat easier. It happens on "ultra" settings as well as "low" and seems to get worse when things get intense. There are no obvious bottlenecks, like high CPU/io usage.

2) Freezes on liquid interaction.
Game has a drinking mini-game, which causes a brief freeze when horn hits the alcoholic beverage. Same thing happens when jumping into water. This however happens only once: "refills" in the minigame, or further water jumps don't yield the same freeze.

3) Frame-rate spikes, even when standing still.
![image](https://user-images.githubusercontent.com/6192229/100318796-e6f46480-2fbe-11eb-96ea-2126d763b5f6.png)

If I can be of any assistance, please direct me at some reading material as to how to provide relevant details or logs.

**Comment by doitsujin** [comment]
We already have a bug report for this game and are well aware of these issues (#409), please use that instead.

> It means game runs slow

I don't really see how that is related to D3D12.

> Freezes on liquid interaction.

Make sure to disable vkd3d logging since the game tries to do something that we cannot implement, and we emit a log message every single time.

**Comment by ofcaah** [comment]
OK then; closing the issue. Sorry for the noise.
