### ISSUE TITLE
Death Stranding: Huge frametime spikes when selecting menu items

### ISSUE THREAD

**Issue by ngoquang2708** [HansKristian-Work/vkd3d-proton#428]
The issue starts when you open the menu -> System -> Options then moving between menu items.
It is not really important though but very annoying.
My PC specs: Intel Core i5-9300H, GeForce GTX 1650 (laptop).
Screenshot:
![20201129122155_1](https://user-images.githubusercontent.com/9676278/100534390-d3f0c700-3240-11eb-850c-a93b5585c61a.jpg)

**Comment by doitsujin** [comment]
Are you sure that this is related to vkd3d at all and not just some game quirk?

**Comment by ngoquang2708** [comment]
I am not sure.
Should I close this or just leave it here for reference later?

**Comment by phush0** [comment]
I don't have this problem with 10875h and RTX5000

**Comment by ngoquang2708** [comment]
No longer exist on version 2.3.1.
