### ISSUE TITLE
Warframe launcher don't show DX12 options

### ISSUE THREAD

**Issue by RSerejo** [HansKristian-Work/vkd3d-proton#434]
i'm trying to test Warframe under DX12 with VKD3D-Proton but i can't do warframe launcher detect DX12 support.

**Comment by doitsujin** [comment]
Please give us more details (Proton log, hardware, driver, ...)

Launchers not offering the option is almost guaranteed to not be our problem in the first place. You'll need to make sure that your wine prefix is set to Windows 10, and some games require Feature Level 12_0 which we currently cannot support on RADV.

**Comment by Saancreed** [comment]
Disregarding the launcher thing, the game seems to deadlock shortly after starting in D3D12 mode anyway.

Here's my log with `VKD3D_DEBUG=trace` from my Wine prefix (using `wine-staging-protonified-tkg-git 5.22.r10.g2a073f33`): [Warframe.x64-1607039127.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/5639729/Warframe.x64-1607039127.log.gz)

I'll try to record an apitrace from a W10 machine sometime tomorrow in case this is not enough to figure out what's wrong.

**Comment by doitsujin** [comment]
> 012c:err:ntdll:RtlpWaitForCriticalSection section 000000007BC67560 "../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 012c, blocked by 01b8, retrying (60 sec)

Not sure what's going on but the thread spewing this doesn't have anything to do with d3d12. Not sure if our bug or not.

Doesn't help that the game is such a massive pain in the arse to get running, so trying to reproduce that is going to be all sorts of "fun". I never managed to make the game work even with D3D11.

**Comment by Saancreed** [comment]
> Not sure if our bug or not.

Right, might as well be a Wine bug or some D3D12–specific game bug (after all, devs warned that D3D12 support is in unstable beta). Fwiw, D3D11 mode has no such issues. I'll try with vkd3d on Windows too maybe.

> Doesn't help that the game is such a massive pain in the arse to get running, so trying to reproduce that is going to be all sorts of "fun". I never managed to make the game work even with D3D11.

That's… interesting. I haven't had any issues with Warframe in D3D11 mode since forever (except maybe the Launcher being unable to tell the exact progress of ongoing game update process). Nowadays I can get a working setup just by creating a new prefix, installing DXVK and `wine msiexec /i Warframe.msi`. Proton-GE also worked for me out of the box with Steam version a few months ago.

**Comment by RSerejo** [comment]
[steam-230410.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/5642713/steam-230410.tar.gz)

**Comment by Saancreed** [comment]
Here is an apitrace recorded on W10 while using native D3D12:
https://drive.google.com/file/d/1kRdnu09JomKP8BtLfLwg3OHY5g6IkofK/view

Here is log file created when trying to run the game with `vkd3d-proton` on W10 (game crashes instead of deadlocking):
https://drive.google.com/file/d/1RqstsnMUeMhTWf_Y-yiybEDzyBJXtrN9/view

Same build as yesterday, older hardware.

**Comment by screwylightbulb** [comment]
> Doesn't help that the game is such a massive pain in the arse to get running, so trying to reproduce that is going to be all sorts of "fun". I never managed to make the game work even with D3D11.

This is very strange to hear. I have never had any issues with Warframe at all using DX11 on Steam. This is my third PC I have it installed on and my partner also plays it on her Manjaro setup. The only quirk is that the updater sometimes says it's done when it's actually still busy downloading stuff. Just let it finish and it works.

**Comment by Iglu47** [comment]
> i'm trying to test Warframe under DX12 with VKD3D-Proton but i can't do warframe launcher detect DX12 support.

> You'll need to make sure that your wine prefix is set to Windows 10, and some games require Feature Level 12_0 which we currently cannot support on RADV (`VKD3D_FEATURE_LEVEL=12_0` might work around that, might also end up not working at all).

also turn off "Launcher GPU Acceleration"
<details><summary>screenshot</summary>
<p>

![2021-01-19_20-47-34](https://user-images.githubusercontent.com/25866099/105770439-4267b200-5f70-11eb-9212-43887e058ce4.png)

</p>
</details>

**Comment by Iglu47** [comment]
it looks like Warframe is working fine in fullscreen mode
![wf-launcher-option](https://user-images.githubusercontent.com/25866099/116140597-38c12800-a6e0-11eb-8b0a-39b2ec6a63b7.png)
if the selection list for the graphic renderer is empty, turn off "Launcher GPU Acceleration" and restart the launcher.
![wf-dx12-f](https://user-images.githubusercontent.com/25866099/116140804-82117780-a6e0-11eb-9aea-1fb0aba4655f.png)

**Comment by jhu54** [comment]
Don't use wine-staging 6.7 - dx12 is not showing as an option when you use that release (with 2.2 or 2.3 vkd3d).

https://bugs.winehq.org/show_bug.cgi?id=51062

**Comment by Blisto91** [comment]
@RSerejo Friendly ping.
Am i correct in assuming that this issue was solved?

**Comment by RSerejo** [comment]
@Blisto91 working very well, even without full screen, Proton GE 7.48.

**Comment by jabuxas** [comment]
![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/94939040/b4eb7950-2529-49ae-8500-6e2bd38331e9)

not sure if it's me, but even with VKD3D_FEATURE_LEVEL=12_0 on lutris, it doesn't seem to work. steam as well.

**Comment by Blisto91** [comment]
What is your dxvk and vkd3d-proton version and GPU and driver?

**Comment by jabuxas** [comment]
dxvk v2.2, vkd3d v2.9, gpu is rx 580, mesa v23.1.3

now that I'm looking at it, though, mesa on gentoo has the USE_EXPAND for
VIDEO_CARDS `d3d12`. i wonder if i would need to compile with that USE flag
as well. i'll give it a try.

Em qua., 9 de ago. de 2023 às 15:47, Blisto91 ***@***.***>
escreveu:

**Comment by jabuxas** [comment]
dxvk v2.2, vkd3d v2.9, gpu is rx 580, mesa v23.1.3

now that I'm looking at it, though, mesa on gentoo has the USE_EXPAND for VIDEO_CARDS `d3d12`. i wonder if i would need to compile with that USE flag as well. i'll give it a try.
