### ISSUE TITLE
Cyberpunk 2077 fails to launch

### ISSUE THREAD

**Issue by ryanwalder** [HansKristian-Work/vkd3d-proton#453]
The CDPR Launcher works fine then CP2077 fails to launch

Steam
Proton 5.0-10
Nvidia 1080ti
Ubuntu 20.04

Proton log:

https://gist.github.com/ryanwalder/bb9bdd0ed226a5f25a4a8a0ca7d10b3e

**Comment by RoyShapiro** [comment]
Strange. It runs even on Ultras for me on Debian 10 with updated Vulkan Loader, but freezes solid with 10-15 minutes. If you restart it, it works fine for another 10-15 minutes, eh-eh-eh... Glad it does at all.

**Comment by Joshua-Ashton** [comment]
You're using Proton 5.0-10 which has a massively outdated version of vkd3d-proton.

**Comment by kassindornelles** [comment]
Use proton 5.13-4, 5.0-10 will not run the game
![image](https://user-images.githubusercontent.com/40970965/101707874-dfc36100-3a6a-11eb-9879-532fff46b52a.png)
