### ISSUE TITLE
Assassin's Creed Valhalla: water is not being rendered

### ISSUE THREAD

**Issue by Saancreed** [HansKristian-Work/vkd3d-proton#458]
Most likely caused by #438 because the game is spewing thousands of `fixme:d3d12_command_list_handle_active_queries: Query (0x????,0) already ended.` I'll bisect to make sure.

**Comment by Saancreed** [comment]
76a7eb7c577f6f139261c97c5be0463f77c92cf5 is good.
aa21d2d03d90a924567ec58ace8c386de47d9f31 causes the game to fail to launch.
051ba691be803a963696baf65a7454773e9e6733 also causes the game to fail to launch.
a888d814222f9e16b9d8d3dc1973b5ad22e6929c is bad.

**Comment by HansKristian-Work** [comment]
Blocker for 2.1.
