### ISSUE TITLE
Error launching Cyberpunk: fixme: vkd3d_set_view_swizzle_for_format: Alpha swizzle is not supported

### ISSUE THREAD

**Issue by JohnnyDilinjer** [HansKristian-Work/vkd3d-proton#467]
Hello, everyone. After CDP logo I get an error:

fixme: vkd3d_create_texture_srv: Ignoring plane slice 1.
fixme: vkd3d_create_texture_srv: Ignoring plane slice 1.
fixme: vkd3d_create_texture_srv: Ignoring plane slice 1.
fixme: vkd3d_set_view_swizzle_for_format: Alpha swizzle is not supported

System freezes and logout.. I am using GFX7 and mesa-git from 12.12 and proton 5.13.4. i compiled the last vkd3d from github and get the same error..
as I understand it, the resource.c file uses DXGI_FORMAT_A8_UNORM, not DXGI_FORMAT_R8G8B8A8_UNORM
Is there a way to fix this?

**Comment by doitsujin** [comment]
The fixme messages are not the reason for your crash. Based on your description you're probably getting a GPU hang, which could be caused by a driver or game bug. Please post a complete log so we can see whether all the required Vulkan features are getting picked up.

**Comment by JohnnyDilinjer** [comment]
> The fixme messages are not the reason for your crash. Based on your description you're probably getting a GPU hang, which could be caused by a driver bug or a random game bug, which is known. Please post a complete log so we can see whether all the required Vulkan features are getting picked up.

Thanks for the answer. I found a solution and therefore close the topic.

**Comment by goliv04053** [comment]
I'm having the same problem that you had. How did you solved that?

**Comment by goliv04053** [comment]
@JohnnyDilinjer In my case, i can run the game but it crashes and in the log says the same thing. I can also send the log if you want to give a look.

**Comment by goliv04053** [comment]
How can i explain... it runs for sometime like 10/15 minutes depending of the graphical settings (I think) and it crashes. And it gaves the same problem about alpha swizzle and Ignoring plane slice.

**Comment by goliv04053** [comment]
[cyberpunk2077.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/5737746/cyberpunk2077.txt)
Here the log, also... sorry about my english.

**Comment by K0bin** [comment]
It's a known issue.

The release page clearly stated that Nvidia GPU currently aren't supported for Cyberpunk.

**Comment by mozo78** [comment]
Does anyone know if NVIDIA know for this problem?

**Comment by K0bin** [comment]
They do.

**Comment by mozo78** [comment]
Thanks :)
