### ISSUE TITLE
screen space reflections broken in Horizon Zero Dawn with RADV

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#469]
Looks like this with vkd3d-proton 2.1 and RADV 21.0.0_devel.132228.574429f9528 (both ACO & LLVM) on 5700 XT:
![1151640_20201228135137_1](https://user-images.githubusercontent.com/13510490/103218327-f860c180-491a-11eb-8857-73a96e89f2ec.png)

Looks correct on Windows D3D12. Would a RenderDoc capture be helpful?

**Comment by doitsujin** [comment]
Can you bisect this? Way more useful than Renderdoc.

Anyway, it's unlikely that this gets addressed for at least another week, vacation etc.

**Comment by aufkrawall** [comment]
It should work to call the build script with a commit as head, instead of `master`, right? At least the output folder is named accordingly.
Though it seems odd that I can go back to e.g. 269bb649d7ade5455c7d8903a3da43c9697f0bf0 and the game still runs the same as with current master/2.1. I made sure that the corresponding d3d12.dll is actually loaded by the game (as proton-tkg always overwrites my symlink in system32 prefix folder).
I also wonder if the game shouldn't invalidate its shader cache with such an old vkd3d-proton commit as head. It doesn't do so for me, so no idea if the issue might be baked into the shader binary by newer vkd3d-proton versions and is picked up by older ones.

**Comment by doitsujin** [comment]
If such an old commit works with HZD then something really isn't working with your build setup. Try symlinking it next to the game exe and start the game with `WINEDLLOVERRIDES=d3d12=n`.

**Comment by aufkrawall** [comment]
I did that and made sure that the module is actually loaded from the game's dir - yet I don't notice a difference vs. vkd3d-proton 2.1.

For compiling, I did
`
./package-release.sh 269bb649d7ade5455c7d8903a3da43c9697f0bf0 /output --no-package`
and simply copied the DLL. :confused:

**Comment by HansKristian-Work** [comment]
Does not reproduce for me on vkd3d-proton master and Mesa master 8ecace073ea68e3819ea7c5637bd479067e1420b with 5700xt.

**Comment by HansKristian-Work** [comment]
I also tried 574429f9528734f078c8c3a56232ba66fa818913, but same result.

**Comment by HansKristian-Work** [comment]
![Screenshot from 2021-01-13 10-32-24](https://user-images.githubusercontent.com/17786731/104433709-b5455600-558a-11eb-827a-6b9bf0297e2a.jpg)
![Screenshot from 2021-01-13 10-31-50](https://user-images.githubusercontent.com/17786731/104433717-b6768300-558a-11eb-9540-9131662f9d25.jpg)

Some screenshots, looks correct to me without downloading tons of updates on Windows to compare.

**Comment by aufkrawall** [comment]
I think it doesn't look correct in your screenshots: Despite of natural limitations of SSR, the weirdly bluish "holes" don't look normal to me. I'm quite certain that also the scene in your screenshots will look different on Windows. The issue btw. also occurs with latest amdvlk-open.

**Comment by HansKristian-Work** [comment]
Ok, I guess I'll do more direct comparison then ...

**Comment by aufkrawall** [comment]
I'll also do that for the scene above (or a better one). It should generally be more noticeable with huge water surfaces.

**Comment by aufkrawall** [comment]
Place:
![Screenshot_20210113_175958](https://user-images.githubusercontent.com/13510490/104488432-a08ab180-55ce-11eb-9cf7-4c4a2d85b7ae.png)

Windows D3D12:
![win](https://user-images.githubusercontent.com/13510490/104488476-ada7a080-55ce-11eb-89bc-e952882fac3e.png)

VKD3D:
![Screenshot_20210113_180011](https://user-images.githubusercontent.com/13510490/104488496-b6987200-55ce-11eb-8b14-0239165672e0.png)

Might not be (just) the SSR, but also the cubemaps or something else.

**Comment by HansKristian-Work** [comment]
Bisected regression to:

commit 30c417bdbf459173a7e6260f171095415f97c925
Author: Hans-Kristian Arntzen <post@arntzen-software.no>
Date:   Mon Nov 16 16:55:55 2020 +0100

    dxil-spirv: Update submodule.
    
    Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

 subprojects/dxil-spirv | 2 +-

**Comment by aufkrawall** [comment]
Hm, then I think specifying a commit as head really doesn't work with `./package-release.sh *commit* /output --no-package`. :question:

**Comment by HansKristian-Work** [comment]
package-release just takes the name of the package, it doesn't check out commits for you.

**Comment by HansKristian-Work** [comment]
Fixed on master now. Was a fallout from the fixes required for Cyberpunk.

**Comment by aufkrawall** [comment]
I can confirm it's fixed, thanks!

Btw: Does texture streaming work correctly for you with RADV? My VRAM consumption is weirdly low with 4.3GB and some textures don't stream in in high resolution (textures set to ultra):
![Screenshot_20210115_154421](https://user-images.githubusercontent.com/13510490/104740958-dc498680-5748-11eb-9e4b-29baa26af5d4.png)
On Windows D3D12, VRAM consumption after loading is ~6.8GB and the wood textures look way more detailed.
On Linux with amdvlk-open, it allocates extreme amounts of both RAM and VRAM.

Well, and my CPU performance with the 6700k is very low too (as anticipated in #299 ), it's roughly 1/3 or less of native D3D12 performance, despite of esync/fsync etc. :(
That is with RADV, amdvlk-open seems to be even worse.

**Comment by HansKristian-Work** [comment]
The game spams sqrt() which enters msvcrt afaik. Don't think it has ever been narrowed down to vkd3d. The game has some weird DXGI interaction going on which we cannot fix.

**Comment by aufkrawall** [comment]
Looks like today's 1.10 update fixed the streaming issue, VRAM consumption with RADV is now > 7.5GB and textures seem to look as expected.
