### ISSUE TITLE
Reshade does not have access to depth buffer

### ISSUE THREAD

**Issue by screwylightbulb** [HansKristian-Work/vkd3d-proton#473]
Reshade seems to work just as well as it does under dxvk, but with d3d12 games, it does not seem to have access to the depth buffer. I have tried in a few dx12 games, but Death Stranding is a good test example.

DisplayDepth.fx gives the following warning:

DisplayDepth.fx(104,2): warning X4000: use of potentially uninitialized variable (F__GetDepth)

Anyhoo, not a priority, just wanted to leave this here. If you do decide to look into it, let me know if I can supply extra information, logs, traces, whatever.

Kernel 5.9, 5.10
Nvidia 455.45.01

**Comment by doitsujin** [comment]
Does Reshade even work with those games on Windows?

This really isn't something we can or should fix on our end; finding "the" depth buffer may be less straight-forward for vkd3d-proton than it is for DXVK since DXVK has a much easier time working with Vulkan render passes, but it's there and I see no inherent reason why Reshade wouldn't be able to detect it.

**Comment by screwylightbulb** [comment]
> Does Reshade even work with those games on Windows?

Yeah, ReShade works on Windows in my specific example of Death Stranding. The buffer is inverted negative but it's there. And ReShade does work perfectly fine with vkd3d-proton, except for anything needing depth info.
 
> This really isn't something we can or should fix on our end; finding "the" depth buffer may be less straight-forward for vkd3d-proton than it is for DXVK since DXVK has a much easier time working with Vulkan render passes, but it's there and I see no inherent reason why Reshade wouldn't be able to detect it.

Anyway, not super important. Thanks for the reply.

**Comment by CeeJayDK** [comment]
I programmed DisplayDepth.fx (I'm a Reshade shader developer)
I'll try and see if I can either get rid of the warning or make a more descriptive warning saying that Reshade cannot detect the depth buffer.

But as for the detection that is on Reshade itself.
I'll mention it to those of our developers that work on the depth detection, but we don't use vkd3d-proton so fixing it won't be a priority.

I would like to know what version of Reshade was used. The latest version is currently 4.9.1 so if you haven't tried that please do.

**Comment by CeeJayDK** [comment]
BTW I suggest closing this issue as it's unlikely to be an issue with vkd3d-proton.

You can raise a new issue on the Reshade github or contact us Reshade developers on our forum or our discord.

**Comment by screwylightbulb** [comment]
> BTW I suggest closing this issue as it's unlikely to be an issue with vkd3d-proton.
> 
> You can raise a new issue on the Reshade github or contact us Reshade developers on our forum or our discord.

Cool, will do. Thanks for hopping in.

**Comment by screwylightbulb** [comment]
@CeeJayDK It is 4.9.1 with the shaders being a fairly recent master. Also, I'm not seeing the error any more, but DisplayDepth is still showing all white. I am trying it on Death Stranding with the depth input reversed. As mentioned, when I use it with a DX11 game, it does work as intended.
