### ISSUE TITLE
STAR WARS Battlefront II (1237950) - Title crashes during the initial loading and silently fails on subsequent launches.

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#474]
### Description:
**_STAR WARS Battlefront II_** (1237950) will successfully open a window and begin loading after the title is restarted for the first time having just initially applied the DirectX 12 option (Set Options -> Video -> Enable DirectX 12 to "On"). However, during the loading, the title will crash to the desktop instead of proceeding to the "Optimizing Shaders..." portion of the loading (see screenshot below). Further attempts to launch the game will result in a silent failure with the game momentarily appearing as running in Steam before closing (no window is observed).

| Windows Reference |
| ---- |
|![Windows - DirectX 12 - Initial Loading](https://user-images.githubusercontent.com/761853/103804711-87a75c80-5020-11eb-9f8f-bc6a47d5c186.png)|

This issue was confirmed on both Windows and Proton 5.13-4.

Please let me know if any additional information is required or if additional testing is needed.

### Software information
[STAR WARS Battlefront II](https://store.steampowered.com/app/1237950/STAR_WARS_Battlefront_II/) (1237950)

### System information
OS: Windows 10 Pro 1909 / Ubuntu 20.04
GPU: Nvidia GeForce GTX 1060 / AMD Radeon RX 580
Beta Drivers: 455.46.04 / 21.0\~git2101060730.8a22fc\~oibaf\~f
Wine version: Proton 5.13-4
VKD3D-Proton version: 2.1 / Master (d003424)

### Log files
VKD3D Log (w/ VKD3D_SHADER_DEBUG=trace): [StarWars Battlefront II VKD3D.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5777737/StarWars.Battlefront.II.VKD3D.log)
DXGI Log: [starwarsbattlefrontii_dxgi.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5777738/starwarsbattlefrontii_dxgi.log)

### API Trace
Trace: https://drive.google.com/file/d/1W53caZtuuy7eYRNqZDRIuhFWM4Xafe0Z/view?usp=sharing
_(Trace file recorded, but I was unable to play it back so I'm including it just in case.)_

**Comment by ZereoX** [comment]
I can confirm this issue is still valid as written on latest master (eb4e852).

**Comment by Etaash-mathamsetty** [comment]
can reproduce here as well

**Comment by FuzzyQuills** [comment]
I was also able to reproduce this the other night on RADV.

**Comment by Blisto91** [comment]
Fresh log with `VKD3D_DEBUG=trace` & `VKD3D_SHADER_DEBUG=trace`

https://mega.nz/file/N1pVgBiJ#Jv7GiHDPS1FbFALOM1YxWXXA7SuNwIMRAtchJdVirQc

**Comment by elogicuk** [comment]
this is still an issue today :(

https://github.com/HansKristian-Work/vkd3d-proton/issues/1602
