### ISSUE TITLE
nvoglv64.dll error in call of duty warzone

### ISSUE THREAD

**Issue by barfin** [HansKristian-Work/vkd3d-proton#480]
![image](https://user-images.githubusercontent.com/37030489/104418958-00f8ff00-558d-11eb-895f-e8fa4d2ffb57.png)

**Comment by K0bin** [comment]
Windows (especially Windows 8) is unsupported.

**Comment by barfin** [comment]
> 
> 
> Windows (especially Windows 8) is unsupported.

so there will never be a fix?

**Comment by doitsujin** [comment]
Not with the amount of information provided. Please post at least a vkd3d log (see README on how to enable logging).

The screenshot is pretty much completely useless and only tells us that there's something crashing inside the Nvidia driver.
