### ISSUE TITLE
Metro Exodus renders into small section of window while Vsync is enabled (Mutter+wayland only)

### ISSUE THREAD

**Issue by Mershl** [HansKristian-Work/vkd3d-proton#508]
Description:
The game starts as expected and renders properly while VSync is disabled.
Enabling VSync in Metro Exodus on mutter (3.38.3) on wayland with vkd3d-git renders the game in a small section (top left) of the screen, the main section does no longer update. The game continues to render correctly in the small section of the window.

This issue only shows on mutter+wayland and vkd3d (DX12). Not reproduceable on Xorg (DX12&DX11) and wayland (DX11). Any hints/ideas we could pass to the maintainers?

Screenshot:
![2021-02-12 20-43-44 mkv-00:00:31 433](https://user-images.githubusercontent.com/520251/107815938-5a16a700-6d74-11eb-8796-b416ccff2a17.png)

**Comment by Mershl** [comment]
Thought it was fixed. Just tested again with latest game version and mutter 41.2. The issue is still reproduciable on mutter wayland.

**Comment by Blisto91** [comment]
@Mershl Friendly ping. Do you still have this issue with the latest version of Mutter, vkd3d-proton, dxvk etc? 🙂

**Comment by Mershl** [comment]
Thanks for the ping Blisto. No longer reproduceable. Tested on Gnome 43 wayland.

**Comment by Mershl** [comment]
The very same issue is visible in GTA5 when enabling VSync to On/Full. Tested on Gnome 45 (wayland), Wine-GE 8-25, Resolution: 3440x1440

This *might* be a Gnome/mutter issue as GTA5 is a DX11 game.

![image](https://github.com/HansKristian-Work/vkd3d-proton/assets/520251/e8daf8fe-aa98-49e9-a4ef-6449cec7138c)
