### ISSUE TITLE
Mesh Shader support?

### ISSUE THREAD

**Issue by romulasry** [HansKristian-Work/vkd3d-proton#510]
https://store.steampowered.com/app/1498800/3DMark_Mesh_Shader_feature_test/?l=english
Requires 3dmark.

https://www.youtube.com/watch?v=qlwR_9AAAVc 3DMark Mesh Shader Feature Test

**Comment by doitsujin** [comment]
There is no cross-vendor mesh shader support in Vulkan yet.
