### ISSUE TITLE
Cyberpunk 2077 hangs on vkd3d-proton 2.2

### ISSUE THREAD

**Issue by pseregiet** [HansKristian-Work/vkd3d-proton#535]
Tried on proton-experimental, proton-6.1-GE-2 and Wine-6.2

Installing d3d12.dll in the game folder (Cyberpunk 2077/bin/x64, next to the Cyberpunk2077.exe) makes the game hang after about a second from launching. You can hear the intro music start to play and MangoHud shows up. You can see by the timeframe histogram that it started and froze shortly after. 

![2021-02-21-030554_1952x1102_scrot](https://user-images.githubusercontent.com/11596839/108613409-ffbfbb00-73f1-11eb-92d4-2bb487830a5f.png)

EDIT: Doesn't hang up with mesa-git

**Comment by HansKristian-Work** [comment]
Yes, users have reported hangs on older Mesa builds, not our bug.
