### ISSUE TITLE
Compilation error - DXIL_SPV_STAGE_RAY_GENERATION’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by tysegall** [HansKristian-Work/vkd3d-proton#541]
Checked out the 2.2 tag.  Compiling on Debian Sid.  Output below:

`
[6/14] Compiling C object libs/vkd3d-shader/libvkd3d-shader.a.p/dxil.c.obj
FAILED: libs/vkd3d-shader/libvkd3d-shader.a.p/dxil.c.obj 
x86_64-w64-mingw32-gcc -Ilibs/vkd3d-shader/libvkd3d-shader.a.p -Ilibs/vkd3d-shader -I../libs/vkd3d-shader -I../include/private -Iinclude -I../include -I../subprojects/Vulkan-Headers/include -I../subprojects/SPIRV-Headers/include -Ilibs/vkd3d-common/libvkd3d_common.a.p -Isubprojects/dxil-spirv -I../subprojects/dxil-spirv -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_GNU_SOURCE '-DPACKAGE_VERSION="2.2"' -D_WIN32_WINNT=0x600 -DVKD3D_BUILD_STANDALONE_D3D12 -fvisibility=hidden -Wno-format -Wno-missing-field-initializers -Wno-unused-parameter -Wdeclaration-after-statement -MD -MQ libs/vkd3d-shader/libvkd3d-shader.a.p/dxil.c.obj -MF libs/vkd3d-shader/libvkd3d-shader.a.p/dxil.c.obj.d -o libs/vkd3d-shader/libvkd3d-shader.a.p/dxil.c.obj -c ../libs/vkd3d-shader/dxil.c
../libs/vkd3d-shader/dxil.c: In function ‘vkd3d_shader_compile_dxil_export’:
../libs/vkd3d-shader/dxil.c:840:21: warning: implicit declaration of function ‘dxil_spv_converter_begin_local_root_descriptor_table’; did you mean ‘dxil_spv_converter_add_local_root_descriptor_table’? [-Wimplicit-function-declaration]
  840 |                 if (dxil_spv_converter_begin_local_root_descriptor_table(converter) != DXIL_SPV_SUCCESS)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     dxil_spv_converter_add_local_root_descriptor_table
../libs/vkd3d-shader/dxil.c:880:21: warning: implicit declaration of function ‘dxil_spv_converter_end_local_root_descriptor_table’; did you mean ‘dxil_spv_converter_add_local_root_descriptor_table’? [-Wimplicit-function-declaration]
  880 |                 if (dxil_spv_converter_end_local_root_descriptor_table(converter) != DXIL_SPV_SUCCESS)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     dxil_spv_converter_add_local_root_descriptor_table
../libs/vkd3d-shader/dxil.c:1027:5: warning: implicit declaration of function ‘dxil_spv_converter_set_entry_point’; did you mean ‘dxil_spv_converter_add_option’? [-Wimplicit-function-declaration]
 1027 |     dxil_spv_converter_set_entry_point(converter, export);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     dxil_spv_converter_add_option
../libs/vkd3d-shader/dxil.c: In function ‘convert_stage’:
../libs/vkd3d-shader/dxil.c:1089:14: error: ‘DXIL_SPV_STAGE_RAY_GENERATION’ undeclared (first use in this function)
 1089 |         case DXIL_SPV_STAGE_RAY_GENERATION:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libs/vkd3d-shader/dxil.c:1089:14: note: each undeclared identifier is reported only once for each function it appears in
../libs/vkd3d-shader/dxil.c:1091:14: error: ‘DXIL_SPV_STAGE_CLOSEST_HIT’ undeclared (first use in this function); did you mean ‘DXIL_SPV_STAGE_COMPUTE’?
 1091 |         case DXIL_SPV_STAGE_CLOSEST_HIT:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |              DXIL_SPV_STAGE_COMPUTE
../libs/vkd3d-shader/dxil.c:1093:14: error: ‘DXIL_SPV_STAGE_MISS’ undeclared (first use in this function); did you mean ‘DXIL_SPV_STAGE_PIXEL’?
 1093 |         case DXIL_SPV_STAGE_MISS:
      |              ^~~~~~~~~~~~~~~~~~~
      |              DXIL_SPV_STAGE_PIXEL
../libs/vkd3d-shader/dxil.c:1095:14: error: ‘DXIL_SPV_STAGE_CALLABLE’ undeclared (first use in this function); did you mean ‘DXIL_SPV_STAGE_COMPUTE’?
 1095 |         case DXIL_SPV_STAGE_CALLABLE:
      |              ^~~~~~~~~~~~~~~~~~~~~~~
      |              DXIL_SPV_STAGE_COMPUTE
../libs/vkd3d-shader/dxil.c:1097:14: error: ‘DXIL_SPV_STAGE_INTERSECTION’ undeclared (first use in this function); did you mean ‘DXIL_SPV_STAGE_INT_MAX’?
 1097 |         case DXIL_SPV_STAGE_INTERSECTION:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              DXIL_SPV_STAGE_INT_MAX
../libs/vkd3d-shader/dxil.c: In function ‘vkd3d_shader_dxil_append_library_entry_points’:
../libs/vkd3d-shader/dxil.c:1160:21: warning: implicit declaration of function ‘dxil_spv_parsed_blob_get_shader_stage_for_entry’; did you mean ‘dxil_spv_parsed_blob_get_shader_stage’? [-Wimplicit-function-declaration]
 1160 |             stage = dxil_spv_parsed_blob_get_shader_stage_for_entry(blob, ascii_entry);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     dxil_spv_parsed_blob_get_shader_stage
../libs/vkd3d-shader/dxil.c:1182:13: warning: implicit declaration of function ‘dxil_spv_parsed_blob_get_num_entry_points’; did you mean ‘dxil_spv_parsed_blob_get_shader_stage’? [-Wimplicit-function-declaration]
 1182 |         if (dxil_spv_parsed_blob_get_num_entry_points(blob, &count) != DXIL_SPV_SUCCESS)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             dxil_spv_parsed_blob_get_shader_stage
../libs/vkd3d-shader/dxil.c:1190:13: warning: implicit declaration of function ‘dxil_spv_parsed_blob_get_entry_point_name’; did you mean ‘dxil_spv_parsed_blob_get_shader_stage’? [-Wimplicit-function-declaration]
 1190 |             dxil_spv_parsed_blob_get_entry_point_name(blob, i, &mangled_entry);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             dxil_spv_parsed_blob_get_shader_stage
[10/14] Compiling C object libs/vkd3d/libvkd3d-proton.a.p/swapchain.c.obj
ninja: build stopped: subcommand failed.
`

**Comment by HansKristian-Work** [comment]
Did you forget to update submodules?
