### ISSUE TITLE
World of Warcraft dx12 graphics crash with rx 5600 xt

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#558]
Using dxvk-1.8.1, Mesa 20.3.4, kernel 5.11.3, wine staging 6.3 (focal), RX 5600 XT, RX 580 graphics card, 2560x1440 resolution.
nvidia 460.39 with gtx 1060.

DirectX 11 play works fine, solid 60-75 FPS (vert sync enabled) on all cards. Switch to DX12, and both the 1060 and 580 cards have no issues, solid fps and smooth play. On the rx 5600 xt, 1-2 mins after starting the game and moving around, the video corrupts freezing everything and screens blanks returning with random colors and shapes overlaying the original game image. Only switching to a terminal session allows a computer restart short of power off button. 

DirectX 12 runs flawlessly on Windows 10 with the rx 5600 xt card. 

Have tried fresh Ubuntu install with AMD drivers, older kernels and somehow the issue is still only evident with the rx 5600 xt card. 

More than happy to get logs etc if you post instructions on how to get them for you. 

Edit: in the system log, just prior to crashing there are a couple of errors:

1. [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
2. amdgpu 0000:03:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
3. [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed
4. [drm:gfx_v10_0_cp_gfx_enable.isra.0 [amdgpu]] *ERROR* failed to halt cp gfx
5. [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=2001403, emitted seq=2001405
6. [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process WoW.exe pid 3467 thread WoW.exe pid 3524
7. Process 1440 (Xorg) of user 0 dumped core.

Stack trace of thread 1475:
#0  0x00007f8ed3f9c4a7 n/a (radeonsi_dri.so + 0x5054a7)
#1  0x00007f8ed3f9fe7b n/a (radeonsi_dri.so + 0x508e7b)
#2  0x00007f8ed4adcbe5 n/a (radeonsi_dri.so + 0x1045be5)
#3  0x00007f8ed4ad5d5b n/a (radeonsi_dri.so + 0x103ed5b)
#4  0x00007f8ed5c81609 start_thread (libpthread.so.0 + 0x9609)
#5  0x00007f8ed5ba6293 __clone (libc.so.6 + 0x122293)
...

A whole lot more in the core dump. Checked the logs, and the first 6 are consistent across the crashes I have observed. Haven't had any crashes using dx11 or other software rendering (OpenGL and Vulkan) we use on this machine, only in WoW with dx12 enabled. Not sure where to address this...

**Comment by doitsujin** [comment]
Sounds like a driver bug then?

**Comment by jhu54** [comment]
It could be related to a REBAR error reported fro rx 5600 xt. I run a MSI z490 PRO MB with MSI RX 5600 XT Gaming MX video card. Kernel 5.11.4 was released yesterday (my time) with the following fix note:

- A REBAR size quirk for the Sapphire Radeon RX 5600 XT PULSE for AMD Smart Access Memory (Resizable BAR) as it only advertised 256MB/512MB/1GB but it also supports 2GB/4GB/8GB so a rebar size quirk is now added to fully access the BAR0.

Enabling Smart Access Memory in the BIOS combined with a kernel upgrade seems to have (fingers and toes crossed) resolved the issue. Last night and again this morning have been able to run WoW with dx12 and no stability issues. No other render apps we use have died and no graphics errors.

For the moment it seems fixed, but am testing with 5.12-rc2 (which has the same fix) on a clean build to see if it is this. Mesa 21.0 (after rc4) builds have other issues with Battlenet not loading I haven't bothered to explore yet...

**Comment by jhu54** [comment]
Perhaps not: found this entry


Matus Zajac
Matus Zajac @matuszajac · 4 months ago

I'm on a Sapphire 5600 XT running Manjaro, kernel 5.10.0-rc1-5-tkg-bmq, I'm seeing this issue when running game FIFA2019 with DX12 - using Lutris profile, Wine 5.19, VKD3D If i start game with DX11 - DXVK 1.7 everything goes fine.

mesa-tkg-git 20.3.0_devel.130440.0e7d45c89a5-1 lib32-mesa-tkg-git 20.3.0_devel.130440.0e7d45c89a5-1

after this cras computer freez completly... sometimes i can change console - and reboot

amdvlk_loader_fifa_vkd3d_crash.log

radeon_loader_fifa19_vkd3d_crash.log

inxi_Fxxxz

lshw_c_display.log
Edited by Matus Zajac 4 months ago

https://gitlab.freedesktop.org/drm/amd/-/issues/934 - lots of discussion but nothing really matches what I am experiencing except this entry...

That said, I tried a few of the kernel parameters and RADV/amdgpu options and now the crashes are hours apart when gaming. Shaping up to be some sort of shader error passing to the display driver from what I can intimate from this thread and others.

**Comment by jhu54** [comment]
A wet rainy day and I found a lot more information which points to the d3d12.dll being the issue here.

To test, I am now running 5.11.7-xanmod1 kernel, wine-staging-6.4-tkg as the base. I have added Warframe to Lutris for testing. Directx 12 (beta) was selected as the Graphics API for all tests (runs well with DirectX 11 in all scenarios)..
Used the default installer and settings in Lutris to install the game with e and f sync enabled (patched kernel and wine).

**test 1:** dxvk version 1.8.1
Confirm Warframe and allow cinematic to run - occasionally gets through but within 2 minutes of game play, graphics crashes requiring hard reset.

**test 2:** dxvk version 1.7.3
Same as above.

**test 3:** dxvk version 1.7.2
Have been able to complete the first area to the extraction point - some slight graphics issues evident.

Repeating test for World of Warcraft with dxvk version 1.7.2 has so far been stable without any further graphics crashes. FPS is lower than the 1.8.1 (for the brief times it is playable) and slightly lower than the dx11 play.

**Comment by jhu54** [comment]
Using the above setup and the dxvk 1.8.1 directory, I repeated the above tests using the 2.0, 2.1 and 2.2 release files for vkd3d-proton with only the 2.0 release working for Warframe. 2.1 gave some image artifacts before the graphics crash. 2.2 crashed during the cinematic on 3 attempts after selecting the warframe.

World of Warcraft was running for about an hour with light play on 2.1 before the graphics crashed. FPS is still lower than dx11. With 2.0, have been playing some heavy battlegrounds - fps is much lower than dx11, but in the last 2 hours, haven't had a graphics crash. Going to keep it running to see if it stable or will just crash after a longer period of time.

**Comment by jhu54** [comment]
Completed some more testing today with the latest AMDVLK (v-2021.Q1.6) drivers installed. VK_ICD_FILENAMES was explicitly set to /etc/vulkan/icd.d/amd_icd64.json (location where the installer placed this file). DRI3 was enabled as recommended. 

Here is the updated test system:

System:
  Host: GGI-LinuxMint Kernel: 5.11.8-xanmod1 x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM 
  Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
CPU:
  Topology: 6-Core model: Intel Core i5-10400F bits: 64 type: MT MCP 
  arch: N/A L2 cache: 12.0 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 69597 
  Speed: 4231 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 4222 2: 4199 
  3: 4154 4: 4272 5: 4141 6: 4195 7: 4146 8: 4227 9: 4236 10: 4229 11: 4195 
  12: 4145 
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
  vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 03:00.0 
  chip ID: 1002:731f 
  Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa alternate: nvidia 
  resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD Radeon RX 5600 XT (NAVI10 DRM 3.40.0 5.11.8-xanmod1 
  LLVM 12.0.0) 
  v: 4.6 Mesa 21.1.0-devel (git-befd9fb 2021-03-21 focal-oibaf-ppa) 
  direct render: Yes

Using wine-staging-6.4-tkg and Lutris 0.5.8.2. To rule out X being involved, the same hardware was used with the daily build of Ubuntu 21.04 using Wayland and the unpatched 5.11.6 kernel and fsync disabled in Lutris (yes also ran a control in the X environment with non-fsync kernel and both patched and unpatched Wine builds).

Tests 1-3 were run with both Warframe and World of Warcraft explicitly using dxvk version 1.8.1 and the AMDVLK (amd_icd64.json) vulkan on the Linux Mint system.

In all tests with both games, no freezes were evident. Stuttering during action scenes was common in Warframe and fps in WoW was much lower, in many cases half of the RADV drivers (before crash of course).

Also rolled back to the dxvk version v1.7.1L-743f309 and again no issues, fps was close to the RADV and under Warframe, play was smooth.

Repeated the tests on the Ubuntu 21.04 with the same results and no difference in observed fps or behaviour from the Linux Mint 20.1 tests.

**Comment by jhu54** [comment]
Thought I would post a quick update:

I have been playing WoW with dx12 (dxvk version 1.8.1, vkd3d version 2.2) with Mesa 21.1.0-devel (git-a7c0cf5 2021-03-26 focal-oibaf-ppa) since it was installed with so far no crashes. I checked on Warframe and have had 2 crashes with Warframe, one at the intro and the second after about an hours play. Actually looking promising here. 

Installed Mesa 21.1.0-devel (git-4b12171 2021-03-27 focal-oibaf-ppa) a few hours ago and have been running some tests in WoW while doing other work and no crashes...

Grabbed a rx 6700 xt to test as well and results for it are the same as for the rx 5600 xt, both with crashes and now today with successful running and no crashes. Would be great if this is a long term fix, but lets wait and see...

**Comment by Rugaliz** [comment]
Hope some fix is found.
I have similar issues with my Saphire 5600XT. My CPU is Ryzen 5800x with latest fedora kernel 5.11 and mesa 20.3 and proton 6.3. 
I don't play WOW but same "crash" happens with Resident Evil 3 (and other games). With RE3 I found out that I could repeat the crash right after game boot in the bridge cutscene right after Nemesis jumps out of the water. At this point, image freezes, saphire LEDs on card and fans stop for a while then come back on.
However for me this happens with DX11, and funny enough switching to DX12 enabled me to pass this stage without crashes. Been playing some hours now with DX12 set on RE3 and no crash so far.

Also is it normal for VK3D to use much more CPU than dxvk? My CPU temps jump 30 ºC
from using DX11 to DX12 on RE3.

I can't quite recall but I think the same kind of crash occurred to me while playing DOTA2, but here I'm using Vulkan directly without any translation from DirectX...

**Comment by Rugaliz** [comment]
After some more testing it seams RE3 also crashes under DirectX12 and VK3D...
I'm starting to think all 5600XT cards are just under a design flaw.

**Comment by jhu54** [comment]
I switched to an rx 6700 xt and still have the same issues with it. On my gtx 1060, dx 12 runs without a hitch. I have been keeping a log of what works and doesn't work with a stable build to revert to when shit hits the fan. This is my stable config:

libdrm: 2.4.104+git2103241700.f5abbc~oibaf~f
Mesa: 21.1.0-devel (git-5c8a7fa6 2021-03-31 focal-oibaf-ppa)
Kernel: 5.11.11-xanmod1

With this config, I sometimes have a graphics crash with Warframe, but a hard reboot and launch the game again and can play for hours without a problem, same for World of Warcraft. If I install the latest release of libdrm, gpu crash on the load screen for WoW and on the Location selector in Warframe. I don't have the issue if I use amdvlk instead of mesa, but performance is terrible. dx 12 puts a lot more on the gpu vs dx 11 which uses more cpu. 

The libdrm is interesting. If I use dx 11 with latest libdrm, no issues across the board. Still, there have been 3 game updates since my last post for Warframe and one for WoW. It is possible that they have addressed some of the issues with dx 12 in those.

**Comment by jhu54** [comment]
System:
  Host: GGI-LinuxMint Kernel: 5.12.0-051200rc7-generic x86_64 bits: 64 
  compiler: N/A Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM 
  Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
CPU:
  Topology: 6-Core model: Intel Core i5-10400F bits: 64 type: MT MCP 
  arch: N/A L2 cache: 12.0 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 69597 
  Speed: 801 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 834 9: 3472 10: 2298 11: 1127 
  12: 800 
Graphics:
  Device-1: AMD vendor: Tul driver: amdgpu v: kernel bus ID: 03:00.0 
  chip ID: 1002:73df 
  Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa alternate: nvidia 
  resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD NAVY_FLOUNDER (DRM 3.40.0 5.12.0-051200rc7-generic 
  LLVM 12.0.0) 
  v: 4.6 Mesa 21.2.0-devel (git-55fb941 2021-04-16 focal-oibaf-ppa) 
  direct render: Yes 

With this config, no longer does the gpu crash, just the game. Here is the error returned:
![Screenshot from 2021-04-10 15-20-11](https://user-images.githubusercontent.com/77519378/115011875-7b218280-9ef2-11eb-8770-786445c9cfab.png)

**Comment by jhu54** [comment]
Closing this one - memory error shown here was real - when I swapped to a 11600K, and ran aida64, uncovered an error with my PNY ram running at its listed speeds. New ram in, and now haven't had an issue in a week.
