### ISSUE TITLE
Installing vkd3d-proton

### ISSUE THREAD

**Issue by FireBurn** [HansKristian-Work/vkd3d-proton#559]
Hi

I'm running vkd3d-proton against wine-staging - which works great btw

I'm using the following patch against the installer however, as it currently fails when the dll file doesn't exist:

```
diff --git a/setup_vkd3d_proton.sh b/setup_vkd3d_proton.sh
index 6b0ed126..c7d264d1 100644
--- a/setup_vkd3d_proton.sh
+++ b/setup_vkd3d_proton.sh
@@ -111,17 +111,12 @@ installFile() {
   fi
 
   if [ -n "$1" ]; then
-    if [ -f "${dstfile}" ] || [ -h "${dstfile}" ]; then
       if ! [ -f "${dstfile}.old" ]; then
         mv -v "${dstfile}" "${dstfile}.old"
       else
         rm -v "${dstfile}"
       fi
       $file_cmd "${srcfile}" "${dstfile}"
-    else
-      echo "${dstfile}: File not found in wine prefix" >&2
-      return 1
-    fi
   fi
   return 0
 }
```

I was wondering if there was a better way to deal with it

**Comment by WinterSnowfall** [comment]
Noticed it as well with wine-staging - I'm guessing proton does not have this problem. Why not do a PR directly and ask for feedback? I would do:

```
     if [ -f "${dstfile}" ] || [ -h "${dstfile}" ]; then
       if ! [ -f "${dstfile}.old" ]; then
         mv -v "${dstfile}" "${dstfile}.old"
       else
         rm -v "${dstfile}"
       fi
     fi
     $file_cmd "${srcfile}" "${dstfile}"
```
since the subsequent checks make little sense if the file is absent.

**Comment by FireBurn** [comment]
My patch was a work around, and dont feel like its the right way to go

If the Devs are happy with it, or what you've done I'll submit a pull request

**Comment by Joshua-Ashton** [comment]
I am more curious as to why you don't have a d3d12 to replace...

**Comment by WinterSnowfall** [comment]
wine-staging does not add one in system32 or syswow64

**Comment by FireBurn** [comment]
There's no dlls if you build wine-staging without vkd3d support

If you enable vkd3d support it requires the upstream vkd3d or it'll fail in the configure

It seems a bit pointless doing all that when you're replacing the dlls with vkd3d-proton after anyway
