### ISSUE TITLE
Forza Horizon 4 (1293830) - Instantly closes

### ISSUE THREAD

**Issue by cow-killer** [HansKristian-Work/vkd3d-proton#560]
Tried Proton Experimental with the latest commit of vkd3d-proton and DXVK, game closes quickly after launching it. No windows or anything. Log is [here](https://gist.githubusercontent.com/cow-killer/bf388a84468b83fb0183277d43028ebf/raw/70c2eb9cf931823a7f425e99ab63eb4ee1277ceb/steam-1293830.log).

I'm guessing it has something to do with having to sign into Xbox Live when launching the game for the first time. Tested on a GTX 1660 with 460.56 drivers.

**Comment by doitsujin** [comment]
The link doesn't work.

Also, we implement D3D12, not Xbox Live. If there's an issue with that then it's not really useful to report this to vkd3d.

**Comment by cow-killer** [comment]
My bad, how about this: https://gist.githubusercontent.com/cow-killer/bf388a84468b83fb0183277d43028ebf/raw/70c2eb9cf931823a7f425e99ab63eb4ee1277ceb/steam-1293830.log

**Comment by cow-killer** [comment]
Great, I guess we can close this then.
