### ISSUE TITLE
Request for setting VKD3D_CONFIG from a config file (similar to DXVK)

### ISSUE THREAD

**Issue by oscarbg** [HansKristian-Work/vkd3d-proton#591]
Hi,
with VKD3D_CONFIG supporting now dxr,force_static_cbv,multi_queue,etc.. now seems (at least for me) easier to switch fast between a combination of these options by using a config file much like DXVK supports..
also for me is easier to put a customized config file for a game on game folder and be sure config is OK rather than setting env variables prior to launching a game launcher like heroic launcher or steam.. these launchers allow setting env variables per game but seems also easier to switch VKD3D config by changing preexisting cfg files than keep changing same env variable.. 
of course a config file could allow overriding also all other VKD3D env variables like:
VKD3D_SHADER_DEBUG,VKD3D_DEBUG,etc..
thanks..

**Comment by Joshua-Ashton** [comment]
We don't have any useful options for users other than flags right now so it'd be a bit awkward.

I think the current system is fine as it is tbh.

If we have more options with more types down the line it may be something to consider.

**Comment by oscarbg** [comment]
Ok.. will close.. and reopen in case wanted later..

**Comment by Alexander020304** [comment]
I would like this because 3rd party launcher does not support launch options currently
