### ISSUE TITLE
Bugs when running StarsX DXR samples: DXRVoxelizer and RayTracedGGX..

### ISSUE THREAD

**Issue by oscarbg** [HansKristian-Work/vkd3d-proton#592]
Hi,

I'm testing some DXR samples from StarsX github site (https://github.com/StarsX).. 

tried to run a few under VKD3D and found two that don't work (don't launch or don't render correctly)..
note testing is easy as cloning the repos pointed below, as they include prebuilt executables in the Bin folder that can be executed directly to expose the shown VKD3D rendering issues..
I'm using latest DXR VKD3D code from using artifact from https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/665766380 on Windows..

*RayTracedGGX sample (https://github.com/StarsX/RayTracedGGX):
doesn't launch..
testing bunny.bat ie:
RayTracedGGX.exe -mesh Media/bunny.obj 0.0 0.0 0.0 1.0
from log error seems to be:

2052:err:vkd3d_dxil_log_callback: dxil-spirv: AGGREGATE unimplemented.

full log
[bunny.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6168850/bunny.txt)

*DXRVoxelizer sample(https://github.com/StarsX/DXRVoxelizer):
starts but renders black screen..
using dragon.bat ie:
DXRVoxelizer.exe -mesh Media/dragon.obj

from log seems no significant info:
[dragon.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6168856/dragon.txt)

**Comment by HansKristian-Work** [comment]
![Screenshot from 2021-03-22 17-03-15](https://user-images.githubusercontent.com/17786731/112020907-0e081080-8b31-11eb-9fd3-8a230ff9d961.png)
![Screenshot from 2021-03-22 16-39-58](https://user-images.githubusercontent.com/17786731/112020914-0ea0a700-8b31-11eb-9f0c-ce791f90701a.png)
![Screenshot from 2021-03-22 16-35-54](https://user-images.githubusercontent.com/17786731/112020916-0f393d80-8b31-11eb-98af-027f57eb16dc.png)

**Comment by oscarbg** [comment]
can’t avoid saying this: awesome!! reiterating thanks to vkded devs as always for your herculean efforts!!
