### ISSUE TITLE
DXR issues testing 3 initial NV DXR tech demos..

### ISSUE THREAD

**Issue by oscarbg** [HansKristian-Work/vkd3d-proton#596]
Hi,
now that seems Ghostrunner DXR should be working with latest VKD3D master I wanted to test 3 initial DXR demos NV released in March 2019 jointly or in similar timeframe with Pascal DXR enabling driver..
I say that because 2 of the 3 demos (Reflections demo and Atomic Heart) are also UE4 based (with DXR support)..
one curiosity altough UE4 initial DXR support was released with 4.22 release (https://developer.nvidia.com/blog/introduction-ray-tracing-unreal-engine-422/) I checked both demos and they are UE 4.20 based, so surely very early DXR support altough they still run with current Windows and drivers..
direct links to demos (all around 4-5GB) are available for example here:
https://www.techpowerup.com/254541/nvidia-also-releases-tech-demos-for-rtx-star-wars-atomic-heart-justice-available-for-
download

All fail similarly using latest from master (https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/680551874)
Atomic Heart:
![atomicheart](https://user-images.githubusercontent.com/669305/112260749-d0a79e00-8c6a-11eb-9ce6-008e19090793.jpg)
Reflections Demo:
![reflectionsdemo](https://user-images.githubusercontent.com/669305/112260743-ceddda80-8c6a-11eb-9303-41fea4ce3fe9.jpg)

note: reflections demo runs fullscreen with default screen resolution and requires "a lot" of VRAM as even my Titan V with 12GB sometimes  fails to launch with allocation errors on native DX12..
note 2: all demos support DLSS 1 & I test on Windows and since these are NV tech demos don't know if even fixing some underlying VKD3D bugs these demos will launch due to default DXVK DXGI reporting AMD GPU by default (DXGI: NvAPI workaround enabled, reporting AMD GPU) or some other NV NVAPI issue..

Justice RTX demo seems a custom 3d engine and fails silently to launch without errors.. (maybe due to mentioned note 2 reasons?)
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6194656/log.txt)

note 3: curiously Justice RTX demo ships and seems to use GFSDK_ShadowLib_DX12.win64.dll wondering if it's enabling conservative rasterization if available similar to FF XV.. I mean DXVK commit : https://github.com/doitsujin/dxvk/commit/2f553b5b164a280b1e452820ac2b3898292d8912 says :"Needed for Nvidia ShadowLibs in Final Fantasy XV"

**Comment by doitsujin** [comment]
Can you please post logs with `VKD3D_DEBUG=trace`?

**Comment by oscarbg** [comment]
> Can you please post logs with `VKD3D_DEBUG=trace` instead of screenshots of an error popup?

sure.. no problem.. just give me a day or two..

**Comment by oscarbg** [comment]
OK here they are,
I have tested Reflections Demo with VKD3D_DEBUG=trace and share the log:
[logtrace.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6211827/logtrace.txt)

note: I updated vkd3d with latest (https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/687289359) including conservative raster support in case it helped but seems no change..

note 2: one thing I didn't was aware last time is that demo seems using 2 NV Gameworks libraries in addition to shadowlib, 3 in total:
GFSDK_RTAO_D3D12.win64.dll
GFSDK_ShadowLib_DX12.win64.dll
GFSDK_RTReflections_D3D12.win64.dll
are present in subfloders in: Reflections_Demo\Engine\Binaries\ThirdParty\GameWorks\
and I'm starting to think if any of these is related to demo failing to launch.. maybe they use nvapi hlsl d3d12 extensions  unconditionally?

also log of atomic heart  with VKD3D_DEBUG=trace very similar:
[logtraceah.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6211852/logtraceah.txt)

finally Justice log no big changes: 
[justicelogtrace.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6211870/justicelogtrace.txt)

also I forgot to mention that this Justice demo launches a GUI which has option to disable dxr at launch, and disabling DXR make no changes (still fails silenctly to launch) so the bug is unrelated to DXR support..

**Comment by DadSchoorse** [comment]
You need a non release build to be able to use `VKD3D_DEBUG=trace` now.

**Comment by SveSop** [comment]
Another demo that "almost starts": [NVIDIA Unreal Engine 4 RTX & DLSS Demo](https://www.guru3d.com/files-details/nvidia-unreal-engine-4-rtx-dlss-demo.html)

[RTX_Showcase.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7232083/RTX_Showcase.log.gz)

**Comment by Blisto91** [comment]
@oscarbg Hello hello and a friendly ping 👋 
Do you still have these issues to this day?

**Comment by Blisto91** [comment]
@oscarbg Double friendly ping :eyes:

**Comment by oscarbg** [comment]
sorry forgot about that!
all three work.. but Reflections_Demo needs https://github.com/SveSop/dxvk-nvapi/tree/elevatordemo branch
I believe only this 2 commits are relevant to the demo:
https://github.com/SveSop/dxvk-nvapi/commit/8098e8400af5bf04e74b8ca3cddf885c9874b84f
https://github.com/SveSop/dxvk-nvapi/commit/4ea1318bc6eccda52ad254f2197d5b92670dd847
