### ISSUE TITLE
Metro Exodus DXR crashes game

### ISSUE THREAD

**Issue by enveeed** [HansKristian-Work/vkd3d-proton#601]
The game runs fine on vkd3d-proton without DXR enabled, but enabling the RTX option in the video settings after launching with `VKD3D_CONFIG=dxr` causes the game to freeze and a few seconds later then pop up with it's own crash reporter.

I've tested DXR functionality with Control and the exact same setup and it works fine there.

Log and vulkaninfo:
[steam-412020.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6215713/steam-412020.log)
[vulkaninfo.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6215714/vulkaninfo.txt)

The games own crash dump - not sure if this is useful.
[MetroExodus_error_report_210327-141800.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/6215717/MetroExodus_error_report_210327-141800.zip)

**Comment by HansKristian-Work** [comment]
Requires local root signature static samplers.

**Comment by HansKristian-Work** [comment]
Local root signatures are implemented now.
