### ISSUE TITLE
Can't run Kingdom Hearts 1.5 + 2.5 HD ReMIX

### ISSUE THREAD

**Issue by xorpix** [HansKristian-Work/vkd3d-proton#604]
Hello!
When i try to run the game (executable of the game or launcher executable it doesn't matter), i get a black screen and one error message spamming in the logs with infinite cycle:
`332:fixme:d3d12_command_list_update_current_framebuffer: Invalid RTV for attachment 0.`
And few other messages which appear very rarely. I'll attach the ghostbin with the log below.
https://ghostbin.com/paste/d2tlt

Will wait for the update on this. Thank You!

**Comment by Joshua-Ashton** [comment]
Needs bundles.

**Comment by Sukid** [comment]
Surprising that this game of all things is using DX12, much more a feature vkd3d doesn't have yet. o_o I wonder why?

I'll just add that I do have the same thing happen, but only if I put the d3d12.dll file in the game folder. Otherwise the game actually fails to link to it completely for some reason. Though that might be some odd quirk of how Heroic Games Launcher sets up the prefix.

**Comment by xorpix** [comment]
What's more funny about this situation is that Kingdom Hearts III runs successfully (but with custom media foundation installation script).

**Comment by Sukid** [comment]
Yeah, III uses DX11 whereas the older game collections use DX12 for some reason.

**Comment by Admiral124** [comment]
>What's more funny about this situation is that Kingdom Hearts III runs successfully (but with custom media foundation installation script).

Apologies for the slightly off topic reply, but which MF installation script did you use to get KHIII to work? I get nothing but a black screen after the copyright information screen.

**Comment by xorpix** [comment]
> Needs bundles.

Do vkd3d devs plan to implement this?

**Comment by doitsujin** [comment]
It's a core API feature so we'll probably have to do it at some point anyway, but it just happens to be one of the most annoying ones.

**Comment by doitsujin** [comment]
Can you test if https://github.com/doitsujin/vkd3d/tree/bundles gets you any further?

In theory this is a complete implementation of bundles, but since we don't have any real test coverage for that I don't expect this to work properly right away.

**Comment by xorpix** [comment]
I need to compile this and then override d3d12 in Lutris settings, right?

**Comment by Sukid** [comment]
@xorpix Yep, do that. I'll also test it myself once I'm done with a few other tasks.

**Comment by MojoJojoDojo** [comment]
> Surprising that this game of all things is using DX12, much more a feature vkd3d doesn't have yet. o_o I wonder why?

Because its a direct port as you can get from Xbox One to PC lol (or at least thats what people figured).

**Comment by Sukid** [comment]
The version @doitsujin linked to indeed gets it to boot! I haven't actually played much yet, but I wanted to make sure I mentioned it at least boots before I forget to say anything at all due to being high.

**Comment by xorpix** [comment]
@Sukid Could You send me compiled dlls please? I can't figure it out..

**Comment by Sukid** [comment]
@xorpix Use dxvk-tools by TKGlitch. https://github.com/Frogging-Family/dxvk-tools
In upvkd3d-proton.cfg, replace the link to the repo with https://github.com/doitsujin/vkd3d, then next to "branch", replace "master" with "bundles".

Then just open a terminal and run ./upvkd3d-proton build and if you're using lutris, then go ./upvkd3d-proton lutris. Otherwise just manually copy the built d3d12.dll into the Kingdom Hearts folder with the executables, and in winecfg set d3d12 to native and dxgi to builtin.

**Comment by xorpix** [comment]
@Sukid Thank You so much for Your explanation. I have the similar problem here. It's a bit different for me though.. When i select a game from the list, it just infinitely spins the heart in the corner.
Here's my log: 
https://ghostbin.com/paste/xXkaP

**Comment by jjtcm** [comment]
I tested the bundles branch with KH2 Final Mix and was able to start and play the game for about an hour without any problems.
Could not see any major graphics errors or the like during the test.
From the performance I have also not noticed a big change compared to Windows.

Tested with a GTX 1080 on wine-tkg 6.3 with Arch Linux.

**Comment by joao-o** [comment]
I also tested kh2 and I was able to get to the menu at least. will report furter after more extensive testing

Tested in gentoo with the bundles branch. game crashed with wine-vanilla-6.0 it looked like some sort of mono crash(wine-mono-5.1.1). after upgrading to wine-staging-6.4 (wine-mono 6.0.0) the game worked. Running a RX480 on 5.10.26 kernel

**Comment by oscarbg** [comment]
Hi,
just confirm that with bundles branch also DX12 SDK sample D3D12Bundles works:
https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12Bundles
wasn't working before of course..

**Comment by xorpix** [comment]
I still can't get it to run. Same errors in logs. Can't figure what i'm doing wrong.

**Comment by joao-o** [comment]
@xorpix I'm running the kh2 executable directly and skipping the launcher, I imagine the other people with positive results are doing the same thing

**Comment by xorpix** [comment]
Oh, i'll try this. Thank You!

**Comment by xorpix** [comment]
Can't manage getting it to work with Launcher. No matter what it shows errors which are decribed in logs above.
