### ISSUE TITLE
Horizon: Zero Dawn crashes after menu screen if using AMD ACO

### ISSUE THREAD

**Issue by benjaminmordaunt** [HansKristian-Work/vkd3d-proton#608]
GPU: R9 380
Proton: tkg-6.5.r1

Release 2.2 of vkd3d-proton enabled me to launch into HZD successfully, but only when the RADV_DEBUG=llvm flag is used. Allowing Mesa to default to ACO results in a crash after hitting "Continue game".

Ideally I want to try out ACO as HZD suffers tremendously from long periods of low FPS (1-5) before restoring to ~30, seemingly at random during gameplay. This occurs with/without async. May be due to 4GB VRAM restriction of this card, but in-game meter suggests I'm within my limits. Idk if the addition of Vulkan layer increases VRAM requirement above what HZD can see?

 I will attach logs when I get a chance.

**Comment by WinterSnowfall** [comment]
> suffers tremendously from long periods of low FPS (1-5) before restoring to ~30, seemingly at random during gameplay.

Have you tried setting `VKD3D_DEBUG=none`? [I was experiencing some major slowdowns in CP2077 at times](https://github.com/HansKristian-Work/vkd3d-proton/issues/465#issuecomment-787084847) and this solved it.

**Comment by doitsujin** [comment]
> Release 2.2 of vkd3d-proton enabled me to launch into HZD successfully, but only when the RADV_DEBUG=llvm flag is used.

Please report this to Mesa, this is probably not our bug.

**Comment by benjaminmordaunt** [comment]
> > suffers tremendously from long periods of low FPS (1-5) before restoring to ~30, seemingly at random during gameplay.
> 
> Have you tried setting `VKD3D_DEBUG=none`? [I was experiencing some major slowdowns in CP2077 at times](https://github.com/HansKristian-Work/vkd3d-proton/issues/465#issuecomment-787084847) and this solved it.

@WinterSnowfall 

This seems to ever-so-slightly help matters, but performance is still unacceptable.
I know this game has issues even on Windows, so I can't expect miracles.

@doitsujin 
I will compile logs and submit to Mesa. Closing for now.
