### ISSUE TITLE
CP2077 mirror flickering

### ISSUE THREAD

**Issue by WinterSnowfall** [HansKristian-Work/vkd3d-proton#610]
At the very start of the Corpo path, during the very first cutscene, the mirror reflection flickers and shows black pixel artifacts around character eyes and other edges. [Here's a recording](https://drive.google.com/file/d/1ISna1V3kcxoN2i5uQM33DvLEUWhr111E/view?usp=sharing).

Everything was fine in this scene with VKD3D-proton 2.1, however the game has also been patched several times since then, so it might be an issue caused by changes to the game engine. I will try VKD3D-proton 2.1 when I get the chance and let you know if it's a regression or not.

The interesting part is that it's the only mirror in the game AFAIK exhibiting this behavior. The mirror in V's apartment bathroom for example looks as expected.

VKD3D-proton version: 2.2.0-7dc2a5cad756957
GPU: Nvidia GTX 1080
Driver: 460.67
Logs: [Cyberpunk2077.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6278347/Cyberpunk2077.log)

**Comment by doitsujin** [comment]
I haven't seen this on AMD, probably the kind of bug that the `mutable_descriptor_type` extension works around.

Please note that the game is known not to work properly on Nvidia cards right now.

**Comment by WinterSnowfall** [comment]
Fair enough, I'll retest whenever Nvidia decides to add the extension to their drivers. To be honest the game is quite stable ever since patch 1.2 came out. There are no more crashes or other issues I have run across previously with VKD3D-proton.

**Comment by RoyShapiro** [comment]
@doitsujin Hi. Does "not working properly on Nvidia" also refer to sun shadows during the day (not observed during other times, such as night or twilight) being all "odd" (appearing and disappearing at weird view angles) and floors/ceilings/walls within the small buildings being blindingly overglared, and also to a strange "heartbeat" pulsing of the frametime graph as observed with mangohud (as if there were consistent stutters every few seconds)? Because this behaviour is what I currently have on RTX3090. This is a bug introduced in CP2077 patch 1.2, if I roll back to 1.12, this entire behavior disappears. GOG version.

I haven't yet reported said things properly yet, wanted to confirm other people have them too first, as I'm almost certain it was already reported a number of times.

**Comment by WinterSnowfall** [comment]
>  floors/ceilings/walls within the small buildings being blindingly overglared

Now that you mention it I've also noticed this, but not any of the rest of the issues you've listed. Guess it makes sense for us to wait for yet more patches from CDPR and `mutable_descriptor_type` to show up in the Nvidia drivers, as per @doitsujin's input above.

P.S.: Regarding frametimes (and I do feel I'm beggining to sound like a broken cassette player...) make sure you try setting `VKD3D_DEBUG=none`. It made a world of difference in my case.

**Comment by doitsujin** [comment]
> @doitsujin Hi. Does "not working properly on Nvidia" also refer to sun shadows during the day

It means that we don't care about Nvidia issues with this game right now since it's *known* to be broken. Pretty much anything can happen when the game reads the wrong descriptors, including crashes, broken/missing geometry, and pink unicorns.

**Comment by kakra** [comment]
> and pink unicorns.

I want those, please implement. ;-)

@RoyShapiro Shadows look fine for me, maybe this behavior changes with different graphic details settings (I'm running on "high" preset)? But I probably can confirm the overglared images, especially when driving first person and moving between different lighted areas, I feel like I need atomic-nuke-proof sunglasses sometimes. The overglared walls inside building seems to be an issue in Windows also - by following some let's play videos on Youtube (without spoiling myself, I only watch the ones that cover story missions I've already done).

**Comment by WinterSnowfall** [comment]
Parking this until the game is more stable and officially supported by vkd3d-proton. I'll ask you to reopen it if it's still a problem once we get to that point.
