### ISSUE TITLE
F1® 2020 (1080110) - Artifacts on various assets (Cars & Character)

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#611]
### Description:
**_F1® 2020_** (1080110) in DirectX 12 mode exhibits the same artifacts that were originally reported with DXVK on it and various other F1 franchise titles ([F1 2018](https://github.com/doitsujin/dxvk/issues/1897), [F1 2020](https://github.com/doitsujin/dxvk/pull/1907)). The issue is most notable when viewing vehicules in the "Showroom" or editing your character in the "Customisation" sections (available from the main menu).

|VKD3D-Proton | Windows |
| ---- | ---- |
|![F1 2020 - DirectX 12 - Proton 6 3-2](https://user-images.githubusercontent.com/761853/114227733-5bfb8180-9943-11eb-9ff8-04d6f4271fac.png)|![F1 2020 - DirectX 12 - Windows](https://user-images.githubusercontent.com/761853/114227557-25256b80-9943-11eb-8b9f-993b4f521e98.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Notes
- On Windows, the title crashes at launch or remains stuck on a black screen with VKD3D-Proton.

### Software information
[F1® 2020](https://store.steampowered.com/app/1080110/F1_2020/) (1080110)

### System information
OS: Ubuntu 20.04
GPU: Nvidia GeForce GTX 1060 / AMD Radeon RX 580
Beta Drivers: 460.67 / 	21.0.2\~kisak1\~b
Wine version: Proton 6.3-2
VKD3D-Proton version: 2.2 / Master (eca8e49)

### Log files
VKD3D Log (w/ VKD3D_SHADER_DEBUG=trace): [F1 2020 - VKD3D.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/6287895/F1.2020.-.VKD3D.zip)

### API Trace
Trace: (Title crashes on launch when attempting to trace using https://github.com/Joshua-Ashton/apitrace/releases/tag/d3d12-alpha-2)

**Comment by Shadistikk** [comment]
https://github.com/doitsujin/dxvk/commit/f869881f558d4abac12018fbf59c896643e21de3 related, same was happening on DX11 as well.

**Comment by doitsujin** [comment]
Game bug, it's really crazy that they ship the same broken shaders in four games in a row with literally no changes.

**Comment by Joshua-Ashton** [comment]
Does this branch fix the issue? https://github.com/HansKristian-Work/vkd3d-proton/tree/f1-2020-war

Automatic builds are available there also.

**Comment by ZereoX** [comment]
Hi @Joshua-Ashton,

I can confirm that the `f1-2020-war` branch build provided [here](https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/740868991) does indeed resolve this issue.

Thanks.

| f1-2020-war |
| ---- |
|![image](https://user-images.githubusercontent.com/761853/114399469-f2f85180-9b6e-11eb-85e9-da4623ebadbc.png)|

**Comment by Joshua-Ashton** [comment]
Nice, made it a PR: https://github.com/HansKristian-Work/vkd3d-proton/pull/615
