### ISSUE TITLE
usage of DXVK's DXGI config options possible?

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#612]
Since DXVK's dxgi.dll is still used, I wonder if it would be possible to make the DXGI config options (CPU prerender limit, vsync interval, backbuffer queue length...) available also in VKD3D-Proton?

**Comment by Joshua-Ashton** [comment]
Not without significant work and a whole set of inter-op stuff and making generic versions of configs and yeah... Not really worth it.
