### ISSUE TITLE
Allow to exclude tests from the testsuite

### ISSUE THREAD

**Issue by hakzsam** [HansKristian-Work/vkd3d-proton#617]
Adding VKD3D_TEST_EXCLUDE or something like that would be useful for us to skip tests that are expected to fail for some reasons.

**Comment by doitsujin** [comment]
Ideally no test should fail; what's going on exactly?

**Comment by hakzsam** [comment]
Ideally :) We have one failure on Pitcairn (GFX6), at least and it's really low priority, so excluding it would make sense to me.
