### ISSUE TITLE
DXBC: Correctly fail pipeline compilation if binding is missing

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#618]
If we miss a binding in the root signature, DXBC backend will not fail compilation and we end up hitting driver with broken SPIR-V.

**Comment by doitsujin** [comment]
What are we supposed to do instead?

Only useful thing I can think of is treating these as unbound resources and returning 0 for reads / discarding stores, but that's going to be a huge amount of work given the mess that vkd3d-shader currently is. And it's technically not even our bug.

**Comment by HansKristian-Work** [comment]
Native drivers fail compilation if root signature is broken. The fix in vkd3d-shader is pretty trivial, it just needs to check for error condition before returning.
