### ISSUE TITLE
Forza Horizon 4 - Invalid SPIR-V

### ISSUE THREAD

**Issue by hakzsam** [HansKristian-Work/vkd3d-proton#619]
`error: line 14132: End of input reached while decoding OpVectorShuffle starting at word 69628: missing ID operand at word offset 4.`

[fh4.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6312277/fh4.txt)

**Comment by HansKristian-Work** [comment]
Caused by sliced file write, not a bug.
