### ISSUE TITLE
How open zst file?

### ISSUE THREAD

**Issue by ToGoRo** [HansKristian-Work/vkd3d-proton#624]
How open zst file?

**Comment by Joshua-Ashton** [comment]
On Windows use https://github.com/mcmilk/7-Zip-zstd

On Linux use literally any tool that exists ever.

**Comment by ToGoRo** [comment]
Can you send it simply in zip format?

**Comment by DadSchoorse** [comment]
If you really need a zip you can just use artifacts from github actions CI. https://github.com/HansKristian-Work/vkd3d-proton/actions.html?&query=workflow%3AArtifacts+(Package)+branch%3Amaster+&workflow_file_name=artifacts.yml

**Comment by ToGoRo** [comment]
This archive on Windows 7 work for Cyberpunk 2077?
