### ISSUE TITLE
worse frame time consistency in Hitman 2 vs. native D3D12 in high resolutions

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#626]
(I mentioned this in #299 , but probably worth an extra ticket)
When cranking up render resolution via the game's own resolution scale slider, frame time consistency gets noticeably worse vs. native D3D12 on Windows or lower CPU bound resolutions with VKD3D-Proton. This especially happens when rotating the camera a lot. I assume that this applies to the game in general (any level or rendered scene) with any settings, as long it's GPU bound and resolution is high.

This is VKD3D-Proton with 1440p 170% resolution scale (vsync off, set WINEDLLOVERRIDES="dxgi=n" to make it start with D3D12):
![Screenshot_20210418_151105](https://user-images.githubusercontent.com/13510490/115147332-c0f95a80-a05a-11eb-845e-c81a52b7f890.png)

This is on Windows with 170% resolution as well and native D3D12 (the default RTSS frame time graph should be more sensitive than MangoHUD's default, it would probably be almost a flat line in MangoHUD):
![hitman2_2021_04_18_14_02_12_762](https://user-images.githubusercontent.com/13510490/115147395-0c136d80-a05b-11eb-8ccb-cb403866ba04.png)

Totally uneducated guess: Perhaps uploads to VRAM somehow stall the GPU?

In World of Warcraft, this issue doesn't exist and the frame time graph stays flat even in 5k render resolution:
![Screenshot_20210418_150402](https://user-images.githubusercontent.com/13510490/115148574-7975cd00-a060-11eb-950b-df3748510ebc.png)

RX 6800, mesa git-master a1653854f50aa429cb1a5e0ece063900cc988554, Linux 5.12-rc7 (futex2 enabled), intel_pstate performance CPU clock governor, latest Proton Experimental, VKD3D-Proton c7eb6fdf617e2ec2b46c662f32f308f14a306f81

**Comment by DadSchoorse** [comment]
You could try `VKD3D_CONFIG=multi_queue`, but that might reduce gpu bound perf because it disables image compression. `RADV_DEBUG=dccstores` should recover some of that tho.

**Comment by aufkrawall** [comment]
Wow, `VKD3D_CONFIG=multi_queue` solves the issue entirely and reduces GPU bound performance by perhaps ~1fps :o  (`RADV_DEBUG=dccstores` doesn't seem to affect frame rate in this case):
![Screenshot_20210418_181342](https://user-images.githubusercontent.com/13510490/115152820-0f1a5800-a073-11eb-8dc2-62b792241fee.png)

I should also give Strange Brigade and Shadow of the Tomb Raider a try, as they showed a similar (if not exactly the same) issue.

**Comment by aufkrawall** [comment]
It also helps Strange Brigade D3D12 a lot, though it's not perfect like Hitman 2:
![Screenshot_20210418_185158](https://user-images.githubusercontent.com/13510490/115154232-17c25c80-a07a-11eb-8ca2-1064a93ff62d.png)
It'd be a flat line on Windows (or with native Vulkan). Though maybe there is something else wrong, as turning off the game's latency reduction (CPU prerender limit 1?) option also has a negative effect, which is not the case with native D3D12:
![Screenshot_20210418_185440](https://user-images.githubusercontent.com/13510490/115154271-4b9d8200-a07a-11eb-93df-b7f10eecc232.png)
![Screenshot_20210418_185436](https://user-images.githubusercontent.com/13510490/115154273-4cceaf00-a07a-11eb-8918-8dba2bdb13d7.png)

Of course no big deal, since there is a native Vulkan path. No idea if it would make sense to specifically optimize for this.
Shadow of the Tomb Raider D3D12 crashes in Proton, so I couldn't test that (D3D11 -> DXVK works).

I wonder if it would make sense to already enable `VKD3D_CONFIG=multi_queue` for Hitman 1-3 by default? I've tested a few levels in Hitman 2 and it really runs fantastically well.

**Comment by DadSchoorse** [comment]
I think the plan is to make `multi_queue` the default at some point.

**Comment by DadSchoorse** [comment]
I guess this can be closed now that #629 is merged.

**Comment by aufkrawall** [comment]
Ok. Great that this could make it for the next release. :)
