### ISSUE TITLE
Seemingly a regression in 2.3? [HZD]

### ISSUE THREAD

**Issue by benjaminmordaunt** [HansKristian-Work/vkd3d-proton#641]
My experience on AMD now that VKD3D 2.3 is released.

System info:
Kernel: 5.11.14
Mesa: mesa-git 21.1.0_devel.133588
VKD3D-proton: 2.3
CPU: Intel i5-6500
GPU: AMD R9 380 Sapphire 4GB
Proton: 6.5-GE-2

I've checked that 2.3.0 is actually loading in the proton log.

Performance seems practically unchanged and stability actually seems to have been reduced.
For example, changing display settings before launching into the game produces the crash dialog. Dragging this to the side and ignoring it allows the UI to continue to run, but attempting to launch into the game gets stuck on a black screen (main thread dying?) with neverending loading circle.

Using graphical settings which are too high for my specs outright crashes the game.

Fullscreen mode appears to be borked again. This seemed to behave well on 2.2, but now produces the crash dialog, crashing the game for real this time.

It's a shame I didn't see any performance uplift here - was hoping for this game to become playable with this release. I imagine this generation of AMD cards just isn't receiving the love it needs, with a focus on the RX {5,6}xxx series?

Can somebody help me identify whether this is a compatibility layer issue or an issue somewhere else? Thanks.

**Comment by HansKristian-Work** [comment]
R9 380 is pre-Polaris, and I don't any of us is testing this. The only plausible problem would be multi queue enablement. You could try `VKD3D_CONFIG=single_queue %command%` perhaps.

**Comment by benjaminmordaunt** [comment]
Fair enough - I suppose a 6 y/o GPU is teetering on the edge of obsolescence. Just a shame the GPU market is what it is at the moment...

**Comment by D33M0N** [comment]
On the other hand, for me, with Vega 64, HZD fps jumped from 40 to 55 thanks to this release. GREAT WORK and thanks @HansKristian-Work :love_letter:

**Comment by benjaminmordaunt** [comment]
@HansKristian-Work

Hey again, I thought I'd check in again using 2.3.1 and provide some more debug information.

Symptons:
- Game's "an error has occurred" screen appears after hitting "Continue" still displays but ignoring it seems to work at least temporarily.
- Game randomly crashes after a few minutes of gameplay.

I have attached my log here with shader debug on `warn`: 
[steam-1151640.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6387233/steam-1151640.log)

I think this is of interest:
```
ACO ERROR:
    In file ../mesa/src/amd/compiler/aco_register_allocation.cpp:1252
    Failed to allocate registers during shader compilation.
```

Is this something to submit to Mesa?

**Comment by DadSchoorse** [comment]
Yes, that looks like something that should be reported on the mesa issue tracker.

**Comment by DadSchoorse** [comment]
> I think this is of interest:
> 
> ```
> ACO ERROR:
>     In file ../mesa/src/amd/compiler/aco_register_allocation.cpp:1252
>     Failed to allocate registers during shader compilation.
> ```
> 
> Is this something to submit to Mesa?
> I know these GPUs aren't exactly priority, but I'd still like to iron out bugs where possible so I can at least play this - even if it is on low.


Actually, that should not happen anymore since https://gitlab.freedesktop.org/mesa/mesa/-/commit/cc8613c8d5ea4e5497a1c4d6cdcd201a250eb519

**Comment by benjaminmordaunt** [comment]
@DadSchoorse Darn it, the Manjaro and AUR mesa-git packages weren't aligned.
