### ISSUE TITLE
Ghostrunner through Steam with dx12

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#645]
Logged into Steam for the first time in a few weeks and enabled dx12 to run Ghostrunner and received the following error:

![Screenshot from 2021-04-25 11-55-02](https://user-images.githubusercontent.com/77519378/115977673-62356300-a5bd-11eb-8241-0b27ad73638f.png)

Anyone else seeing errors with the Unreal Engine through steam with dx12? Runs just fine with dx11.
Did notice that there were a bunch of steam updates that downloaded as it ran fine with vkd3d 2.2 a few weeks ago.

Current config:
System:
  Host: GGI-LinuxMint Kernel: 5.12.0-rc8-tkg-cfs x86_64 bits: 64 
  compiler: N/A Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM 
  Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
CPU:
  Topology: 6-Core model: Intel Core i5-10400F bits: 64 type: MT MCP 
  arch: N/A L2 cache: 12.0 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 69597 
  Speed: 2528 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 4093 2: 4084 
  3: 4100 4: 4076 5: 4090 6: 4083 7: 3715 8: 4065 9: 3932 10: 3770 11: 3754 
  12: 3148 
Graphics:
  Device-1: AMD vendor: Tul driver: amdgpu v: kernel bus ID: 03:00.0 
  chip ID: 1002:73df 
  Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa alternate: nvidia 
  resolution: 2560x1440~60Hz 
  OpenGL: 
  renderer: AMD NAVY_FLOUNDER (DRM 3.40.0 5.12.0-rc8-tkg-cfs LLVM 12.0.0) 
  v: 4.6 Mesa 21.2.0-devel (git-7e905bd 2021-04-24 focal-oibaf-ppa) 
  direct render: Yes 
vkd3d: 2.3

**Comment by Oschowa** [comment]
What vulkan driver are you using? This error will currently happen with either AMDVLK or the vulkan driver from amdgpu-pro. It should work fine with RADV.

**Comment by jhu54** [comment]
Yep forgot I had installed the AMDVLK drivers to test them. Switch the env variable to RADV and works fine. Thx
