### ISSUE TITLE
DirectX 12 not available as an option with wine-staging 6.7 using Warframe

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#650]
Just cross posting this to keep you in the loop on this "bug". 

https://bugs.winehq.org/show_bug.cgi?id=51062#c11

**Comment by Tk-Glitch** [comment]
This can be closed imho.

Here's 6.8 staging with current vkd3d-proton head:
![Screenshot_20210517_155343](https://user-images.githubusercontent.com/741977/118500566-2eff7300-b728-11eb-9794-24424d18cf04.png)

The game will crash with it, but the option is there. The bug as been marked as invalid on winehq.

Also a duplicate of https://github.com/HansKristian-Work/vkd3d-proton/issues/434

**Comment by jhu54** [comment]
Yeah sorry - forgot to close it last night when I was reviewing my bugs.
