### ISSUE TITLE
CP77 DXR freeze

### ISSUE THREAD

**Issue by aguinet** [HansKristian-Work/vkd3d-proton#652]
Hello everyone,

For the record, I tried Cyberpunk 2077 with DXR activated. Activating DXR in the game config works, but then it freezes after a few seconds of rendering in the actual game. I have to kill the process with `kill -9`. I tried to gdb into the process, but I don't really know which thread should I inspect to debug this...

I launched the game from Steam, using Proton experimental [1]. The command line is the following:

VKD3D_CONFIG=dxr %command% --launcher-skip

I use the official Nvidia driver through their official installer, version 465.24.02.

I verified that raytracing works natively on my setup with https://github.com/GPSnoopy/RayTracingInVulkan .

[1] ~/.local/share/Steam/steamapps/common/Proton - Experimental$ cat version 
1619725651 experimental-6.3-20210429

**Comment by kakra** [comment]
This happens for me, two. Seems to also affect Control (it freezes early in the logo screens or on a black screen, very rarely getting to the menu screen, it would then freeze when continuing your savepoint).

CP77 first launched up the menu, then froze a few seconds within the game. Successive launches then made it crash until I disabled DXR again.

**Comment by luigifcruz** [comment]
In my case, Control works flawlessly and Cyberpunk hangs when loading the game.

**Comment by Continous** [comment]
This is almost certainly an issue with VKD3D's incomplete implementation of DXR, as through my testing Cyberpunk does not hang simply on enabling of DXR. If you enable DXR but do not enable any of the other features, while the game does run like dogshit; the game does not crash. At all. It is only if you enable Raytraced Lighting, Sun Shadows, or Reflections that Cyberpunk 2077 will crash.

Tracking issue #154 maybe be more productive and relevant.

**Comment by shmerl** [comment]
In my experience combining recent radv with `RADV_PERFTEST=rt` and recent vkd3d-proton, CP2077 simply doesn't allow enabling ray tracing in the settings since it claims the card doesn't support it.

**Comment by Continous** [comment]
This may be because the RADV version properly reports only supported extensions, as opposed to just any and all RT extensions.

**Comment by Joshua-Ashton** [comment]
It probably is a RADV issue, it works on NV.

**Comment by Joshua-Ashton** [comment]
It does detect DXR support.

**Comment by shmerl** [comment]
In CP2077 it just doesn't allow to turn it on in the UI with a tooltip "Requires a DXR-read graphics card". So how can you see that it detects it?

From my vulkaninfo

```
RADV_PERFTEST=rt vulkaninfo | rg -i raytrac
VkPhysicalDeviceRayTracingPipelinePropertiesKHR:
VkPhysicalDeviceRayTracingPipelineFeaturesKHR:
        rayTracingPipeline                                    = true
        rayTracingPipelineShaderGroupHandleCaptureReplay      = false
        rayTracingPipelineShaderGroupHandleCaptureReplayMixed = false
        rayTracingPipelineTraceRaysIndirect                   = false
```

**Comment by Joshua-Ashton** [comment]
Are you setting `VKD3D_CONFIG=dxr`?

**Comment by bmd7297** [comment]
I have the same problem with AMD (RADV).

I don't know how to help but I'm getting literally the exact same error.

I've set `RADV_PERFTEST=rt VKD3D_CONFIG=dxr` in the launch settings, but yeah it won't work in CP77.

Strangely it works just fine in Control (albeit with very low FPS), but it doesn't work like at all with CP77.

**Comment by bmd7297** [comment]
```
[Information][ (0)] [TID 328][red-launcher]: Shutting down SSL manager.
libGL error: failed to create drawable
libGL error: failed to create drawable
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  2649
  Current serial number in output stream:  2649
0620:err:vkd3d_dxil_log_callback: dxil-spirv: Requested an alignment of < 4 bytes in RawBufferLoad with texel buffer. This is unimplementable.
0620:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to emit instruction.
0620:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.
```

There's the best log I can give.

**Comment by jarrard** [comment]
Got a 6800XT and mesa-git, tried RADV_PERFTEST=rt VKD3D_CONFIG=dxr in Control Ultimate Edition and well, upon loading it just freezes and soon after I must force restart the desktop. Once it causes graphical distortion on screen. 

Its a shame AMD cards are still not ready for RT under Linux :(

**Comment by shmerl** [comment]
> dxil-spirv: Requested an alignment of < 4 bytes in RawBufferLoad with texel buffer. This is unimplementable.

Does this mean some feature won't ever be supported or this isn't a blocker for CP2077 working?

**Comment by shmerl** [comment]
I found out (just in case someone wasn't aware) that at least [radv is still missing](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5684) some ray tracing Vulkan extensions, namely `VK_KHR_ray_query`, this impacts CP2077.

**Comment by tizzir** [comment]
As of the 1.5 update, the game hangs with a Nvidia GPU after just enabling raytracing in the graphics menu and returning to the game. This is without enabling any of the 3 raytracing effects (reflections/shadows/lighting.)

**Comment by kakra** [comment]
Update 1.5 also freezes the system hard when I tried opening the perks menu: The system no longer responded, audio looped, Alt+SysRq+B didn't reboot the system. Pressing the reset button took around 5 seconds before I could see the desktop slowly drawing from top to bottom, then the system rebooted. Looks like the GPU freezes.

NVIDIA 1660 Ti with 510 beta driver, Proton Experimental as of 2022-02-15, DLSS enabled, raytracing disabled

I didn't yet try to reproduce the problem. Similar freezes could be seen one time or another before, occurring seemingly random in the game but usually when opening the map, the perk tree or the inventory.

OTOH, performance seems to have much improved.

**Comment by nalyDylan** [comment]
> I found out (just in case anyone wasn't aware) that at least [radv is still missing](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5684) some ray tracing Vulkan extensions, namely `VK_KHR_ray_query`, this impacts CP2077.

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14565
There's a ton of work on raytracing being done for radv all of a sudden, assumedly in anticipation of the SteamDeck. Seems to be an all around net positive for AMD owners though

**Comment by tizzir** [comment]
FWIW, I am encountering these crashes on a NVidia 30 series GPU, with the most up to date feature drivers.

I don't know if it's of any use, but when enabling logging, I see plenty of:

```
011c:err:vkd3d_dxil_log_callback: dxil-spirv: TODO: RDAT SubobjectTable is not handled
! RTPSO creation will likely fail.
011c:err:d3d12_state_object_parse_subobjects: Failed to parse DXIL library.
```

followed by even more:

```
0118:err:d3d12_device_GetRaytracingAccelerationStructurePrebuildInfo: Acceleration structure is not supported. Calling this is invalid.
```

This occurs when I start the game and turn on raytracing (which crashes the game.)

full log attached:
[cp2077rt.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8128962/cp2077rt.log)

**Comment by eaglemmoomin** [comment]
Just to confirm with the 1.5 patch on a RTX 3080 and the 5.10 driver I also see a crash to desktop after enabling any RT options then trying to run the benchmark,

**Comment by Lsfhv** [comment]
also 1.5 patch on RTX 3070, with these launch options : VKD3D_CONFIG=dxr %command% --launcher-skip
Crash to desktop after enabling any RT options in game.

**Comment by shmerl** [comment]
radv just implemented `VK_KHR_ray_query` and I tried enabling ray tracing in Cyberpunk 2077, but it's still hanging after that.

**Comment by triffid** [comment]
CP2077 (v1.52) doesn't even open a window for me if I specify `VKD3D_CONFIG=dxr` or `dxr11`, just thinks for a few seconds then exits.

I'm running the GOG build through lutris with nvidia drivers v510.54, DXVK v1.10L (L for lutris I guess), VKD3D v2.6, DXVK NVAPI v0.5.3, wine version "`lutris-fshack-7.2-x86_64`", and launch options `-dx12 --launcher-skip -skipStartScreen` with an RTX3070 GPU.

Works great without `dxr`, but it would be nice if I could make it a bit prettier…

**Comment by eXt73** [comment]
> CP2077 (v1.52) doesn't even open a window for me if I specify `VKD3D_CONFIG=dxr` or `dxr11`, just thinks for a few seconds then exits.
> 
> I'm running the GOG build through lutris with nvidia drivers v510.54, DXVK v1.10L (L for lutris I guess), VKD3D v2.6, DXVK NVAPI v0.5.3, wine version "`lutris-fshack-7.2-x86_64`", and launch options `-dx12 --launcher-skip -skipStartScreen` with an RTX3070 GPU.
> 
> Works great without `dxr`, but it would be nice if I could make it a bit prettier…

I can say it. While in version 1.3 it was possible to launch RT shadows and lighting [although with distortions - blue/metallic discoloration], but without RT reflections, from version 1.5 we have a crash immediately.

**Comment by sigzegv** [comment]
I confirm on NV RT was working fine with CP77 v1.3, and totally crashes with v1.5.. Looks like a regression on CDPR that implemented a new thing on RT that is not in vkd3d yet ?

**Comment by shmerl** [comment]
Ray tracing started working in Cyberpunk 2077 in latest Mesa main and vkd3d-proton without crashing the game! Performance is completely tanked though with ray racing enabled 😆, but I wouldn't expect much of this generation of RDNA2 anyway.

Also, looks like some graphics might be not fully correct when ray tracing is enabled.

Set up: Sapphire Pulse RX 6800 XT, 2560x1440.

No RT:

![cp2077_no_rt](https://user-images.githubusercontent.com/310927/170854704-8c7acbdc-887b-4e0a-a382-fe183f98be53.jpg)

RT (all options enabled, lighting setting on ultra):

![cp2077_rt](https://user-images.githubusercontent.com/310927/170854719-76f18709-daa9-4dfc-8221-ef249ff29ada.jpg)

**Comment by eXt73** [comment]
> Ray tracing started working in Cyberpunk 2077 in latest Mesa main and vkd3d-proton without crashing the game! Performance is completely tanked though with ray tracing enabled laughing, but I wouldn't expect much from this generation of RDNA2 anyway.
> 
> Also, looks like some graphics might be not fully correct when ray tracing is enabled.
> 

Wow ... not bad ;) Under Nvidia the game still crashes right away ...

**Comment by jp7677** [comment]
Actually it works perfectly on NVIDIA RTX when using this PR/branch: https://github.com/HansKristian-Work/vkd3d-proton/pull/1094
I needed some time to see the differences between RTX en non-RTX since I have no Windows to compare, but once you know where look for differences (e.g. reflections in the water, shadows in the desert or shadows from bike headlights), it looks really stunning.

**Comment by eaglemmoomin** [comment]
Can confirm with Proton-GE-7.19 RT with NVidia RTX seems to be working. Running the benchmark actually works over several runs. Seeing 71 fps average on balanced with a 3080 and tweaked normal settings plus all the RT settings on at Psycho.

**Comment by spinktvis** [comment]
Confirmed working here as well, Proton GE 7.20. Amazing work! Performance hit is not as severe as I expected. Running on Ultra RT settings.

**Comment by eXt73** [comment]
Unfortunately, there are some bugs - plant shadows in the case of a close source of light, e.g. a street lamp:
![Screenshot_20220529_183048](https://user-images.githubusercontent.com/20760088/171034079-4731f1f2-994c-4dac-a21f-e140d0e43d3b.jpg)

**Comment by K0bin** [comment]
And you're sure those bugs do not happen on Windows?

**Comment by shmerl** [comment]
There are definitely bugs with radv at least. As I posted [here](https://github.com/daniel-schuermann/mesa/issues/36#issuecomment-1140384763).

I'm going to make another test shortly with a recent PR that improves performance.

**Comment by eXt73** [comment]
> And you're sure those bugs do not happen on Windows?

I do not have Windows on any machine = therefore I will not confirm it - is it a result of game errors or VKD3D implementation

**Comment by shmerl** [comment]
With pending [PR !15030](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15030) for radv performance gets better with ray tracing than without it, though it's still not a playable level on those settings.

No ray tracing ~ 86 fps:

![cp2077_no_rt](https://user-images.githubusercontent.com/310927/171036119-7e325c12-c37a-493d-9492-5019486c9caf.jpg)

Ray tracing ~11 fps:

![cp2077_rt](https://user-images.githubusercontent.com/310927/171036174-31b8beec-9f53-43a3-9bd6-afae5b5b4033.jpg)

Notice also that visuals don't look correct (for example reflections don't seem to work at all), so things aren't fully implemented yet I assume.

**Comment by jp7677** [comment]
> Unfortunately, there are some bugs - plant shadows in the case of a close source of light, e.g. a street lamp: 

From what I'm seeing, Proton GE uses vkd3d-proton from master. As stated earlier, you really need this (draft-) PR/branch https://github.com/HansKristian-Work/vkd3d-proton/pull/1094

**Comment by eXt73** [comment]
> > Niestety jest kilka błędów - cienie roślin w przypadku bliskiego źródła światła, np. lampy ulicznej:
> 
> Z tego co widzę, Proton GE używa vkd3d-proton z mastera. Jak wspomniano wcześniej, naprawdę potrzebujesz tego (szkicowego) PR/oddziału #1094

Unfortunately, I do not have time to compile VKD3D on my own - so I will probably have to wait for these patches to be transferred to master and compilation by GE ;)

**Comment by eXt73** [comment]
> > Unfortunately, there are some bugs - plant shadows in the case of a close source of light, e.g. a street lamp:
> 
> From what I'm seeing, Proton GE uses vkd3d-proton from master. As stated earlier, you really need this (draft-) PR/branch #1094

Unfortunately, I do not have time to compile VKD3D on my own - so I will probably have to wait for these patches to be transferred to master and compilation by GE ;)

**Comment by jarrard** [comment]
Yeah AMDGPU+RADV are pretty terrible still. I doubt even RDNA3 will change that. Could be years before RT becomes viable for AMD cards under Linux.  

NVIDIA REALLY have complete dominance if your even remotely interested in stuff like RayTracing and DLSS.  Many still consider those two things fake and scam effects but their not.  

I don't know how the AMDGPU-PRO or amdvlk does with RT but I wouldn't be surprised if it didn't even boot the game in most instances.

It's a real shame as RT under Windows for AMD cards is not terrible, normally about %30 slower then NVIDIA if you ignore DLSS!

**Comment by jarrard** [comment]
> I do not have Windows on any machine = therefore I will not confirm it - is it a result of game errors or VKD3D implementation

I could test this out under Win10 sometime. 
I have it on dual-boot backup (separate SSD) for testing purposes like this.  
Allot of people using NVIDIA vs AMD RT comparisons forget they turn on DLSS. You gotta turn that off to really compare. 
It be nice if FSR2 was in more games but that will likely take a few years.

**Comment by shmerl** [comment]
> Yeah AMDGPU+RADV are pretty terrible still. I doubt even RDNA3 will change that. Could be years before RT becomes viable for AMD cards under Linux.

Let's not get off-topic. It's about the stack not using hardware fully. It's very usable already if the driver would actually be optimized for it.

**Comment by jarrard** [comment]
> It's very usable already if the driver would actually be optimized for it. And it indeed has nothing to do with DLSS. radv and vkd3d-proton are progressing there.

First sentence is contradiction. Secondly DLSS is relevant because people are DIRECTLY comparing AMD performance with NVIDIA+DLSS... Lets not do that shall we!

**Comment by shmerl** [comment]
Not sure what people are comparing, DLSS is irrelevant to the above really, so I agree that it's not appropriate to bring it into the comparison even.

**Comment by mercuriete** [comment]
Remember to enable dynamic resolution scaling and FSR to auto.
I have a 6900XT and on windows I need to enable that in order to have 60fps on cyberpunk.

I will do some test on my gaming rig when I have some time.

thanks to the vkd3d-proton team for the amazing job :)

**Comment by coffee-lord** [comment]
Is [this](https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/2313343264) arfifact  (it's a recent CI run from #1094) a debug or a release build? Can we use that until it's merged upstream/GE?

It seems to work fairly well but the perf diff is noticable.

**Comment by tizzir** [comment]
@coffee-lord I'm not sure about the artifact you've linked, but here is a version I've compiled that seems to work just fine for all RT features in the game:
[cp2077rt_vkd3d-proton.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8820079/cp2077rt_vkd3d-proton.zip)
.

**Comment by eXt73** [comment]
> @coffee-lord I'm not sure about the artifact you've linked, but here is a version I've compiled that seems to work just fine for all RT features in the game: [cp2077rt_vkd3d-proton.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/8820079/cp2077rt_vkd3d-proton.zip) .

oki thanks for this compilation - you can see you have to do it yourself, but I already work sometimes after 12-18 h = continuous lack of time: P Confirm - I did a quick test - as you can see EVERYTHING works perfectly + higher efficiency and best of all, it does not clog VRAM. It manages to go down from the maximum 6 GB VRAM to about 5.5 - 5.7 = no clipping ... Late in the evening I will see a stationary RTX 3060 with 12 GB VRAM. Thanks again for this compilation.

![Screenshot_20220602_110759](https://user-images.githubusercontent.com/20760088/171597545-5f395351-bea7-42b0-9e9b-621f5b9d2678.jpg)
![Screenshot_20220602_110746](https://user-images.githubusercontent.com/20760088/171597553-690e45c8-be7e-41d2-8d24-eaea05dc40f7.jpg)
![Screenshot_20220602_110734](https://user-images.githubusercontent.com/20760088/171597556-57951246-5b9c-4708-affa-fc8a8308c4fe.jpg)

**Comment by eXt73** [comment]
In addition to correctly generated shadows, the issue of rendering of reflections has also improved - you can see it in both Cyberpunk 2077 and Dying Light 2. Below is an example in CP2077:

VKD3D - Master:
![Screenshot_20220601_130636](https://user-images.githubusercontent.com/20760088/171801418-bb34d013-8b24-42b6-b119-b4e2b33b9ec1.jpg)
![Screenshot_20220601_130612](https://user-images.githubusercontent.com/20760088/171801420-deb27695-91f2-4894-842f-3affa4e8b8e1.jpg)

VKD3D with fixes - build by tizzir:

![285823091_5430628923667223_5607200234512682760_n](https://user-images.githubusercontent.com/20760088/171801617-d98546e4-6665-448f-b84a-5961901ab979.jpg)
![285760245_5430628897000559_5204192399629429617_n](https://user-images.githubusercontent.com/20760088/171801620-656e9148-23ae-400f-a802-62250ce015fe.jpg)

**Comment by gardotd426** [comment]
#1094 says it's been obsoleted, but not merged. What exactly does that mean for anyone wanting to check for improvements? I always build my own VKD3D-Proton, but I just build from master.

**Comment by gardotd426** [comment]
Addendum to previous comment: it looks like the commits from #1094 were committed to master earlier today/yesterday. So master should be enough (though you'll obviously have to compile yourself).

**Comment by shmerl** [comment]
Just tried recent vkd3d-proton and CP2077 instantly crashes with ray tracing is enabled (Mesa main, radv, RX 6800 XT).

Wine: 7.12.

So either it's a regression in vkd3d-proton or it's hitting some stack problem that was happening before when Vulkan stuff was eating too much stack. Wine kind of fixed that, but may be increased usage of RT is causing this again?

**Comment by shmerl** [comment]
See also:

* https://bugs.winehq.org/show_bug.cgi?id=52795
*  https://gitlab.freedesktop.org/mesa/mesa/-/issues/6173

**Comment by shmerl** [comment]
What exactly is missing in radv to support `AddToStateObject`? Just to keep track on when it would be added to test it.

Thanks!

**Comment by aguinet** [comment]
FYI, with the [Proton GE 7-28](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-28) build, RTX works like a charm with an NVIDIA GPU

**Comment by aguinet** [comment]
a

**Comment by shmerl** [comment]
According to [this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6076#note_1682251), radv now possibly should have enough for ray tracing to work in Cyberpunk 2077.

Is something still missing there or it's just the matter of fixing bugs now?

**Comment by shmerl** [comment]
To track it for radv in Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7986

**Comment by shmerl** [comment]
Looks like radv will soon get  fix for the crash!
