### ISSUE TITLE
bad frame time variance in Strange Brigade without latency reduction option

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#656]
When not using the latency reduction option (which is nothing but limiting the number of CPU prerendered frames to a lower value?), the frame time variance basically breaks while being GPU bound:
![Screenshot_20210505_130056](https://user-images.githubusercontent.com/13510490/117149404-7ba58e80-adb7-11eb-8fb6-c17ec7dc72c2.png)
![Screenshot_20210505_130047](https://user-images.githubusercontent.com/13510490/117149406-7cd6bb80-adb7-11eb-9a3f-8448bf9d4d74.png)

Now this is not a tragedy for this individual case, since there is a native Vulkan renderer. Though I wonder if this also affects other games. E.g. also Cyberpunk 2077 is worse than native D3D12 when being GPU bound (whereas not when being CPU bound and CPU bound fps are also very high).

There is this Mesa report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4689
Though amdvlk is severely CPU bound with VKD3D-Proton in Strange Brigade (and other games), which in return means there is no CPU prerender at all then. So I'm not sure RADV can be blamed here.

Latest Proton Exp. with VKD3D-Proton 2.3.1, Linux-tkg 5.12 futex2, mesa git-master 139226.b13d0eea127.

**Comment by aufkrawall** [comment]
Not sure if related, but there's also worse frame time variance in Control vs. native D3D12 or DXVK (especially when running):
![Screenshot_20210615_184714](https://user-images.githubusercontent.com/13510490/122092851-b1a04e80-ce0a-11eb-8afc-ad31f3211d63.png)
![Screenshot_20210615_184041](https://user-images.githubusercontent.com/13510490/122092857-b36a1200-ce0a-11eb-9908-fd1e09da0195.png)

This is with 6d1d60e8988fa923eb23972b8915e10aec62e98f .

**Comment by aufkrawall** [comment]
My frame time variance is fine in both cases with RTX 3060 driver, so this is probably related in some way to RADV.

**Comment by aufkrawall** [comment]
There are frequent stutter spikes in SotTR on RTX 3060, usually when changing camera perspective or when running:
![Screenshot_20210908_161100](https://user-images.githubusercontent.com/13510490/132525964-c59b8eb8-7255-46c7-98aa-dba413a944bf.png)

This is with d2b3238b2dbda67c44ece9672c97bd7dd933eeed and Nvidia 470.62.02 .

**Comment by aufkrawall** [comment]
With recent git-master on RTX 3060 (recent Arch Linux packages), Strange Brigade is now smooth also without latency reduction option ticked.

Shadow of the Tomb Raider is smooth on Windows with VKD3D-Proton. In Proton 7.0-3/Experimental, it still has some stutter issues, but apparently not caused by VKD3D-Proton.

Control is still a bit unsmooth vs. native D3D12.

**Comment by Blisto91** [comment]
@aufkrawall Was this issue solved? 🙂

**Comment by aufkrawall** [comment]
> @aufkrawall Was this issue solved? 🙂

Would have liked to re-test it, but Control doesn't start for me with the new HDR mod (which I use solely for game/engine fixes, not for actual HDR output) & VKD3D-Proton on Windows.

**Comment by aufkrawall** [comment]
Correction, the HDR mod actually works with VKD3D-Proton on Windows.

But frame time variance is still not optimal with latest git-master and Nvidia 528.49 vs. native D3D12 or D3D11 -> DXVK:
![Control_DX12_2023_02_19_18_05_02_882](https://user-images.githubusercontent.com/13510490/219963271-902937f1-f260-4fbe-830b-9788841ff052.png)
![Control_DX12_2023_02_19_18_02_59_390](https://user-images.githubusercontent.com/13510490/219963280-68f004e3-0961-41f7-86e5-a70271452c43.png)

I think the same should be visible in MangoHUD on Linux (as I tested it there originally), frame time graph often shows way more variance than there should be.

**Comment by aufkrawall** [comment]
Control seemed to be fine on RADV with 7800 XT. Closing, as probably not specific enough to justify keeping this open.
