### ISSUE TITLE
do m&ms racing team work?

### ISSUE THREAD

**Issue by BigFatHairyGamer** [HansKristian-Work/vkd3d-proton#661]
![image](https://user-images.githubusercontent.com/56777037/117645218-41a30680-b182-11eb-91e9-a379aef33746.png)

does it work on linux in emulator? i think its originally for the wii, sorry if this is the wrong place

![image](https://user-images.githubusercontent.com/56777037/117645514-99da0880-b182-11eb-85ab-1d67a7713451.png)

i can try it and attach logs later but the game isn't on Steam is that okay?

image above of what the game should look like

**Comment by BigFatHairyGamer** [comment]
i am thinking...

dolphin.. it support direct x 12. maybe you can use it in wine or proton to test to see if this game works?

**Comment by niobium93** [comment]
Dolphin natively supports Linux and Vulkan. You don't need Wine, Proton or vkd3d to use it on Linux.

**Comment by Joshua-Ashton** [comment]
Yes, it does.

![image](https://user-images.githubusercontent.com/21316711/118102374-9f2c9280-b3d0-11eb-9110-a78b45eda706.png)
