### ISSUE TITLE
DIRT 5 rendering issues

### ISSUE THREAD

**Issue by CME42** [HansKristian-Work/vkd3d-proton#662]
This game has multiple rendering issues with the most prominent one where the sun is too bright in certain areas and time of date (although the lightning is generally off, there are also places where it's too dark, but i don't have any screenshots), missing grass/bushes/trees (visible in the left bottom area of the screenshot) and since today's game update wrong colors on AMD (but i can put the last two in a separate issue if you want).
The issues are also reproducible on windows and nvidia with vkd3d, i haven't tried it with amd+windows yet.

All the graphics settings were set to medium for the screenshots. To reproduce the issue, you have to start an arcade race -> free play -> location: brazil, the redeemer, weather: clear and time: afternoon.

To get the game running you either need WINEDLLOVERRIDES="atiadlxx=b" or DXVK DXGI (I'm using the latter fwiw).

Proton: Experimental
VKD3D: master 1744896142c283433fb490a9f86c013513273df1

Windows AMD native d3d12:
![20210502014450_1](https://user-images.githubusercontent.com/11275913/117874146-ef0c3c00-b2a0-11eb-8d98-e5b1c5fca5df.jpg)
VKD3D nvidia (1060, 465.24.02):
![20210511184118_1](https://user-images.githubusercontent.com/11275913/117874175-f5021d00-b2a0-11eb-91d9-069182c5e7b9.jpg)
VKD3D AMD (both 6900xt and picasso/vega, tested mesa main and 21.0.3)
![20210511205816_1](https://user-images.githubusercontent.com/11275913/117874191-f7fd0d80-b2a0-11eb-8499-a8789f85a135.jpg)
vkd3d log (created on amd): 
[dirt5.txt.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/6461609/dirt5.txt.gz)

I can't provide any apitrace/d3d12 renderdoc/d3d12 nsight since all the tools are failing in one way or another. To capture a vulkan renderdoc it is necessary to use a recent git build.

**Comment by Joshua-Ashton** [comment]
```
native on native trace:
 - no issues
vkd3d-proton on vkd3d-proton trace:
 - intense brightness
 - weird black floor/shadow
vkd3d-proton on native trace:
 - weird black floor/shadow
```

**Comment by HansKristian-Work** [comment]
Fixed on master now.
