### ISSUE TITLE
EA Sports Fifa 21 UI rendering issues

### ISSUE THREAD

**Issue by yoyossef** [HansKristian-Work/vkd3d-proton#664]
A Fifa 21 comparison between DXVK and VKD3D-Proton in the menus, the in-game parts seem to be running just fine (I'll test that furthermore just in case) but the UI isn't.

Proton: 6.8-GE-1 
GPU: AMD 6800 XT, driver: mesa-git
<details>
<summary>Screenshots (DXVK vs VKD3D-Proton)</summary>
<br>
<img src="https://cdn.discordapp.com/attachments/761735275604738100/843409759255265300/unknown.png">
<img src="https://cdn.discordapp.com/attachments/761735275604738100/843411249018175508/unknown.png">
<img src="https://cdn.discordapp.com/attachments/761735275604738100/843409915023196180/unknown.png">
<img src="https://cdn.discordapp.com/attachments/761735275604738100/843411393814200330/unknown.png">
</details>

Logs: [vkd3d_fifa_21.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6488965/vkd3d_fifa_21.log)

Video: https://streamable.com/neoauz

**Comment by HansKristian-Work** [comment]
Seems to have been fixed at some point, because it renders just fine for me on RX 6800.
![fifa](https://user-images.githubusercontent.com/17786731/132345049-8bab09fd-2299-4695-9143-69cfcc567f2e.jpg)
