### ISSUE TITLE
Metro Exodus Enhanced Edition (1449560) - Title requires DXR 1.1 and FP16 support.

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#669]
### Edit:
See comment below: https://github.com/HansKristian-Work/vkd3d-proton/issues/669#issuecomment-899723484

Update logs with 7ff3ef2:
|VKD3D_LOG|VKD3D_DESCRIPTOR_QA|
| ---- | ---- |
|[VKD3D.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7039870/VKD3D.zip)|[VKD3D_DESCRIPTOR_QA.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7039871/VKD3D_DESCRIPTOR_QA.zip)|

### Description:
**_Metro Exodus Enhanced Edition_** (1449560) title reports that the minimum system requirements are not met when launched and closes to a crash handler if **_Run Anyway_** is used. Title indicates it requires SM6.5, but VKD3D-Proton only advertises / supports 6.2 (or 6.3 with `VKD3D_CONFIG=dxr`)

| VKD3D-Proton (2.3.1) | Crash Handler |
| ---- | ---- |
|![Screenshot from 2021-05-23 10-21-25](https://user-images.githubusercontent.com/761853/119345688-3ca48380-bc67-11eb-86d1-50f19a28a6a2.png)|![Crash Handler](https://user-images.githubusercontent.com/761853/119345862-72496c80-bc67-11eb-9019-7281e5659b42.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Notes
- To run this application on Windows, you must be on version **20H2 or newer** to support SM 6.5.
- On Proton 6.3-4, the game remains open as long as the crash handler is not dismissed and plays through the opening cinematic before remaining stuck on a black screen .

### Software information
- Metro Exodus Enhanced Edition (1449560) is available with the purchase of the base game, [Metro Exodus](https://store.steampowered.com/app/412020/Metro_Exodus/).

### System information
OS: Windows 10 Pro 21H1 / Ubuntu 20.04
GPU: AMD Radeon RX 5700 XT
Drivers: 21.5.2 / 21.1.1
Wine version: Proton 6.3-4
VKD3D-Proton version: 2.3.1 / Master (925a930)

### Log files
Log (w/ VKD3D_DEBUG=trace): [MEEE_VKD3D.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6532209/MEEE_VKD3D.log)

### Trace
- Title immediately crashes to desktop when attempting to trace (https://github.com/Joshua-Ashton/apitrace/releases/tag/d3d12-alpha-2) and produces a 0KB file.

**Comment by jqadev** [comment]
@HansKristian-Work @Joshua-Ashton I tested this game against [Proton-6.15-GE-1](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.15-GE-1) containing the latest changes and unmet requirements slightly changed.

![Screenshot from 2021-08-16 20-11-24](https://user-images.githubusercontent.com/20422423/129610473-bc39a8ef-a00d-41ed-9c36-90cba3fa7948.png)

@ZereoX please adjust the title to inform about missing support for both DXR 1.1 and 16bit floating point arithmetic.

**Comment by yhojann-cl** [comment]
Same error using a radeon rx 6800 xt and ryzen 7 5800X3D on ubuntu 22.04 lts.

**Comment by K0bin** [comment]
RT support in vkd3d-Proton and especially in RADV is experimental right now and disabled by default. You need to enable it with the following environment variables: `RADV_PERFTEST=rt` and `VKD3D_CONFIG=dxr,dxr11`. I don't know whether RADV can run Metro Exodus EE (most likely won't run it well though) but it should work on Nvidia GPUs.

**Comment by yhojann-cl** [comment]
> `RADV_PERFTEST=rt` and `VKD3D_CONFIG=dxr,dxr11`

Thanks, i paste this content in launch properties:

```
RADV_PERFTEST=rt VKD3D_CONFIG=dxr,dxr11 %command%
```

But have same warning.

**Comment by ZereoX** [comment]
I can confirm this issue is no longer present on the latest master (08909d9). I was able to proceed into game on Steam Deck by selecting "Run Anyway". 

I also confirmed that exposing DXR via the previously proposed environment variables bypasses the system requirements warning all together:
> RADV_PERFTEST=rt VKD3D_CONFIG=dxr,dxr11 %command%

**Comment by yhojann-cl** [comment]
Thanks, works fine!, using amd radeon rx 6800 xt, ryzen 7 5800x3d and 128gb of ram, in 4k resolution run at 5fps, in 1080p run at ~30fps and the junction temperature of the gpu is 99ºc in 5 minuts of gameplay.
