### ISSUE TITLE
Resident Evil Village: Lens Flare shining through walls

### ISSUE THREAD

**Issue by Oschowa** [HansKristian-Work/vkd3d-proton#670]
In Resident Evil Village, the sun, and potentionally other light sources, shine through walls when they are at the edge of the screen. So far i've only been able to reproduce it about 70% into the game (after you get the 3rd body flask and are on the way to Heisenberg), when sun stands low in the sky. It only happens when 'Lens Flare' is enabled in the game's display settings. I've confirmed this doesn't happen on native d3d12 on the same hardware.

I've tested on a RX580 and proton experimental, also tried vkd3d master, it happens on both RADV and amdvlk{-pro}.

vkd3d trace log: https://drive.google.com/file/d/19dZxWgqzkclAlp6KcPWZz4dx3U_BNEWn/view?usp=sharing

Video of the issue:

https://user-images.githubusercontent.com/8129300/119484943-d008b200-bd56-11eb-8dcb-d18d73d9b396.mp4

I've recorded an apitrace on windows with the latest d3d12 alpha from @Joshua-Ashton , but it fails to replay everywhere properly, i can try again if you have any ideas of what might help: https://drive.google.com/file/d/1vq2uDqlnoVkGpSKpEFPKKZskFLEYMMdI/view?usp=sharing

Also captured a d3d12 and vkd3d/vulkan renderdoc, although i know these are probably useless..
d3d12: https://drive.google.com/file/d/1AU_iusKqvB46Iw3UKvX6wXsgWpP6unFn/view?usp=sharing
vkd3d: https://drive.google.com/file/d/1rNb5tKQrKxpnb80ZustfMuXK2VugCpQe/view?usp=sharing

**Comment by HansKristian-Work** [comment]
Does it reproduce on NV?

**Comment by HansKristian-Work** [comment]
Identified a bug in dxil-spirv which causes this issue.
