### ISSUE TITLE
Necromunda: Hired Gun: black/rainbow glow around some models

### ISSUE THREAD

**Issue by HanFox** [HansKristian-Work/vkd3d-proton#681]
Mesa 21.1.1 on a AMD 5700 XT.

I've not noticed it anywhere else besides around NPCs, but they get a weird rainbow/black glow around them.

This does not happen with DXVK (i.e. when the game is set to Dx11 instead of 12).

Tracelog: [vkd3d.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6576855/vkd3d.log)

Screenshot (not the best, but shows the issue on the female at the front):
![20210601151554_1](https://user-images.githubusercontent.com/1781312/120338675-5dff1280-c2ec-11eb-8ce2-60deba6367ea.jpg)

**Comment by HansKristian-Work** [comment]
I can reproduce on Mesa master e64e5e82ed845718d4dfa6759c2491a4fce2328d and RX 6800. Does not happen on NV Ampere, so likely a driver bug.

**Comment by HansKristian-Work** [comment]
Game is just broken. It does implicit LOD in non-uniform control flow:

Shader 75dcbd76ee898815 looks like:

```
layout(location = 0) noperspective in vec4 v0;

    if (floatBitsToUint(r0.w) == 0u)
    {
        o0 = texture(sampler2D(_13[_35.table0 + 4u], _8[_35.table1 + 1u]), v0.xy);
        return;
    }

    r2 = texture(sampler2D(_13[_35.table0 + 5u], _8[_35.table1 + 1u]), v0.xy);
    o0 = vec4(_395.x, _395.y, _395.z, o0.w);
    o0.w = 0.0;
```

**Comment by HanFox** [comment]
I see. Well I reported the issue via Focus Home's Support form. We'll see what happens, I guess. Thanks for looking into it.

**Comment by HansKristian-Work** [comment]
On further study, this might be an exception in the D3D11 functional spec that is actually well defined, sigh ...
