### ISSUE TITLE
Your device not support directx12 features on NVIDIA GTX 1060

### ISSUE THREAD

**Issue by bulbashenko** [HansKristian-Work/vkd3d-proton#685]
When I run Death Stranding with vkd3d-proton an error comes out that supposedly my device does not support `VK_VALVE_mutable_descriptor_type` 

All drivers are recent and installed normally. Maybe I'm doing something wrong, but on the classic vkd3d the game starts without problems...

OS: Fedora 34

**Comment by HansKristian-Work** [comment]
This is not a problem, and is expected.
