### ISSUE TITLE
GravityMark crashes

### ISSUE THREAD

**Issue by niobium93** [HansKristian-Work/vkd3d-proton#705]
[GravityMark](https://gravitymark.tellusim.com/) in D3D12 mode crashes on startup.
Tested on:
Arch Linux
AMD Radeon RX 5700 XT
Kernel 5.12.11-zen1-1-zen
RADV from Mesa 21.1.2
wine-tkg 6.10.r6.g876024f4 (with and without fsync2 turned on)
dxgi from DXVK: v1.9-1-g6b8ab4fd
vkd3d-proton 2.3.1
[GravityMark vkd3d-proton.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6674297/GravityMark.vkd3d-proton.log)

**Comment by niobium93** [comment]
Forgot VKD3D_DEBUG=trace before so: 
[GravityMark vkd3d-proton2.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6674363/GravityMark.vkd3d-proton2.log)

**Comment by HansKristian-Work** [comment]
I doubt this is our bug: 
```
0130:fixme:nvapi:unimplemented_stub function 0x2ddfb66e is unimplemented!
```

**Comment by Joshua-Ashton** [comment]
Looks like `NvAPI_GPU_GetPCIIdentifiers` which should be trivial.

Maybe this can be implemented in https://github.com/jp7677/dxvk-nvapi down the line.

**Comment by Joshua-Ashton** [comment]
Does doing `WINEDLLOVERRIDES=nvapi=d` workaround the problem? You're on AMD so ideally nvapi not existing shouldn't be a problem.

**Comment by HansKristian-Work** [comment]
It crashes somewhere in dxil-spirv, but the shader compiles fine in standalone CLI.

**Comment by niobium93** [comment]
It crashes both without nvapi and with dxvk-nvapi. Here's a new log with dxvk-nvapi: 
[GravityMark vkd3d-proton3.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6677159/GravityMark.vkd3d-proton3.log)
I will build a debug build of vkd3d-proton tomorrow, too tired to bother today.

**Comment by HansKristian-Work** [comment]
No further log is required, I've reproduced it.

**Comment by HansKristian-Work** [comment]
From my PoV, the bench works fine now. There are some driver bugs though. There are no obvious validation errors that would explain it.
- RADV Polaris works (reported)
- amdgpu-pro works
- NV works when not using VK_KHR_buffer_device_address (reported)
