### ISSUE TITLE
Enabling TLS with MingW

### ISSUE THREAD

**Issue by rgc183** [HansKristian-Work/vkd3d-proton#706]
Currently I am using 

```
#if defined(_WIN32)
__declspec(thread) type data;
#endif
```

Its giving me an warning:
`warning: ‘thread’ attribute directive ignored [-Wattributes]`
Any idea WAR for this?

**Comment by rgc183** [comment]
@HansKristian-Work

**Comment by HansKristian-Work** [comment]
Why is this vkd3d-proton's bug?

**Comment by rgc183** [comment]
I was wondering if we need to add any flag in meson build to enable this.

**Comment by Joshua-Ashton** [comment]
Use `thread_local`.
