### ISSUE TITLE
nVidia 470.42.01 beta drivers - and DXR

### ISSUE THREAD

**Issue by SveSop** [HansKristian-Work/vkd3d-proton#711]
Installing the nVidia 470.42.01 driver today on my RTX2070, and i can't seem to get DXR working.

I had previously the D3D12RaytracinHelloWorld and friends demo's running with `VKD3D_CONFIG=dxr` on the 465.31 and previous drivers, (described here: [https://github.com/HansKristian-Work/vkd3d-proton/issues/568#issuecomment-802466935](https://github.com/HansKristian-Work/vkd3d-proton/issues/568#issuecomment-802466935) but today it crashes much like: [https://github.com/HansKristian-Work/vkd3d-proton/issues/488](https://github.com/HansKristian-Work/vkd3d-proton/issues/488) with a `Failed to create Vulkan device, vr -3`

Same with World of Warcraft (even tho i know it is not supporting DXR) it will crash if this option is set.
I know.. beta driver and whatnot, but might be worth checking if you got the chance? (Or let me know what logs you need).

**Comment by SveSop** [comment]
This seem just like [https://github.com/HansKristian-Work/vkd3d-proton/issues/500](https://github.com/HansKristian-Work/vkd3d-proton/issues/500)
Loading `nvidia_uvm` manually does not help, but running native vulkan RT demo from here: [https://www.geeks3d.com/20210219/vulkan-ray-tracing-tested-on-geforce-rtx-20-30-radeon-rx-6000-and-even-on-geforce-gtx/](https://www.geeks3d.com/20210219/vulkan-ray-tracing-tested-on-geforce-rtx-20-30-radeon-rx-6000-and-even-on-geforce-gtx/) BEFORE running D3D12RaytracinHelloWorld with `VKD3D_CONFIG=dxr` makes it work.

Before Geeks3D RT demo:
```
$: lsmod|grep -i nvidia
nvidia_drm             69632  3
nvidia_modeset       1200128  6 nvidia_drm
nvidia              35295232  210 nvidia_modeset
drm_kms_helper        311296  1 nvidia_drm
drm                   598016  7 drm_kms_helper,nvidia,nvidia_drm
```
After Geeks3D RT demo:
```
$ lsmod|grep -i nvidia
nvidia_uvm           1130496  0
nvidia_drm             69632  3
nvidia_modeset       1200128  6 nvidia_drm
nvidia              35295232  211 nvidia_uvm,nvidia_modeset
drm_kms_helper        311296  1 nvidia_drm
drm                   598016  7 drm_kms_helper,nvidia,nvidia_drm
```
Loading nvidia_uvm manually with `modprobe nvidia_uvm` "looks the same", but still fails with : 
`err:vkd3d_create_vk_device: Failed to create Vulkan device, vr -3.`

As i said above, this is NOT the case if i use eg. driver 465.31. So, scrap this as "notourbug", since it seems to be a driver bug?

**Comment by HansKristian-Work** [comment]
This is an NV bug that popped up again for whatever reason, you need to report this to NV.

**Comment by liam-middlebrook** [comment]
@SveSop could you check if running the following command before launching the game allows it to launch successfully?
`nvidia-modprobe -u -c=0`

**Comment by SveSop** [comment]
> @SveSop could you check if running the following command before launching the game allows it to launch successfully?
> `nvidia-modprobe -u -c=0`

@liam-middlebrook That seems to fix it.
Guess nvidia-modprobe loads this a bit different than modprobe (since the latter requires sudo priv maybe?).

Will add this to my launcher script for now then, and see if it gets fixed in 470.42.02? :) Thanks.

**Comment by HansKristian-Work** [comment]
I had similar issues actually, but I didn't even need to run VKD3D_CONFIG=dxr to repro it.
`sudo nvidia-modprobe -u -c=0` worked around it.

**Comment by smcv** [comment]
Is it safe to run `nvidia-modprobe -u -c=0` unconditionally, even if the driver version is old?

https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/327 tracks a pressure-vessel change that will do this automatically before running any Proton game in a a pressure-vessel (Steam Linux Runtime) container. The Nvidia user-space driver would normally do this itself if I understand correctly, but it cannot do this from inside the container, because the container irrevocably drops privileges to prevent it from being used as a privilege-escalation vector.

**Comment by tgurr** [comment]
I just want to throw in the small info that some distributions also handle the creation of the `/dev/nvidia-uvm{,-tools}` nodes on a packaging level by installing a respective udev rule, e.g. https://github.com/negativo17/nvidia-kmod-common/blob/master/60-nvidia.rules

**Comment by HansKristian-Work** [comment]
Should have been resolved in Steam runtime ages ago.

**Comment by smcv** [comment]
> https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/327 tracks a pressure-vessel change that will do this automatically before running any Proton game in a a pressure-vessel (Steam Linux Runtime) container.
...
> Should have been resolved in Steam runtime ages ago.

Yes, this was in soldier depot 0.20210630.17 (Steampipe build ID 6958579).

**Comment by SveSop** [comment]
Probably solved in steam runtime, but for "anything else" it is the same (eg. regular wine usage)... However, it seems it is solved if using the drivers from PPA, as this contains a udev rule and a binary to load the uvm module and set the right permissions instead of using `nvidia-modprobe`

Guess i can blame myself for not using distro driver packages, but use the .run file directly from nVidia then.

IF anyone else got issues with this when using manually installed drivers on Ubuntu - you can get the udev rule and binary from the nvidia-kernel-common-XX .deb package.
`/lib/udev/rules.d/71-nvidia.rules`
and
`/sbin/ub-device-create`

**Comment by aufkrawall** [comment]
I just have been terribly haunted by this when using 470.74, packaged in nvidia-all-tkg. Ping  @Tk-Glitch , just in case. No idea how upstream Arch packages handle this. Really terrible that such things can happen with out of tree drivers, it's super random with Read Dead Redemption 2 in Wine (not Proton) and makes you see things when you close your eyes...

**Comment by aufkrawall** [comment]
The issue occurs also with packaged Nvidia drivers offered by Arch repository. Guess I'll have to report it...

**Comment by memeruiz** [comment]
Another reason to get this error is to not have libnvidia-rtcore libnvoptix1 packages in debian (possibly also Ubuntu).

They give raytracing support to Nvidia in Linux
