### ISSUE TITLE
RE Village framerate collapses, AMD Ryzen 7 3700X 8-Core Processor + RTX 2070 SUPER

### ISSUE THREAD

**Issue by sunlightspectre** [HansKristian-Work/vkd3d-proton#740]
Hello there,

**System info:**

```Win 8.1, AMD Ryzen 7 3700X 8-Core Processor + RTX 2070 SUPER```

Drivers should be up to date, using vkd3d 2.4. Software, RE Village - 
**Issue:**

```The game takes a while to load as vkd3d initalises; but by all other metrics seems to boot fine. After booting, the game seems to rapidly crash towards a frame rate of about 10-20 fps, with audio-desynching from actions and cutscenes. Given that hardware requirements are exceeded, I want to see what I can do to improve performance - or let you know the specifics in case it helps refine vkd3d down the line. ```

That's all,
Thank you for time and hard work..!

**Comment by K0bin** [comment]
You're probably using a dxgi.dll without the RE8 workaround: https://github.com/doitsujin/dxvk/pull/2053

**Comment by sunlightspectre** [comment]
@K0bin 

Thanks, that's very interesting - as is the talk going on in that PR. I *think* 1.9 looks like it should be better for working Vulkan in RE Village in Windows? I'm not nearly smart enough to say for certain.

**Comment by K0bin** [comment]
No, that hack has not made it into 1.9 so that release will perform the same as whatever you're using now.

**Comment by sunlightspectre** [comment]
One last question, then, before I close this. To build dxgi from the pr on windows, it'd be (from elevated command prompt in the directory):

`setup_dxvk.sh install`

Followed by moving dxgi.dll to the proper directory?

**Comment by K0bin** [comment]
Just download the build over there and use the dxgi.dll from that.
https://github.com/doitsujin/dxvk/actions/runs/821484657

That's easier than explaining how to build it on Windows.

**Comment by sunlightspectre** [comment]
_lordy, it was that simple_

Right, I'm going to go into a moment of monastic shame. Thanks for the assist, @K0bin ; closing this.

**Comment by K0bin** [comment]
No reason to be ashamed. Great if it works now.

**Comment by sunlightspectre** [comment]
Very much so! The framerate is incredibly solid, even at high settings. I cannot thank you enough!

**Comment by sunlightspectre** [comment]
Going to tentatively re-open this; the game now fails to initialise. I thought it might be a problem with REFramework, and it still _might_ be; given that the log created by that somehow balloons to 1000+ pages, copying it is a bit of a problem. But I seem to have the problem even without it, so... 

Anyway, here's the new situation:

The game failed to load properly post-update. Just a black screen. Re-installing the game allows it to be played for a short period of time, then a crash; when the game crashes, it refuses to load at all in the future. Uninstalling, NOT verifying files, allows for a similar twelve-second window before crashing. I've heard of other people with similar problems so I am NOT sure that this is a proton issue, but am posting this here in the case someone has had a similar issue WHILE using proton, and knows a workaround (besides rolling back the game version, which is - difficult, on steam).

One last oddity  - I've noticed the stuttering and framerate that the RE8 workaround had fixed is back. I don't know what the new patch did, but it actually seemed to actively make performance _worse,_ at least for me.

**Comment by Oschowa** [comment]
You need vkd3d-proton master for RE8 to not crash since the game patch that introduced FSR, you can download a build here https://github.com/HansKristian-Work/vkd3d-proton/suites/3372298445/artifacts/79417142

**Comment by sunlightspectre** [comment]
> You need vkd3d-proton master for RE8 to not crash since the game patch that introduced FSR, you can download a build here https://github.com/HansKristian-Work/vkd3d-proton/suites/3372298445/artifacts/79417142

Much obliged, I'll try this version and re-close if applicable.
