### ISSUE TITLE
F1® 2021 (1134570) - Title crashes on menus or when transitioning into game.

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#744]
## EDIT:

See comment below for update: https://github.com/HansKristian-Work/vkd3d-proton/issues/744#issuecomment-904625702

### Description:
**_F1® 2021_** (1134570) title launches to a black screen and subsequently crashes to the game's crash handle (EGO Dumper). On Windows however, the title never opens a window and simply throws up EGO Dumper immediately. The same issue is observed when attempting to make a trace file.

| Proton-Experimental | Windows |
| ---- | ---- |
|![Black Screen](https://user-images.githubusercontent.com/761853/125789301-b0a249e8-5c00-40e7-8d13-7f6ff5ad69de.png)|![EGO Dumper - Windows](https://user-images.githubusercontent.com/761853/125789199-57f79333-0ce9-46de-a809-2a832c7d8108.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Notes
- On Proton, the EGO Dumper will frequently not open and the application will remain running in the background and must be manually terminated.

### Software information
- [F1® 2021](https://store.steampowered.com/app/1134570/F1_2021/).

### System information
OS: Windows 10 Pro 21H1 / Ubuntu 20.04
GPU: AMD Radeon RX 5700 XT / Nvidia GTX 1060
Windows Drivers: 21.6.2 / 471.11
Linux Drivers: Mesa 21.2-rc1 / 465.31
Wine version: Proton 6.3-5 / Experimental
VKD3D-Proton version: 2.4 / Master (925a930)

### Log files
| |Proton|Windows|
| ---- | ---- | ---- |
|VKD3D_LOG|[VKD3D_LOG.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6823122/VKD3D_LOG.log)|[VKD3D_LOG.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6823125/VKD3D_LOG.txt)|
|VKD3D_DESCRIPTOR_QA|[VKD3D_DESCRIPTOR_QA.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6823124/VKD3D_DESCRIPTOR_QA.log)|[VKD3D_DESCRIPTOR_QA.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6823127/VKD3D_DESCRIPTOR_QA.log)|

### Trace
- Title immediately crashes when attempting to trace.

**Comment by ZereoX** [comment]
Hi @HansKristian-Work,

As of https://github.com/HansKristian-Work/vkd3d-proton/commit/7ff3ef265480f0b4527f0a7bbfc5098bd4d0b173, the game now launches and you can reach the main menu, but it continues to crash to the game's crash handler when attempting to load into game or do pretty much anything else.

|7ff3ef265480f0b4527f0a7bbfc5098bd4d0b173|
| ---- |
|![7ff3ef265480f0b4527f0a7bbfc5098bd4d0b173](https://user-images.githubusercontent.com/761853/130621678-e590c1c3-bbf5-405f-8da1-94f68aba476e.png)|


I've attached update logs:
|VKD3D_LOG|VKD3D_DESCRIPTOR_QA|
| ---- | ---- |
|[VKD3D.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7039346/VKD3D.zip)|[VKD3D_DESCRIPTOR_QA.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7039347/VKD3D_DESCRIPTOR_QA.zip)|

**Comment by HansKristian-Work** [comment]
I'm ingame with https://github.com/HansKristian-Work/vkd3d-proton/pull/783 at least.

**Comment by HansKristian-Work** [comment]
Got further again on AMD. In game now on RADV and seems to run just fine.

**Comment by HansKristian-Work** [comment]
Fixed a while ago on master.
