### ISSUE TITLE
low GPU bound performance vs. DXVK in Hitman 2 on Nvidia

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#750]
In the benchmark scenes that aren't CPU bound with DXVK, it has a clear lead by ~30% over VKD3D-Proton 2.4:
![Screenshot_20210722_144053](https://user-images.githubusercontent.com/13510490/126640878-e80f2772-939b-4d31-a23b-556e29ca2220.png)
![Screenshot_20210722_144011](https://user-images.githubusercontent.com/13510490/126640886-a38231db-0215-4fab-86fd-283b9d716aa2.png)
![Screenshot_20210722_143627](https://user-images.githubusercontent.com/13510490/126640902-8b30e415-9a83-4d34-ae2c-76464983efe5.png)
I think this was far less distinct with my previous RX 6800 & RADV.

RTX 3060 470.57.02, Proton Experimental, Linux-tkg 5.13.4 (futex2 enabled)

**Comment by Leopard1907** [comment]
Can you try with `force_static_cbv`?

https://github.com/HansKristian-Work/vkd3d-proton#environment-variables

**Comment by aufkrawall** [comment]
It does not affect frame rate in this case.

**Comment by Blisto91** [comment]
@aufkrawall Hello there. Has this improved with newer vkd3d-proton versions plus drivers?

**Comment by aufkrawall** [comment]
Yes. I tested with Hitman 3 instead of 2 (since owners of 2 can play its content inside Hitman 3), and GPU bound performance hit vs. native D3D12 is <10% with latest consumer drivers and vkd3d-proton git-master.
