### ISSUE TITLE
Forza Horizon 4 crashes during first race on Fortune Island

### ISSUE THREAD

**Issue by alasky17** [HansKristian-Work/vkd3d-proton#753]
Originally reported here: https://github.com/ValveSoftware/Proton/issues/4667#issuecomment-886052347 

Forza Horizon 4 crashes consistently when playing the first race on Fortune Island before completing the race.  It crashes somewhere in the middle of the race, shortly after a slo-mo moment during a jump.  The first time, you need to drive manually to the Fortune Island location.  After that, you can fast-travel, although it costs CR to do so.

To get to Fortune Island: 
1) Go in-game (must have completed first season of races to unlock main game)
2) Open map, select Fortune Island as destination (in center right hand area of the map)
3) Drive to Fortune Island.
4) Enter Fortune Island area (press x when in the correct location).
5) You will immediately be dropped into a "race".  Follow track until game crashes.

Unfortunately the log was too large to upload here directly, even after I cut out all the lines that happened before starting the Fortune Island race.  I uploaded it here with the lock code 'forza': https://www.codeweavers.com/xfer/alasky/proton-test/forza-fortune-island-crash.log.xz

**Comment by gofman** [comment]
A bit of context, why it was reported here:

From the log, the crash is inside d3d12.dll:
13703.016:00f8:00fc:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\d3d12.dll" at 000000035E4E0000: native
...
14111.849:00f8:0268:trace:seh:dispatch_exception code=c0000005 flags=0 addr=000000035E5237CE ip=000000035E5237CE tid=0268

This is probably in d3d12_command_list_update_graphics_pipeline(), there is access to NULL with offset 0x28.

**Comment by JacoG-RH** [comment]
Not sure if this will be useful to anyone, or even the same bug, but I have included the last 5000 lines of my log before a crash here. This is on NVIDIA 465 drivers.

[steam-1293830-n5000.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7029710/steam-1293830-n5000.zip)

**Comment by Tk-Glitch** [comment]
It seems to be fixed on current master, at least on RADV. However the "displays" (used to display points and stuff at the end of a race or wheelspins) are gone. I'm going to try and find out if this is coming from vkd3d-proton or something else though.
