### ISSUE TITLE
After merge robustness2-requirement branche, VKD3D-Proten not work on Windows with AMD GPU.

### ISSUE THREAD

**Issue by okt04175** [HansKristian-Work/vkd3d-proton#754]
After merge this (vkd3d: Nuke code paths for !nullDescriptor.) :
https://github.com/HansKristian-Work/vkd3d-proton/commit/4a7be4ba0ab73b5e09b3b233e75360f3f30f5cc2
https://github.com/HansKristian-Work/vkd3d-proton/commit/3c7f18886392be4c7f843faac5799c5b125772b2

Anything use VKD3D-Proten will crash immediately , just generate 0kb log. 
Make the fork without robustness2-requirement maybe will let VKD3D-Proten work on Windows with AMD GPU again.

CPU : AMD Ryzen7 5800X
RAM : 64GB
GPU : AMD RX 6900XT
GPU Drivers : AMD Adrenalin 21.5.2

BTW, citra has same issues too, maybe robustness2 is not suitable for Windows AMD GPU Driver.
https://community.citra-emu.org/t/yuzu-has-encountered-an-error-while-running-the-video-core-in-super-mario-odyssey/413469

**Comment by HansKristian-Work** [comment]
The latest AMD drivers should have the extension. robustness2 is a hard requirement for D3D12.

**Comment by okt04175** [comment]
You may never care any problem on Windows, but VKD3D-PROTON is Win7/8.1's life saver of gaming, Win7/8.1 AMD GPU users will care.
Anyway, I'll try to make fork without robustness2. Before merge robustness2, Win7/8.1 can use VKD3D-PROTON to run DX11+12 games in DX12 mode without problem.
M$ wants to kill Win7/8.1 so that they can easily promote Win10. I am dissatisfied with M$'s method of promoting Win10, I want Win7/8.1 to survive until the day of Win10 EOL.
After Win10 EOL, I'll choose Linux to replace Win7/8.1 not Win11.
