### ISSUE TITLE
Hitman 3 dxil-spirv issues

### ISSUE THREAD

**Issue by exorsize** [HansKristian-Work/vkd3d-proton#755]
Yesterday I could play Hitman3 fine via legendary. Today it keeps crashing.

Is the 3.5 update the issue? It did download and update ~2.7gb today.

err:vkd3d_dxil_log_callback: dxil-spirv: Invalid component type for image.

some info
----
info:  Game: HITMAN3.exe
info:  DXVK: v1.9.1-3-geb95a9fb
info:  Found config file: /home/****/legendary/HITMAN3/dxvk.conf
info:  Found built-in config:
info:  Effective configuration:
info:    dxgi.customVendorId = 10de
info:    dxgi.nvapiHack = False
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 11.0.1, 256 bits)
info:  AMD RADV VEGA10 (ACO):
info:    Driver: 20.3.5
info:    Vulkan: 1.2.145
info:    Memory Heap[0]:
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]:
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]:
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7

System information:
    Wine build: wine-6.10.r0.g8a3554ad ( TkG Staging Esync Fsync ) <--- a lutris build that seems to launch, wine 6.13 crashes
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.10.0-8-amd64

Looking around I did not find much info regarding this error, any insight is greatly appreciated.
Happy to supply more info/logs if needed.

**Comment by Oschowa** [comment]
Can you try with vkd3d-proton master? 2.4 crashes the same way for me, but it looks like it's already fixed on master.

**Comment by exorsize** [comment]
After building vkd3d-proton master, the game works fine again.
Thank you!
