### ISSUE TITLE
[Regression][Bisected] - Evil Genius 2: World Domination (700600) - Title fails to launch since v2.4

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#760]
### Description:
**_Evil Genius 2: World Domination_** (700600) launches to a black screen before throwing up a crash reporter. The title launches succesfully on version 2.3.1.

| 2.4 | 2.3.1 |
| ---- | ---- |
|![2 4](https://user-images.githubusercontent.com/761853/127543982-1c759d66-2053-4acd-ab8c-20d907785c7b.png)|![2 3](https://user-images.githubusercontent.com/761853/127544176-11c70100-2eb9-4bff-9e2d-2b19910f7cf5.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Git Bisect
```
fee18f182091ae6d9f07cca066e52dff896f7dac is the first bad commit
commit fee18f182091ae6d9f07cca066e52dff896f7dac
Author: Hans-Kristian Arntzen <post@arntzen-software.no>
Date:   Fri May 28 15:28:32 2021 +0200

    dxil-spirv: Update submodule.
    
    Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

 subprojects/dxil-spirv | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

### Software information
- [Evil Genius 2: World Domination](https://store.steampowered.com/app/700600/Evil_Genius_2_World_Domination/).

### System information
OS: Windows 10 Pro 21H1 / Ubuntu 20.04
GPU: AMD Radeon RX 5700 XT / Nvidia GTX 1060
Windows Drivers: 21.6.2 / 471.11
Linux Drivers: Mesa 21.2-rc1 / 465.31
Wine version: Proton 6.3-5 / Experimental
VKD3D-Proton version: 2.4 / Master (a2a7d78)

### Log files
VKD3D_LOG: [VKD3D_LOG.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6902749/VKD3D_LOG.txt)
Shader Dump: [EG2_SHADER_DUMP.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/6902751/EG2_SHADER_DUMP.zip)

### Trace
- https://drive.google.com/file/d/1LSnuqf3TU32hGMViEr4U6-BUFwOQPuf7/view?usp=sharing

**Comment by HansKristian-Work** [comment]
Reproduced some validation errors which would explain crashes.
