### ISSUE TITLE
Horizon Zero Dawn crashes on launch, Failed to create Vulkan device vr -3

### ISSUE THREAD

**Issue by PhitherekReborn** [HansKristian-Work/vkd3d-proton#764]
Horizon Zero Dawn: Complete Edition from GOG fails to launch after my last system update, as the error is from vkd3d I suppose this is the correct place to post it. It was working fine with only some random crashes on the initial load screen before, now it just crashes with the error message. Here is the log:
[hzd_gog_lutris_vkd3d_trace.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6911882/hzd_gog_lutris_vkd3d_trace.txt)

I'm using Lutris with the latest Lutris Runtime and the GOG Galaxy launcher, the result is the same without the launcher.

**Comment by doitsujin** [comment]
Known Nvidia driver issue that has been reported roughly 500 times here already.

**Comment by Oschowa** [comment]
You can probably work around it by running `nvidia-modprobe -u -c=0` manually before starting the game.

**Comment by PhitherekReborn** [comment]
Tried the workaround, didn't work in my case

**Comment by joethefox** [comment]
After last nvidia drivers update, 470.57.02, in my environment I was able to fix the issue by raising the default swap file size from 2GB to 16GB. 
System has 16 GB Ram.

**Comment by HansKristian-Work** [comment]
Out of memory issue has a workaround on master now.
