### ISSUE TITLE
Battlefield 5 crashes after 15 minutes or so

### ISSUE THREAD

**Issue by kleinermob** [HansKristian-Work/vkd3d-proton#765]
2708:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2708:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2708:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2708:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2708:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2708:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2708:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2708:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2708:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2708:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2708:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2708:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2708:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2708:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2708:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2708:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
2708:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
2708:fixme:d3d12_device_SetResidencyPriority: iface 000000003e790030, object_count 1, objects 0000000031a3e110, priorities 0000000031a3e0e0 stub!
2708:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x3d.
2708:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x31.
2708:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x1d.
2708:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
2708:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x2.
2652:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
2652:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
2652:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
2652:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
2652:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.

OS: OpenSUSE Tumbleweed
GPU: RX 570 8GB
Mesa 21.1.6
Wine: lutris-fshack-6.14-2

**Comment by kleinermob** [comment]
okay, tried to load a map and it crashed while doing that

1936:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1936:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1936:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1936:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1936:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1936:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1936:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1936:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1936:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1936:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1936:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1936:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1936:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1936:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1936:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1936:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
1936:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
1936:fixme:d3d12_device_SetResidencyPriority: iface 000000003e790030, object_count 1, objects 0000000031a3e110, priorities 0000000031a3e0e0 stub!
1936:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x3d.
1936:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x31.
1936:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x1d.
1936:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
1936:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
1140:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.

**Comment by kleinermob** [comment]
now crashes at startup for some reason

1504:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1504:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1504:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1504:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1504:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1504:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1504:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1504:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1504:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1504:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1504:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1504:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1504:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
1504:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
1504:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
1504:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
1504:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
1504:fixme:d3d12_device_SetResidencyPriority: iface 000000003cc80030, object_count 1, objects 000000002ff2e110, priorities 000000002ff2e0e0 stub!
1504:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x3d.
1504:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x31.
1504:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x1d.
1504:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
1504:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x2.
416:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
416:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.

**Comment by kleinermob** [comment]
Did a restart and its the same after few minutes it freezes 

2232:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2232:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2232:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2232:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2232:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2232:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2232:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2232:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2232:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2232:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2232:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2232:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2232:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
2232:info:vkd3d_instance_init: vkd3d-proton - build: 98865355976676.
2232:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
2232:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 2048, may be inaccurate.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x42.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x44.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x45.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x59.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x64.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x65.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x66.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x67.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x68.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x69.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6a.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6b.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6c.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6d.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6e.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x6f.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x70.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x71.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x72.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x82.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x83.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
2232:fixme:d3d12_device_CheckFeatureSupport: Unhandled format 0x84.
2232:fixme:d3d12_device_SetResidencyPriority: iface 000000003cc80030, object_count 1, objects 000000002ff2e110, priorities 000000002ff2e0e0 stub!
2232:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x3d.
2232:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x31.
2232:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x1d.
2232:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
2232:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x2.
2192:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.
2192:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x2.

**Comment by K0bin** [comment]
Those logs don't contain anything of interest. You can stop posting more of them.
