### ISSUE TITLE
Control - weird issue with reflections

### ISSUE THREAD

**Issue by DistantThunder** [HansKristian-Work/vkd3d-proton#766]
![image](https://user-images.githubusercontent.com/3923810/129375295-c770071f-9b9a-49a4-864a-cb963f6d83ff.png)
![image](https://user-images.githubusercontent.com/3923810/129375676-1d3299ce-7d7e-45c8-9eda-d5a070a8d986.png)

Hello, playing Control from EGS with VKD3D v2.4.x, I notice some weird grainy reflections a bit reminiscent of CP2077 borked SSR.

I do not remember this from Windows gameplay. 

Worth a look?

**Comment by K0bin** [comment]
Can you verify that this doesnt happen on Windows? (by providing screenshots of the same spot for example)

**Comment by doitsujin** [comment]
Please only report bugs that are **proven** to not happen on Windows.

**Comment by CME42** [comment]
I've seen this issue on AMD with radv+aco (both 6900xt and picasso apu), but it doesn't happen on every start of the game. Also i could never repro it on nvidia, so this is possibly a radv bug - and for extra fun it doesn't happen with a renderdoc of the game.

**Comment by Iglu47** [comment]
@DistantThunder unlikely but did clearing the graphics cache help?

**Comment by enveeed** [comment]
I think this is a bug (might be an amd driver one), I'm on NVIDIA and it never looked like this on any setting for me, both on vkd3d and in Windows.

**Comment by DistantThunder** [comment]
@doitsujin @K0bin 

I stand corrected, I reproduce on Windows drivers.

![screenshot_00001](https://user-images.githubusercontent.com/3923810/129489589-7d04477a-f8fc-4153-af6c-83c1bf951973.png)
![screenshot_00000](https://user-images.githubusercontent.com/3923810/129489605-0378ec4d-b05f-4aaf-a717-ba2870b03f4d.png)

I'll close this issue then. May I remark though that Windows is getting basically the double of RadV/VKD3D performance?

**Comment by DistantThunder** [comment]
@CME42 Yeah, what got me is that entering & leaving a room can make it go away. Makes sense why I didn't remember it from Windows.

**Comment by doitsujin** [comment]
> May I remark though that Windows is getting basically the double of RadV/VKD3D performance?

That's expected since you're CPU limited, and will not change given the massive hoops we have to jump through to make the binding model work. This is also affected by your system and wine configuration (fsync, CPU governor, etc).

**Comment by DistantThunder** [comment]
Thanks for the explanation. I do run the game with FSYNC and Gamemode from an SSD  so I didn't expect that much a of performance difference but the way you put it makes sense. 

I've tried the game with DXVK and didn't obtain frames reminiscent of D3D12 performance. Although much better than VKD3D:

![image](https://user-images.githubusercontent.com/3923810/129874244-87c232dc-e6b0-43f4-a8b4-3e302b8d0c4a.png)


Will have to check how it fares with DX11 on Windows. If it's still that much of a difference, it might mean something other than D3D12 translation is to be blamed here.
