### ISSUE TITLE
Cyberpunk 2077 - Border on pistol iron sight

### ISSUE THREAD

**Issue by K0bin** [HansKristian-Work/vkd3d-proton#791]
![image](https://user-images.githubusercontent.com/1131720/132250772-330cdcad-d6c5-4152-a8d5-2e6986a0b14a.png)

VKD3D-Proton version: 7ff3ef265480f0b4527f0a7bbfc5098bd4d0b173 + Pipeline cache memory usage workaround
Nvidia 1070, 470.63.01
Game version 1.3
Save game: [cp_save.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7117811/cp_save.tar.gz)

The texture used looks alright:
![image](https://user-images.githubusercontent.com/1131720/132251391-3535428e-935d-45a8-8fa2-27420fd2bfbc.png)

So it's probably a shader bug.
[cp_shader.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7117429/cp_shader.tar.gz)

**Comment by K0bin** [comment]
![image](https://user-images.githubusercontent.com/1131720/132261457-6e04b7a1-2e71-4377-8e88-72e81c547cae.png)
^ Windows 10 D3D12 on Nvidia

Just Cyberpunk being Cyberpunk.

**Comment by Dahipppo1555** [comment]
Hi, this is not a VKD3D bug. This is even present on windows, i can confirm that.

**Comment by K0bin** [comment]
Yes, I already tested that. The screenshot above is a Windows screenshot. That's why I closed the issue.
