### ISSUE TITLE
Enabling rt with 21.3.0-devel git-f109526 and VKD3D-PROTON dxr causes Ghostrunner to crash on launch + other games

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#808]
All games are configured to use dx12. Graphics card is an rx 6700 xt.

Using the latest git clone for VKD3D-PROTON with VKD3D_CONFIG=dxr and oibaf 21.3.0-devel git-f109526 Mesa and RADV_PERFTEST=rt enabled, Ghostrunner demo (either through Steam or Heroic Games Launcher) fails to launch and gives a generic "fatal error". Disabling either option allows the game to run. Using Control with both options enabled, game starts, recognizes raytracing hardware is available but enabling any raytracing option causes an immediate crash when resuming the game. World of Warcraft does not recognize any raytracing hardware is present with both options enabled.
 
```
System:
  Host: GGI-LinuxMint Kernel: 5.14.6-tkg-bmq x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 5.0.5 wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma 
  base: Ubuntu 20.04 focal 
CPU:
  Topology: 6-Core model: 11th Gen Intel Core i5-11600K bits: 64 
  type: MT MCP arch: N/A L2 cache: 12.0 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 93888 
  Speed: 4800 MHz min/max: 800/4900 MHz Core speeds (MHz): 1: 4800 2: 4800 
  3: 4800 4: 4800 5: 4800 6: 4800 7: 4800 8: 4800 9: 4800 10: 4800 11: 4800 
  12: 4800 
Graphics:
  Device-1: AMD vendor: Tul driver: amdgpu v: kernel bus ID: 03:00.0 
  chip ID: 1002:73df 
  Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD Radeon RX 6700 XT (NAVY_FLOUNDER DRM 3.42.0 
  5.14.6-tkg-bmq LLVM 12.0.1) 
  v: 4.6 Mesa 21.3.0-devel (git-f109526 2021-09-21 focal-oibaf-ppa) 
  direct render: Yes 
```

**Comment by jhu54** [comment]
This is issue #5379 in the Mesa issues log (same everything) - more a reference pointer here in case anything pops up that affects this project. Note - I am running everything through Steam with Proton-6.16-GE-1 for simplicity

**Comment by doitsujin** [comment]
Please bear in mind that RADV's implementation is still very much in development and **known** not to work with all games yet.
