### ISSUE TITLE
Cyberpunk 2077 1.31 - Win 11 - AMD GPU Complete crash (No black screen)

### ISSUE THREAD

**Issue by Euronisko** [HansKristian-Work/vkd3d-proton#811]
### Crash is immediate, no black screen, the crash dump is kinda useless in this game but the stack trace is pointing to:
```
Error reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x40.
File: <Unknown>(0)
```
Pointed to 0x38 on 21.9.1 drivers if I recall correctly? (Could be a missing lead here since I am not 100% sure on that statement as I went around trying to fix this back and forth through a lot of things)

DXVK cache builds, no screen shows then the game crashes with its crash handler shown.

Also with only DXVK (without VKD3D installed) the game window is shown for around 3/5 seconds with a black screen then crashes. Where VKD3D crashes immediately.

Tested on Clear game directory (I even reinstalled to confirm since I had mods earlier)
local appdata for the game (settings and so on) was removed while testing.
Setup:
1950x | 6900xt | Windows **11** | Drivers tested: 21.2.3 and 21.9.1 (WDDM 2.7 and 3.0 respectively) and with PRO 21.Q3
DXVK (dxgi) Version 1.8.3/1.9.1/1.9.2 tested

Same setup tested on laptop with 5800h and rtx 3080 mobile with Windows 10 and worked perfectly.

If you need any more information let me know.

P.s. Seems to run perfectly fine in Control and GhostRunner Demo, did not work in DMC5 (just black screen - no crash though just lock)

**Comment by doitsujin** [comment]
This game is known to require `VK_VALVE_mutable_descriptor_type` due to game bugs.

**Comment by HansKristian-Work** [comment]
And AMD Windows drivers rarely, if ever, run vkd3d-proton anyways.
