### ISSUE TITLE
Assasins creed valhalla hang vkd3d

### ISSUE THREAD

**Issue by Gaming1992** [HansKristian-Work/vkd3d-proton#820]
Clear

**Comment by Oschowa** [comment]
Your GPU is below minimum requirements even on windows and most likely just doesn't have enough VRAM to run the game on linux, there is nothing to fix. Also, pirated games are unsupported for obvious reason.

**Comment by Gaming1992** [comment]
> Your GPU is below minimum requirements even on windows and most likely just doesn't have enough VRAM to run the game on linux, there is nothing to fix. Also, pirated games are unsupported for obvious reason.

then linux is not recommended for pirated games like windows, yes, it's heavier, gt 1030 meets the requirements on windows
