### ISSUE TITLE
Support SetDepthBounds via D3D12GraphicsCommandListExt

### ISSUE THREAD

**Issue by jp7677** [HansKristian-Work/vkd3d-proton#827]
Hi,

Could you please consider adding a new extension method to D3D12GraphicsCommandListExt for SetDepthBounds?

While looking into an issue with Battlefield5 crashing when DXVK-NVAPI is in use (https://github.com/jp7677/dxvk-nvapi/issues/45),  logging revealed that the engine (Frostbite) wants to use NVAPI to create graphics pipeline state objects with extension support for SetDepthBounds. Unfortunate the game crashes according to that report when creating graphics pipeline state objects through NVAPI fails. Once this succeeds though, it uses NVAPI to set depth bounds.

Related NVAPI methods:
```
NvAPI_Status __cdecl NvAPI_D3D12_CreateGraphicsPipelineState(ID3D12Device *pDevice, const D3D12_GRAPHICS_PIPELINE_STATE_DESC *pPSODesc, NvU32 numExtensions, const NVAPI_D3D12_PSO_EXTENSION_DESC** ppExtensions, ID3D12PipelineState **ppPSO)

NvAPI_Status __cdecl NvAPI_D3D12_SetDepthBoundsTestValues(ID3D12GraphicsCommandList *pCommandList, const float minDepth, const float maxDepth)
```

I've clicked together a branch for DXVK-NVAPI that implements those two methods and just ackknowledges SetDepthBounds (https://github.com/jp7677/dxvk-nvapi/pull/46). The game/engine does no longer crashes with that branch when using NVAPI-DXVK, but it would be even better to be able to forward SetDepthBounds into D3D12/VKD3D-Proton, like it is implemented for DXVK or similar to the Cubin extensions for VKD3D-Proton. Eventually this will also yield a tiny bit of extra performance.

Please let me know if more info is needed.

PS: I guess no bump of the interface version (thus D3D12GraphicsCommandListExt1) is needed, since there hasn't been any VKD3D-Proton release since the introduction of that interfaces (I also guess there are no other consumers other than DXVK-NVAPI).

**Comment by doitsujin** [comment]
We already support depth bounds via [standard D3D12 methods](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-omsetdepthbounds)]. I don't know why Nvidia felt the need to reinvent the wheel there.

**Comment by jp7677** [comment]
Thanks for the hints, with knowing that, having this as an extension if ofc not needed.
