### ISSUE TITLE
slight corruption on water with RT reflections in Metro EE

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#855]
With RT reflections, there are bright spots on the water surface, which are not there with "hybrid" ones (solely SSR):

![Screenshot_20211013_205621](https://user-images.githubusercontent.com/13510490/137207239-8b4fddcf-cd17-4080-91b2-31ffda6f41e9.png)
![Screenshot_20211013_205637](https://user-images.githubusercontent.com/13510490/137207244-7d8e771c-ad55-47fc-bcc4-48bce40873cf.png)
(The different far geometry LOD between the screenshot might be a quirk of the game.)

They get a lot more visible with DLSS; the lower the resolution, the more. But I thinkt it might not be directly linked to DLSS, as when looking ever so closely, it also gets more visible when using the game's own resolution scale/TAAU solution.

The weird thing is that the artifacts disappear when moving the camera so that reflected objects/landscape gets out of screen space. Uneducated guess: The artifacts look a bit like RT noise. Perhaps something's off with the denoiser or blending with SSR? 

The issue does not occur on Windows with native D3D12. Afaict only very far areas are affected, RT reflections of close objects seem to be fine. I also haven't found any issues so far with just plain SSR instead of RT reflections. Then native D3D12 and VKD3D-Proton seem to look identical.

latest vkd3d git-master + Nvidia Linux 470.62.05, RTX 3060

**Comment by aufkrawall** [comment]
I've found out that the game always crashes with HairWorks enabled in the Volga level, probably when some animals (there are rabbits) with it are about to be rendered. It is 100% reproducible by loading the Volga level and then follow Anna to the boat. Would a renderdoc capture be helpful?

**Comment by aufkrawall** [comment]
Broken SSR with RT reflections are apparently a game bug, happens also on native Nvidia D3D12 in some scenes:
![MetroExodus_2022_12_25_18_44_29_633](https://user-images.githubusercontent.com/13510490/209478663-c5370621-bf65-48ff-a34d-b97e61c42f54.png)
![MetroExodus_2022_12_25_18_44_18_090](https://user-images.githubusercontent.com/13510490/209478666-1d7d8467-6ef0-42ac-979b-034faa72200d.png)

The HairWorks fix for Witcher 3 doesn't help this game. The HW DLLs also look vastly different and aren't interchangeable between those games.

**Comment by Blisto91** [comment]
@aufkrawall Hi there. Are you still having issues with this game or is it fine now?

**Comment by aufkrawall** [comment]
I'm fine with closing this as a game bug.
