### ISSUE TITLE
Age of Empires 4 (1466860) most units fail to render

### ISSUE THREAD

**Issue by aeikum** [HansKristian-Work/vkd3d-proton#880]
Most of the in-game unit graphics fail to render in Age of Empires 4. Screenshot and log attached, notice the floating swords in the bottom-left.

The game is playable currently on the bleeding-edge branch of Proton Experimental. (Just needed 06104aec963 picked from upstream Wine to become playable.)

[steam-1466860.log](https://github.com/HansKristian-Work/vkd3d-proton/files/7435729/steam-1466860.log)

![Screenshot_2021-10-28_11-07-00](https://user-images.githubusercontent.com/34554541/139294151-1b4b10b8-99cd-4e6c-b5ad-e6fb4988e32b.png)

**Comment by techy2493** [comment]
Trying to generate some logs for this, but haven't had a lot of luck so far getting logging turned on, am going to keep trying though. In the meantime wanted to indicate that the linked thread is now closed and a new one was created which continues to track this error on the Proton side.

https://github.com/ValveSoftware/Proton/issues/5258

I posted this there, but I'll include it  here as well for ease of access. Here's an image of rendering, I'll include settings as configured in a moment as an edit.

![image](https://media.giphy.com/media/CCtYDO5FOTFzLtiHmf/giphy.gif)

**Comment by sulix** [comment]
I've re-run a few of my experiments on the final game, version 5.0.5544.0 (appid 1466860, build id 7595436), and my observations are:

There are two "types" of issues here (which are likely at least related, if not the same issue):
- Some objects don't display at all.
- Some display, but have incorrect transforms (the "wiggling" seen in the rocks, spears, some trees, etc).
It seems possible the former is simply the latter, with a big enough transform flaw that the rendered item is not visible at all (offscreen, culled, etc.)

Looking at the game under renderdoc, there are two possible codepaths which can occur, both of which have this issue. I think they probably depend on the game settings or something.
1. A depth pre-pass renders the objects (typically in Depth-only pass 3 or 4, with shader hash a2675ea7efda0520 or 063ac6fa716bddb6). See [this renderdoc capture](https://davidgow.net/stuff/aoe4-berrybush-depthpass.rdc.bz2).
2. The colour and depth are rendered at the same time (typically Color Pass 3, with shader hash 2a62ba8f721daf38 or fbda694dd47ef82e). See [this renderdoc capture](https://davidgow.net/stuff/aoe4-berrybush-colour.rdc.bz2)

In both of these cases, both the "wiggled" and totally invisible objects appear to be rendered with ``vkCmdDrawIndexed()``, and their meshes can be viewed in renderdoc. Only some of them actually do appear. (And for whatever reason, the mesh viewer isn't showing any VS Output in renderdoc whether they appear or not — though that feels like it's probably just some Vulkan feature that's beyond my OpenGL 2.0-era knowledge.) One other thing I'm not sure of is how the per-instance buffer seems to have a format of R16_UINT, but accesses everything as though they're 32-bit uints (including having 4-byte aligned offsets, etc).

In any case, hopefully the renderdoc captures can be of some use. I wish I could get some D3D12 API traces as well, but it looks like the d3d12 ApiTrace support doesn't handle OpenExternalHeap(), which would be required…

**Comment by sulix** [comment]
Okay — it looks like it was the alignment mismatch on the per-instance data which was causing this issue. Fixing it (as in PR #884) makes the units appear for me:
![The battle of hastings with people and trees in it](https://davidgow.net/stuff/aoe4-visibleobjects.png)

**Comment by HansKristian-Work** [comment]
Should be fixed on master now thanks to @sulix.

**Comment by Blisto91** [comment]
Can confirm this issue is fixed
