### ISSUE TITLE
Diablo 2 Resurrected - Flickering shadows/patterns in smoke

### ISSUE THREAD

**Issue by Mershl** [HansKristian-Work/vkd3d-proton#890]
### Description
Smoke and some light emitting objects show flickering shadows and patterns, especially visible when moving.

The issue was much more prominent in VKD3D 2.4. With VKD3D 2.5 it got a lot less noticeable but is still there - see the following screencaps.

### Screencaps
VKD3D 2.4: https://streamable.com/qujizr
VKD3D 2.5: https://streamable.com/8i269g

### To reproduce
The easiest reproducer is in Dark Wood (an early area of the game). Search for the burning building seen in the screencaps.

Tested on wine-ge-6.20 + mesa-git (4th of November) + RADV on a AMD RX6800.  
Tested quite a few graphic options of the game, which had no effect on the issue.

Based on other users feedback this is not reproduciable on Nvidia.

**Comment by kub0x** [comment]
Tesded on VKD3D 2.5 using Proton-6.20-GE-1 and Wine-6.20-GE-1:

- Experienced flickering on fullscreen window when Freesync is enabled on my monitor and the compositor is off. Remember that freesync only works when compositor is off or unredir fullscreen option is enabled.
- Black squares and artifacts on screen on dark areas. It's very noticeable when you move you see a trace of black squares moving around, it's like there's a black hidden layout.
- General stutter when changing player direction using keyboard + mouse

Finally, playing with an USB controller fixes the stutter and partially solves flicker, as it only flickers sometimes when you open a menu (inventory, waypoints, options).

Another important point, is that some poeple @ Windows had problems with an OSD, an on-screen display. So disabling Mangohud or DXK_HUD is mandatory. I can confirm that at a certain point, with Mangohud the game cannot detect window focus and GPU is at 30-50%, won't hit 90-100% so game starts to drop FPS til' you restart it.

For me the game is enjoyable with freesync + compositor off + USB controller. Any other configuration makes it to feel buggy and slowish.

**Comment by Mershl** [comment]
The flickering shadows/patterns in the smoke issue on mesa is no longer reproduciable as of mesa 21.3.2 or mesa-git.

@kub0x as your found issues go much deeper than mine (I do not use freesync, or have noticed the black square artifacts) I'd suggest doing a re-test (using vkd3d-git and mesa-git could see some of them fixed) and creating a new issue, if they are still reproduciable.
