### ISSUE TITLE
zst

### ISSUE THREAD

**Issue by thunderpants** [HansKristian-Work/vkd3d-proton#892]
zst ,cute.
Come on man ,who the hell uses that ?
Now we have go looking for third-party programs to open it ,adding more stuff we don't need to our pc's..
Less is more.

A zip ,rar or 7zip is all that is needed

Apart from that ,great job 👍

**Comment by Iglu47** [comment]
Zstandard/zstd is one of the popular and effective lossless data compression algorithms.
I have never heard that in modern distributions there was some problem with its support
(what you wrote does not make sense at all).

It looks like you still know about how to open archives encoded with this algorithm,
but if you want to avoid Zstandard at all costs, just the reminder: for example, you can use ready-made binary builds
https://github.com/HansKristian-Work/vkd3d-proton/actions/workflows/artifacts.yml?query=branch%3Amaster
among which there will even be more recent versions than versions on just tags (be wiser with them).

**Comment by doitsujin** [comment]
There's arguably no support for zst on Windows, but I don't see a good reason to cater to that.

**Comment by gardotd426** [comment]
>A zip ,rar or 7zip is all that is needed

This is first and foremost a Linux project. Tar is the standard archiving program on Linux. It's going to be on literally every Linux desktop machine. 7zip and rar are not standard on Linux, and rar is proprietary.  ​

This is like going onto a GH project for a Windows-specific application and telling them to stop shipping .zips and start shipping tars
