### ISSUE TITLE
Cyberpunk 2077: fence_signal_external_events_locked errors, command_list index warnings, eventual crash

### ISSUE THREAD

**Issue by Mershl** [HansKristian-Work/vkd3d-proton#903]
## Description
Started playing Cyberpunk 2077 a few days ago. From the start I saw crashes after ~30 minutes of gameplay. Enabling `PROTON_LOG=1` shows a huge amount of `d3d12_fence_signal_external_events_locked: Failed to signal event, hr #80004005.` errors and different `warn:d3d12_command_list_*` warnings.

I'm able to reproduce the issue on Proton 6.3-7 (vkd3d 2.4.0) and Proton Experimental (vkd3d 2.5.0).

## Looking further into it
The fence errors are reported while UI is displayed. The eventual crash always happens on opening an UI (opening main menu using Escape or I to open the Inventory UI). Staying in the main menu also leads to a crash after ~5 minutes (seen once so far).

## Specs
- AMDGPU RX6800 (mesa 21.2.2, radv)
- Fedora 35
- Reproduciable on wayland and Xorg session
- Cyberpunk 2077 (Game version 1.31) (Steam)

## Full Log
[steam-1091500.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7540099/steam-1091500.zip)

**Comment by HansKristian-Work** [comment]
That error is benign and is fixed on master. It's related to waitable swapchain fence. We try to ReleaseSemaphore(), but the count is already saturated.

**Comment by Mershl** [comment]
Got it, so it's most likely not the source of the crash. Do you have a guess based on the log?

**Comment by HansKristian-Work** [comment]
Nothing obvious. The "Not supported for queue type 2" thing is also fixed long ago.

**Comment by Mershl** [comment]
Latest proton-experimental (using vkd3d 2.5.0) shows the same crash, but different messages in the log.
For example `fence_signal_event: Failed to release semaphore. Application likely forgot to wait for presentation event.` is new.

[steam-1091500-experimental.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/7541515/steam-1091500-experimental.zip)

**Comment by Mershl** [comment]
The eventual crashes were casued by Mangohud. After confirming the issue again I've disabled Mangohud and played for 2 hours without a single crash.
