### ISSUE TITLE
Hellblade: Senua's Sacrifice - Freezes for a short while with console spam after turning on FSR

### ISSUE THREAD

**Issue by buzzcut-s** [HansKristian-Work/vkd3d-proton#909]
# Specs
GPU: NVIDIA 1660Ti 
Drivers: 495.44

Using latest Proton-Experimental as of posting this.
Using vkd3d-proton built from master (commit: https://github.com/HansKristian-Work/vkd3d-proton/commit/99e067d6816c07b773b6856ba0ec5e7257bc41c1)

# Description
Hellblade: Senua's Sacrifice recently had an update on PC where they added support for AMD FSR. 

Enabling FSR on vkd3d-proton results in the game freezing with the following console spam :
`0154:fixme:shader_sm4_read_param: Skipping modifier 0x00004000`

Setting `VKD3D_SHADER_DEBUG=none` works around it and FSR works as expected.

# Reproduction steps 
Turn on AMD FSR in the graphics settings on the latest update. 

# vkd3d-proton logs
https://drive.google.com/drive/folders/1ySacWDCN68o03Wki_ZoC7cUHHTAzYqNw?usp=sharing

# Shader Dump 
https://drive.google.com/file/d/1lAk0lL-DTdZ2pSwCHN8PZOdiMIs52dcG/view?usp=sharing

# Edit
To be noted is that the game doesn't *really* freeze indefinitely. It only freezes/waits, while spamming the console with fixmes, for around 30 seconds before continuing normally as expected. 

This freezing/waiting is reduced to 0 seconds when setting the above `VKD3D_SHADER_DEBUG` to `none`.

Please let me know what else would be helpful. :)

**Comment by doitsujin** [comment]
Does it **really** freeze or is it just taking its time spamming log messages?

**Comment by buzzcut-s** [comment]
> Enabling log messages does not magically create an infinite loop out of nowhere, it's just slow, and we should probably ignore some of the modifiers.

That makes sense yeah.

My bad, looks like you're right. I didn't let it run long enough as soon as it froze. It exits the freeze and continues just as expected after waiting around 30 seconds.

I'll update the issue to reflect this more clearly. :)
