### ISSUE TITLE
Missing indirect rendering features

### ISSUE THREAD

**Issue by K0bin** [HansKristian-Work/vkd3d-proton#910]
Halo Infinite appears to use D3D12 indirect rendering features that aren't supported by Vulkan (as far as I know).

`7eb4:fixme:d3d12_command_list_ExecuteIndirect: Ignoring unhandled argument type 0x6.`
`7eb4:fixme:d3d12_command_list_ExecuteIndirect: Ignoring unhandled argument type 0x4.`

Argument type 6 is `D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT_BUFFER_VIEW`.
Argument type 4 is `D3D12_INDIRECT_ARGUMENT_TYPE_INDEX_BUFFER_VIEW`.

**Comment by Fullbrik** [comment]
Is there a way to improperly implement these until vulkan has support? It might make games like halo work, even if it slows down the game a bit.

**Comment by rupansh** [comment]
Maybe relevant

https://vkguide.dev/docs/gpudriven/draw_indirect/

**Comment by doitsujin** [comment]
What exactly is that link supposed to help with? We do support simple indirect draws and dispatches, as well as indirect multidraw with indirect draw count, but not stuff like indirect vertex buffers because there is no corresponding Vulkan feature other than an Nvidia vendor extension.

**Comment by rupansh** [comment]
> indirect vertex buffers

Ah my bad i misunderstood the initial comment! I thought indirect rendering wasn't supported.

**Comment by TheEssem** [comment]
For anyone who missed it: #923 has a prototype for this based on the Nvidia vendor extension.

**Comment by hugeblank** [comment]
Is there any information regarding AMD support?

**Comment by M-Ro** [comment]
> For anyone who missed it: #923 has a prototype for this based on the Nvidia vendor extension.

For the people coming from the Halo Infinite issue thread - This doesn't appear to help with Halo Infinite yet. Crashes immediately after the initial loading spinner.

Nvidia 1080Ti, 470.74 drivers (stable, not vulkan beta)

[vkd3d.log](https://github.com/HansKristian-Work/vkd3d-proton/files/7654777/vkd3d.log)

[game crashlog](https://github.com/HansKristian-Work/vkd3d-proton/files/7654782/crash_info.txt)

**Comment by TheEssem** [comment]
Any idea if the newly-released Vulkan 1.3 has anything that could help with this?

**Comment by hugeblank** [comment]
> Any idea if the newly-released Vulkan 1.3 has anything that could help with this?

Probably not. I don't see any mention in the api docs of "indirect vertex buffers" like the above conversation suggests has been missing from Vulkan. Someone more proficient in reading specifications would have to confirm this, though.

See: 
- [1.3 Core API + all published extensions PDF](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/pdf/vkspec.pdf)
- [Conversation on gamingonlinux.com](https://www.gamingonlinux.com/2022/01/vulkan-api-13-released-new-roadmap-and-profiles-feature/comment_id=218188)

**Comment by K0bin** [comment]
Vulkan 1.3 doesn't have any new features or extensions. It just moves existing extensions into the core API. VKD3D-Proton already uses many of those extensions so it pretty much already uses Vulkan 1.3.

It can be implemented using VK_NV_device_generated_commands and there's a WIP implementation using that in PR 923. It doesn't really work yet due to driver issues though.

**Comment by DistantThunder** [comment]
Hi, just to know:

* https://github.com/KhronosGroup/Vulkan-Docs/commit/71decb7f868d3891974eab139f03c7c6c87fea4d

>  * Adds an optional new indirect ray tracing dispatch command,
    flink:vkCmdTraceRaysIndirect2KHR, which sources the shader binding table
    parameters as well as the dispatch dimensions from the device.
    The <<features-rayTracingPipelineTraceRaysIndirect2,
    pname:rayTracingPipelineTraceRaysIndirect2>> feature indicates whether
    this functionality is supported.

Is this related?

**Comment by K0bin** [comment]
Not to this issue but it's required for VKD3D-Proton to be able to implement DirectX Ray Tracing 1.1.

**Comment by DistantThunder** [comment]
Ah yes, not indirect rendering, sorry I misread. So stuff like CP2077 will start working again hopefully?

**Comment by K0bin** [comment]
This is implemented in 2.7.
