### ISSUE TITLE
Regression - RTX Showcase Demo (The Attic)

### ISSUE THREAD

**Issue by SveSop** [HansKristian-Work/vkd3d-proton#915]
Demo: [https://developer.nvidia.com/rtx-technology-showcase](https://developer.nvidia.com/rtx-technology-showcase)

Crash:
```
0108:info:d3d12_device_determine_ray_tracing_tier: DXR support enabled.
0108:info:d3d12_device_determine_ray_tracing_tier: DXR 1.1 support enabled.
0108:warn:d3d12_device_QueryInterface: {a7aa6116-9c8d-4bba-9083-b4d816b71b78} not implemented, returning E_NOINTERFACE.
0108:warn:d3d12_device_QueryInterface: {ccffef16-7b69-468f-bce3-cd953369a39a} not implemented, returning E_NOINTERFACE.
0108:warn:d3d12_resource_validate_create_info: Ignoring optimized clear value.
0140:fixme:d3d12_state_object_parse_subobjects: Object config flag #4 is not supported.
0144:fixme:d3d12_state_object_parse_subobjects: Object config flag #4 is not supported.
013c:fixme:d3d12_state_object_parse_subobjects: Object config flag #4 is not supported.
```
good: 930e7cb2511d2113c751b3ea7b9b23bdbec379c0
bad: d61f562a3ec329f3c5fda9a43042a816ab824f45
[vkd3d.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7573099/vkd3d.log.gz)

**Comment by DadSchoorse** [comment]
Needs handling of `D3D12_STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS` and probably `AddToStateObject`.

**Comment by SveSop** [comment]
> Needs handling of `D3D12_STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS` and probably `AddToStateObject`.

So because new interface was introduced, it now needs handling of `D3D12_STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS` to get it working again?

**Comment by HansKristian-Work** [comment]
Not really a regression. It's a DXR 1.1 API we need to implement eventually.

**Comment by SveSop** [comment]
I see. 
The demo works with raytracing (same as it did) if i set `VKD3D_CONFIG=dxr` instead of dxr11. That it worked before, was probably because of some sort of fallback due to missing interface or something i guess.

Ill just close it for now, since i guess DXR 1.1 is currently WIP. Can always reopen if a new issue arises with this.
