### ISSUE TITLE
Regression on The Ascent (Steam AppID: 979690) with DXR11

### ISSUE THREAD

**Issue by LordDaveTheKind** [HansKristian-Work/vkd3d-proton#922]
The game ([SteamDB record](https://steamdb.info/app/979690/)) now hangs immediately at the rendering of the menu screen, after the presentation videos. Here below the launch command I have used: 

`VKD3D_CONFIG=dxr11 PROTON_ENABLE_NVAPI=1 mangohud gamemoderun %command% -dx12`

Tested Proton versions have been:
-  Proton Experimental (Steam shipped release)
-  Proton GE 6.21-2

and both of them present the same outcome.

Last time I tested was with the older NVIDIA Driver 470.63.01 and it was working perfectly. I don't know if it is actually related to the update of the NVIDIA Driver to release 495.44.

Here is [the full trace of vkd3d log](https://raw.githubusercontent.com/LordDaveTheKind/log-dumps/main/vkd3d-dxr11-theascent-979690-202111251117.log).

Please let me know if I have to share more info about this case.

All the best,
Dave

**Comment by SveSop** [comment]
This could be related to https://github.com/HansKristian-Work/vkd3d-proton/issues/915 where d61f562a3ec329f3c5fda9a43042a816ab824f45 and up added some new interfaces that are not fully supported when it comes to dxr11.

Possibly try to launch the game with `VKD3D_CONFIG=dxr` and see if it works then?

**Comment by LordDaveTheKind** [comment]
I can confirm that the crash is caused by the Nvidia Driver 495.44. Downgrading to release 470.63 solved it.
