### ISSUE TITLE
Forza Horizon 4 crash in Lego Speed Champions

### ISSUE THREAD

**Issue by TensaFlow** [HansKristian-Work/vkd3d-proton#927]
Forza Horizon 4 crashes during the first race in Lego Speed Champions (aka Lego Valley). I also tested with Proton Experimental, as well as the latest vkd3d-proton.

**Logs**
Here are all [error logs](https://gist.github.com/TensaFlow/9a5339601dfed5c3285cdbd938e82989), and all [warning logs](https://gist.github.com/TensaFlow/7e1f962222ff59858661ec85bb2553f9), as well as the [first](https://gist.github.com/TensaFlow/36120667c0378d78b1bf8258743071e0#file-steam-1293830_first_5k-log) and [last](https://gist.github.com/TensaFlow/36120667c0378d78b1bf8258743071e0#file-steam-1293830_last_5k-log) 5000 lines of the crash log.

**System Information**
GPU: RTX 3060
Driver/LLVM version: Nvidia 495.44
Kernel version: 5.15.6
Link to full system information report as [Gist](https://gist.github.com/TensaFlow/55765292026bfb36543b9435c0e53769).
Proton version: 6.3-8 (also tested with Experimental)

**Steps to replicate:**
1. Open map, select Lego Speed Champions as destination (North of map area).
2. Fast travel, or drive to destination.
3. Press X to enter Lego Speed Champions / Lego Valley.
4. After the cutscene, you will be dropped into a race. After a few seconds the game crashes.

Unclear if this is related to a [similar crash](https://github.com/HansKristian-Work/vkd3d-proton/issues/753) with Fortune Island, which was reported as fixed in 6.3-7 and has no comments since October.

**Comment by TensaFlow** [comment]
One of the things in the log was:
`0154:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.`
Looks like I wasnt able to share my entire log file, which was 1.8GB.

**Comment by Blisto91** [comment]
@TensaFlow Friendly ping. Are you still having this issue?

**Comment by TensaFlow** [comment]
@Blisto91 No, it works properly now. Thanks for checking!
