### ISSUE TITLE
Root signature long haul [Nvidia]

### ISSUE THREAD

**Issue by RoyShapiro** [HansKristian-Work/vkd3d-proton#928]
This is more of an annoyance (or seems that way) than an actual bug, but some games,
say **Deliver Us The Moon** (but there are others), take a very long time to load, with terminal being filled with messages like:
`NUMBER:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0xFU.`
Where NUMBER is a decimal number, and FU is a 1 or 2 digit hexadecimal.

_Maybe a coincidence, but all of said games are from GOG and thus don't benefit from Steam's shader cache._

This seems to take much longer (speaking of orders of magnitude) on Nvidia cards than on AMD cards.
For example, on an AMD card, the number of such messages can be 10-15, and it only takes 10 seconds, and the hexadecimals don't seem to repeat themselves, while on Nvidia card the same game with the same settings can take upwards of 1 minute 30 seconds, and the hexadecimal numbers seem to cycle multiple times with the number of such lines being in the hundreds.

_Taking the naive approach:_
At first, considering that the games otherwise run fine, I thought that that's a typical "stdout makes things run slow" kind of issue, so I tried "`VKD3D_DEBUG=none`" and even commenting out the respective line in the code, but the games still take the same time to load, just without the messages.
And if the whole code block _is made to skip root sigs with the same id_ (like make an array, if it's in array skip it, otherwise do it and add to array), then visual artifacts such as missing objects, textures e.t.c, start to appear en masse indicating some sort of shader failure. So my second hunch that something just loops unnecessarily is also false.

I certainly know precious nothing about root signatures (_other that they allow shaders to access resources,_ but I don't seem to recall that from D3D9 times), so I don't understand how it works.
If anyone can spare a little time to enlighten me as to what is happening during this long load and why it takes so long on Nvidia, it would be wonderful.

Thanks in advance,
Roy

**Comment by HansKristian-Work** [comment]
Creating a root signature maps to vkCreatePipelineLayout in Vulkan, and I have seen vkCreatePipelineLayout take 5 ms on NV in the past for unknown reasons. It should be closer to 5 microseconds ...

**Comment by RoyShapiro** [comment]
@HansKristian-Work Thank you!
I've made a few naive measurements using `gettimeofday` (_yes, not exactly the "best" tool to measure such a thing, but for a quick & dirty approach..._), and on my Nvidia RTX 3090 (power limit of 250 watts imposed, but the same occurs without it too, it might affect measurements, though) it takes between 11ms to 32ms (0.012s being the most common) for each `vkCreatePipelineLayout` call in problematic games. So, about twice your measurements for NV (O_o).
You're absolutely right: the games that have the problem spam this function like crazy.

**Comment by RoyShapiro** [comment]
If anyone else still has this issue, as @HansKristian-Work points out, it has to do with how Nvidia drivers process `vkCreatePipelineLayout` calls.
**Updating the drivers** to the recent `470.94` or `495.46` branches (_although the latter one one bugs out with raytracing in any UE games, but that's a whole different story_) **fixes the problem**.
With either driver `vkCreatePipelineLayout` is virtually instant.
