### ISSUE TITLE
Life is Strange: True Colors (936790) graphical glitch in DX12 mode.

### ISSUE THREAD

**Issue by besentv** [HansKristian-Work/vkd3d-proton#935]
### Summary
There is a graphical glitch in the 3rd chapter of episode 4.

How the glitch looks like: 
![image](https://user-images.githubusercontent.com/10588728/144242911-d4274e69-7341-433a-8b34-3882b17cbf7a.png)

How it's supposed to look like:
![image](https://user-images.githubusercontent.com/10588728/144242920-172eaf6b-3207-4d8b-b69e-57b384ea0e6f.png)

### Steps to reproduce
Get my save files from [https://drive.google.com/drive/folders/1b4vRPyTu_lJNZh3R7rMYhr2Sl-Uk4Erf?usp=sharing](url)
and put them into: ./steamapps/compatdata/936790/pfx/drive_c/users/steamuser/Documents/My Games/LifeIsStrange3/Steam/<your_steamID>/

Start the game in DX12 mode then do these steps from the main menu:

1. Go to chapters -> Open Chapter 4 -> Replay "Rooftop rendevouz" (3rd image from left)
2. After load, skip dialogue with space.
3.  Select "So happy for you.".
4.  Skip dialogue.
5.  Select "Berlin".
6.  Skip dialogue.
7.  Select "A big loft.".
8.  Skip dialogues.
9.  Select "kiss".
10. Wait for the yellow glow to expand in a glitchy mess.

### System info

Proton Version used: 6.21-GE-2

> System:    Kernel: 5.15.2-2-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: KDE Plasma 5.23.3 tk: Qt 5.15.2
>            wm: kwin_x11 dm: SDDM Distro: Manjaro Linux base: Arch Linux
> CPU:       Info: 6-Core model: Intel Core i7-5930K bits: 64 type: MT MCP arch: Haswell rev: 2 cache: L1: 384 KiB L2: 1.5 MiB
>            L3: 15 MiB
>            flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 84013
>            Speed: 3496 MHz min/max: 1200/3700 MHz Core speeds (MHz): 1: 3539 2: 2844 3: 1956 4: 3542 5: 2267 6: 1617 7: 1902
>            8: 3533 9: 3428 10: 2822 11: 1894 12: 1582
> Graphics:  Device-1: NVIDIA TU116 [GeForce GTX 1660 Ti] vendor: ZOTAC driver: nvidia v: 495.44 bus-ID: 02:00.0
>            chip-ID: 10de:2182
>            Device-2: Logitech BRIO Ultra HD Webcam type: USB driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 4-1:2
>            chip-ID: 046d:085e
>            Device-3: AVerMedia AVerMedia USB Device type: USB driver: snd-usb-audio,uvcvideo bus-ID: 8-2:3 chip-ID: 07ca:0570
>            Display: x11 server: X.Org 1.21.1.1 compositor: kwin_x11 driver: loaded: nvidia resolution: 1: 1920x1080
>            2: 1920x1080~60Hz s-dpi: 92
>            OpenGL: renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 495.44 direct render: Yes

**Comment by HansKristian-Work** [comment]
It is reproducible on RTX 3070. Seems to be a draw call with tessellation and 12 control points. No obvious reason this fails based on looking at the shader diffs though ...

**Comment by HansKristian-Work** [comment]
It works fine on RADV. I'll declare this a driver bug. Not exactly super high priority to look into since it's an optional backend, not our bug, and just a goofy glitch.

**Comment by besentv** [comment]
Seems like Nvidia fixed this. Closing.
