### ISSUE TITLE
Guardians of the galaxy crashes when interacting with certain items

### ISSUE THREAD

**Issue by vaslabs** [HansKristian-Work/vkd3d-proton#937]
I've created a few builds, this seems to be some invalid access call activated with the recent change for dsv and dynamic dsv
I'm interested to debug more, currently I can't get any useful information (at least to my eye) from proton log (https://github.com/ValveSoftware/Proton/issues/5250#issuecomment-982144924)

I'm also interested to investigate this issue myself as well, just need a few pointers on how to see where the invalid access happens.
 
I'll have more time to work on it on the weekend, my builds are [here](https://github.com/vaslabs/vkd3d-proton/actions), thanks for making it easy to build !

Edit: I'm very rookie with these things but the issue from the wine backtrace points into the xaudio dll
```
PE	    7fe6b8290000-    7fe6b8294000	Deferred        xaudio2_8
PE	    7fe72c310000-    7fe72c313000	Deferred        wineopenxr
```
```Backtrace:
=>0 0x00007fe716576a32 (0x00007fe6406d5690)
0x00007fe716576a32: testb	$0x6,0x000000000000004c(%rdx)
Modules:
```

reopen if this is wrong, I'm closing it here

~~I can confirm it's the sound
doing sound=pulseaudio via winetricks solves the issue for me~~
Edit: waiting for the dialogs to finish also helps the issue
+ I disabled the EQ in the sound settings, not sure if that helped, I'll update in the proton issue as I go along in the game

Edit 2: I was wrong about the sounds, it didn't crash because it happened that I waited for the dialogs to stop

**Comment by bundyo** [comment]
The sound=pulseaudio is not doing anything for me. Just waiting for characters to stop talking does. However this won't work for the code scene, as you can't wait them to stop.

(Dunno about EQ, which one do you mean? The game one was disabled here already and still crashes)

**Comment by vaslabs** [comment]
Yeah, the only way to play now is to get through with the old vkd3d and then swap and wait for the dialogs to finish. But I think the crash is with xaudio, I might have another go to find the exact issue on the weekend, although I'm less motivated now 😅

**Comment by bundyo** [comment]
Just for info, as I posted elsewhere - some of Marvel's GotG crashes do seem connected to fonts/font rendering - disabling subtitles completely seems to fix the crashes when opening the donut logs while someone is talking.

**Comment by vaslabs** [comment]
I disabled sound completely and (sound=disabled) there's no xaudio or alsa or pulse being loaded but the crash  still happens

**Comment by vaslabs** [comment]
The crash seems to have something to do with this https://github.com/vaslabs/vkd3d-proton/commit/a494e323bfad4a8164bf75e1254df6e9b858889d

It's passing at least from the Nova console at the start, if anyone is looking for a workaround to play the game (I don't promise anything, this was trial and error) you can give this https://github.com/vaslabs/vkd3d-proton/actions/runs/1539486080 a go

**Comment by alasky17** [comment]
@vaslabs Nice!  This fixed the Nova console crash for me :) (with AMD RX 570)

**Comment by howels** [comment]
What's the deal with nvidia cards here? Still crashing and using latest proton-GE 7-10 which appears to have the PR mentioned above in.  
Is the crash with nvidia cards a different issue to this one?
