### ISSUE TITLE
Godfall rendering issues

### ISSUE THREAD

**Issue by Saancreed** [HansKristian-Work/vkd3d-proton#942]
Glitches encountered in the tutorial area, in the next room after picking up the shield (after less than 5 minutes of gameplay). They look like this:

![Screenshot_20211209_223317](https://user-images.githubusercontent.com/26201033/145489754-610da973-109d-47c0-a853-647f5286135a.png)

There are no such issues when launching the game with `-dx11` argument, forcing it to use DXVK instead:

![Screenshot_20211210_002538](https://user-images.githubusercontent.com/26201033/145491618-e1fc57f8-2280-40bb-b043-5d2a03d12e5f.png)

Unfortunately, I couldn't apitrace the game, with wrapper DLLs in place all it does is print `apitrace: warning: D3D12CreateDevice: unexpected IUnknown pointer 0000000011EC8390`, but here are some dumped shaders and a log file (with default log levels):

https://drive.google.com/file/d/1yG39fMyowZcLs1m9xZT_n8uLlZyfAPgn/view?usp=drivesdk

[Godfall.log](https://github.com/HansKristian-Work/vkd3d-proton/files/7689080/Godfall.log)

Epic is giving away Godfall (well, some parts of it) for the next few days, might be useful for repro purposes. Also fwiw I had to remove videos directory because mfplat was causing some issues.

* Nvidia GTX 1660 Ti Mobile, 495.44
* `vkd3d-proton` commit c0a3fa8adc58945

**Comment by Oschowa** [comment]
Seems to work fine on AMD, RADV 6700XT  
  
![Screenshot from 2021-12-10 13-03-26](https://user-images.githubusercontent.com/8129300/145571697-830e75c2-6e79-42f0-93fd-aaeaf046481f.png)
