### ISSUE TITLE
Final Fantasy VII Remake : Intergrade  - VKD3D v2.5

### ISSUE THREAD

**Issue by DistantThunder** [HansKristian-Work/vkd3d-proton#944]
# System specs

Operating System: Arch Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.7-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 62.7 Gio of RAM
Graphics Processor: AMD Radeon RX 6900 XT
Mesa 21.3.1

# Game: Final Fantasy VII Remake : Intergrade (Epic Game Store)
* VKD3D version : v2.5
* Proton-6.21-GE-2

# Description

The game launched once and when trying to launch it for a second time, it crashes before the menu, displaying:

![image](https://user-images.githubusercontent.com/3923810/146461042-3b150dcb-d5bc-4f69-a7a6-fd18a875e8c2.png)

Logs with VKD3D Warn set:
* [ffvii_remake.log](https://github.com/HansKristian-Work/vkd3d-proton/files/7730918/ffvii_remake.log)

**Comment by DistantThunder** [comment]
By the way, to quell this problem, you can use the  "-dx11" flag when launching the game. However its is still D3D12 that is being used as while in-game, it's VKD3D that is translating.

**Comment by K0bin** [comment]
If anyone happens to have a working Windows installation, could you run the game with [D3D12 apitrace](https://github.com/Joshua-Ashton/apitrace/releases/tag/d3d12-alpha-4) and upload the trace file?

**Comment by Oschowa** [comment]
Apitrace seems to work and also replay fine on windows: https://drive.google.com/file/d/1oJVpuJT0hbxuE6E0NleZFvwl6Vz41aiq/view?usp=sharing  
  
The crashes with vkd3d-proton in this game seem a bit random, you can successfully load into the first level and at least play for a bit around 1/5 of the time. With DXVK it seems completely stable.

**Comment by DistantThunder** [comment]
Here are two traces: 
One only on the Menu & the other one with some in-game

* https://transfert.free.fr/7UAUSu

The crashes mostly happen either before the Menu or while loading in-game.

**Comment by DistantThunder** [comment]
Contrary to my previous claims, the game does feature a D3D11 render path. But DXVK is considerably less smooth than VKD3D.

**Comment by Senshi00** [comment]
> 

How do you run it with DXVK? I tried running it with the -dx11 argument but the game is still using VKD3D.

**Comment by Senshi00** [comment]
> Apitrace seems to work and also replay fine on windows: https://drive.google.com/file/d


> Apitrace seems to work and also replay fine on windows: https://drive.google.com/file/d/1oJVpuJT0hbxuE6E0NleZFvwl6Vz41aiq/view?usp=sharing
> 
> The crashes with vkd3d-proton in this game seem a bit random, you can successfully load into the first level and at least play for a bit around 1/5 of the time. With DXVK it seems completely stable.

How do you run it with DXVK? I tried running it with the -dx11 argument but the game is still using VKD3D.

**Comment by Mershl** [comment]
@Senshi00 See https://www.pcgamingwiki.com/wiki/Final_Fantasy_VII_Remake_Intergrade#Force_DirectX_11_for_more_consistent_frametimes. It may depend on your used EGS launcher.

**Comment by artivision** [comment]
> > Apitrace seems to work and also replay fine on windows: https://drive.google.com/file/d
> 
> > Apitrace seems to work and also replay fine on windows: https://drive.google.com/file/d/1oJVpuJT0hbxuE6E0NleZFvwl6Vz41aiq/view?usp=sharing
> > The crashes with vkd3d-proton in this game seem a bit random, you can successfully load into the first level and at least play for a bit around 1/5 of the time. With DXVK it seems completely stable.
> 
> How do you run it with DXVK? I tried running it with the -dx11 argument but the game is still using VKD3D.

Final Fantasy VII Remake Intergrade\Engine\Binaries\ThirdParty\EOS\

After **AppName=FFVIIRemakeIntergrade** add -dx11, should be like:
AppName=FFVIIRemakeIntergrade -dx11

Be aware of updates, maybe the revert that.

**Comment by gladiac1337** [comment]
I can confirm the game is working fine now in D3D12 mode with this change. Thanks!

**Comment by DistantThunder** [comment]
I confirm it's now Ok as well. Thanks!
