### ISSUE TITLE
Warframe New War dx12 crashes before the login screen

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#947]
I have noticed people on ProtonDB and Reddit reporting that Warframe with the New War content (new patches etc) can no longer run in dx12 with Proton Experimental or Proton-GE6.21. As this has not been reported here, I am adding this entry so you are aware of these problems. 
I will try to replicate on my system when I can re-install it through Steam.

**Comment by jhu54** [comment]
I was able to reproduce the error in Steam. With a fresh install, I had no issues, but if I allow Steam to compile the Vulkan Shaders before the game launches, using dx12 mode crashes out immediately before the login screen is displayed. If I rename the shadercache/230410 folder and restart the game, it proceeds through to the login screen.
It would appear that something goes wrong with the Vulkan shaders compilation and how they are processed with dx12 that is causing the crash.

**Comment by Emanem** [comment]
Hi - have the same issue - or at least triggered by the same.

On Nvidia - with latest stable drivers, if pre-caching is disabled the game bombs straight away in DX12 mode (i.e. vkd3d).
Seems like an assertion on the graphics pipeline fails.

More details and logs [here](https://github.com/ValveSoftware/Proton/issues/167#issuecomment-997376282).

**Comment by Oschowa** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/pull/953 fixes this for me.

**Comment by Emanem** [comment]
Hi - Is there a quick build I can test? Or do we know when it will be included in next proton experimental/main release/GE?

**Comment by Oschowa** [comment]
You can download a build of vkd3d-proton master from the github actions and copy the x64 d3d12.dll into `$steamlib/steamapps/common/Proton - Experimental/files/lib64/wine/vkd3d-proton` overwriting the old one to test.   
  
https://github.com/HansKristian-Work/vkd3d-proton/suites/4883161470/artifacts/139782399

**Comment by HansKristian-Work** [comment]
Should be fixed on master.

**Comment by Emanem** [comment]
Been playing for ~2 hours in d3d12 mode, no issue so far.

**Comment by globabee** [comment]
Warframe works well in d3d12 with this library however, game stucks at blackscreen when you call for in-game quit dialog. When this happens, electron apps (discord, chromium) freezing too. This problem happens on wayland, sway, proton-7.0rc3-GE-1

**Comment by cactushydrocodone** [comment]
Does not work for me with newest proton-GE.
I even downloaded the latest master artifacts and overwrote the DLLs, same bug :/
