### ISSUE TITLE
Red Dead Redemption 2 stuck at loading screen in DX12 mode.

### ISSUE THREAD

**Issue by ghost** [HansKristian-Work/vkd3d-proton#948]
![screenshot](https://i.postimg.cc/zvHbmD0g/68747470733a2f2f692e706f7374696d672e63632f38433234565433762f353334353334352e706e67.png)

```
013c:fixme:vkd3d_dxbc_compiler_emit_sync: Unhandled sync flags 0x8.
0148:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write ma
sk 0x1 (0xf).
0148:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x
2 2.
0148:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled register 0x11.
11 2.
0148:fixme:vkd3d_dxbc_compiler_emit_dereference_register: Relative addressing no
t implemented.
sk 0x2 (0xf).
sk 0x4 (0xf).
2 4.
013c:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write ma
013c:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x
013c:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled register 0x11.
013c:fixme:vkd3d_dxbc_compiler_emit_dereference_register: Relative addressing no
sk 0x8 (0xf).
```

The issue was mentioned before on the proton-git issue thread for the game.

Tested on both 2.5 and latest git with no difference.

My GPU is radeon with Mesa 21.3.1

**Comment by doitsujin** [comment]
Anything else in the logs? The compiler messages are harmless.

**Comment by goldenboy313** [comment]
```
0128:fixme:d3d12_root_signature_init_global: Ignoring root signature flags 0x1d.
```

Nothing else without debugging enabled. So I will be posting a log of +all,-heap next.

**Comment by goldenboy313** [comment]
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/7945533/log.txt)

**Comment by K0bin** [comment]
You need to use a special build of vkd3d-proton that has trace enabled. The logs you uploaded doesn't have any trace lines.

**Comment by goldenboy313** [comment]
oh yeah my bad. here it again with re-compiled build
[log.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/7952704/log.txt)

**Comment by K0bin** [comment]
This also doesn't have any trace lines.

**Comment by goldenboy313** [comment]
finally, third time's the charm. with --debug flag
https://www50.zippyshare.com/v/OPnZKXlC/file.html

**Comment by K0bin** [comment]
This time the link is dead. HTTP 403. ;P

**Comment by goldenboy313** [comment]
https://ufile.io/byou6njs

**Comment by Dark-Matter7232** [comment]
> Anything else in the logs? The compiler messages are probably harmless.

CPU: Ryzen 7 4800H
GPU: RTX3050
DIstro: Nobara 
Mesa: Mesa 22.2.2
Drivers: Nvidia beta 525.53
VKD3D: 2.7

RDR2 freezes on loading screen
![Screenshot from 2022-11-13 13-18-32](https://user-images.githubusercontent.com/38481036/201511572-429e6146-a1e1-4c4c-8b6c-07ed3b31dcef.png)

Logs with `VKD3D_DEBUG=trace` : https://p.const.eu.org/ETJJPqDf

**Comment by Blisto91** [comment]
@Dark-Matter7232 Can you still reproduce this issue with newest dxvk and vkd3d-proton? I could with proton 7 but not experimental

**Comment by Dark-Matter7232** [comment]
> @Dark-Matter7232 Can you still reproduce this issue with newest dxvk and vkd3d-proton? I could with proton 7 but not experimental

yes.

**Comment by elogicuk** [comment]
Still not working in DX12 mode :(

Software information
Red Dead Redemption 2
DirectX-12

System information
GPU: NVIDIA GeForce RTX 4070
Driver: 535.54.03
Wine version: tested many all the same results
VKD3D-Proton version: 2.9


415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_check_index_range: Unhandled register 0x11.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x11 2.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dereference_register: Relative addressing not implemented.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x4 (0xf).
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 4.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_check_index_range: Unhandled register 0x11.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x11 2.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dereference_register: Relative addressing not implemented.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x8 (0xf).
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 4.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_check_index_range: Unhandled register 0x11.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x11 2.
415.229:01e0:01fc:fixme:vkd3d-proton:vkd3d_dxbc_compiler_emit_dereference_register: Relative addressing not implemented.

**Comment by HansKristian-Work** [comment]
Dup of https://github.com/HansKristian-Work/vkd3d-proton/issues/1623

**Comment by akai-hana** [comment]
any fixes?
