### ISSUE TITLE
Resident Evil Village: Ray Tracing doesn't work (even if it can be enabled in the menu)

### ISSUE THREAD

**Issue by sancheztavo** [HansKristian-Work/vkd3d-proton#949]
After enabling Ray Tracing with max quality settings I've noticed that no reflections at all can be seen and the resulting image sometimes looks much darker (I assume because GI is also broken)
I'm attaching similar screenshots from the same configuration in windows for comparison, the most obvious example is the electric kettle in the kitchen and the lighting in the dining room.
![vkd3d_1](https://user-images.githubusercontent.com/3267628/147436019-f7af9542-9c4c-4a13-9579-4bc06b37a782.jpg)
![windows_1](https://user-images.githubusercontent.com/3267628/147436022-db1ab0fd-85e1-44bf-83d8-fb072e6c650d.jpg)
![vkd3d_2](https://user-images.githubusercontent.com/3267628/147436021-0f252838-289b-439f-a970-f00cdd72143a.jpg)
![windows_2](https://user-images.githubusercontent.com/3267628/147436024-ff0936dd-0a17-4201-9bf5-73a1b410e15e.jpg)

I've tested this with many Proton versions, including Proton-7.0rc2-GE-1, which updated dkd3d-proton 7 days ago. I also tried different Nvidia drivers, up to 495.44, in all cases the result was the same.

I've attached a log file with VKD3D_DEBUG and VKD3D_SHADER_DEBUG set to warn. The command line used in steam was `VKD3D_DEBUG=warn VKD3D_SHADER_DEBUG=warn PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=dxr11 %command%` 
[vkd3d-dxr11.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7778517/vkd3d-dxr11.log.gz)

And also, since I saw `0110:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.` errors, I also tried with `VKD3D_CONFIG=dxr11,no_upload_hvv` which removed those warnings but the result was the same
[vkd3d-dxr11,no_upload_hvv.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7778519/vkd3d-dxr11.no_upload_hvv.log.gz)

My hardware/OS is:
GPU: RTX 2060 Super
CPU: i7 3770k
Kubuntu 20.04

Let me know what else I can do to help.

**Comment by rajasrijan** [comment]
I've the same issue.
Cyberpunk 2077 also has this exact same issue, so i guess some implementation is missing.

**Comment by tizzir** [comment]
I can confirm these findings on the Nvidia drivers up to the current 510.x releases as well. Not sure if AMD exhibits the same issue.

**Comment by K0bin** [comment]
@Kamynsky It will actually allow you to enable it in the menu if you set VKD3D_CONFIG=dxr11. You just went out of your way to make sure that it doesn't.

RE8 only allows you to enable RT if your GPU supports feature level 12_2. So VKD3D_Proton reports 12_2 if dxr11 is enabled. You override that with VKD3D_FEATURE_LEVEL=12_1.

So once again, please don't just use random environment variables you find somewhere if you don't understand **why** they are used and what they do.

**Comment by Kamynsky** [comment]
Sir , as you can see in the first post with RT enabled there are reflections on the electric kettle 
https://i.imgur.com/dYPDSoz.jpg
This screen is taken from the game with my launch options and config file edited.
Below is proton log from the launch that screen was taken 
https://gist.github.com/Kamynsky/4e8f1ea3fd3ab7d0a0ea5e877d69e287
But yes , you are right , putting only VKD3D_CONFIG=dxr11 makes RT available . 
Sorry for taking up your time . Didn't mean any harm only wanted to help

**Comment by Blisto91** [comment]
Seems to be working with my 7900xtx and mesa-git tested on Proton experimental without any extra edits except the usual RT env vars. 
If any Nvidia users can confirm then i think this can be closed.

<details>
  <summary>Screenshots</summary>

![Screenshot_20230603_230632](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/274098fa-eefe-46c1-aa78-4fb5c9c10305)
![Screenshot_20230603_230706](https://github.com/HansKristian-Work/vkd3d-proton/assets/47954800/4937328e-848f-4bd7-a907-b8abd6d295af)
</details>

**Comment by Blisto91** [comment]
Ray tracing tested by @runar-work to be working on Nvidia.
