### ISSUE TITLE
Borderlands 3: Takes sometimes forever to load a level.

### ISSUE THREAD

**Issue by DoomedSouls** [HansKristian-Work/vkd3d-proton#951]
Benchmark sequence takes always 5 min to load. The same behavior during normal gameplay after multiple level are loaded. For example the first level is loaded in 10 sec the second level also but the third level will take 5 to 10 mins to load. I never have this Problem with windows 11 on dx12 or dx11.

Operating System: Arch Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.12-xanmod1-tt-1 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6900 XT
Mesa 21.3.3-1
Proton 7.0rc3-GE-1

**Comment by Blisto91** [comment]
@DoomedSouls Hi there. Is this still an issue you experience to this day? 🙂
