### ISSUE TITLE
Mortal Shell rendering issues with sunrays/post-process

### ISSUE THREAD

**Issue by Emanem** [HansKristian-Work/vkd3d-proton#952]
Hi,

Seems like Mortal Shell has trouble correctly rendering sunrays/post-process in DX12 mode - via VKD3D.
I've tried current Proton/Experimental and GE (at time of writing this), unfortunately those all yield to same on screen artifacts.

It's fairly easy to reproduce; you can see this issue in the main menu; DX11 mode:
![](https://user-images.githubusercontent.com/5248232/147888007-c09620ab-bab3-4f62-a090-205d3cde88d6.png)
DX12 mode:
![](https://user-images.githubusercontent.com/5248232/147888019-330be5e3-e58a-47a8-b49b-6e75824e10a5.png)

Please note the game doesn't crash, it's just having trouble rendering such effects.
It's running as borderless window, with everything set to _Ultra_.

My setup is Ubuntu 20.04.3, Nvidia 3080 Ti with drivers 495.46; I've also submitted the same to generic [Mortal Shell](https://github.com/ValveSoftware/Proton/issues/5085) thread on Proton github repo.

**Comment by HansKristian-Work** [comment]
Looks fine to me on RADV.

![screen](https://user-images.githubusercontent.com/17786731/149959531-f7f7552b-4636-4eee-96c4-f258c2a460b9.jpg)

**Comment by Emanem** [comment]
What version are you running on? I've tried the latest Proton Experimental right now and still persists on Nvidia.
If you have a VKD3D version you want me to try out, happy to give it a shot.

**Comment by HansKristian-Work** [comment]
Latest vkd3d-proton master. It's very likely an NV driver bug. There are some pending bugs with tessellation which is likely causing this issue too, but need to verify that.

**Comment by Emanem** [comment]
If I use the latest build [from master](https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/1717781812), and I set to use D3D12 + Ray Tracing, I still get the same issue - as you're mentioning perhaps and Nvidia driver issue...

**Comment by Emanem** [comment]
Still having same issue with drivers 510.47.03 - hope Nvidia will fix it sooner or later...

**Comment by Blisto91** [comment]
@Emanem Hi there. Do you know if this is still an issue today? 🙂

**Comment by Emanem** [comment]
Hi,

Can confirm that now all seems good. I am now running with:
* Proton Experimental
* Nvidia 525.78.01
* Nvidia RTX 4090
And the rendering issues are gone.

Not sure if it has been the drivers or (most likely) a more recent VKD3D update.
Excellent job, can close this issue!

**Comment by Blisto91** [comment]
Thank you for testing again! 👍
