### ISSUE TITLE
death stranding unsupported directx 12

### ISSUE THREAD

**Issue by Hadrianneue** [HansKristian-Work/vkd3d-proton#957]
i've used an environment variable in that past that would force directx 1x features that would work with death stranding, but i'm unable to find on vkd3d documentation. 

its VKD3D_FEATURE_LEVEL=12_0, wonder why this env is not documented.

**Comment by Hadrianneue** [comment]
its VKD3D_FEATURE_LEVEL=12_0, wonder why this env is not documented.

**Comment by K0bin** [comment]
Because it's a hack and only necessary on GPUs that don't support the required features.

**Comment by Hadrianneue** [comment]
> Because it's a hack and only necessary on GPUs that don't support the required features.

but mine does, its these extensions, right? (unless its something missing on mesa's side)

D3D12_TILED_RESOURCES_TIER_2 
D3D12_RESOURCE_BINDING_TIER_2

**Comment by K0bin** [comment]
If it's not enabled by default, there's some Vulkan feature missing.

**Comment by doitsujin** [comment]
You didn't exaxctly tell us which GPU and which driver you're using either.

**Comment by Hadrianneue** [comment]
> You didn't exaxctly tell us which GPU and which driver you're using either.

its a r7 360 0x665F
