### ISSUE TITLE
Resizeable BAR of Nvidia cause artifacts, ghosting and glitching

### ISSUE THREAD

**Issue by AgostinoA** [HansKristian-Work/vkd3d-proton#966]
I am testing many games. I have discovered very strange bugs that cause artifacts, ghosting and glitching depend on Resizeable BAR of Nvidia. I am testing with the same OS and driver, but with 2 different video cards.

Nvidia RTX 3070 Max-Q (Resizeable BAR ON) Razer Blade 2021
Nvidia RTX 2070 Max-Q (Resizeable BAR OFF) Razer Blade 2020
The Resizeable BAR is present only from the RTX 3000 series version.
Resizer Bar ON, some recent games like: Days Gone, Fallout 4, etc.
The problem is very obvious and truly causes epilesia.

With Nvidia's current drivers, the Resizeable BAR cannot be disabled. But with older versions, where the Resizeable BAR function was still off, these problems don't arise.

Does anyone know of a way to disable it from the Linux Nvidia driver, the Resizeable BAR?
There is a tweak to disable the Resizeable BAR from the Bios.
But from my bios, trying to activate CSM, the Resizeable BAR, it doesn't work. Moreover, on laptops the management of the basic bios is very limited.
It does not have a dedicated entry to disable it

Razer Blade 2021 - System Information
GPU: - Nvidia RTX 3070 Max-Q - Resizeable BAR ON
Driver/LLVM version: Nvidia 495.44
Kernel version: 5.14.15
Proton version: all

Razer Blade 2020 - System Information (NO PROBLEMS)
GPU: - Nvidia RTX 2070 Max-Q - Resizeable BAR OFF
Driver/LLVM version: Nvidia 495.44
Kernel version: 5.14.15
Proton version: all

DaysGone so  ghosting I can see the skulls of the characters, hahaha
I tried with no_upload_hvv, but it doesn't work.

Does anyone know how to disable it or ask NVIDIA to give the option, to put a toggle to enable or disable the BAR.
Or does anyone know the way to disable 4G Deconding without generating the Kernel Panic XD.

Can you help me ? XD

https://user-images.githubusercontent.com/28324952/147268927-f2ee85db-4f33-44ec-8471-c441b4ecc048.mp4

**Comment by HansKristian-Work** [comment]
> I tried with no_upload_hvv, but it doesn't work.

If that option doesn't help I'm not sure what we can do. That option will never attempt to use any BAR memory.

**Comment by AgostinoA** [comment]
Agreed, but the fact is strange, xk if I use the old driver of Nvidia the problem, does not arise. Because in this driver, Res. BAR is off.

**Comment by Blisto91** [comment]
@AgostinoA Hi there with a friendly ping. Do you know if this is still an issue with newer drivers and vkd3d-proton?

**Comment by AgostinoA** [comment]
None of this problem has been fixed by the recent release
