### ISSUE TITLE
Age of Empires IV won't start

### ISSUE THREAD

**Issue by scorp10n2000** [HansKristian-Work/vkd3d-proton#989]
Possible issue
"@PantelD I think one of you with the problem needs to open a issue at the [vkd3d-proton repo.](https://github.com/HansKristian-Work/vkd3d-proton)
If people with 700 series can run the game fine on Windows then it's either a vkd3d-proton issue or a driver issue. But they probably have to be made aware, else it won't get fixed." 

And my own report on the Proton issue taken from:
https://github.com/ValveSoftware/Proton/issues/5258
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Age of Empires IV won't start

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5545.
@scorp10n2000 posted on 2022-02-05T10:31:07:
Compatibility Report

  Name of the game with compatibility issues: 
  Age of Empires IV, Game no longer starts after latest update.
  
  Steam AppID of the game: 
  https://store.steampowered.com/app/1466860/Age_of_Empires_IV/

System Information

  GPU: NVIDIA GeForce GTX TITAN X
  Driver/LLVM version: 4.6.0 NVIDIA 510.47.03
  OS: EndeavourOS
  Kernel version: 5.16.5-arch1-1
  Link to full system information report as [Gist]: 
    https://gist.github.com/scorp10n2000/76fab4f82847b3d0906b3b7b01df683c
 Tried Proton version: 6.3.8 & Experimental

I confirm:

    [ x ] that I haven't found an existing compatibility report for this game.
    [ x ] that I have checked whether there are updates for my system available.

Proton Log:
https://gist.github.com/scorp10n2000/1485669801c714254d5821918c468d71

Symptoms:
Game won't start, CTD

Reproduction:
Start game in steam with any Proton version.

**Comment by SveSop** [comment]
Seem to be running for me with Proton-6.21-GE-1 with same driver and RTX2070 card. (Ubuntu tho, but i cant see how that should matter much).

I had some desync issues with newer Proton-GE than this when playing multiplayer, so i have not really revisited other GE versions... You could perhaps try Proton-GE as a comparison to Proton-experimental?

**Comment by scorp10n2000** [comment]
Okay, well no need the new Proton 7 fixed it!
It works again as far as I can tell, performance seems to gotten worse doh,
but I haven't tested enough yet.


/David J

**Comment by atif-rehman-ideofuzion** [comment]
[I have posted an issue on ubuntu 20.04](https://github.com/ValveSoftware/Proton/issues/5258#issuecomment-1054270498) and was suggested to put a comment here as it may be DX12 issue.
let me know if something is there to help.

**Comment by Blisto91** [comment]
@yhoyhoj Can you install `vulkan-tools` and show the output of `vulkaninfo` ?

**Comment by Blisto91** [comment]
@scorp10n2000 Friendly ping. Was it correct that this had been solved?

**Comment by scorp10n2000** [comment]
Yeah it's resolved.


/David Johansson
